function audit = validate_stage89_8h_runtime_h2(params, hourlyCounts)
%VALIDATE_STAGE89_8H_RUNTIME_H2 Hard gate for the six-by-eight-hour runtime.
if nargin < 2
    hourlyCounts = repmat(8,6,1);
end
hourlyCounts = hourlyCounts(:);
pass = params.dt_h==8 && params.enable_hourly_grid && ...
    params.hourly_grid.n_operating_stages==6 && ...
    params.hourly_grid.hours_per_stage==8 && numel(hourlyCounts)==6 && ...
    all(hourlyCounts==8) && sum(hourlyCounts)==48;
if ~pass
    error('Stage89M:Formal8hGate', ...
        'Formal runtime must have six operating stages with eight hourly periods each.');
end
audit = struct('pass',true,'operating_stage_count',6, ...
    'hours_per_operating_stage',hourlyCounts,'total_operating_hours',48, ...
    'formal_8h_mainline_used',true,'legacy_6h_path_used',false);
end
