function finalize_stage81_short_training_h2()
%FINALIZE_STAGE81_SHORT_TRAINING_H2 Combine symmetric SAA/DRO short-training evidence.
rootDir = fileparts(fileparts(mfilename('fullpath')));
runId = char(string(getenv('STAGE81_RUN_ID')));
if isempty(runId), runId = 'run-004'; end
if isempty(regexp(runId, '^run-\d{3}$', 'once'))
    error('finalize_stage81_short_training_h2:BadRunId', ...
        'STAGE81_RUN_ID must be run-xxx.');
end
runDir = fullfile(rootDir, 'results', 'task-002-stage2b-b3-smoke', ...
    '81-hourly-grid-short-training', runId);
names = ["saa", "chi2_eta003"];
for i = 1:2
    caseDir = fullfile(runDir, "case-" + names(i));
    required = {'TRAIN_DONE.txt','checkpoint_reload_audit.txt', ...
        'training_summary.csv','electrolyzer_site_diagnostics.csv', ...
        'h2_decision_summary.csv','hourly_grid_training_diagnostics.csv', ...
        'pv_training_diagnostics.csv','cut_dimension_audit.txt'};
    for j = 1:numel(required)
        if ~isfile(fullfile(caseDir, required{j}))
            error('finalize_stage81_short_training_h2:MissingCaseOutput', ...
                'Missing %s for %s.', required{j}, names(i));
        end
    end
end
s1 = readtable(fullfile(runDir, 'case-saa', 'training_summary.csv'), 'TextType', 'string');
s2 = readtable(fullfile(runDir, 'case-chi2_eta003', 'training_summary.csv'), 'TextType', 'string');
summary = [s1; s2]; writetable(summary, fullfile(runDir, 'training_summary.csv'));
e1 = readtable(fullfile(runDir, 'case-saa', 'electrolyzer_site_diagnostics.csv'));
e2 = readtable(fullfile(runDir, 'case-chi2_eta003', 'electrolyzer_site_diagnostics.csv'));
h1 = readtable(fullfile(runDir, 'case-saa', 'h2_decision_summary.csv'));
h2 = readtable(fullfile(runDir, 'case-chi2_eta003', 'h2_decision_summary.csv'));
g1 = readtable(fullfile(runDir, 'case-saa', 'hourly_grid_training_diagnostics.csv'));
g2 = readtable(fullfile(runDir, 'case-chi2_eta003', 'hourly_grid_training_diagnostics.csv'));
p1 = readtable(fullfile(runDir, 'case-saa', 'pv_training_diagnostics.csv'));
p2 = readtable(fullfile(runDir, 'case-chi2_eta003', 'pv_training_diagnostics.csv'));
comparison = table((1:4).', h1.production_mean_kg, h2.production_mean_kg, ...
    h1.end_inventory_mean_kg, h2.end_inventory_mean_kg, ...
    h1.htt_in_mean_kg, h2.htt_in_mean_kg, ...
    h1.htt_out_mean_kg, h2.htt_out_mean_kg, ...
    e1.average_p_el_kw, e2.average_p_el_kw, ...
    e1.full_power_frequency, e2.full_power_frequency, ...
    e1.grid_limited_frequency, e2.grid_limited_frequency, ...
    'VariableNames', {'site','saa_production_mean_kg','dro_production_mean_kg', ...
    'saa_inventory_mean_kg','dro_inventory_mean_kg','saa_htt_in_mean_kg', ...
    'dro_htt_in_mean_kg','saa_htt_out_mean_kg','dro_htt_out_mean_kg', ...
    'saa_average_p_el_kw','dro_average_p_el_kw','saa_full_power_frequency', ...
    'dro_full_power_frequency','saa_grid_limited_frequency', ...
    'dro_grid_limited_frequency'});
writetable(comparison, fullfile(runDir, 'saa_dro_short_training_comparison.csv'));
allPass = all(summary.stop_flag == 2) && all(summary.solver_errors == 0) && ...
    all(summary.structural_pass ~= 0) && ...
    g1.terminal_semantics_errors == 0 && g2.terminal_semantics_errors == 0 && ...
    g1.min_voltage_pu >= 0.90 - 1e-8 && g2.min_voltage_pu >= 0.90 - 1e-8 && ...
    g1.max_voltage_pu <= 1.10 + 1e-8 && g2.max_voltage_pu <= 1.10 + 1e-8 && ...
    g1.max_branch_utilization <= 1 + 1e-8 && g2.max_branch_utilization <= 1 + 1e-8 && ...
    g1.max_eq_error <= 1e-6 && g2.max_eq_error <= 1e-6 && ...
    g1.max_ineq_violation <= 1e-8 && g2.max_ineq_violation <= 1e-8 && ...
    p1.available_equals_used_plus_curtailed_max_error_kwh <= 1e-8 && ...
    p2.available_equals_used_plus_curtailed_max_error_kwh <= 1e-8 && ...
    p1.pv_bound_max_violation_kw <= 1e-8 && p2.pv_bound_max_violation_kw <= 1e-8;
judgment = ternary(allPass, 'PASS_READY_FOR_FORMAL_TRAINING', 'FAIL');
fid = fopen(fullfile(runDir, 'final_judgment.txt'), 'w');
fprintf(fid, 'FINAL_JUDGMENT=%s\nrun=%s\n', judgment, runId);
fprintf(fid, 'saa_wall_time_s=%.12g\ndro_wall_time_s=%.12g\n', ...
    s1.actual_wall_time_s, s2.actual_wall_time_s);
fprintf(fid, 'saa_iterations=%d\ndro_iterations=%d\n', s1.iterations, s2.iterations);
fprintf(fid, 'saa_cuts=%d\ndro_cuts=%d\n', s1.cut_count, s2.cut_count);
fprintf(fid, 'stage7_terminal_only=1\nstage8_absorbing_zero=1\ncut_dimension=4\n');
fprintf(fid, 'saa_min_voltage_pu=%.12g bus=%d hour=%d\n', ...
    g1.min_voltage_pu, g1.min_voltage_bus, g1.min_voltage_hour);
fprintf(fid, 'dro_min_voltage_pu=%.12g bus=%d hour=%d\n', ...
    g2.min_voltage_pu, g2.min_voltage_bus, g2.min_voltage_hour);
fprintf(fid, 'saa_max_branch_utilization=%.12g branch=%d->%d hour=%d\n', ...
    g1.max_branch_utilization, g1.tight_from, g1.tight_to, g1.tight_hour);
fprintf(fid, 'dro_max_branch_utilization=%.12g branch=%d->%d hour=%d\n', ...
    g2.max_branch_utilization, g2.tight_from, g2.tight_to, g2.tight_hour);
fprintf(fid, 'saa_pv_utilization=%.12g\ndro_pv_utilization=%.12g\n', ...
    p1.pv_utilization_ratio, p2.pv_utilization_ratio);
fprintf(fid, 'formal_oos_run=0\n');
fclose(fid);
end

function out = ternary(cond, a, b)
if cond, out = a; else, out = b; end
end
