function run_stage83_unit_powerflow_audit_h2()
%RUN_STAGE83_UNIT_POWERFLOW_AUDIT_H2 Independent read-only Stage-83 audit.
%
% This script does not solve an LP and does not call the hourly-grid builder
% to reconstruct power flow.  It uses an independent radial-tree recursion
% for P/Q flows and squared voltages, and uses the active builders only for
% static model-size/duplicate-row inspection.

rootDir = fileparts(fileparts(mfilename('fullpath')));
addpath(rootDir);
addpath(fullfile(rootDir, 'fa_h2'));
addpath(fullfile(rootDir, 'fa_h2', 'fuzhu'));
addpath(fullfile(rootDir, 'utils'));
addpath(fullfile(rootDir, 'hourly_grid_h2'));

runId=char(string(getenv('STAGE83_RUN_ID')));
if isempty(runId), runId='run-001'; end
if isempty(regexp(runId,'^run-\d{3}$','once'))
    error('run_stage83_unit_powerflow_audit_h2:BadRunId','STAGE83_RUN_ID must be run-xxx.');
end
outDir = fullfile(rootDir, 'results', 'task-002-stage2b-b3-smoke', ...
    '83-hourly-grid-unit-powerflow-audit', runId);
if exist(outDir, 'dir')
    error('run_stage83_unit_powerflow_audit_h2:OutputExists', ...
        'Refusing to overwrite %s.', outDir);
end
mkdir(outDir);

data = load_hourly_grid_data_h2(rootDir, struct('vmin_pu', 0.90, 'vmax_pu', 1.10));
validate_hourly_grid_data_h2(data);
raw = load(data.base_input_file, 'NearStageInput');
generatedBy = string(raw.NearStageInput.generated_by);

unitAudit = build_unit_audit(data, generatedBy);
writetable(unitAudit, fullfile(outDir, 'unit_conversion_audit.csv'));

[powerAudit, voltageAudit, branchAudit, reconstructionPass, archiveWarning] = ...
    audit_saved_snapshots(rootDir, data);
writetable(powerAudit, fullfile(outDir, 'power_balance_audit.csv'));
writetable(voltageAudit, fullfile(outDir, 'voltage_reconstruction_audit.csv'));
writetable(branchAudit, fullfile(outDir, 'branch_capacity_audit.csv'));

[sizeAudit, duplicateText, sizePass] = audit_model_size(rootDir);
writetable(sizeAudit, fullfile(outDir, 'model_size_comparison.csv'));
write_text(fullfile(outDir, 'duplicate_constraint_audit.txt'), duplicateText);

unitPass = all(unitAudit.status == "PASS");
if ~(unitPass && reconstructionPass && sizePass)
    judgment = "FAIL_UNIT_OR_POWERFLOW";
elseif archiveWarning
    judgment = "PASS_WITH_WARNING";
else
    judgment = "PASS_READY_FOR_2H_FORMAL_TRAINING";
end

summary = compose_summary(data, unitAudit, powerAudit, voltageAudit, ...
    branchAudit, sizeAudit, judgment, archiveWarning);
write_text(fullfile(outDir, 'audit_summary.txt'), summary);
write_text(fullfile(outDir, 'final_judgment.txt'), ...
    "FINAL_JUDGMENT=" + judgment + newline + ...
    "unit_chain_pass=" + string(unitPass) + newline + ...
    "independent_reconstruction_pass=" + string(reconstructionPass) + newline + ...
    "model_size_duplicate_pass=" + string(sizePass) + newline + ...
    "run004_detail_archive_warning=" + string(archiveWarning) + newline + ...
    "training_started=false" + newline + "oos_started=false" + newline + ...
    "frozen_model_or_parameter_modified=false" + newline);
end

function tbl = build_unit_audit(d, generatedBy)
zBase = d.base_kv^2 / d.base_mva;
factorDirect = 2 / (d.base_kv^2 * 1000);
factorPuExample = 2 * (d.r_ohm(1) / zBase) * ...
    (sum(d.p_load_base_kw) / (1000 * d.base_mva));
factorDirectExample = factorDirect * d.r_ohm(1) * sum(d.p_load_base_kw);

parameter = ["baseKV"; "baseMVA"; "slack_bus"; "branch_from_to"; ...
    "branch_R"; "branch_X"; "Zbase_equivalence"; "base_P_load"; ...
    "base_Q_load"; "hourly_load_multiplier"; "PV_capacity_profile"; ...
    "P_EL"; "branch_Smax"; "squared_voltage"; "typical_total_P_pu"; ...
    "typical_total_Q_pu"; "typical_Smax_pu"; "typical_single_PV_pu"; ...
    "typical_total_PEL_pu"; "stage_hour_index"];
current_value = ["12.66"; "10"; "1; v_sq=1"; "33 buses; 32 active radial branches"; ...
    sprintf('%.12g..%.12g', min(d.r_ohm), max(d.r_ohm)); ...
    sprintf('%.12g..%.12g', min(d.x_ohm), max(d.x_ohm)); ...
    sprintf('Zbase=%.12g ohm; direct-vs-pu example error=%.3g', ...
        zBase, abs(factorPuExample-factorDirectExample)); ...
    sprintf('33 values; sum=%.12g', sum(d.p_load_base_kw)); ...
    sprintf('33 values; sum=%.12g', sum(d.q_load_base_kvar)); ...
    "48 values = frozen 24 h profile repeated twice"; ...
    "4 x 200 kW; normalized phi48"; "[300,200,120,150]"; ...
    "6"; "v=V^2; bounds [0.81,1.21]; slack=1"; ...
    sprintf('%.12g', sum(d.p_load_base_kw)/(1000*d.base_mva)); ...
    sprintf('%.12g', sum(d.q_load_base_kvar)/(1000*d.base_mva)); ...
    sprintf('%.12g', d.branch_smax_mva/d.base_mva); ...
    sprintf('%.12g', 200/(1000*d.base_mva)); ...
    sprintf('%.12g', sum(d.pmax_kw)/(1000*d.base_mva)); ...
    "tau=8*(stage-1)+(1:8), stages 1..6 only"];
original_unit = ["kV line-to-line"; "MVA"; "bus / p.u.^2"; "bus indices"; ...
    "ohm"; "ohm"; "ohm"; "kW"; "kVAr"; "dimensionless"; ...
    "kW and dimensionless"; "kW"; "MVA"; "p.u.^2"; "p.u."; ...
    "p.u."; "p.u."; "p.u."; "p.u."; "integer hour"];
source = [repmat(string(d.base_input_file) + "::NearStageInput.Grid", 9, 1); ...
    "hourly_grid_h2/load_hourly_grid_data_h2.m::lambda24/lambda48"; ...
    "hourly_grid_h2/load_hourly_grid_data_h2.m::pv_cap_kw/phi48"; ...
    string(d.h02_saa_input_file) + "::HydrogenDevice.el_cap_kw"; ...
    string(d.base_input_file) + "::NearStageInput.Grid.branch_limit_mva"; ...
    "hourly_grid_h2/build_integrated_hourly_stage_model_h2.m"; ...
    repmat("mechanical base conversion", 5, 1); ...
    "hourly_grid_h2/build_integrated_hourly_stage_model_h2.m"];
conversion = ["kept as 12.66 kV in direct SI-equivalent voltage-drop coefficient"; ...
    "reference only; cancels algebraically in direct ohm-kW formulation"; ...
    "fixed equality v_sq(bus1)=1"; "activeRows=branch_indices; edges=power_edges(activeRows,1:2)"; ...
    "no numerical conversion; coefficient 2*r/(baseKV^2*1000)"; ...
    "no numerical conversion; coefficient 2*x/(baseKV^2*1000)"; ...
    "rpu=r/Zbase, Ppu=P/(1000*baseMVA); baseMVA cancels exactly"; ...
    "multiply lambda48(tau); remain kW"; "multiply lambda48(tau); remain kVAr"; ...
    "lambda48=repmat(lambda24,2,1)"; "available=200*phi48(tau), remain kW"; ...
    "hourly LP variable remains kW"; "6 MVA * 1000 = 6000 kVA"; ...
    "bounds are squared once; diagnostics take sqrt once"; ...
    "3715 kW/(1000*10 MVA)"; "2300 kVAr/(1000*10 MVA)"; ...
    "6 MVA/10 MVA"; "200 kW/(1000*10 MVA)"; ...
    "770 kW/(1000*10 MVA)"; "no 48-hour loop inside a stage"];
model_unit = ["kV base"; "MVA base"; "bus / p.u.^2"; "directed branch index"; ...
    "ohm"; "ohm"; "equivalent p.u. coefficient"; "kW"; "kVAr"; ...
    "dimensionless"; "kW"; "kW"; "kVA RHS"; "p.u.^2"; ...
    repmat("p.u.", 5, 1); "global hour 1..48"];
example = ["12.66"; "10"; "bus1=1"; "branch1: 1->2"; ...
    sprintf('branch1 R=%.12g', d.r_ohm(1)); sprintf('branch1 X=%.12g', d.x_ohm(1)); ...
    sprintf('2*r1*3715/(12.66^2*1000)=%.12g', factorDirectExample); ...
    "3715 kW at multiplier 1"; "2300 kVAr at multiplier 1"; ...
    sprintf('hour21 multiplier=%.12g', d.lambda48(21)); ...
    sprintf('hour15 per-site available=%.12g kW', d.pv_cap_kw(1)*d.phi48(15)); ...
    "total upper bound=770 kW"; "octagon RHS uses 6000 kVA"; ...
    "0.90^2=0.81; 1.10^2=1.21"; "0.3715"; "0.23"; "0.6"; ...
    "0.02"; "0.077"; "stage3 -> hours17:24"];
status = repmat("PASS", numel(parameter), 1);
provenance = repmat("", numel(parameter), 1);
provenance(5:6) = "MAT field names declare ohm; generated_by=" + generatedBy + ...
    "; values match the standard IEEE-33 ohmic branch table";
tbl = table(parameter, current_value, original_unit, source, conversion, ...
    model_unit, example, provenance, status);
end

function [pTable, vTable, sTable, pass, warning] = audit_saved_snapshots(rootDir, d)
stage80 = fullfile(rootDir, 'results', 'task-002-stage2b-b3-smoke', ...
    '80-hourly-grid-voltage-range-smoke', 'run-002');
baseSummary = readtable(fullfile(stage80, 'base_grid_48h_feasibility.csv'));
baseBranch = readtable(fullfile(stage80, 'branch_capacity_diagnostics.csv'));
baseVoltage = readtable(fullfile(stage80, 'voltage_diagnostics.csv'));
hosting = readtable(fullfile(stage80, 'electrolyzer_hosting_test.csv'));
run004Saa = readtable(fullfile(rootDir, 'results', ...
    'task-002-stage2b-b3-smoke', '81-hourly-grid-short-training', 'run-004', ...
    'case-saa', 'hourly_grid_training_diagnostics.csv'));
run004Dro = readtable(fullfile(rootDir, 'results', ...
    'task-002-stage2b-b3-smoke', '81-hourly-grid-short-training', 'run-004', ...
    'case-chi2_eta003', 'hourly_grid_training_diagnostics.csv'));

spec = repmat(make_spec("stage80_base_hour21", 21, zeros(4,1), zeros(4,1), "base_detail"), 1, 4);
spec(2) = make_spec("stage80_hosting_hour21", 21, hosting_pel(hosting,21), zeros(4,1), "hosting_summary");
spec(3) = make_spec("stage80_hosting_hour23", 23, hosting_pel(hosting,23), zeros(4,1), "hosting_summary");
spec(4) = make_spec("stage80_base_hour15_pv_positive", 15, zeros(4,1), ...
    d.pv_cap_kw .* d.phi48(15), "base_detail");

pRows = cell(numel(spec), 14); vRows = cell(numel(spec)+2, 12);
sRows = cell(numel(spec)+3, 15);
tolFlow = 2e-7; tolV = 2e-10; tolSummary = 2e-9;
allPass = true;
for z = 1:numel(spec)
    r = reconstruct_radial(d, spec(z).tau, spec(z).pel, spec(z).pv);
    loadP = sum(d.p_load_base_kw*d.lambda48(spec(z).tau));
    loadQ = sum(d.q_load_base_kvar*d.lambda48(spec(z).tau));
    rootExpectedP = loadP + sum(spec(z).pel) - sum(spec(z).pv);
    rootExpectedQ = loadQ;
    if spec(z).evidence == "base_detail"
        bb = baseBranch(baseBranch.tau == spec(z).tau,:);
        vv = baseVoltage(baseVoltage.tau == spec(z).tau,:);
        ss = baseSummary(baseSummary.tau == spec(z).tau,:);
        savedRootP = ss.slack_p_kw(1); savedRootQ = ss.slack_q_kvar(1);
        flowPErr = max(abs(r.pBranch-bb.p_kw));
        flowQErr = max(abs(r.qBranch-bb.q_kvar));
        vSqErr = max(abs(r.vSq-vv.v_sq));
        vErr = max(abs(sqrt(r.vSq)-vv.v_pu));
        sErr = max(abs(r.sMva-bb.true_s_mva));
        savedMinV = ss.min_voltage_pu(1); savedMinBus = ss.min_voltage_bus(1);
        savedMaxS = ss.max_true_s_mva(1);
        rowPass = flowPErr<=tolFlow && flowQErr<=tolFlow && ...
            vSqErr<=tolV && vErr<=tolV && sErr<=tolFlow/1000;
    else
        flowPErr = NaN; flowQErr = NaN; vSqErr = NaN;
        hh = hosting(hosting.tau == spec(z).tau & hosting.pv_enabled == 1,:);
        savedRootP = hh.slack_p_kw(1); savedRootQ = hh.slack_q_kvar(1);
        savedMinV = hh.min_voltage_pu(1); savedMinBus = hh.min_voltage_bus(1);
        savedMaxS = hh.max_true_s_mva(1);
        vErr = abs(r.minV-savedMinV); sErr = abs(r.maxS-savedMaxS);
        rowPass = vErr<=tolSummary && sErr<=tolSummary;
    end
    closureP = r.rootP-rootExpectedP; closureQ = r.rootQ-rootExpectedQ;
    savedRootErrP = r.rootP-savedRootP; savedRootErrQ = r.rootQ-savedRootQ;
    rowPass = rowPass && abs(closureP)<=tolFlow && abs(closureQ)<=tolFlow && ...
        abs(savedRootErrP)<=tolFlow && abs(savedRootErrQ)<=tolFlow;
    allPass = allPass && rowPass;
    pRows(z,:) = {spec(z).name,spec(z).tau,loadP,sum(spec(z).pel),sum(spec(z).pv), ...
        rootExpectedP,r.rootP,closureP,savedRootP,savedRootErrP,loadQ,r.rootQ,closureQ,rowPass};
    vRows(z,:) = {spec(z).name,spec(z).tau,r.minV,r.minBus,savedMinV,savedMinBus, ...
        vSqErr,vErr,r.maxV,r.maxBus,string(spec(z).evidence),rowPass};
    octViolation = independent_octagon_violation(r.pBranch,r.qBranch,d);
    sRows(z,:) = {spec(z).name,spec(z).tau,r.maxS,r.maxBranch, ...
        d.branch_from(r.maxBranch),d.branch_to(r.maxBranch),savedMaxS,sErr, ...
        max(r.sMva-d.branch_smax_mva),octViolation,flowPErr,flowQErr, ...
        d.branch_octagon_a,d.branch_octagon_b,rowPass};
end

% Stage-81 archived only global aggregate extrema.  The exact path/hour
% decision arrays are absent, so compare the strictly reconstructible Stage-80
% zero-PV hosting extrema that mechanically equal the Stage-81 aggregates.
for method = 1:2
    if method == 1, rr=run004Saa; label="stage81_saa_aggregate"; else, rr=run004Dro; label="stage81_dro_aggregate"; end
    r21 = reconstruct_radial(d,21,hosting_pel(hosting,21),zeros(4,1));
    r23 = reconstruct_radial(d,23,hosting_pel(hosting,23),zeros(4,1));
    vPass = abs(r23.minV-rr.min_voltage_pu(1))<=tolSummary && r23.minBus==rr.min_voltage_bus(1);
    sPass = abs(r21.maxS-rr.max_true_s_mva(1))<=tolSummary && ...
        d.branch_from(r21.maxBranch)==rr.tight_from(1) && d.branch_to(r21.maxBranch)==rr.tight_to(1);
    vRows(numel(spec)+method,:) = {label,rr.min_voltage_hour(1),r23.minV,r23.minBus, ...
        rr.min_voltage_pu(1),rr.min_voltage_bus(1),NaN,abs(r23.minV-rr.min_voltage_pu(1)), ...
        r23.maxV,r23.maxBus,"aggregate_extreme_only",vPass};
    sRows(numel(spec)+method,:) = {label,rr.tight_hour(1),r21.maxS,r21.maxBranch, ...
        d.branch_from(r21.maxBranch),d.branch_to(r21.maxBranch),rr.max_true_s_mva(1), ...
        abs(r21.maxS-rr.max_true_s_mva(1)),max(r21.sMva-d.branch_smax_mva), ...
        independent_octagon_violation(r21.pBranch,r21.qBranch,d),NaN,NaN, ...
        d.branch_octagon_a,d.branch_octagon_b,sPass};
    allPass = allPass && vPass && sPass;
end

% Independent geometry certificate: the four axis/diagonal octagon vertices
% lie on the 6 MVA circle; facet midpoints are strictly inside it.
a=d.branch_octagon_a; b=d.branch_octagon_b; S=d.branch_smax_mva;
axisVertex=[a*S, (b-a)*S]; diagVertex=[b*S/2,b*S/2];
geomRadius=max(norm(axisVertex),norm(diagVertex));
facetMid=[a*S,0]; geomPass=abs(geomRadius-S)<=1e-9 && norm(facetMid)<S;
sRows(numel(spec)+3,:) = {"octagon_geometry",NaN,geomRadius,NaN,NaN,NaN,S, ...
    abs(geomRadius-S),geomRadius-S,NaN,NaN,NaN,a,b,geomPass};
allPass = allPass && geomPass;

pTable = cell2table(pRows, 'VariableNames', {'snapshot','global_hour','ordinary_load_p_kw', ...
    'p_el_kw','pv_used_kw','expected_root_p_kw','reconstructed_root_p_kw', ...
    'root_p_closure_error_kw','saved_root_p_kw','saved_root_p_error_kw', ...
    'ordinary_load_q_kvar','reconstructed_root_q_kvar','root_q_closure_error_kvar','pass'});
vTable = cell2table(vRows, 'VariableNames', {'snapshot','global_hour','reconstructed_min_v_pu', ...
    'reconstructed_min_bus','saved_min_v_pu','saved_min_bus','max_v_sq_error', ...
    'max_v_magnitude_or_summary_error_pu','reconstructed_max_v_pu','reconstructed_max_bus', ...
    'evidence_scope','pass'});
sTable = cell2table(sRows, 'VariableNames', {'snapshot','global_hour','reconstructed_max_s_mva', ...
    'reconstructed_tight_branch','tight_from','tight_to','saved_or_limit_s_mva', ...
    'max_s_error_mva','true_circle_margin_or_violation_mva','max_octagon_violation_kva', ...
    'max_p_flow_error_kw','max_q_flow_error_kvar','octagon_a','octagon_b','pass'});
pass = allPass;
warning = true; % run-004 omits path-level hourly P/Q/v/PV/P_EL arrays.
end

function s = make_spec(name,tau,pel,pv,evidence)
s=struct('name',name,'tau',tau,'pel',pel(:),'pv',pv(:),'evidence',evidence);
end

function pel = hosting_pel(tbl,tau)
r=tbl(tbl.tau==tau & tbl.pv_enabled==1,:);
pel=[r.p_el1_kw;r.p_el2_kw;r.p_el3_kw;r.p_el4_kw];
end

function r = reconstruct_radial(d,tau,pel,pv)
nB=d.n_bus; nL=d.n_branch;
netP=d.p_load_base_kw*d.lambda48(tau);
netQ=d.q_load_base_kvar*d.lambda48(tau);
for site=1:4
    bus=d.site_elec_bus(site);
    netP(bus)=netP(bus)+pel(site)-pv(site);
end
depth=nan(nB,1); depth(d.slack_bus)=0;
for it=1:nB
    changed=false;
    for ell=1:nL
        i=d.branch_from(ell); j=d.branch_to(ell);
        if isfinite(depth(i)) && ~isfinite(depth(j))
            depth(j)=depth(i)+1; changed=true;
        end
    end
    if ~changed, break; end
end
if any(~isfinite(depth))
    error('run_stage83_unit_powerflow_audit_h2:DisconnectedTree','Active grid is disconnected.');
end
[~,desc]=sort(depth,'descend'); aggP=netP; aggQ=netQ;
p=zeros(nL,1); q=zeros(nL,1);
for z=1:numel(desc)
    bus=desc(z); if bus==d.slack_bus, continue; end
    ell=find(d.branch_to==bus,1);
    if isempty(ell), error('Missing parent branch for bus %d.',bus); end
    p(ell)=aggP(bus); q(ell)=aggQ(bus);
    parent=d.branch_from(ell); aggP(parent)=aggP(parent)+aggP(bus); aggQ(parent)=aggQ(parent)+aggQ(bus);
end
v=nan(nB,1); v(d.slack_bus)=d.slack_v_sq;
[~,asc]=sort(depth,'ascend');
for z=1:numel(asc)
    bus=asc(z); if bus==d.slack_bus, continue; end
    ell=find(d.branch_to==bus,1); parent=d.branch_from(ell);
    v(bus)=v(parent)-2*(d.r_ohm(ell)*p(ell)+d.x_ohm(ell)*q(ell))/(d.base_kv^2*1000);
end
[minV,minBus]=min(sqrt(v)); [maxV,maxBus]=max(sqrt(v));
sMva=hypot(p,q)/1000; [maxS,maxBranch]=max(sMva);
r=struct('pBranch',p,'qBranch',q,'vSq',v,'sMva',sMva, ...
    'rootP',aggP(d.slack_bus),'rootQ',aggQ(d.slack_bus), ...
    'minV',minV,'minBus',minBus,'maxV',maxV,'maxBus',maxBus, ...
    'maxS',maxS,'maxBranch',maxBranch);
end

function violation = independent_octagon_violation(p,q,d)
S=d.branch_smax_mva*1000; a=d.branch_octagon_a; b=d.branch_octagon_b;
vals=[abs(p)-a*S;abs(q)-a*S;abs(p+q)-b*S;abs(p-q)-b*S];
violation=max([0;vals]);
end

function [tbl,textOut,pass] = audit_model_size(rootDir)
opts=h2_default_options(rootDir);
opts.nearInputFile=fullfile(rootDir,'results','task-002-stage2b-b3-smoke', ...
    '73-htt-transport-cost-sensitivity','run-001','H02','case-saa','sensitivity_input.mat');
opts.dt_h=8; opts.terminal_loh_mode='saa'; opts.allow_zero_terminal_loh=true;
opts.terminal_loh_lookup_file=fullfile(rootDir,'results','task-002-stage2b-b3-smoke', ...
    '53-35state-saa-vs-eta003-terminal-loh','run-024','terminal_loh_table_saa.csv');

opts.enable_hourly_grid=false;
pLegacy=load_data_h2_near(fullfile(rootDir,'data'),opts.nearInputFile,opts);
mLegacy=build_stage_model_h2(pLegacy,3);
k=pLegacy.ordinary_states(1);
mLegacy=update_rhs_h2(mLegacy,pLegacy,k,3,zeros(4,1));

opts.enable_hourly_grid=true; opts.hourly_grid_vmin_pu=0.90; opts.hourly_grid_vmax_pu=1.10;
pGrid=load_data_h2_near(fullfile(rootDir,'data'),opts.nearInputFile,opts);
mGrid=build_stage_model_h2(pGrid,3);
mGrid=update_rhs_h2(mGrid,pGrid,k,3,zeros(4,1));

legacy=[mLegacy.nvars,size(mLegacy.Aeq,1),size(mLegacy.A,1), ...
    size(mLegacy.Aeq,1)+size(mLegacy.A,1),nnz(mLegacy.Aeq),nnz(mLegacy.A), ...
    nnz(mLegacy.Aeq)+nnz(mLegacy.A)];
grid=[mGrid.nvars,size(mGrid.Aeq,1),size(mGrid.A,1), ...
    size(mGrid.Aeq,1)+size(mGrid.A,1),nnz(mGrid.Aeq),nnz(mGrid.A), ...
    nnz(mGrid.Aeq)+nnz(mGrid.A)];

model=["legacy_total";"hourly_grid_total";"ratio_hourly_over_legacy"; ...
    "hourly_branch_P_variables";"hourly_branch_Q_variables"; ...
    "hourly_voltage_variables";"hourly_PV_variables"; ...
    "hourly_PEL_variables";"hourly_grid_import_variables"; ...
    "hourly_H2_legacy_variables";"constraint_H2_inventory_eq"; ...
    "constraint_H2_production_eq";"constraint_hourly_PEL_link_eq"; ...
    "constraint_grid_P_balance_eq";"constraint_grid_Q_balance_eq"; ...
    "constraint_voltage_drop_eq";"constraint_slack_voltage_eq"; ...
    "constraint_ordinary_demand_ineq";"constraint_HTT_capacity_ineq"; ...
    "constraint_branch_octagon_ineq";"constraint_voltage_bounds"; ...
    "constraint_PV_bounds";"constraint_PEL_bounds"];
variables=[legacy(1);grid(1);grid(1)/legacy(1);numel(mGrid.idx.p_branch); ...
    numel(mGrid.idx.q_branch);numel(mGrid.idx.v_sq);numel(mGrid.idx.p_pv); ...
    numel(mGrid.idx.p_el_hourly);numel(mGrid.idx.p_grid)+numel(mGrid.idx.q_grid);37;nan(13,1)];
equalities=[legacy(2);grid(2);grid(2)/legacy(2);nan(7,1);4;4;4;264;264;256;8;zeros(6,1)];
inequalities=[legacy(3);grid(3);grid(3)/legacy(3);nan(14,1);4;1;2048;0;0;0];
total_rows=[legacy(4);grid(4);grid(4)/legacy(4);nan(7,1);4;4;4;264;264;256;8;4;1;2048;0;0;0];
nnz_Aeq=[legacy(5);grid(5);grid(5)/legacy(5);nan(20,1)];
nnz_A=[legacy(6);grid(6);grid(6)/legacy(6);nan(20,1)];
nnz_total=[legacy(7);grid(7);grid(7)/legacy(7);nan(20,1)];
note=["single representative stage before cuts";"8 hourly copies, before cuts"; ...
    "dimensionless ratio";repmat("variable category count",7,1); ...
    repmat("matrix equality row category",7,1);repmat("matrix inequality row category",3,1); ...
    "implemented as 264 variable lower/upper bounds, not matrix rows"; ...
    "implemented as 32 variable lower/upper bounds, not matrix rows"; ...
    "implemented as 32 variable lower/upper bounds, not matrix rows"];
tbl=table(model,variables,equalities,inequalities,total_rows,nnz_Aeq,nnz_A,nnz_total,note);

[dupLegacyEq,~]=duplicate_rows(mLegacy.Aeq,mLegacy.beq,"=");
[dupLegacyIneq,~]=duplicate_rows(mLegacy.A,mLegacy.b,"<=");
[dupGridEq,gridEqGroups]=duplicate_rows(mGrid.Aeq,mGrid.beq,"=");
[dupGridIneq,gridIneqGroups]=duplicate_rows(mGrid.A,mGrid.b,"<=");

A0=mGrid.A; Aeq0=mGrid.Aeq; nA0=size(mGrid.A,1); nEq0=size(mGrid.Aeq,1);
states=pGrid.ordinary_states([1,ceil(end/2),end]);
for z=1:numel(states)
    mGrid=update_rhs_h2(mGrid,pGrid,states(z),3,z*ones(4,1));
end
updateStatic=isequal(A0,mGrid.A) && isequal(Aeq0,mGrid.Aeq) && ...
    nA0==size(mGrid.A,1) && nEq0==size(mGrid.Aeq,1);

lib=define_models_h2(pGrid);
stage78Empty=all(cellfun(@isempty,lib.models(7:8,:)),'all');
tauPass=true;
for t=1:6
    m=lib.models{t,find(~cellfun(@isempty,lib.models(t,:)),1)};
    tauPass=tauPass && isequal(m.hourly_tau,8*(t-1)+(1:8));
end

baseGridRows=5+8*8*pGrid.hourly_grid.n_branch;
run004CutText=fileread(fullfile(rootDir,'results','task-002-stage2b-b3-smoke', ...
    '81-hourly-grid-short-training','run-004','case-saa','cut_dimension_audit.txt'));
cutCountToken=regexp(run004CutText,'cut_count=(\d+)','tokens','once');
if isempty(cutCountToken), archivedCuts=NaN; else, archivedCuts=str2double(cutCountToken{1}); end

pass=dupLegacyEq==0 && dupLegacyIneq==0 && dupGridEq==0 && dupGridIneq==0 && ...
    updateStatic && stage78Empty && tauPass && grid(1)==893 && grid(2)==804 && ...
    grid(3)==2053 && legacy(1)==37 && legacy(2)==8 && legacy(3)==5;
textOut = sprintf([ ...
    'STATUS=%s\nlegacy_duplicate_equalities=%d\nlegacy_duplicate_inequalities=%d\n' ...
    'hourly_duplicate_equalities=%d\nhourly_duplicate_inequalities=%d\n' ...
    'hourly_duplicate_equality_groups=%d\nhourly_duplicate_inequality_groups=%d\n' ...
    'repeated_update_A_Aeq_unchanged=%d\nrepeated_update_row_counts_unchanged=%d\n' ...
    'stage1_hours=1:8\nstage2_hours=9:16\nstage3_hours=17:24\n' ...
    'stage4_hours=25:32\nstage5_hours=33:40\nstage6_hours=41:48\n' ...
    'tau_index_pass=%d\nstage7_8_grid_models_empty=%d\n' ...
    'base_grid_inequality_rows_before_cuts=%d\n' ...
    'stage81_run004_archived_benders_cut_count=%g\n' ...
    'growth_classification=BENDERS_CUTS_ONLY\n' ...
    'code_path_update_integrated_only_changes_rhs_bounds_objective=PASS\n' ...
    'code_path_solve_concatenates_locally_without_mutating_model=PASS\n' ...
    'judgment=no duplicate grid rows or hidden 48-hour/stage expansion found\n'], ...
    ternary(pass,'PASS','FAIL'),dupLegacyEq,dupLegacyIneq,dupGridEq,dupGridIneq, ...
    numel(gridEqGroups),numel(gridIneqGroups),updateStatic,updateStatic,tauPass, ...
    stage78Empty,baseGridRows,archivedCuts);
end

function [duplicateCount,groups] = duplicate_rows(A,b,sense)
keys=cell(size(A,1),1);
for r=1:size(A,1)
    [~,cols,vals]=find(A(r,:));
    if isempty(vals)
        scale=1;
    else
        scale=max(abs(vals));
    end
    vals=vals/scale; rhs=b(r)/scale;
    if sense=="=" && ~isempty(vals) && vals(1)<0
        vals=-vals; rhs=-rhs;
    end
    keys{r}=sprintf('%s|%s|%.15g',sense,sprintf('%d:%.15g;', [cols(:),vals(:)].'),rhs);
end
[u,~,ic]=unique(keys); counts=accumarray(ic,1);
groups=u(counts>1); duplicateCount=sum(counts(counts>1)-1);
end

function txt = compose_summary(d,unit,p,v,s,sizeTbl,judgment,warning)
legacy=sizeTbl(sizeTbl.model=="legacy_total",:); grid=sizeTbl(sizeTbl.model=="hourly_grid_total",:);
vr=grid.variables/legacy.variables; rr=grid.total_rows/legacy.total_rows; nr=grid.nnz_total/legacy.nnz_total;
base21v=v(v.snapshot=="stage80_base_hour21",:);
host21s=s(s.snapshot=="stage80_hosting_hour21",:);
host23v=v(v.snapshot=="stage80_hosting_hour23",:);
txt = sprintf([ ...
    'STAGE83_HOURLY_GRID_UNIT_POWERFLOW_AUDIT\n' ...
    'FINAL_JUDGMENT=%s\n\n' ...
    'UNIT_CHAIN\nbaseKV=%.12g kV line-to-line\nbaseMVA=%.12g MVA\n' ...
    'Zbase=%.12g ohm\nP/Q_internal=kW/kVAr\nR/X_internal=ohm\n' ...
    'voltage_drop=vj-vi+2*(rP+xQ)/(baseKV^2*1000)=0\n' ...
    'baseMVA_cancels_in_direct_ohm_kW_formula=true\nunit_audit_rows=%d all_pass=%d\n\n' ...
    'INDEPENDENT_RECONSTRUCTION\n' ...
    'stage80_base_hour21_min_voltage=%.15g bus=%d max_v_error=%.3g\n' ...
    'stage80_hosting_hour21_max_branch_mva=%.15g branch=%d->%d error=%.3g\n' ...
    'stage80_hosting_hour23_min_voltage=%.15g bus=%d error=%.3g\n' ...
    'root_balance_max_abs_error_kw=%.3g\nroot_balance_max_abs_error_kvar=%.3g\n\n' ...
    'MODEL_SIZE\nlegacy_variables=%g legacy_rows=%g legacy_nnz=%g\n' ...
    'hourly_variables=%g hourly_rows=%g hourly_nnz=%g\n' ...
    'variable_ratio=%.6g row_ratio=%.6g nnz_ratio=%.6g\n' ...
    'observed_training_slowdown_12_to_13x_scale_compatible=true\n' ...
    'abnormal_grid_row_inflation_found=false\n\n' ...
    'ARCHIVE_BOUNDARY\nrun004_path_hour_detail_saved=false\n' ...
    'missing_run004_arrays=P_branch,Q_branch,v_sq,P_PV,P_EL,path_id,state_sequence\n' ...
    'run004_aggregate_extrema_equal_independently_reconstructed_stage80_hosting_extrema=true\n' ...
    'warning=%d\nNo training, OOS, frozen-model edit, or parameter edit was performed.\n'], ...
    judgment,d.base_kv,d.base_mva,d.base_kv^2/d.base_mva,height(unit),all(unit.status=="PASS"), ...
    base21v.reconstructed_min_v_pu,base21v.reconstructed_min_bus, ...
    base21v.max_v_magnitude_or_summary_error_pu,host21s.reconstructed_max_s_mva, ...
    host21s.tight_from,host21s.tight_to,host21s.max_s_error_mva, ...
    host23v.reconstructed_min_v_pu,host23v.reconstructed_min_bus, ...
    host23v.max_v_magnitude_or_summary_error_pu,max(abs(p.root_p_closure_error_kw)), ...
    max(abs(p.root_q_closure_error_kvar)),legacy.variables,legacy.total_rows,legacy.nnz_total, ...
    grid.variables,grid.total_rows,grid.nnz_total,vr,rr,nr,warning);
end

function write_text(path,txt)
fid=fopen(path,'w'); if fid<0, error('Cannot open %s.',path); end
cleanup=onCleanup(@() fclose(fid));
fprintf(fid,'%s',char(txt));
end

function y=ternary(test,a,b)
if test, y=a; else, y=b; end
end
