function audit = validate_hourly_grid_data_h2(data)
%VALIDATE_HOURLY_GRID_DATA_H2 Fail closed on frozen Stage-79 identities.

checks = struct();
checks.bus_count = data.n_bus == 33;
checks.branch_count = data.n_branch == 32;
checks.radial_edges = size(unique([data.branch_from; data.branch_to]), 1) == 33;
checks.base_kv = abs(data.base_kv - 12.66) <= 1e-12;
checks.base_mva = abs(data.base_mva - 10) <= 1e-12;
checks.slack = data.slack_bus == 1 && abs(data.slack_v_sq - 1) <= 1e-12;
checks.mapping = isequal(data.site_elec_bus(:).', [24, 14, 18, 31]);
checks.mapping_separate = ~isequal(data.site_elec_bus, data.road_site_node) || ...
    strcmp(data.mapping_class, 'SYNTHETIC_BENCHMARK_COUPLING_ASSUMPTION');
checks.load48 = numel(data.lambda48) == 48 && ...
    max(abs(data.lambda48(1:24) - data.lambda48(25:48))) <= 1e-12;
checks.pv48 = numel(data.phi48) == 48 && ...
    max(abs(data.phi48(1:24) - data.phi48(25:48))) <= 1e-12;
checks.tariff_unique_shape = numel(data.tariff24) == 24 && ...
    numel(data.tariff48) == 48 && ...
    max(abs(data.tariff48(1:24) - data.tariff48(25:48))) <= 1e-12;
checks.tariff_frozen = max(abs(data.tariff24(:).' - [ ...
    0.3,0.3,0.3,0.3,0.32,0.36,0.45,0.58,0.68,0.74,0.78,0.82, ...
    0.86,0.88,0.8,0.72,0.7,0.78,0.92,0.98,0.95,0.8,0.55,0.35])) <= 1e-12;
checks.pmax = max(abs(data.pmax_kw(:).' - [300, 200, 120, 150])) <= 1e-12;
checks.k_h2 = abs(data.k_h2_kg_per_kwh - 0.0195) <= 1e-12;
checks.tank = max(abs(data.tank_cap_kg(:).' - [300, 200, 100, 150])) <= 1e-12;
checks.htt = abs(data.htt_capacity_kg_per_stage - 160) <= 1e-12;
checks.cd = abs(data.transport_distance_coefficient - 0.2) <= 1e-12;
checks.smax = abs(data.branch_smax_mva - 6) <= 1e-12;
checks.voltage = (abs(data.vmin_pu - 0.95) <= 1e-12 && ...
    abs(data.vmax_pu - 1.05) <= 1e-12) || ...
    (abs(data.vmin_pu - 0.90) <= 1e-12 && ...
    abs(data.vmax_pu - 1.10) <= 1e-12);
checks.h02_saa_dro_pmax = max(abs(double( ...
    data.h02_saa_input.HydrogenDevice.el_cap_kw(:)) - double( ...
    data.h02_dro_input.HydrogenDevice.el_cap_kw(:)))) <= 1e-12;
checks.h02_saa_dro_tank = max(abs(double( ...
    data.h02_saa_input.HydrogenDevice.tank_cap_kg(:)) - double( ...
    data.h02_dro_input.HydrogenDevice.tank_cap_kg(:)))) <= 1e-12;
checks.h02_saa_dro_demand = max(abs(double( ...
    data.h02_saa_input.NormalDemand.stage_template_kg(:)) - double( ...
    data.h02_dro_input.NormalDemand.stage_template_kg(:)))) <= 1e-12;
checks.h02_saa_dro_road = max(abs(double( ...
    data.h02_saa_input.Spatial.site_to_site_road_km(:)) - double( ...
    data.h02_dro_input.Spatial.site_to_site_road_km(:)))) <= 1e-12;

names = fieldnames(checks);
passed = false(numel(names), 1);
for k = 1:numel(names)
    passed(k) = logical(checks.(names{k}));
end
audit = table(string(names), passed, ...
    'VariableNames', {'check_name', 'passed'});
if ~all(passed)
    error('validate_hourly_grid_data_h2:IdentityFailure', ...
        'Frozen Stage-79 input validation failed: %s', ...
        strjoin(cellstr(audit.check_name(~audit.passed)), ', '));
end
end
