function audit_step04CB_full_capacity_h2(preparedFile,outputDir)
%AUDIT_STEP04CB_FULL_CAPACITY_H2 Independent FULL_CAPACITY fixed-T audit.

started=tic;preparedFile=string(preparedFile);outputDir=string(outputDir);
thisDir=fileparts(mfilename('fullpath'));rootDir=fileparts(fileparts(thisDir));
addpath(rootDir);addpath(thisDir);add_gurobi_path();
assert_git_gate("task/002-stage2b-b3-smoke", ...
    "2661960674675b2b15c9ca81cf1827d0dd0df1f6");
tmpDir=outputDir+".tmp";if isfolder(outputDir)||isfolder(tmpDir),error('FULL_CAPACITY output exists.');end
mkdir(tmpDir);
diary(fullfile(tmpDir,'matlab_diary.txt'));cleanupDiary=onCleanup(@()diary('off')); %#ok<NASGU>
P=load(preparedFile,'DnomRaw','AnomRaw','CnomRaw','Dext','Aext','Cext','pathId', ...
    'replicaRank','Cap','M','gamma','etas','design','riskType','topKs','nPaths','nReplicas');
if P.nPaths~=27||P.nReplicas~=135,error('State19 extreme count gate failed.');end
T=P.Cap(:).';config=struct('gurobiOutputFlag',0,'gurobiFeasibilityTol',1e-9, ...
    'gurobiOptimalityTol',1e-9,'gurobiThreads',1,'objectiveScale',1e5,'gurobiTimeLimit',1800);
nom=evaluate_step04CA2_period_fixed_T_detailed_h2(P.DnomRaw,P.AnomRaw,P.CnomRaw, ...
    repmat(T,size(P.DnomRaw,1),1),P.M,config);
ext=evaluate_step04CA2_period_fixed_T_detailed_h2(P.Dext,P.Aext,P.Cext, ...
    repmat(T,P.nReplicas,1),P.M,config);
if nom.exitflag~=1||ext.exitflag~=1,error('FULL_CAPACITY fixed-T recourse failed.');end

rows=cell(6,43);row=0;
for ee=1:2
    [nRisk,probResidual]=nominal_risk(ones(size(P.DnomRaw,1),1)/size(P.DnomRaw,1),nom.operating_loss,P.etas(ee));
    for dd=1:3
        row=row+1;[eRisk,activePaths,activeRows]=extreme_risk(ext.operating_loss,P.pathId,P.replicaRank,P.riskType(dd),P.topKs(dd));
        residual=max([probResidual,nom.max_demand_balance_error,max(0,nom.max_site_capacity_violation), ...
            nom.objective_reconstruction_abs_error,ext.max_demand_balance_error, ...
            max(0,ext.max_site_capacity_violation),ext.objective_reconstruction_abs_error]);
        pass=residual<=1e-5;
        rows(row,:)={0,P.etas(ee),P.design(dd),P.riskType(dd),P.topKs(dd),NaN,NaN, ...
            T(1),T(2),T(3),T(4),sum(T),4,P.gamma*sum(T),nRisk,P.gamma*sum(T)+nRisk,eRisk, ...
            mean(nom.operating_loss),pct(nom.operating_loss,90),pct(nom.operating_loss,95), ...
            pct(nom.operating_loss,99),max(nom.operating_loss),mean(ext.operating_loss), ...
            pct(ext.operating_loss,90),pct(ext.operating_loss,95),pct(ext.operating_loss,99),max(ext.operating_loss), ...
            mean(nom.shortage_kg),pct(nom.shortage_kg,95),max(nom.shortage_kg), ...
            mean(ext.shortage_kg),pct(ext.shortage_kg,95),max(ext.shortage_kg), ...
            mean(nom.service_satisfaction_rate),mean(ext.service_satisfaction_rate), ...
            mean(nom.shortage_kg<=1e-8),mean(ext.shortage_kg<=1e-8), ...
            mean(nom.unreachable_demand_kg),mean(ext.unreachable_demand_kg), ...
            join(string(activePaths),';'),join(string(activeRows),';'),residual,pass};
    end
end
audit=cell2table(rows,'VariableNames',{'case_id','eta','design','risk_type','top_k','kappa','beta_ext', ...
    'T1','T2','T3','T4','TerminalLOH_total','capacity_binding_count','first_stage_cost', ...
    'nominal_risk','J_base','extreme_risk','nominal_loss_mean','nominal_loss_q90','nominal_loss_q95', ...
    'nominal_loss_q99','nominal_loss_max','extreme_loss_mean','extreme_loss_q90','extreme_loss_q95', ...
    'extreme_loss_q99','extreme_loss_max','nominal_shortage_mean_kg','nominal_shortage_q95_kg', ...
    'nominal_shortage_max_kg','extreme_shortage_mean_kg','extreme_shortage_q95_kg', ...
    'extreme_shortage_max_kg','nominal_service_rate','extreme_service_rate', ...
    'nominal_zero_shortage_share','extreme_zero_shortage_share', ...
    'nominal_unreachable_demand_mean_kg','extreme_unreachable_demand_mean_kg', ...
    'active_path_ids','active_replica_rows','maximum_mechanical_residual','fixed_audit_pass'});
if ~all(audit.fixed_audit_pass),error('FULL_CAPACITY mechanical audit failed.');end
writetable(audit,fullfile(tmpDir,'full_capacity_fixed_audit.csv'));
lossRows=cell(12,23);row=0;
for ee=1:2
    for dd=1:3
        row=row+1;lossRows(row,:)=domain_cell(P.etas(ee),P.design(dd),P.riskType(dd),P.topKs(dd),"NOMINAL",nom);
        row=row+1;lossRows(row,:)=domain_cell(P.etas(ee),P.design(dd),P.riskType(dd),P.topKs(dd),"EXTREME",ext);
    end
end
lossSummary=cell2table(lossRows,'VariableNames',{'case_id','eta','design','risk_type','top_k','kappa','domain', ...
    'loss_mean','loss_q90','loss_q95','loss_q99','loss_max','shortage_mean_kg', ...
    'shortage_q95_kg','shortage_max_kg','shortage_W1_mean_kg','shortage_W2_mean_kg', ...
    'shortage_W3_mean_kg','service_rate_mean','zero_shortage_share', ...
    'unreachable_demand_mean_kg','unreachable_demand_share','total_demand_mean_kg'});
writetable(lossSummary,fullfile(tmpDir,'full_capacity_loss_shortage_summary.csv'));
site=(1:4).';capacity=P.Cap(:);capacityTable=table(site,capacity,capacity,zeros(4,1),true(4,1), ...
    'VariableNames',{'site_id','TerminalLOH','capacity','capacity_slack','capacity_binding'});
writetable(capacityTable,fullfile(tmpDir,'full_capacity_binding.csv'));
fid=fopen(fullfile(tmpDir,'full_capacity_mechanical_audit.txt'),'w');cleanupFid=onCleanup(@()fclose(fid));
fprintf(fid,'status=PASS\nstate19_extreme_paths=27\nstate19_extreme_replicas=135\n');
fprintf(fid,'maximum_mechanical_residual=%.15g\nruntime_sec=%.9f\n',max(audit.maximum_mechanical_residual),toc(started));
cleanupFid=[];diary off;cleanupDiary=[]; %#ok<NASGU>
movefile(tmpDir,outputDir);
fprintf('FULL_CAPACITY_AUDIT_COMPLETE|status=PASS|runtime=%.3f\n',toc(started));
end

function row=domain_cell(eta,design,riskType,topK,domain,ev)
row={0,eta,design,riskType,topK,NaN,domain,mean(ev.operating_loss),pct(ev.operating_loss,90), ...
    pct(ev.operating_loss,95),pct(ev.operating_loss,99),max(ev.operating_loss),mean(ev.shortage_kg), ...
    pct(ev.shortage_kg,95),max(ev.shortage_kg),mean(ev.stage_shortage_kg(:,1)), ...
    mean(ev.stage_shortage_kg(:,2)),mean(ev.stage_shortage_kg(:,3)),mean(ev.service_satisfaction_rate), ...
    mean(ev.shortage_kg<=1e-8),mean(ev.unreachable_demand_kg), ...
    sum(ev.unreachable_demand_kg)/sum(ev.total_demand_kg),mean(ev.total_demand_kg)};
end
function [value,residual]=nominal_risk(q,loss,eta)
if eta<=1e-14,value=sum(q.*loss);residual=abs(sum(q)-1);else
    out=solve_flat_chi2_worst_probability_h2(q,loss,eta);value=out.worst_value;
    residual=max([abs(sum(out.worst_probability)-1),max(0,-min(out.worst_probability)),max(0,out.divergence_used-eta)]);
end
end
function [value,activePaths,activeRows]=extreme_risk(loss,pathId,replicaRank,riskType,topK)
paths=unique(pathId,'sorted');pathLoss=zeros(numel(paths),1);active=zeros(numel(paths),1);
for pp=1:numel(paths),members=find(pathId==paths(pp));[pathLoss(pp),ii]=max(loss(members));active(pp)=members(ii);if ~isequal(sort(replicaRank(members)),(1:numel(members)).'),error('Replica ranks failed.');end,end
if riskType=="R1_MAX",[value,selected]=max(pathLoss);selected=selected(:);else,[~,order]=sortrows([-pathLoss,paths],[1,2]);selected=order(1:topK);value=mean(pathLoss(selected));end
activePaths=paths(selected);activeRows=active(selected);
end
function value=pct(x,p),x=sort(double(x(:)));index=max(1,min(numel(x),ceil(p*numel(x)/100)));value=x(index);end
function assert_git_gate(expectedBranch,expectedHead)
[s1,b]=system('git branch --show-current');[s2,h]=system('git rev-parse HEAD');[s3,u]=system('git rev-parse @{upstream}');if s1~=0||s2~=0||s3~=0||strtrim(string(b))~=expectedBranch||strtrim(string(h))~=expectedHead||strtrim(string(u))~=expectedHead,error('Git gate failed.');end
end
function add_gurobi_path(),for candidate={fullfile(getenv('GUROBI_HOME'),'matlab'),'D:\gurobi1201\win64\matlab','C:\gurobi1201\win64\matlab'},if ~isempty(candidate{1})&&isfolder(candidate{1}),addpath(candidate{1});end,end,end
