function audit_step04CB_isolated_case_h2(preparedFile,caseDir)
%AUDIT_STEP04CB_ISOLATED_CASE_H2 Independent full fixed-T audit for one case.

started=tic;preparedFile=string(preparedFile);caseDir=string(caseDir);
thisDir=fileparts(mfilename('fullpath'));rootDir=fileparts(fileparts(thisDir));
addpath(rootDir);addpath(thisDir);add_gurobi_path();
assert_git_gate("task/002-stage2b-b3-smoke", ...
    "2661960674675b2b15c9ca81cf1827d0dd0df1f6");
summaryFile=fullfile(caseDir,'case_summary.csv');if ~isfile(summaryFile),error('Case summary is missing.');end
if isfile(fullfile(caseDir,'case_fixed_audit.csv')),error('Case fixed audit already exists.');end
diary(fullfile(caseDir,'fixed_audit_matlab_diary.txt'));cleanupDiary=onCleanup(@()diary('off')); %#ok<NASGU>
P=load(preparedFile,'DnomRaw','AnomRaw','CnomRaw','q','Dext','Aext','Cext', ...
    'pathId','replicaRank','Cap','M','gamma','nPaths','nReplicas');
S=readtable(summaryFile,'TextType','string');if height(S)~=1||S.solver_status~="OPTIMAL"||~aslogical(S.mechanical_pass)
    error('Optimization summary did not pass.');
end
T=[double(S.T1),double(S.T2),double(S.T3),double(S.T4)];eta=double(S.eta);
riskType=string(S.risk_type);topK=double(S.top_k);betaExt=double(S.beta_ext);
config=struct('gurobiOutputFlag',0,'gurobiFeasibilityTol',1e-9, ...
    'gurobiOptimalityTol',1e-9,'gurobiThreads',1,'objectiveScale',1e5,'gurobiTimeLimit',1800);
fprintf('FIXED_AUDIT_START|case=%d\n',double(S.case_id));
nom=evaluate_step04CA2_period_fixed_T_detailed_h2(P.DnomRaw,P.AnomRaw,P.CnomRaw, ...
    repmat(T,size(P.DnomRaw,1),1),P.M,config);
ext=evaluate_step04CA2_period_fixed_T_detailed_h2(P.Dext,P.Aext,P.Cext, ...
    repmat(T,P.nReplicas,1),P.M,config);
assert_optimal(nom,'nominal raw fixed-T');assert_optimal(ext,'extreme fixed-T');
[nomRisk,probabilityAudit]=nominal_risk(ones(size(P.DnomRaw,1),1)/size(P.DnomRaw,1),nom.operating_loss,eta);
[extRisk,activePaths,activeRows]=extreme_risk(ext.operating_loss,P.pathId,P.replicaRank,riskType,topK);
Jbase=P.gamma*sum(T)+nomRisk;enhancedObjective=Jbase+betaExt*extRisk;
nominalRiskError=abs(nomRisk-double(S.nominal_risk));extremeRiskError=abs(extRisk-double(S.extreme_risk));
objectiveError=abs(enhancedObjective-double(S.enhanced_objective));
mechanicalResidual=max([nom.max_demand_balance_error,max(0,nom.max_site_capacity_violation), ...
    nom.objective_reconstruction_abs_error,ext.max_demand_balance_error, ...
    max(0,ext.max_site_capacity_violation),ext.objective_reconstruction_abs_error, ...
    nominalRiskError,extremeRiskError,objectiveError,probabilityAudit]);
pass=nominalRiskError<=1e-5&&extremeRiskError<=1e-5&&objectiveError<=1e-5&& ...
    nom.max_demand_balance_error<=1e-7&&nom.max_site_capacity_violation<=1e-7&& ...
    ext.max_demand_balance_error<=1e-7&&ext.max_site_capacity_violation<=1e-7&& ...
    nom.objective_reconstruction_abs_error<=1e-5&&ext.objective_reconstruction_abs_error<=1e-5&& ...
    P.nPaths==27&&P.nReplicas==135;
if ~pass,error('Independent fixed-T audit failed, residual %.9g.',mechanicalResidual);end

audit=table(double(S.case_id),eta,string(S.design),riskType,topK,double(S.kappa),betaExt, ...
    T(1),T(2),T(3),T(4),sum(T),sum(P.Cap-T<=1e-5),P.gamma*sum(T),nomRisk,Jbase,extRisk, ...
    enhancedObjective,nominalRiskError,extremeRiskError,objectiveError, ...
    nom.max_demand_balance_error,nom.max_site_capacity_violation, ...
    ext.max_demand_balance_error,ext.max_site_capacity_violation, ...
    nom.objective_reconstruction_abs_error,ext.objective_reconstruction_abs_error, ...
    mean(nom.operating_loss),pct(nom.operating_loss,90),pct(nom.operating_loss,95), ...
    pct(nom.operating_loss,99),max(nom.operating_loss),mean(ext.operating_loss), ...
    pct(ext.operating_loss,90),pct(ext.operating_loss,95),pct(ext.operating_loss,99),max(ext.operating_loss), ...
    mean(nom.shortage_kg),pct(nom.shortage_kg,95),max(nom.shortage_kg), ...
    mean(ext.shortage_kg),pct(ext.shortage_kg,95),max(ext.shortage_kg), ...
    mean(nom.service_satisfaction_rate),mean(ext.service_satisfaction_rate), ...
    mean(nom.shortage_kg<=1e-8),mean(ext.shortage_kg<=1e-8), ...
    mean(nom.unreachable_demand_kg),mean(ext.unreachable_demand_kg), ...
    sum(nom.unreachable_demand_kg)/sum(nom.total_demand_kg), ...
    sum(ext.unreachable_demand_kg)/sum(ext.total_demand_kg), ...
    join(string(activePaths),';'),join(string(activeRows),';'),mechanicalResidual,pass,toc(started), ...
    'VariableNames',{'case_id','eta','design','risk_type','top_k','kappa','beta_ext', ...
    'T1','T2','T3','T4','TerminalLOH_total','capacity_binding_count','first_stage_cost', ...
    'nominal_risk','J_base','extreme_risk','enhanced_objective','nominal_risk_error', ...
    'extreme_risk_error','objective_error','nominal_demand_balance_error', ...
    'nominal_capacity_violation','extreme_demand_balance_error','extreme_capacity_violation', ...
    'nominal_objective_reconstruction_error','extreme_objective_reconstruction_error', ...
    'nominal_loss_mean','nominal_loss_q90','nominal_loss_q95','nominal_loss_q99','nominal_loss_max', ...
    'extreme_loss_mean','extreme_loss_q90','extreme_loss_q95','extreme_loss_q99','extreme_loss_max', ...
    'nominal_shortage_mean_kg','nominal_shortage_q95_kg','nominal_shortage_max_kg', ...
    'extreme_shortage_mean_kg','extreme_shortage_q95_kg','extreme_shortage_max_kg', ...
    'nominal_service_rate','extreme_service_rate','nominal_zero_shortage_share', ...
    'extreme_zero_shortage_share','nominal_unreachable_demand_mean_kg', ...
    'extreme_unreachable_demand_mean_kg','nominal_unreachable_demand_share', ...
    'extreme_unreachable_demand_share','active_path_ids','active_replica_rows', ...
    'maximum_mechanical_residual','fixed_audit_pass','fixed_audit_runtime_sec'});
writetable(audit,fullfile(caseDir,'case_fixed_audit.csv'));

lossSummary=[domain_row(S,"NOMINAL",nom);domain_row(S,"EXTREME",ext)];
writetable(lossSummary,fullfile(caseDir,'case_loss_shortage_summary.csv'));
site=(1:4).';capacity=P.Cap(:);value=T(:);binding=capacity-value<=1e-5;
capacityTable=table(repmat(double(S.case_id),4,1),site,value,capacity,capacity-value,binding, ...
    'VariableNames',{'case_id','site_id','TerminalLOH','capacity','capacity_slack','capacity_binding'});
writetable(capacityTable,fullfile(caseDir,'case_capacity_binding.csv'));
fid=fopen(fullfile(caseDir,'fixed_audit_mechanical.txt'),'w');cleanupFid=onCleanup(@()fclose(fid));
fprintf(fid,'status=PASS\ncase_id=%d\nnominal_risk_error=%.15g\nextreme_risk_error=%.15g\n', ...
    double(S.case_id),nominalRiskError,extremeRiskError);
fprintf(fid,'objective_error=%.15g\nmaximum_mechanical_residual=%.15g\n',objectiveError,mechanicalResidual);
fprintf('FIXED_AUDIT_COMPLETE|case=%d|status=PASS|residual=%.9g|runtime=%.3f\n', ...
    double(S.case_id),mechanicalResidual,toc(started));
end

function row=domain_row(S,domain,ev)
unreachableShare=sum(ev.unreachable_demand_kg)/sum(ev.total_demand_kg);
row=table(double(S.case_id),double(S.eta),string(S.design),string(S.risk_type), ...
    double(S.top_k),double(S.kappa),domain,mean(ev.operating_loss),pct(ev.operating_loss,90), ...
    pct(ev.operating_loss,95),pct(ev.operating_loss,99),max(ev.operating_loss), ...
    mean(ev.shortage_kg),pct(ev.shortage_kg,95),max(ev.shortage_kg), ...
    mean(ev.stage_shortage_kg(:,1)),mean(ev.stage_shortage_kg(:,2)),mean(ev.stage_shortage_kg(:,3)), ...
    mean(ev.service_satisfaction_rate),mean(ev.shortage_kg<=1e-8), ...
    mean(ev.unreachable_demand_kg),unreachableShare,mean(ev.total_demand_kg), ...
    'VariableNames',{'case_id','eta','design','risk_type','top_k','kappa','domain', ...
    'loss_mean','loss_q90','loss_q95','loss_q99','loss_max','shortage_mean_kg', ...
    'shortage_q95_kg','shortage_max_kg','shortage_W1_mean_kg','shortage_W2_mean_kg', ...
    'shortage_W3_mean_kg','service_rate_mean','zero_shortage_share', ...
    'unreachable_demand_mean_kg','unreachable_demand_share','total_demand_mean_kg'});
end

function [value,residual]=nominal_risk(q,loss,eta)
if eta<=1e-14,value=sum(q.*loss);residual=abs(sum(q)-1);else
    out=solve_flat_chi2_worst_probability_h2(q,loss,eta);value=out.worst_value;
    residual=max([abs(sum(out.worst_probability)-1),max(0,-min(out.worst_probability)), ...
        max(0,out.divergence_used-eta)]);
end
end

function [value,activePaths,activeRows]=extreme_risk(loss,pathId,replicaRank,riskType,topK)
paths=unique(pathId,'sorted');pathLoss=zeros(numel(paths),1);active=zeros(numel(paths),1);
for pp=1:numel(paths)
    members=find(pathId==paths(pp));[pathLoss(pp),ii]=max(loss(members));active(pp)=members(ii);
    if ~isequal(sort(replicaRank(members)),(1:numel(members)).'),error('Replica ranks failed.');end
end
if riskType=="R1_MAX",[value,selected]=max(pathLoss);selected=selected(:);else
    [~,order]=sortrows([-pathLoss,paths],[1,2]);selected=order(1:topK);value=mean(pathLoss(selected));
end
activePaths=paths(selected);activeRows=active(selected);
end

function value=pct(x,p)
x=sort(double(x(:)));index=max(1,min(numel(x),ceil(p*numel(x)/100)));value=x(index);
end
function tf=aslogical(x)
if isstring(x)||ischar(x),tf=ismember(lower(string(x)),["true","1","yes","pass"]);else,tf=logical(x);end
end
function assert_optimal(out,label),if out.exitflag~=1,error('%s failed: %s',label,out.status);end,end
function assert_git_gate(expectedBranch,expectedHead)
[s1,b]=system('git branch --show-current');[s2,h]=system('git rev-parse HEAD');[s3,u]=system('git rev-parse @{upstream}');
if s1~=0||s2~=0||s3~=0||strtrim(string(b))~=expectedBranch||strtrim(string(h))~=expectedHead||strtrim(string(u))~=expectedHead,error('Git gate failed.');end
end
function add_gurobi_path()
for candidate={fullfile(getenv('GUROBI_HOME'),'matlab'),'D:\gurobi1201\win64\matlab','C:\gurobi1201\win64\matlab'}
    if ~isempty(candidate{1})&&isfolder(candidate{1}),addpath(candidate{1});end
end
end
