function [comparisonTbl, recommendation] = ...
    compare_Wstep40_45_foundation_h2(result, config)
%COMPARE_WSTEP40_45_FOUNDATION_H2 Symmetric physical comparison of 40/45.

S = result.D_Hres3h_summary;
candidates = sort(unique(double(S.Wstep(:))));
if numel(candidates) ~= 2 || ~isequal(candidates(:), [40; 45])
    error('compare_Wstep40_45_foundation_h2:UnexpectedCandidates', ...
        'This comparison requires exactly Wstep 40 and 45.');
end
rmaxValues = sort(unique(double(result.stage_risk.Rmax(:))));
if ~isequal(rmaxValues(:), [30; 40; 50])
    error('compare_Wstep40_45_foundation_h2:UnexpectedRmax', ...
        'Expected Rmax support points 30, 40, and 50.');
end

comparisonTbl = build_state_comparison(S, result.stage_risk);
candidateTbl = build_candidate_rmax_table(S, result.stage_risk, ...
    candidates, rmaxValues);
candidateTbl = add_symmetric_support(candidateTbl, candidates);
candidateSummary = summarize_candidates(candidateTbl, candidates, rmaxValues);
[status, recommendedWstep, reason] = ...
    select_foundation_Wstep_recommendation_h2(candidateSummary);

ref = comparisonTbl(comparisonTbl.Rmax == config.RmaxRef, :);
meanAbsDDelta = mean(abs(ref.D_total_delta_W45_minus_W40_kg));
meanD40 = mean(ref.W40_D_total_mean_kg);
relativeDSignal = meanAbsDDelta / max(meanD40, eps);
meanRoadDelta = mean(abs( ...
    (ref.W45_road_closed_W1_mean + ref.W45_road_closed_W2_mean + ...
    ref.W45_road_closed_W3_mean) - ...
    (ref.W40_road_closed_W1_mean + ref.W40_road_closed_W2_mean + ...
    ref.W40_road_closed_W3_mean)));

riskRef40 = select_risk_vectors(result.stage_risk, config.RmaxRef, 40);
riskRef45 = select_risk_vectors(result.stage_risk, config.RmaxRef, 45);

recommendation = struct();
recommendation.status = status;
recommendation.recommended_Wstep = recommendedWstep;
recommendation.reason = reason;
recommendation.allowed_statuses = ...
    "recommend_40|recommend_45|inconclusive_40_45";
recommendation.candidate_table = candidateTbl;
recommendation.candidate_summary = candidateSummary;
recommendation.mean_abs_D_delta_kg = meanAbsDDelta;
recommendation.relative_D_signal = relativeDSignal;
recommendation.mean_abs_road_closed_delta = meanRoadDelta;
recommendation.W45_W1_risk_higher = ...
    riskRef45.line(2) > riskRef40.line(2) && ...
    riskRef45.road(2) > riskRef40.road(2);
recommendation.W40_risk = riskRef40;
recommendation.W45_risk = riskRef45;
end

function T = build_state_comparison(S, stageRisk)
groups = unique(S(:, {'Rmax', 'a', 'loc'}), 'rows');
groups = sortrows(groups, {'Rmax', 'a', 'loc'});
rows = {};
for gg = 1:height(groups)
    r40 = select_D_row(S, groups(gg, :), 40);
    r45 = select_D_row(S, groups(gg, :), 45);
    risk40 = select_risk_vectors(stageRisk, groups.Rmax(gg), 40);
    risk45 = select_risk_vectors(stageRisk, groups.Rmax(gg), 45);
    rows(end + 1, :) = {groups.Rmax(gg), groups.a(gg), ...
        groups.loc(gg), r40.D_W1_mean_kg, r40.D_W2_mean_kg, ...
        r40.D_W3_mean_kg, r40.D_total_mean_kg, ...
        r45.D_W1_mean_kg, r45.D_W2_mean_kg, r45.D_W3_mean_kg, ...
        r45.D_total_mean_kg, r45.D_total_mean_kg - r40.D_total_mean_kg, ...
        relative_delta(r45.D_total_mean_kg, r40.D_total_mean_kg), ...
        r40.P_loss_W1_mean_kW, r40.P_loss_W2_mean_kW, ...
        r40.P_loss_W3_mean_kW, r45.P_loss_W1_mean_kW, ...
        r45.P_loss_W2_mean_kW, r45.P_loss_W3_mean_kW, ...
        r40.road_closed_W1_mean, r40.road_closed_W2_mean, ...
        r40.road_closed_W3_mean, r45.road_closed_W1_mean, ...
        r45.road_closed_W2_mean, r45.road_closed_W3_mean, ...
        risk40.line(2), risk40.line(3), risk40.line(4), ...
        risk45.line(2), risk45.line(3), risk45.line(4), ...
        risk40.road(2), risk40.road(3), risk40.road(4), ...
        risk45.road(2), risk45.road(3), risk45.road(4)}; %#ok<AGROW>
end
T = cell2table(rows, 'VariableNames', ...
    {'Rmax', 'a', 'loc', 'W40_D_W1_mean_kg', 'W40_D_W2_mean_kg', ...
    'W40_D_W3_mean_kg', 'W40_D_total_mean_kg', ...
    'W45_D_W1_mean_kg', 'W45_D_W2_mean_kg', ...
    'W45_D_W3_mean_kg', 'W45_D_total_mean_kg', ...
    'D_total_delta_W45_minus_W40_kg', 'D_total_relative_delta', ...
    'W40_P_loss_W1_mean_kW', 'W40_P_loss_W2_mean_kW', ...
    'W40_P_loss_W3_mean_kW', 'W45_P_loss_W1_mean_kW', ...
    'W45_P_loss_W2_mean_kW', 'W45_P_loss_W3_mean_kW', ...
    'W40_road_closed_W1_mean', 'W40_road_closed_W2_mean', ...
    'W40_road_closed_W3_mean', 'W45_road_closed_W1_mean', ...
    'W45_road_closed_W2_mean', 'W45_road_closed_W3_mean', ...
    'W40_line_pFail_p95_W1', 'W40_line_pFail_p95_W2', ...
    'W40_line_pFail_p95_W3', 'W45_line_pFail_p95_W1', ...
    'W45_line_pFail_p95_W2', 'W45_line_pFail_p95_W3', ...
    'W40_road_pClose_p95_W1', 'W40_road_pClose_p95_W2', ...
    'W40_road_pClose_p95_W3', 'W45_road_pClose_p95_W1', ...
    'W45_road_pClose_p95_W2', 'W45_road_pClose_p95_W3'});
end

function row = select_D_row(S, groupRow, wstep)
row = S(S.Rmax == groupRow.Rmax & S.a == groupRow.a & ...
    S.loc == groupRow.loc & S.Wstep == wstep, :);
if height(row) ~= 1
    error('compare_Wstep40_45_foundation_h2:MissingDRow', ...
        'Expected one D summary row per Rmax/Wstep/a/loc.');
end
end

function T = build_candidate_rmax_table(S, stageRisk, candidates, rmaxValues)
rows = {};
for cc = 1:numel(candidates)
    wstep = candidates(cc);
    for rr = 1:numel(rmaxValues)
        rmax = rmaxValues(rr);
        risk = select_risk_vectors(stageRisk, rmax, wstep);
        D = S(S.Rmax == rmax & S.Wstep == wstep, :);
        if isempty(D)
            error('compare_Wstep40_45_foundation_h2:MissingCandidateD', ...
                'Missing D rows for Rmax=%g Wstep=%g.', rmax, wstep);
        end
        lineW1Gain = risk.line(2) - risk.line(1);
        roadW1Gain = risk.road(2) - risk.road(1);
        combined = max(risk.line, risk.road);
        mainLine = max(risk.line(3:4));
        mainRoad = max(risk.road(3:4));
        mainCombined = max(combined(3:4));
        w1Enhanced = lineW1Gain >= max(0.05, 0.25 * risk.line(1)) || ...
            roadW1Gain >= max(0.03, 0.25 * risk.road(1));
        mainReached = mainCombined >= 0.5 && ...
            mainCombined >= 1.05 * combined(2);
        skipsMain = mainCombined + 0.02 < combined(2) || ...
            (mainLine < 0.25 && mainRoad < 0.25);
        D1 = mean(D.D_W1_mean_kg);
        D2 = mean(D.D_W2_mean_kg);
        D3 = mean(D.D_W3_mean_kg);
        Dtotal = mean(D.D_total_mean_kg);
        dMainShare = (D2 + D3) / max(Dtotal, eps);
        w1ToMain = combined(2) / max(mainCombined, eps);
        balanceScore = max(0, 1 - abs(w1ToMain - 0.55) / 0.55);
        progressionScore = 2 * double(w1Enhanced) + ...
            2 * double(mainReached) + 2 * double(~skipsMain) + ...
            balanceScore + dMainShare;
        rows(end + 1, :) = {wstep, rmax, risk.line(1), risk.line(2), ...
            mainLine, risk.road(1), risk.road(2), mainRoad, ...
            lineW1Gain, roadW1Gain, combined(2), mainCombined, ...
            w1ToMain, w1Enhanced, mainReached, skipsMain, ...
            D1, D2, D3, Dtotal, dMainShare, progressionScore}; %#ok<AGROW>
    end
end
T = cell2table(rows, 'VariableNames', ...
    {'candidate_Wstep', 'Rmax', 'line_pFail_p95_lf7', ...
    'line_pFail_p95_W1', 'line_pFail_p95_main_W2W3', ...
    'road_pClose_p95_lf7', 'road_pClose_p95_W1', ...
    'road_pClose_p95_main_W2W3', 'line_W1_gain_vs_lf7', ...
    'road_W1_gain_vs_lf7', 'combined_W1_risk', ...
    'combined_main_W2W3_risk', 'W1_to_main_risk_ratio', ...
    'W1_enhanced_pass', 'main_impact_reached_pass', ...
    'skips_main_impact_band', 'D_W1_mean_kg', 'D_W2_mean_kg', ...
    'D_W3_mean_kg', 'D_total_mean_kg', 'D_main_W2W3_share', ...
    'symmetric_progression_score'});
end

function T = add_symmetric_support(T, candidates)
n = height(T);
T.W1_not_earlier_than_other = false(n, 1);
T.main_line_not_worse_than_other = false(n, 1);
T.main_road_not_worse_than_other = false(n, 1);
T.D_main_share_not_worse_than_other = false(n, 1);
T.joint_support_vs_other = false(n, 1);
for ii = 1:n
    otherW = candidates(candidates ~= T.candidate_Wstep(ii));
    other = T(T.candidate_Wstep == otherW & T.Rmax == T.Rmax(ii), :);
    if height(other) ~= 1
        error('compare_Wstep40_45_foundation_h2:MissingSymmetricPair', ...
            'Missing candidate pair for Rmax=%g.', T.Rmax(ii));
    end
    T.W1_not_earlier_than_other(ii) = ...
        T.line_pFail_p95_W1(ii) <= other.line_pFail_p95_W1 + 1e-9 && ...
        T.road_pClose_p95_W1(ii) <= other.road_pClose_p95_W1 + 1e-9;
    T.main_line_not_worse_than_other(ii) = ...
        T.line_pFail_p95_main_W2W3(ii) >= ...
        other.line_pFail_p95_main_W2W3 - 0.02;
    T.main_road_not_worse_than_other(ii) = ...
        T.road_pClose_p95_main_W2W3(ii) >= ...
        other.road_pClose_p95_main_W2W3 - 0.05;
    T.D_main_share_not_worse_than_other(ii) = ...
        T.D_main_W2W3_share(ii) >= other.D_main_W2W3_share - 0.03;
    T.joint_support_vs_other(ii) = T.W1_not_earlier_than_other(ii) && ...
        T.main_line_not_worse_than_other(ii) && ...
        T.main_road_not_worse_than_other(ii) && ...
        T.D_main_share_not_worse_than_other(ii);
end
end

function S = summarize_candidates(T, candidates, rmaxValues)
rows = {};
for cc = 1:numel(candidates)
    wstep = candidates(cc);
    sub = T(T.candidate_Wstep == wstep, :);
    nRmax = numel(rmaxValues);
    w1Count = sum(sub.W1_enhanced_pass);
    mainCount = sum(sub.main_impact_reached_pass);
    skipCount = sum(sub.skips_main_impact_band);
    lowerW1Count = sum(sub.W1_not_earlier_than_other);
    jointCount = sum(sub.joint_support_vs_other);
    physicallyValid = w1Count >= ceil(2 * nRmax / 3) && ...
        mainCount == nRmax && skipCount == 0;
    rows(end + 1, :) = {wstep, nRmax, w1Count, mainCount, ...
        skipCount, lowerW1Count, sum(sub.main_line_not_worse_than_other), ...
        sum(sub.main_road_not_worse_than_other), ...
        sum(sub.D_main_share_not_worse_than_other), jointCount, ...
        jointCount == nRmax, physicallyValid, ...
        mean(sub.line_pFail_p95_W1), mean(sub.road_pClose_p95_W1), ...
        mean(sub.combined_main_W2W3_risk), mean(sub.D_total_mean_kg), ...
        mean(sub.D_main_W2W3_share), mean(sub.symmetric_progression_score)}; %#ok<AGROW>
end
S = cell2table(rows, 'VariableNames', ...
    {'candidate_Wstep', 'Rmax_count', 'W1_enhanced_Rmax_count', ...
    'main_impact_Rmax_count', 'skipped_main_band_Rmax_count', ...
    'lower_W1_risk_Rmax_count', 'main_line_not_worse_Rmax_count', ...
    'main_road_not_worse_Rmax_count', ...
    'D_main_share_not_worse_Rmax_count', 'joint_support_Rmax_count', ...
    'Rmax_ordering_stable', 'physically_valid', ...
    'mean_line_pFail_p95_W1', 'mean_road_pClose_p95_W1', ...
    'mean_main_W2W3_combined_risk', 'mean_D_total_kg', ...
    'mean_D_main_W2W3_share', 'mean_symmetric_progression_score'});
end

function out = select_risk_vectors(S, rmax, wstep)
sub = S(S.Rmax == rmax & S.Wstep == wstep, :);
sub = sortrows(sub, 'stage_index');
if height(sub) ~= 4
    error('compare_Wstep40_45_foundation_h2:MissingRiskRows', ...
        'Expected four stage-risk rows for Rmax=%g Wstep=%g.', rmax, wstep);
end
out = struct();
out.line = sub.line_pFail_p95_across_cases(:).';
out.road = sub.road_pClose_p95_across_cases(:).';
end

function r = relative_delta(value, base)
if abs(base) <= eps
    if abs(value) <= eps
        r = 0;
    else
        r = Inf;
    end
else
    r = (value - base) / abs(base);
end
end
