function [hresTbl, comparisonTbl, stateSaturationTbl, roadACTbl, ...
    checksTbl, diagnostics] = compare_damage_persistence_modes_v2_h2(result, config)
%COMPARE_DAMAGE_PERSISTENCE_MODES_V2_H2 Build v2 comparison and checks.

T = result.by_slice;
hresTbl = build_hres_summary(T, config);
stateSaturationTbl = build_state_saturation(T, result, config);
comparisonTbl = build_mode_comparison(stateSaturationTbl, hresTbl);
roadACTbl = build_road_ac_table(T);

[commonPass, commonEvidence, w1Pass] = check_common_random_numbers(T);
[fixedReusePass, fixedReuseEvidence] = check_fixed_threshold_reuse(T);
[fixedLineViol, fixedRoadViol, fixedSlowViol] = ...
    monotonic_violation_counts(T, "persistent_fixed_resistance");
[cumLineViol, cumRoadViol, cumSlowViol] = ...
    monotonic_violation_counts(T, "persistent_independent_draws");
[dTotalPass, dTotalError] = check_D_total(T, hresTbl);

expectedRows = numel(config.damageModes) * numel(config.RmaxValues) * ...
    numel(config.aValues) * numel(config.locValues) * config.Nmc * config.W;
expectedStateRows = numel(config.damageModes) * numel(config.RmaxValues) * ...
    numel(config.aValues) * numel(config.locValues) * config.W;
roadACPass = all(T.A_binary_ok) && all(T.reachable_C_all_finite) && ...
    all(T.unreachable_C_excluded_from_statistics) && ...
    all(T.finite_C_count == T.reachable_pair_count);

[oldOutputPass, oldOutputEvidence] = verify_old_outputs(config);
[mspFilePass, mspEvidence] = verify_msp_files(config);
sourceScan = scan_sources(config.executedSourceFiles);
[wstepConfigPass, wstepEvidence] = verify_wstep_configuration(config);

rmaxAggregate = build_rmax_aggregate(T, hresTbl, config);
overestimateByRmax = build_overestimate_by_rmax(rmaxAggregate);
overallCum = mean(hresTbl.D_Hres3h_total_kg( ...
    hresTbl.damage_mode == "persistent_independent_draws"));
overallFixed = mean(hresTbl.D_Hres3h_total_kg( ...
    hresTbl.damage_mode == "persistent_fixed_resistance"));
overallOverestimate = overallCum - overallFixed;
overallOverestimateRelative = relative_delta(overallCum, overallFixed);
overestimateDetected = overallOverestimateRelative >= config.overestimateThreshold;

fixedStageDistinction = build_fixed_stage_distinction(T, config);
fixedStageDistinctionPass = all(fixedStageDistinction.D_stage_range_ratio >= ...
    config.stageDistinctionThreshold | ...
    fixedStageDistinction.failed_line_stage_range_ratio >= ...
    config.stageDistinctionThreshold);
fixedAggregateSaturation = build_fixed_aggregate_saturation(T, result, config);
maxFixedAggregateSaturation = max(fixedAggregateSaturation.max_saturation_share);
fixedMassSaturation = maxFixedAggregateSaturation >= config.massSaturationThreshold;

checks = {
    "expected_by_slice_row_count", height(T) == expectedRows, height(T), ...
    compose("expected %d", expectedRows), "";
    "three_modes_present", isequal(sort(unique(T.damage_mode)), ...
    sort(config.damageModes(:))), numel(unique(T.damage_mode)), ...
    strjoin(unique(T.damage_mode), " | "), "";
    "common_random_numbers_base_inputs", commonPass, NaN, commonEvidence, "";
    "W1_identical_across_modes", w1Pass, NaN, ...
    "all modes use the W1 stage draw before inheritance differs", "";
    "fixed_component_threshold_reused_W1_W3", fixedReusePass, NaN, ...
    fixedReuseEvidence, "";
    "fixed_failed_lines_nondecreasing", fixedLineViol == 0, fixedLineViol, ...
    "checked by Rmax/a/loc/scenario", "";
    "fixed_closed_roads_nondecreasing", fixedRoadViol == 0, fixedRoadViol, ...
    "checked by Rmax/a/loc/scenario", "";
    "fixed_slowdown_nondecreasing", fixedSlowViol == 0, fixedSlowViol, ...
    "checked by Rmax/a/loc/scenario", "";
    "cumulative_draw_failed_lines_nondecreasing", cumLineViol == 0, cumLineViol, ...
    "persistent independent draws retain cumulative OR", "";
    "cumulative_draw_closed_roads_nondecreasing", cumRoadViol == 0, cumRoadViol, ...
    "persistent independent draws retain cumulative OR", "";
    "cumulative_draw_slowdown_nondecreasing", cumSlowViol == 0, cumSlowViol, ...
    "persistent independent draws retain cumulative max", "";
    "D_total_is_W1_W2_W3_sum", dTotalPass, dTotalError, ...
    "scenario Hres3h total independently compared with slice rows", "";
    "slice_duration_is_1h", all(abs(T.slice_duration_h - 1) <= 1e-12), ...
    config.sliceDurationH, "all output slices", "";
    "Hres_total_is_3h", all(abs(hresTbl.Hres_total_h - 3) <= 1e-12), ...
    config.HresTotalH, "W1+W2+W3 only", "";
    "road_A_C_diagnostics_valid", roadACPass, ...
    sum(~T.A_binary_ok | ~T.reachable_C_all_finite | ...
    ~T.unreachable_C_excluded_from_statistics), ...
    "A is binary; reachable C is finite; unreachable C is excluded", "";
    "C_definition_is_dist_n", all(T.C_definition == config.CDefinition), NaN, ...
    "formal service cost is the current shortest path dist(n)", "";
    "state_level_saturation_row_count", height(stateSaturationTbl) == expectedStateRows, ...
    height(stateSaturationTbl), compose("expected %d", expectedStateRows), "";
    "Wstep_read_from_config_in_evaluator", wstepConfigPass, config.Wstep, ...
    wstepEvidence, "";
    "no_repair_mechanism", all(T.repair_enabled == 0), NaN, ...
    "repair_enabled is false for every row", "";
    "protected_old_outputs_unchanged", oldOutputPass, NaN, ...
    oldOutputEvidence, "";
    "protected_MSP_files_unchanged", mspFilePass, NaN, mspEvidence, "";
    "no_WDRO_or_Gurobi_call", sourceScan.no_WDRO_call, ...
    sourceScan.WDRO_call_hit_count, "executed-source call scan", "";
    "no_MSP_call", sourceScan.no_MSP_call, sourceScan.MSP_call_hit_count, ...
    "executed-source call scan", "";
    "no_Stage2A2_path_prob_B3_Stage2C_call", sourceScan.no_B3_call, ...
    sourceScan.B3_call_hit_count, "executed-source call scan", "";
    "fixed_stage_distinction_diagnostic", NaN, ...
    min(fixedStageDistinction.D_stage_range_ratio), ...
    "minimum fixed-resistance D stage range ratio by Rmax", ...
    conditional_warning(~fixedStageDistinctionPass, ...
    "fixed-resistance mode has weak stage distinction");
    "fixed_mass_saturation_diagnostic", NaN, maxFixedAggregateSaturation, ...
    compose("aggregate threshold %.3g", config.massSaturationThreshold), ...
    conditional_warning(fixedMassSaturation, ...
    "fixed-resistance mode shows mass saturation in an aggregate stage");
    "cumulative_OR_overestimate_diagnostic", NaN, overallOverestimateRelative, ...
    compose("cumulative minus fixed D total = %.12g kg", overallOverestimate), ...
    conditional_warning(overestimateDetected, ...
    "persistent independent draws materially exceed fixed resistance")};
checksTbl = cell2table(checks, 'VariableNames', ...
    {'check_name', 'passed', 'observed_value', 'evidence', 'warning'});

requiredPass = all(checksTbl.passed(~isnan(checksTbl.passed)) == 1);
if requiredPass && fixedReusePass && fixedLineViol == 0 && fixedRoadViol == 0
    B3Recommendation = "recommend_persistent_fixed_resistance";
else
    B3Recommendation = "inconclusive_requires_fix_before_B3";
end

diagnostics = struct();
diagnostics.common_random_numbers_pass = commonPass;
diagnostics.common_random_numbers_evidence = commonEvidence;
diagnostics.W1_identical_across_modes = w1Pass;
diagnostics.fixed_threshold_reuse_pass = fixedReusePass;
diagnostics.fixed_threshold_reuse_evidence = fixedReuseEvidence;
diagnostics.fixed_line_monotonic_violation_count = fixedLineViol;
diagnostics.fixed_road_monotonic_violation_count = fixedRoadViol;
diagnostics.fixed_slowdown_monotonic_violation_count = fixedSlowViol;
diagnostics.cumulative_line_monotonic_violation_count = cumLineViol;
diagnostics.cumulative_road_monotonic_violation_count = cumRoadViol;
diagnostics.cumulative_slowdown_monotonic_violation_count = cumSlowViol;
diagnostics.rmax_aggregate = rmaxAggregate;
diagnostics.overestimate_by_rmax = overestimateByRmax;
diagnostics.overall_cumulative_D_mean_kg = overallCum;
diagnostics.overall_fixed_D_mean_kg = overallFixed;
diagnostics.overall_cumulative_minus_fixed_D_kg = overallOverestimate;
diagnostics.overall_cumulative_minus_fixed_D_relative = overallOverestimateRelative;
diagnostics.cumulative_overestimate_detected = overestimateDetected;
diagnostics.fixed_stage_distinction = fixedStageDistinction;
diagnostics.fixed_stage_distinction_pass = fixedStageDistinctionPass;
diagnostics.fixed_aggregate_saturation = fixedAggregateSaturation;
diagnostics.max_fixed_aggregate_saturation_share = maxFixedAggregateSaturation;
diagnostics.fixed_mass_saturation_detected = fixedMassSaturation;
diagnostics.old_output_pass = oldOutputPass;
diagnostics.msp_file_pass = mspFilePass;
diagnostics.source_scan = sourceScan;
diagnostics.wstep_config_pass = wstepConfigPass;
diagnostics.required_check_pass = requiredPass;
diagnostics.B3_recommendation = B3Recommendation;
end

function H = build_hres_summary(T, config)
groups = unique(T(:, {'damage_mode','Rmax','Wstep','a','loc','scenario_id'}), ...
    'rows');
groups = sortrows(groups, {'damage_mode','Rmax','a','loc','scenario_id'});
rows = cell(height(groups), 33);
for gg = 1:height(groups)
    q = T(T.damage_mode == groups.damage_mode(gg) & ...
        T.Rmax == groups.Rmax(gg) & T.Wstep == groups.Wstep(gg) & ...
        T.a == groups.a(gg) & T.loc == groups.loc(gg) & ...
        T.scenario_id == groups.scenario_id(gg), :);
    q = sortrows(q, 'stage_index');
    onlyW = height(q) == 3 && isequal(string(q.stage), ["W1";"W2";"W3"]);
    if ~onlyW
        error('compare_damage_persistence_modes_v2_h2:BadScenarioStages', ...
            'Every scenario must contain W1, W2, and W3 exactly once.');
    end
    rows(gg, :) = {groups.damage_mode(gg), groups.Rmax(gg), ...
        groups.Wstep(gg), groups.a(gg), groups.loc(gg), ...
        groups.scenario_id(gg), q.common_random_seed(1), ...
        q.P_loss_total_kW(1), q.P_loss_total_kW(2), q.P_loss_total_kW(3), ...
        q.D_slice_total_kg(1), q.D_slice_total_kg(2), q.D_slice_total_kg(3), ...
        sum(q.D_slice_total_kg), q.failed_line_count(1), ...
        q.failed_line_count(2), q.failed_line_count(3), ...
        q.closed_road_count(1), q.closed_road_count(2), q.closed_road_count(3), ...
        q.slow_road_count(1), q.slow_road_count(2), q.slow_road_count(3), ...
        q.reachable_pair_share(1), q.reachable_pair_share(2), ...
        q.reachable_pair_share(3), q.C_finite_mean(1), q.C_finite_mean(2), ...
        q.C_finite_mean(3), config.sliceDurationH, ...
        sum(q.slice_duration_h), height(q), onlyW};
end
H = cell2table(rows, 'VariableNames', ...
    {'damage_mode','Rmax','Wstep','a','loc','scenario_id', ...
    'common_random_seed','P_loss_W1_kW','P_loss_W2_kW','P_loss_W3_kW', ...
    'D_W1_kg','D_W2_kg','D_W3_kg','D_Hres3h_total_kg', ...
    'failed_line_W1','failed_line_W2','failed_line_W3', ...
    'closed_road_W1','closed_road_W2','closed_road_W3', ...
    'slow_road_W1','slow_road_W2','slow_road_W3', ...
    'reachable_pair_share_W1','reachable_pair_share_W2', ...
    'reachable_pair_share_W3','C_finite_mean_W1','C_finite_mean_W2', ...
    'C_finite_mean_W3','slice_duration_h','Hres_total_h', ...
    'stage_count','contains_only_W1_W2_W3'});
end

function S = build_state_saturation(T, result, config)
groups = unique(T(:, {'damage_mode','Rmax','Wstep','a','loc','stage','stage_index'}), ...
    'rows');
groups = sortrows(groups, {'damage_mode','Rmax','a','loc','stage_index'});
rows = cell(height(groups), 22);
for gg = 1:height(groups)
    q = T(T.damage_mode == groups.damage_mode(gg) & ...
        T.Rmax == groups.Rmax(gg) & T.Wstep == groups.Wstep(gg) & ...
        T.a == groups.a(gg) & T.loc == groups.loc(gg) & ...
        T.stage_index == groups.stage_index(gg), :);
    lineSat = mean(q.failed_line_count >= result.n_lines);
    roadSat = mean(q.closed_road_count >= result.n_roads);
    loadSat = mean(q.P_loss_total_kW >= ...
        result.max_P_loss_kW - config.fullLossTolerance);
    dSat = mean(q.D_slice_total_kg >= ...
        result.max_D_slice_kg - config.fullLossTolerance);
    rows(gg, :) = {groups.damage_mode(gg), groups.Rmax(gg), ...
        groups.Wstep(gg), groups.a(gg), groups.loc(gg), groups.stage(gg), ...
        groups.stage_index(gg), height(q), lineSat, roadSat, loadSat, dSat, ...
        mean(q.failed_line_count), mean(q.closed_road_count), ...
        mean(q.slow_road_count), mean(q.P_loss_total_kW), ...
        mean(q.D_slice_total_kg), mean(q.reachable_pair_share), ...
        mean_finite(q.C_finite_mean), mean_finite(q.C_finite_p95), ...
        mean(q.finite_C_count == 0), max([lineSat,roadSat,loadSat,dSat])};
end
S = cell2table(rows, 'VariableNames', ...
    {'damage_mode','Rmax','Wstep','a','loc','stage','stage_index', ...
    'scenario_count','full_line_failure_share','full_road_closure_share', ...
    'full_load_loss_share','full_D_slice_share','failed_line_count_mean', ...
    'closed_road_count_mean','slow_road_count_mean','P_loss_mean_kW', ...
    'D_slice_mean_kg','reachable_pair_share_mean','C_finite_mean', ...
    'C_finite_p95_mean','no_finite_C_scenario_share','max_saturation_share'});
end

function C = build_mode_comparison(S, H)
groups = unique(S(:, {'Rmax','Wstep','a','loc','stage','stage_index'}), 'rows');
groups = sortrows(groups, {'Rmax','a','loc','stage_index'});
rows = cell(height(groups), 57);
for gg = 1:height(groups)
    ind = select_state_mode(S, groups(gg,:), "independent_snapshot");
    cum = select_state_mode(S, groups(gg,:), "persistent_independent_draws");
    fix = select_state_mode(S, groups(gg,:), "persistent_fixed_resistance");
    hInd = H(H.damage_mode == "independent_snapshot" & ...
        H.Rmax == groups.Rmax(gg) & H.a == groups.a(gg) & ...
        H.loc == groups.loc(gg), :);
    hCum = H(H.damage_mode == "persistent_independent_draws" & ...
        H.Rmax == groups.Rmax(gg) & H.a == groups.a(gg) & ...
        H.loc == groups.loc(gg), :);
    hFix = H(H.damage_mode == "persistent_fixed_resistance" & ...
        H.Rmax == groups.Rmax(gg) & H.a == groups.a(gg) & ...
        H.loc == groups.loc(gg), :);
    rows(gg, :) = {groups.Rmax(gg), groups.Wstep(gg), groups.a(gg), ...
        groups.loc(gg), groups.stage(gg), groups.stage_index(gg), ...
        ind.failed_line_count_mean, cum.failed_line_count_mean, ...
        fix.failed_line_count_mean, cum.failed_line_count_mean-fix.failed_line_count_mean, ...
        relative_delta(cum.failed_line_count_mean,fix.failed_line_count_mean), ...
        ind.closed_road_count_mean,cum.closed_road_count_mean,fix.closed_road_count_mean, ...
        cum.closed_road_count_mean-fix.closed_road_count_mean, ...
        relative_delta(cum.closed_road_count_mean,fix.closed_road_count_mean), ...
        ind.slow_road_count_mean,cum.slow_road_count_mean,fix.slow_road_count_mean, ...
        cum.slow_road_count_mean-fix.slow_road_count_mean, ...
        relative_delta(cum.slow_road_count_mean,fix.slow_road_count_mean), ...
        ind.P_loss_mean_kW,cum.P_loss_mean_kW,fix.P_loss_mean_kW, ...
        cum.P_loss_mean_kW-fix.P_loss_mean_kW, ...
        relative_delta(cum.P_loss_mean_kW,fix.P_loss_mean_kW), ...
        ind.D_slice_mean_kg,cum.D_slice_mean_kg,fix.D_slice_mean_kg, ...
        cum.D_slice_mean_kg-fix.D_slice_mean_kg, ...
        relative_delta(cum.D_slice_mean_kg,fix.D_slice_mean_kg), ...
        ind.reachable_pair_share_mean,cum.reachable_pair_share_mean, ...
        fix.reachable_pair_share_mean, ...
        cum.reachable_pair_share_mean-fix.reachable_pair_share_mean, ...
        relative_delta(cum.reachable_pair_share_mean,fix.reachable_pair_share_mean), ...
        ind.C_finite_mean,cum.C_finite_mean,fix.C_finite_mean, ...
        cum.C_finite_mean-fix.C_finite_mean, ...
        relative_delta(cum.C_finite_mean,fix.C_finite_mean), ...
        ind.full_load_loss_share,cum.full_load_loss_share,fix.full_load_loss_share, ...
        cum.full_load_loss_share-fix.full_load_loss_share, ...
        ind.full_road_closure_share,cum.full_road_closure_share, ...
        fix.full_road_closure_share,cum.full_road_closure_share-fix.full_road_closure_share, ...
        mean(hInd.D_Hres3h_total_kg),mean(hCum.D_Hres3h_total_kg), ...
        mean(hFix.D_Hres3h_total_kg), ...
        mean(hCum.D_Hres3h_total_kg)-mean(hFix.D_Hres3h_total_kg), ...
        relative_delta(mean(hCum.D_Hres3h_total_kg),mean(hFix.D_Hres3h_total_kg)), ...
        pct(hInd.D_Hres3h_total_kg,95),pct(hCum.D_Hres3h_total_kg,95), ...
        pct(hFix.D_Hres3h_total_kg,95)};
end
C = cell2table(rows, 'VariableNames', ...
    {'Rmax','Wstep','a','loc','stage','stage_index', ...
    'ind_failed_mean','cumulative_failed_mean','fixed_failed_mean', ...
    'cumulative_minus_fixed_failed','cumulative_vs_fixed_failed_relative', ...
    'ind_closed_mean','cumulative_closed_mean','fixed_closed_mean', ...
    'cumulative_minus_fixed_closed','cumulative_vs_fixed_closed_relative', ...
    'ind_slow_mean','cumulative_slow_mean','fixed_slow_mean', ...
    'cumulative_minus_fixed_slow','cumulative_vs_fixed_slow_relative', ...
    'ind_P_loss_mean_kW','cumulative_P_loss_mean_kW','fixed_P_loss_mean_kW', ...
    'cumulative_minus_fixed_P_loss_kW','cumulative_vs_fixed_P_loss_relative', ...
    'ind_D_slice_mean_kg','cumulative_D_slice_mean_kg','fixed_D_slice_mean_kg', ...
    'cumulative_minus_fixed_D_slice_kg','cumulative_vs_fixed_D_slice_relative', ...
    'ind_reachable_pair_share','cumulative_reachable_pair_share', ...
    'fixed_reachable_pair_share','cumulative_minus_fixed_reachable_share', ...
    'cumulative_vs_fixed_reachable_relative', ...
    'ind_C_finite_mean','cumulative_C_finite_mean','fixed_C_finite_mean', ...
    'cumulative_minus_fixed_C_mean','cumulative_vs_fixed_C_relative', ...
    'ind_full_load_loss_share','cumulative_full_load_loss_share', ...
    'fixed_full_load_loss_share','cumulative_minus_fixed_full_load_share', ...
    'ind_full_road_closure_share','cumulative_full_road_closure_share', ...
    'fixed_full_road_closure_share','cumulative_minus_fixed_full_road_share', ...
    'ind_D_Hres3h_mean_kg','cumulative_D_Hres3h_mean_kg', ...
    'fixed_D_Hres3h_mean_kg','cumulative_minus_fixed_D_Hres3h_kg', ...
    'cumulative_vs_fixed_D_Hres3h_relative','ind_D_Hres3h_p95_kg', ...
    'cumulative_D_Hres3h_p95_kg','fixed_D_Hres3h_p95_kg'});
end

function row = select_state_mode(S, group, mode)
row = S(S.Rmax == group.Rmax & S.Wstep == group.Wstep & ...
    S.a == group.a & S.loc == group.loc & ...
    S.stage_index == group.stage_index & S.damage_mode == mode, :);
if height(row) ~= 1
    error('compare_damage_persistence_modes_v2_h2:MissingModeRow', ...
        'Expected one state/stage row for mode %s.', mode);
end
end

function R = build_road_ac_table(T)
names = {'damage_mode','Rmax','Wstep','a','loc','stage','stage_index', ...
    'scenario_id','common_random_seed','reachable_pair_count', ...
    'reachable_pair_share','finite_C_count','C_finite_mean','C_finite_p95', ...
    'C_finite_max','unreachable_pair_count','A_binary_ok', ...
    'reachable_C_all_finite','unreachable_C_excluded_from_statistics', ...
    'closed_road_count','slow_road_count','slowdown_severity_mean', ...
    'slowdown_severity_max','C_definition'};
R = T(:, names);
end

function [pass, evidence, w1Pass] = check_common_random_numbers(T)
[G,~] = findgroups(T(:, {'Rmax','Wstep','a','loc','stage_index','scenario_id'}));
countPass = all(splitapply(@numel, T.Rmax, G) == 3);
seedPass = all(splitapply(@same_numeric, T.common_random_seed, G));
linePass = all(splitapply(@same_numeric, T.base_line_stage_uniform_checksum, G));
roadPass = all(splitapply(@same_numeric, T.base_road_stage_uniform_checksum, G));
fixedLinePass = all(splitapply(@same_numeric, T.fixed_line_threshold_checksum, G));
fixedRoadPass = all(splitapply(@same_numeric, T.fixed_road_threshold_checksum, G));
probPass = all(splitapply(@same_two_numeric, T.line_pFail_mean, ...
    T.road_pClose_mean, G));
pass = countPass && seedPass && linePass && roadPass && ...
    fixedLinePass && fixedRoadPass && probPass;

W1 = T(T.stage_index == 1, :);
[G1,~] = findgroups(W1(:, {'Rmax','Wstep','a','loc','scenario_id'}));
w1Pass = all(splitapply(@same_numeric, W1.failed_line_count, G1)) && ...
    all(splitapply(@same_numeric, W1.closed_road_count, G1)) && ...
    all(splitapply(@same_numeric, W1.P_loss_total_kW, G1)) && ...
    all(splitapply(@same_numeric, W1.D_slice_total_kg, G1)) && ...
    all(splitapply(@same_numeric, W1.reachable_pair_share, G1)) && ...
    all(splitapply(@same_numeric_nan, W1.C_finite_mean, G1));
evidence = string(sprintf(['rows_per_group=%d; seed=%d; base_line=%d; ' ...
    'base_road=%d; fixed_line=%d; fixed_road=%d; probability=%d; W1=%d'], ...
    countPass,seedPass,linePass,roadPass,fixedLinePass,fixedRoadPass,probPass,w1Pass));
end

function [pass, evidence] = check_fixed_threshold_reuse(T)
F = T(T.damage_mode == "persistent_fixed_resistance", :);
errorPass = all(F.fixed_line_threshold_reuse_max_abs_error <= 1e-12) && ...
    all(F.fixed_road_threshold_reuse_max_abs_error <= 1e-12);
[G,~] = findgroups(F(:, {'Rmax','Wstep','a','loc','scenario_id'}));
lineStagePass = all(splitapply(@same_numeric, ...
    F.applied_line_threshold_checksum, G));
roadStagePass = all(splitapply(@same_numeric, ...
    F.applied_road_threshold_checksum, G));
lineFixedPass = all(abs(F.applied_line_threshold_checksum - ...
    F.fixed_line_threshold_checksum) <= 1e-12);
roadFixedPass = all(abs(F.applied_road_threshold_checksum - ...
    F.fixed_road_threshold_checksum) <= 1e-12);
W1 = F(F.stage_index == 1, :);
w1SourcePass = all(abs(W1.fixed_line_threshold_checksum - ...
    W1.base_line_stage_uniform_checksum) <= 1e-12) && ...
    all(abs(W1.fixed_road_threshold_checksum - ...
    W1.base_road_stage_uniform_checksum) <= 1e-12);
pass = errorPass && lineStagePass && roadStagePass && ...
    lineFixedPass && roadFixedPass && w1SourcePass;
evidence = string(sprintf(['exact_error=%d; line_across_stage=%d; ' ...
    'road_across_stage=%d; applied_equals_fixed=%d/%d; W1_source=%d'], ...
    errorPass,lineStagePass,roadStagePass,lineFixedPass,roadFixedPass,w1SourcePass));
end

function [lineViol, roadViol, slowViol] = monotonic_violation_counts(T, mode)
sub = T(T.damage_mode == mode, :);
groups = unique(sub(:, {'Rmax','a','loc','scenario_id'}), 'rows');
lineViol = 0;
roadViol = 0;
slowViol = 0;
for gg = 1:height(groups)
    q = sub(sub.Rmax == groups.Rmax(gg) & sub.a == groups.a(gg) & ...
        sub.loc == groups.loc(gg) & sub.scenario_id == groups.scenario_id(gg), :);
    q = sortrows(q, 'stage_index');
    lineViol = lineViol + any(diff(q.failed_line_count) < 0);
    roadViol = roadViol + any(diff(q.closed_road_count) < 0);
    slowViol = slowViol + any(diff(q.slowdown_severity_mean) < -1e-12);
end
end

function [pass, maxError] = check_D_total(T, H)
maxError = 0;
for ii = 1:height(H)
    q = T(T.damage_mode == H.damage_mode(ii) & T.Rmax == H.Rmax(ii) & ...
        T.Wstep == H.Wstep(ii) & T.a == H.a(ii) & T.loc == H.loc(ii) & ...
        T.scenario_id == H.scenario_id(ii), :);
    q = sortrows(q, 'stage_index');
    if height(q) ~= 3 || ~isequal(string(q.stage), ["W1";"W2";"W3"])
        pass = false;
        maxError = Inf;
        return;
    end
    maxError = max(maxError, abs(sum(q.D_slice_total_kg) - ...
        H.D_Hres3h_total_kg(ii)));
end
pass = maxError <= 1e-9;
end

function A = build_rmax_aggregate(T, H, config)
rows = cell(numel(config.damageModes)*numel(config.RmaxValues), 17);
rr = 0;
for mode = config.damageModes(:).'
    for rmax = config.RmaxValues(:).'
        rr = rr + 1;
        q = T(T.damage_mode == mode & T.Rmax == rmax, :);
        stage = zeros(3,5);
        for ss = 1:3
            z = q(q.stage_index == ss, :);
            stage(ss,:) = [mean(z.failed_line_count),mean(z.closed_road_count), ...
                mean(z.P_loss_total_kW),mean(z.D_slice_total_kg), ...
                mean(z.reachable_pair_share)];
        end
        h = H(H.damage_mode == mode & H.Rmax == rmax, :);
        rows(rr,:) = {mode,rmax,stage(1,1),stage(2,1),stage(3,1), ...
            stage(1,2),stage(2,2),stage(3,2),stage(1,3),stage(2,3),stage(3,3), ...
            stage(1,4),stage(2,4),stage(3,4),mean(h.D_Hres3h_total_kg), ...
            pct(h.D_Hres3h_total_kg,95),mean(stage(:,5))};
    end
end
A = cell2table(rows, 'VariableNames', ...
    {'damage_mode','Rmax','failed_W1_mean','failed_W2_mean','failed_W3_mean', ...
    'closed_W1_mean','closed_W2_mean','closed_W3_mean', ...
    'P_loss_W1_mean_kW','P_loss_W2_mean_kW','P_loss_W3_mean_kW', ...
    'D_W1_mean_kg','D_W2_mean_kg','D_W3_mean_kg', ...
    'D_Hres3h_mean_kg','D_Hres3h_p95_kg','reachable_pair_share_stage_mean'});
end

function O = build_overestimate_by_rmax(A)
rmaxValues = unique(A.Rmax);
rows = cell(numel(rmaxValues), 10);
for ii = 1:numel(rmaxValues)
    r = rmaxValues(ii);
    cum = A(A.Rmax == r & A.damage_mode == "persistent_independent_draws", :);
    fix = A(A.Rmax == r & A.damage_mode == "persistent_fixed_resistance", :);
    rows(ii,:) = {r,cum.D_Hres3h_mean_kg,fix.D_Hres3h_mean_kg, ...
        cum.D_Hres3h_mean_kg-fix.D_Hres3h_mean_kg, ...
        relative_delta(cum.D_Hres3h_mean_kg,fix.D_Hres3h_mean_kg), ...
        mean([cum.failed_W1_mean,cum.failed_W2_mean,cum.failed_W3_mean])- ...
        mean([fix.failed_W1_mean,fix.failed_W2_mean,fix.failed_W3_mean]), ...
        mean([cum.closed_W1_mean,cum.closed_W2_mean,cum.closed_W3_mean])- ...
        mean([fix.closed_W1_mean,fix.closed_W2_mean,fix.closed_W3_mean]), ...
        mean([cum.P_loss_W1_mean_kW,cum.P_loss_W2_mean_kW,cum.P_loss_W3_mean_kW])- ...
        mean([fix.P_loss_W1_mean_kW,fix.P_loss_W2_mean_kW,fix.P_loss_W3_mean_kW]), ...
        cum.reachable_pair_share_stage_mean-fix.reachable_pair_share_stage_mean, ...
        cum.D_Hres3h_p95_kg-fix.D_Hres3h_p95_kg};
end
O = cell2table(rows, 'VariableNames', ...
    {'Rmax','cumulative_D_Hres3h_mean_kg','fixed_D_Hres3h_mean_kg', ...
    'cumulative_minus_fixed_D_mean_kg','cumulative_vs_fixed_D_relative', ...
    'failed_line_stage_mean_delta','closed_road_stage_mean_delta', ...
    'P_loss_stage_mean_delta_kW','reachable_pair_share_delta', ...
    'D_Hres3h_p95_delta_kg'});
end

function D = build_fixed_stage_distinction(T, config)
rows = cell(numel(config.RmaxValues), 5);
for ii = 1:numel(config.RmaxValues)
    r = config.RmaxValues(ii);
    q = T(T.damage_mode == "persistent_fixed_resistance" & T.Rmax == r, :);
    failed = zeros(1,3); closed = zeros(1,3); pLoss = zeros(1,3); d = zeros(1,3);
    for ss = 1:3
        z = q(q.stage_index == ss,:);
        failed(ss)=mean(z.failed_line_count);closed(ss)=mean(z.closed_road_count);
        pLoss(ss)=mean(z.P_loss_total_kW);d(ss)=mean(z.D_slice_total_kg);
    end
    rows(ii,:)={r,normalized_range(failed),normalized_range(closed), ...
        normalized_range(pLoss),normalized_range(d)};
end
D=cell2table(rows,'VariableNames',{'Rmax','failed_line_stage_range_ratio', ...
    'closed_road_stage_range_ratio','P_loss_stage_range_ratio','D_stage_range_ratio'});
end

function S = build_fixed_aggregate_saturation(T, result, config)
rows=cell(numel(config.RmaxValues)*3,7);rr=0;
for r=config.RmaxValues(:).'
    for ss=1:3
        q=T(T.damage_mode=="persistent_fixed_resistance" & T.Rmax==r & ...
            T.stage_index==ss,:);rr=rr+1;
        line=mean(q.failed_line_count>=result.n_lines);
        road=mean(q.closed_road_count>=result.n_roads);
        load=mean(q.P_loss_total_kW>=result.max_P_loss_kW-config.fullLossTolerance);
        d=mean(q.D_slice_total_kg>=result.max_D_slice_kg-config.fullLossTolerance);
        rows(rr,:)={r,ss,line,road,load,d,max([line,road,load,d])};
    end
end
S=cell2table(rows,'VariableNames',{'Rmax','stage_index','line_saturation_share', ...
    'road_saturation_share','load_saturation_share','D_saturation_share', ...
    'max_saturation_share'});
end

function [pass,evidence]=verify_old_outputs(config)
after=snapshot_directories(config.protectedOutputDirs);b=config.protectedOutputBefore;
pass=isequal(b.file_count,after.file_count) && ...
    all(abs(b.latest_datenum-after.latest_datenum)<=1e-12 | ...
    (isnan(b.latest_datenum)&isnan(after.latest_datenum))) && ...
    isequal(b.total_bytes,after.total_bytes);
evidence=string(sprintf('protected directories=%d; unchanged=%d',height(b),pass));
end

function [pass,evidence]=verify_msp_files(config)
after=snapshot_files(config.protectedMSPFiles);b=config.protectedMSPBefore;
pass=isequal(b.exists,after.exists) && ...
    all(abs(b.datenum-after.datenum)<=1e-12 | ...
    (isnan(b.datenum)&isnan(after.datenum))) && isequal(b.bytes,after.bytes);
evidence=string(sprintf('protected MSP files=%d; unchanged=%d',height(b),pass));
end

function [pass,evidence]=verify_wstep_configuration(config)
sourceFile=fullfile(config.moduleDir,'src','evaluate_fixed_resistance_damage_h2.m');
text=strip_comments(string(fileread(sourceFile)));
usesConfig=contains(text,'config.Wstep');
hardcodedStage=~isempty(regexp(text,'damageStageOffsets\s*\([^\)]*\)\s*\*\s*40','once'));
hardcodedAssignment=~isempty(regexp(text,'Wstep\s*=\s*40','once'));
pass=usesConfig && ~hardcodedStage && ~hardcodedAssignment;
evidence=string(sprintf('uses_config=%d; hardcoded_stage=%d; hardcoded_assignment=%d', ...
    usesConfig,hardcodedStage,hardcodedAssignment));
end

function scan=scan_sources(files)
wdro=["solve_wdro_terminal_loh_lp_h2\\s*\\(","gurobi\\s*\\("];
msp=["run_h2_with_options\\s*\\(","train_models_h2\\s*\\(", ...
    "forward_pass_h2\\s*\\(","backward_pass_h2\\s*\\(", ...
    "main_msp_h2_near\\s*\\("];
b3=["run_[A-Za-z0-9_]*Stage2A2[A-Za-z0-9_]*\\s*\\(", ...
    "compute_[A-Za-z0-9_]*path_prob[A-Za-z0-9_]*\\s*\\(", ...
    "run_[A-Za-z0-9_]*B3[A-Za-z0-9_]*\\s*\\(", ...
    "run_stage2C[^\\n]*\\("];
w=0;m=0;b=0;
for ii=1:numel(files)
    text=strip_comments(string(fileread(files{ii})));
    w=w+count_patterns(text,wdro);m=m+count_patterns(text,msp);b=b+count_patterns(text,b3);
end
scan=struct('WDRO_call_hit_count',w,'MSP_call_hit_count',m,'B3_call_hit_count',b, ...
    'no_WDRO_call',w==0,'no_MSP_call',m==0,'no_B3_call',b==0);
end

function T=snapshot_directories(paths)
T=table(strings(numel(paths),1),zeros(numel(paths),1),zeros(numel(paths),1), ...
    zeros(numel(paths),1),'VariableNames',{'path','file_count','latest_datenum','total_bytes'});
for ii=1:numel(paths)
    T.path(ii)=string(paths{ii});
    if ~isfolder(paths{ii}),T.file_count(ii)=-1;T.latest_datenum(ii)=NaN;T.total_bytes(ii)=-1;continue;end
    x=dir(fullfile(paths{ii},'**','*'));x=x(~[x.isdir]);T.file_count(ii)=numel(x);
    if isempty(x),T.latest_datenum(ii)=0;T.total_bytes(ii)=0;else,T.latest_datenum(ii)=max([x.datenum]);T.total_bytes(ii)=sum([x.bytes]);end
end
end

function T=snapshot_files(paths)
T=table(strings(numel(paths),1),false(numel(paths),1),zeros(numel(paths),1), ...
    zeros(numel(paths),1),'VariableNames',{'path','exists','datenum','bytes'});
for ii=1:numel(paths)
    T.path(ii)=string(paths{ii});T.exists(ii)=isfile(paths{ii});
    if T.exists(ii),x=dir(paths{ii});T.datenum(ii)=x.datenum;T.bytes(ii)=x.bytes;else,T.datenum(ii)=NaN;T.bytes(ii)=-1;end
end
end

function tf=same_numeric(x),tf=max(double(x))-min(double(x))<=1e-12;end
function tf=same_numeric_nan(x)
x=double(x);tf=(all(isnan(x)) || (all(isfinite(x)) && max(x)-min(x)<=1e-12));
end
function tf=same_two_numeric(x,y),tf=same_numeric(x)&&same_numeric(y);end
function n=count_patterns(text,patterns)
n=0;for ii=1:numel(patterns),n=n+numel(regexp(text,patterns(ii),'match','ignorecase'));end
end
function text=strip_comments(text)
lines=splitlines(text);for ii=1:numel(lines),p=strfind(lines(ii),'%');if ~isempty(p),lines(ii)=extractBefore(lines(ii),p(1));end,end;text=strjoin(lines,newline);
end
function r=normalized_range(x),r=(max(x)-min(x))/max(max(abs(x)),eps);end
function r=relative_delta(value,base)
if abs(base)<=eps,if abs(value)<=eps,r=0;else,r=Inf;end,else,r=(value-base)/abs(base);end
end
function s=conditional_warning(condition,text)
if condition,s=string(text);else,s="";end
end
function value=mean_finite(x)
x=double(x(:));x=x(isfinite(x));if isempty(x),value=NaN;else,value=mean(x);end
end
function value=pct(x,p)
x=sort(double(x(:)));x=x(isfinite(x));if isempty(x),value=NaN;else,idx=max(1,min(numel(x),ceil(p/100*numel(x))));value=x(idx);end
end
