function [summaryTbl, comparisonTbl, checksTbl, diagnostics] = ...
    compare_independent_persistent_damage_h2(result, config)
%COMPARE_INDEPENDENT_PERSISTENT_DAMAGE_H2 Summarize mode consequences.

T = result.by_slice;
summaryTbl = build_summary(T, result, config);
comparisonTbl = build_comparison(summaryTbl);
[commonPass, commonEvidence] = check_common_random_numbers(T);
[dTotalPass, dTotalError] = check_D_total(T, summaryTbl);
independentRecoveryCount = count_independent_recovery(T);

persistentRows = summaryTbl.damage_mode == "persistent_damage";
lineMonotonicPass = all(summaryTbl.failed_line_monotonic_violation_count( ...
    persistentRows) == 0);
roadMonotonicPass = all(summaryTbl.closed_road_monotonic_violation_count( ...
    persistentRows) == 0);
slowdownMonotonicPass = all(summaryTbl.slowdown_monotonic_violation_count( ...
    persistentRows) == 0);

stageAggregate = build_stage_aggregate(T, result, config);
persistentAggregate = stageAggregate( ...
    stageAggregate.damage_mode == "persistent_damage", :);
maxSaturation = max([persistentAggregate.line_saturation_share; ...
    persistentAggregate.road_saturation_share; ...
    persistentAggregate.load_saturation_share; ...
    persistentAggregate.D_saturation_share]);
massSaturation = maxSaturation >= config.massSaturationThreshold;
stageDistinctionByRmax = build_stage_distinction_by_rmax(stageAggregate);
persistentDistinction = stageDistinctionByRmax( ...
    stageDistinctionByRmax.damage_mode == "persistent_damage", :);
stageDistinctionPass = all(persistentDistinction.D_stage_range_ratio >= ...
    config.stageDistinctionThreshold | ...
    persistentDistinction.failed_line_stage_range_ratio >= ...
    config.stageDistinctionThreshold);

[oldOutputPass, oldOutputEvidence] = verify_old_outputs(config);
[mspFilePass, mspEvidence] = verify_msp_files(config);
sourceScan = scan_sources(config.executedSourceFiles);
rowCountExpected = numel(config.damageModes) * numel(config.RmaxValues) * ...
    numel(config.aValues) * numel(config.locValues) * config.Nmc * config.W;

checks = {
    "common_random_numbers", commonPass, NaN, commonEvidence, "";
    "persistent_failed_lines_nondecreasing", lineMonotonicPass, ...
    sum(summaryTbl.failed_line_monotonic_violation_count(persistentRows)), ...
    "persistent failed_line_count checked scenario by scenario", "";
    "persistent_closed_roads_nondecreasing", roadMonotonicPass, ...
    sum(summaryTbl.closed_road_monotonic_violation_count(persistentRows)), ...
    "persistent closed_road_count checked scenario by scenario", "";
    "persistent_slowdown_severity_nondecreasing", slowdownMonotonicPass, ...
    sum(summaryTbl.slowdown_monotonic_violation_count(persistentRows)), ...
    "persistent slowdown multiplier mean checked scenario by scenario", "";
    "independent_snapshot_recovery_observed", independentRecoveryCount > 0, ...
    independentRecoveryCount, ...
    "independent mode permits later failed/closed counts to decrease", "";
    "D_total_is_W1_W2_W3_sum", dTotalPass, dTotalError, ...
    "scenario totals independently compared with Hres3h summary", "";
    "slice_duration_is_1h", all(abs(T.slice_duration_h - 1) <= 1e-12), ...
    config.sliceDurationH, "all W1-W3 rows use one hour", "";
    "Hres_total_is_3h", config.W * config.sliceDurationH == 3, ...
    config.W * config.sliceDurationH, "three one-hour slices", "";
    "no_repair_mechanism", all(T.repair_enabled == 0), NaN, ...
    "repair_enabled is false for every row", "";
    "expected_output_row_count", height(T) == rowCountExpected, height(T), ...
    compose("expected %d rows", rowCountExpected), "";
    "persistent_mass_saturation_diagnostic", NaN, maxSaturation, ...
    compose("mass saturation threshold %.3g; observed maximum %.6g", ...
    config.massSaturationThreshold, maxSaturation), ...
    conditional_warning(massSaturation, "persistent damage shows mass saturation");
    "Wstep40_stage_distinction_diagnostic", NaN, ...
    min(persistentDistinction.D_stage_range_ratio), ...
    "persistent stage distinction evaluated separately for each Rmax", ...
    conditional_warning(~stageDistinctionPass, "Wstep40 stage distinction is weak");
    "no_old_output_overwritten", oldOutputPass, NaN, oldOutputEvidence, "";
    "no_MSP_modified_or_called", mspFilePass && sourceScan.no_MSP_call, NaN, ...
    mspEvidence + "; MSP call hits=" + sourceScan.MSP_call_hit_count, "";
    "no_WDRO_or_Gurobi_call", sourceScan.no_WDRO_call, NaN, ...
    "WDRO/Gurobi call hits=" + sourceScan.WDRO_call_hit_count, "";
    "no_formal_B3_or_path_prob_call", sourceScan.no_B3_call, NaN, ...
    "B3/path-probability call hits=" + sourceScan.B3_call_hit_count, ""};
checksTbl = cell2table(checks, 'VariableNames', ...
    {'check_name', 'passed', 'numeric_value', 'evidence', 'warning'});
if iscell(checksTbl.passed)
    checksTbl.passed = cellfun(@double, checksTbl.passed);
else
    checksTbl.passed = double(checksTbl.passed);
end

if commonPass && lineMonotonicPass && roadMonotonicPass && ...
        slowdownMonotonicPass && stageDistinctionPass
    if massSaturation
        recommendation = "recommend_persistent_damage_with_saturation_review";
    else
        recommendation = "recommend_persistent_damage";
    end
else
    recommendation = "do_not_adopt_persistent_damage_yet";
end

diagnostics = struct();
diagnostics.common_random_numbers_pass = commonPass;
diagnostics.common_random_numbers_evidence = commonEvidence;
diagnostics.independent_recovery_scenario_count = independentRecoveryCount;
diagnostics.persistent_line_monotonic_pass = lineMonotonicPass;
diagnostics.persistent_road_monotonic_pass = roadMonotonicPass;
diagnostics.persistent_slowdown_monotonic_pass = slowdownMonotonicPass;
diagnostics.max_persistent_saturation_share = maxSaturation;
diagnostics.mass_saturation_detected = massSaturation;
diagnostics.stage_distinction_pass = stageDistinctionPass;
diagnostics.stage_aggregate = stageAggregate;
diagnostics.stage_distinction_by_Rmax = stageDistinctionByRmax;
diagnostics.B3_recommendation = recommendation;
diagnostics.old_output_pass = oldOutputPass;
diagnostics.msp_file_pass = mspFilePass;
diagnostics.source_scan = sourceScan;
end

function S = build_summary(T, result, config)
groups = unique(T(:, {'damage_mode', 'Rmax', 'a', 'loc'}), 'rows');
groups = sortrows(groups, {'damage_mode', 'Rmax', 'a', 'loc'});
rows = {};
for gg = 1:height(groups)
    sub = T(T.damage_mode == groups.damage_mode(gg) & ...
        T.Rmax == groups.Rmax(gg) & T.a == groups.a(gg) & ...
        T.loc == groups.loc(gg), :);
    stageMean = zeros(10, 3);
    lineSat = zeros(1, 3);
    roadSat = zeros(1, 3);
    loadSat = zeros(1, 3);
    dSat = zeros(1, 3);
    for ss = 1:3
        q = sub(sub.stage_index == ss, :);
        stageMean(:, ss) = [mean(q.failed_line_count); ...
            mean(q.closed_road_count); mean(q.slow_road_count); ...
            mean(q.P_loss_total_kW); mean(q.D_slice_total_kg); ...
            mean(q.newly_failed_line_count); mean(q.newly_closed_road_count); ...
            mean(q.slowdown_multiplier_mean); mean(q.outage_node_count); ...
            height(q)];
        lineSat(ss) = mean(q.failed_line_count >= result.n_lines);
        roadSat(ss) = mean(q.closed_road_count >= result.n_roads);
        loadSat(ss) = mean(q.P_loss_total_kW >= 0.99 * result.max_P_loss_kW);
        dSat(ss) = mean(q.D_slice_total_kg >= 0.99 * result.max_D_slice_kg);
    end
    [Dtotal, lineViol, roadViol, slowdownViol] = scenario_diagnostics(sub, config.Nmc);
    failedDist = normalized_range(stageMean(1, :));
    closedDist = normalized_range(stageMean(2, :));
    pLossDist = normalized_range(stageMean(4, :));
    dDist = normalized_range(stageMean(5, :));
    massSat = max([lineSat, roadSat, loadSat, dSat]);
    rows(end + 1, :) = {groups.damage_mode(gg), groups.Rmax(gg), ...
        groups.a(gg), groups.loc(gg), config.Nmc, ...
        stageMean(1,1), stageMean(1,2), stageMean(1,3), ...
        stageMean(2,1), stageMean(2,2), stageMean(2,3), ...
        stageMean(3,1), stageMean(3,2), stageMean(3,3), ...
        stageMean(4,1), stageMean(4,2), stageMean(4,3), ...
        stageMean(5,1), stageMean(5,2), stageMean(5,3), ...
        mean(Dtotal), pct(Dtotal,95), max(Dtotal), ...
        lineSat(1), lineSat(2), lineSat(3), ...
        roadSat(1), roadSat(2), roadSat(3), ...
        loadSat(1), loadSat(2), loadSat(3), ...
        dSat(1), dSat(2), dSat(3), lineViol, roadViol, slowdownViol, ...
        failedDist, closedDist, pLossDist, dDist, massSat}; %#ok<AGROW>
end
S = cell2table(rows, 'VariableNames', ...
    {'damage_mode', 'Rmax', 'a', 'loc', 'Nmc', ...
    'failed_line_W1_mean', 'failed_line_W2_mean', 'failed_line_W3_mean', ...
    'closed_road_W1_mean', 'closed_road_W2_mean', 'closed_road_W3_mean', ...
    'slow_road_W1_mean', 'slow_road_W2_mean', 'slow_road_W3_mean', ...
    'P_loss_W1_mean_kW', 'P_loss_W2_mean_kW', 'P_loss_W3_mean_kW', ...
    'D_W1_mean_kg', 'D_W2_mean_kg', 'D_W3_mean_kg', ...
    'D_Hres3h_total_mean_kg', 'D_Hres3h_total_p95_kg', ...
    'D_Hres3h_total_max_kg', 'line_saturation_W1_share', ...
    'line_saturation_W2_share', 'line_saturation_W3_share', ...
    'road_saturation_W1_share', 'road_saturation_W2_share', ...
    'road_saturation_W3_share', 'load_saturation_W1_share', ...
    'load_saturation_W2_share', 'load_saturation_W3_share', ...
    'D_saturation_W1_share', 'D_saturation_W2_share', ...
    'D_saturation_W3_share', 'failed_line_monotonic_violation_count', ...
    'closed_road_monotonic_violation_count', ...
    'slowdown_monotonic_violation_count', ...
    'failed_line_stage_range_ratio', 'closed_road_stage_range_ratio', ...
    'P_loss_stage_range_ratio', 'D_stage_range_ratio', ...
    'max_saturation_share'});
end

function C = build_comparison(S)
groups = unique(S(:, {'Rmax', 'a', 'loc'}), 'rows');
groups = sortrows(groups, {'Rmax', 'a', 'loc'});
rows = {};
for gg = 1:height(groups)
    ind = select_mode(S, groups(gg,:), "independent_snapshot");
    per = select_mode(S, groups(gg,:), "persistent_damage");
    rows(end + 1, :) = {groups.Rmax(gg), groups.a(gg), groups.loc(gg), ...
        ind.failed_line_W1_mean, ind.failed_line_W2_mean, ind.failed_line_W3_mean, ...
        per.failed_line_W1_mean, per.failed_line_W2_mean, per.failed_line_W3_mean, ...
        ind.closed_road_W1_mean, ind.closed_road_W2_mean, ind.closed_road_W3_mean, ...
        per.closed_road_W1_mean, per.closed_road_W2_mean, per.closed_road_W3_mean, ...
        ind.slow_road_W1_mean, ind.slow_road_W2_mean, ind.slow_road_W3_mean, ...
        per.slow_road_W1_mean, per.slow_road_W2_mean, per.slow_road_W3_mean, ...
        ind.P_loss_W1_mean_kW, ind.P_loss_W2_mean_kW, ind.P_loss_W3_mean_kW, ...
        per.P_loss_W1_mean_kW, per.P_loss_W2_mean_kW, per.P_loss_W3_mean_kW, ...
        ind.D_W1_mean_kg, ind.D_W2_mean_kg, ind.D_W3_mean_kg, ...
        per.D_W1_mean_kg, per.D_W2_mean_kg, per.D_W3_mean_kg, ...
        ind.D_Hres3h_total_mean_kg, per.D_Hres3h_total_mean_kg, ...
        per.D_Hres3h_total_mean_kg - ind.D_Hres3h_total_mean_kg, ...
        relative_delta(per.D_Hres3h_total_mean_kg, ind.D_Hres3h_total_mean_kg), ...
        ind.max_saturation_share, per.max_saturation_share, ...
        ind.D_stage_range_ratio, per.D_stage_range_ratio}; %#ok<AGROW>
end
C = cell2table(rows, 'VariableNames', ...
    {'Rmax','a','loc', ...
    'ind_failed_W1','ind_failed_W2','ind_failed_W3', ...
    'per_failed_W1','per_failed_W2','per_failed_W3', ...
    'ind_closed_W1','ind_closed_W2','ind_closed_W3', ...
    'per_closed_W1','per_closed_W2','per_closed_W3', ...
    'ind_slow_W1','ind_slow_W2','ind_slow_W3', ...
    'per_slow_W1','per_slow_W2','per_slow_W3', ...
    'ind_P_loss_W1_kW','ind_P_loss_W2_kW','ind_P_loss_W3_kW', ...
    'per_P_loss_W1_kW','per_P_loss_W2_kW','per_P_loss_W3_kW', ...
    'ind_D_W1_kg','ind_D_W2_kg','ind_D_W3_kg', ...
    'per_D_W1_kg','per_D_W2_kg','per_D_W3_kg', ...
    'ind_D_Hres3h_total_kg','per_D_Hres3h_total_kg', ...
    'D_total_delta_persistent_minus_independent_kg', ...
    'D_total_relative_delta', 'ind_max_saturation_share', ...
    'per_max_saturation_share', 'ind_D_stage_range_ratio', ...
    'per_D_stage_range_ratio'});
end

function row = select_mode(S, group, mode)
row = S(S.Rmax == group.Rmax & S.a == group.a & S.loc == group.loc & ...
    S.damage_mode == mode, :);
if height(row) ~= 1
    error('compare_independent_persistent_damage_h2:MissingModeRow', ...
        'Expected one summary row for each mode.');
end
end

function [Dtotal, lineViol, roadViol, slowdownViol] = scenario_diagnostics(sub, Nmc)
Dtotal = zeros(Nmc,1);
lineViol = 0;
roadViol = 0;
slowdownViol = 0;
for mm = 1:Nmc
    q = sub(sub.scenario_id == mm, :);
    q = sortrows(q, 'stage_index');
    if height(q) ~= 3
        error('compare_independent_persistent_damage_h2:BadScenarioStages', ...
            'Each scenario must contain W1, W2, and W3 exactly once.');
    end
    Dtotal(mm) = sum(q.D_slice_total_kg);
    lineViol = lineViol + any(diff(q.failed_line_count) < 0);
    roadViol = roadViol + any(diff(q.closed_road_count) < 0);
    slowdownViol = slowdownViol + any(diff(q.slowdown_multiplier_mean) < -1e-12);
end
end

function A = build_stage_aggregate(T, result, config)
groups = unique(T(:, {'damage_mode','Rmax','stage','stage_index'}), 'rows');
groups = sortrows(groups, {'damage_mode','Rmax','stage_index'});
rows = {};
for gg = 1:height(groups)
    q = T(T.damage_mode == groups.damage_mode(gg) & ...
        T.Rmax == groups.Rmax(gg) & T.stage_index == groups.stage_index(gg), :);
    rows(end+1,:) = {groups.damage_mode(gg), groups.Rmax(gg), ...
        groups.stage(gg), groups.stage_index(gg), mean(q.failed_line_count), ...
        mean(q.closed_road_count), mean(q.slow_road_count), ...
        mean(q.P_loss_total_kW), mean(q.D_slice_total_kg), ...
        mean(q.failed_line_count >= result.n_lines), ...
        mean(q.closed_road_count >= result.n_roads), ...
        mean(q.P_loss_total_kW >= 0.99*result.max_P_loss_kW), ...
        mean(q.D_slice_total_kg >= 0.99*result.max_D_slice_kg), ...
        config.Nmc * numel(config.aValues) * numel(config.locValues)}; %#ok<AGROW>
end
A = cell2table(rows, 'VariableNames', ...
    {'damage_mode','Rmax','stage','stage_index','failed_line_mean', ...
    'closed_road_mean','slow_road_mean','P_loss_mean_kW','D_mean_kg', ...
    'line_saturation_share','road_saturation_share', ...
    'load_saturation_share','D_saturation_share','case_count'});
end

function D = build_stage_distinction_by_rmax(A)
groups = unique(A(:, {'damage_mode','Rmax'}), 'rows');
rows = {};
for gg = 1:height(groups)
    q = A(A.damage_mode == groups.damage_mode(gg) & ...
        A.Rmax == groups.Rmax(gg), :);
    q = sortrows(q,'stage_index');
    rows(end+1,:) = {groups.damage_mode(gg), groups.Rmax(gg), ...
        normalized_range(q.failed_line_mean.'), ...
        normalized_range(q.closed_road_mean.'), ...
        normalized_range(q.P_loss_mean_kW.'), ...
        normalized_range(q.D_mean_kg.')}; %#ok<AGROW>
end
D = cell2table(rows, 'VariableNames', ...
    {'damage_mode','Rmax','failed_line_stage_range_ratio', ...
    'closed_road_stage_range_ratio','P_loss_stage_range_ratio', ...
    'D_stage_range_ratio'});
end

function [pass, evidence] = check_common_random_numbers(T)
[G,~] = findgroups(T(:, {'Rmax','Wstep','a','loc','stage_index','scenario_id'}));
pairPass = all(splitapply(@numel, T.Rmax, G) == 2);
seedPass = all(splitapply(@(x) max(x)==min(x), T.common_random_seed, G));
linePass = all(splitapply(@(x) max(x)-min(x)<=1e-12, ...
    T.line_uniform_checksum, G));
roadPass = all(splitapply(@(x) max(x)-min(x)<=1e-12, ...
    T.road_uniform_checksum, G));
rawLinePass = all(splitapply(@(x) max(x)==min(x), ...
    T.raw_failed_line_draw_count, G));
rawRoadPass = all(splitapply(@(x) max(x)==min(x), ...
    T.raw_closed_road_draw_count, G));
probPass = all(splitapply(@same_base_probability, T.line_pFail_mean, ...
    T.road_pClose_mean, G));
pass = pairPass && seedPass && linePass && roadPass && ...
    rawLinePass && rawRoadPass && probPass;
evidence = string(sprintf(['paired=%d; seed=%d; line_checksum=%d; ' ...
    'road_checksum=%d; raw_line=%d; raw_road=%d; probability=%d'], ...
    pairPass,seedPass,linePass,roadPass,rawLinePass,rawRoadPass,probPass));
end

function tf = same_base_probability(lineP, roadP)
tf = max(lineP)-min(lineP)<=1e-12 && max(roadP)-min(roadP)<=1e-12;
end

function [pass, maxError] = check_D_total(T, S)
maxError = 0;
groups = unique(S(:, {'damage_mode','Rmax','a','loc'}), 'rows');
for gg = 1:height(groups)
    sub = T(T.damage_mode == groups.damage_mode(gg) & ...
        T.Rmax == groups.Rmax(gg) & T.a == groups.a(gg) & ...
        T.loc == groups.loc(gg), :);
    totals = zeros(max(sub.scenario_id),1);
    for mm = 1:numel(totals)
        q = sub(sub.scenario_id==mm,:);
        if height(q)~=3 || ~isequal(sort(string(q.stage)), ["W1";"W2";"W3"])
            pass = false;
            maxError = Inf;
            return;
        end
        totals(mm)=sum(q.D_slice_total_kg);
    end
    row = S(S.damage_mode == groups.damage_mode(gg) & ...
        S.Rmax == groups.Rmax(gg) & S.a == groups.a(gg) & ...
        S.loc == groups.loc(gg), :);
    err = max([abs(mean(totals)-row.D_Hres3h_total_mean_kg), ...
        abs(pct(totals,95)-row.D_Hres3h_total_p95_kg), ...
        abs(max(totals)-row.D_Hres3h_total_max_kg)]);
    maxError = max(maxError,err);
end
pass = maxError <= 1e-9;
end

function n = count_independent_recovery(T)
n=0;
sub=T(T.damage_mode=="independent_snapshot",:);
groups=unique(sub(:,{'Rmax','a','loc','scenario_id'}),'rows');
for gg=1:height(groups)
    q=sub(sub.Rmax==groups.Rmax(gg) & sub.a==groups.a(gg) & ...
        sub.loc==groups.loc(gg) & sub.scenario_id==groups.scenario_id(gg),:);
    q=sortrows(q,'stage_index');
    if any(diff(q.failed_line_count)<0) || any(diff(q.closed_road_count)<0)
        n=n+1;
    end
end
end

function [pass,evidence]=verify_old_outputs(config)
after=snapshot_directories(config.protectedOutputDirs);
b=config.protectedOutputBefore;
pass=isequal(b.file_count,after.file_count) && ...
    all(abs(b.latest_datenum-after.latest_datenum)<=1e-12 | ...
    (isnan(b.latest_datenum)&isnan(after.latest_datenum))) && ...
    isequal(b.total_bytes,after.total_bytes);
evidence=string(sprintf('protected directories=%d; unchanged=%d',height(b),pass));
end

function [pass,evidence]=verify_msp_files(config)
after=snapshot_files(config.protectedMSPFiles);
b=config.protectedMSPBefore;
pass=isequal(b.exists,after.exists) && ...
    all(abs(b.datenum-after.datenum)<=1e-12 | ...
    (isnan(b.datenum)&isnan(after.datenum))) && isequal(b.bytes,after.bytes);
evidence=string(sprintf('protected MSP files=%d; unchanged=%d',height(b),pass));
end

function scan=scan_sources(files)
wdro=["solve_wdro_terminal_loh_lp_h2\\s*\\(","gurobi\\s*\\("];
msp=["run_h2_with_options\\s*\\(","train_models_h2\\s*\\(", ...
    "forward_pass_h2\\s*\\(","backward_pass_h2\\s*\\(", ...
    "main_msp_h2_near\\s*\\("];
b3=["build_lookahead_W3_DAC_samples_h2\\s*\\(", ...
    "compute_[A-Za-z0-9_]*path_prob[A-Za-z0-9_]*\\s*\\(", ...
    "run_[A-Za-z0-9_]*B3[A-Za-z0-9_]*\\s*\\(", ...
    "run_stage2C[^\\n]*\\("];
w=0;m=0;b=0;
for ii=1:numel(files)
    text=strip_comments(string(fileread(files{ii})));
    w=w+count_patterns(text,wdro);
    m=m+count_patterns(text,msp);
    b=b+count_patterns(text,b3);
end
scan=struct('WDRO_call_hit_count',w,'MSP_call_hit_count',m, ...
    'B3_call_hit_count',b,'no_WDRO_call',w==0,'no_MSP_call',m==0, ...
    'no_B3_call',b==0);
end

function T=snapshot_directories(paths)
T=table(strings(numel(paths),1),zeros(numel(paths),1), ...
    zeros(numel(paths),1),zeros(numel(paths),1), ...
    'VariableNames',{'path','file_count','latest_datenum','total_bytes'});
for ii=1:numel(paths)
    T.path(ii)=string(paths{ii});
    if ~isfolder(paths{ii}), T.file_count(ii)=-1;T.latest_datenum(ii)=NaN;T.total_bytes(ii)=-1;continue;end
    x=dir(fullfile(paths{ii},'**','*'));x=x(~[x.isdir]);T.file_count(ii)=numel(x);
    if isempty(x),T.latest_datenum(ii)=0;T.total_bytes(ii)=0;else,T.latest_datenum(ii)=max([x.datenum]);T.total_bytes(ii)=sum([x.bytes]);end
end
end

function T=snapshot_files(paths)
T=table(strings(numel(paths),1),false(numel(paths),1), ...
    zeros(numel(paths),1),zeros(numel(paths),1), ...
    'VariableNames',{'path','exists','datenum','bytes'});
for ii=1:numel(paths)
    T.path(ii)=string(paths{ii});T.exists(ii)=isfile(paths{ii});
    if T.exists(ii),x=dir(paths{ii});T.datenum(ii)=x.datenum;T.bytes(ii)=x.bytes;else,T.datenum(ii)=NaN;T.bytes(ii)=-1;end
end
end

function n=count_patterns(text,patterns)
n=0;for ii=1:numel(patterns),n=n+numel(regexp(text,patterns(ii),'match','ignorecase'));end
end

function text=strip_comments(text)
lines=splitlines(text);for ii=1:numel(lines),p=strfind(lines(ii),'%');if ~isempty(p),lines(ii)=extractBefore(lines(ii),p(1));end,end;text=strjoin(lines,newline);
end

function r=normalized_range(x)
r=(max(x)-min(x))/max(max(abs(x)),eps);
end

function r=relative_delta(value,base)
if abs(base)<=eps,if abs(value)<=eps,r=0;else,r=Inf;end,else,r=(value-base)/abs(base);end
end

function s=conditional_warning(condition,text)
if condition,s=string(text);else,s="";end
end

function value=pct(x,p)
x=sort(double(x(:)));x=x(isfinite(x));if isempty(x),value=NaN;else,idx=max(1,min(numel(x),ceil(p/100*numel(x))));value=x(idx);end
end
