function result = evaluate_foundation_fix_chain_h2(config, foundation)
%EVALUATE_FOUNDATION_FIX_CHAIN_H2 Evaluate fixed coordinates and Hres3h MC.

near = foundation.raw_near;
requiredGrid = {'P_load_base_kw'};
for ii = 1:numel(requiredGrid)
    if ~isfield(near.Grid, requiredGrid{ii})
        error('evaluate_foundation_fix_chain_h2:MissingRealLoadData', ...
            ['NearStageInput.Grid.%s is required. No IEEE33 fallback or ' ...
            'placeholder load is allowed in this audit.'], requiredGrid{ii});
    end
end
if ~isfield(near.HydrogenDevice, 'eta_FC') || ...
        ~isfield(near.HydrogenDevice, 'h2_lhv_kWh_per_kg')
    error('evaluate_foundation_fix_chain_h2:MissingHydrogenConversion', ...
        'NearStageInput HydrogenDevice conversion fields are required.');
end

Pnode = double(near.Grid.P_load_base_kw(:));
etaFC = double(near.HydrogenDevice.eta_FC);
lhv = double(near.HydrogenDevice.h2_lhv_kWh_per_kg);
if numel(Pnode) ~= height(foundation.layout.nodes)
    error('evaluate_foundation_fix_chain_h2:BadLoadLength', ...
        'P_load_base_kw length must equal the node count.');
end

riskTbl = build_full_risk(config, foundation);
stageRiskTbl = summarize_stage_risk(riskTbl);
mcTbl = run_comparable_smoke_mc(config, foundation, Pnode, etaFC, lhv);
dSummaryTbl = summarize_hres3h(mcTbl, config);

result = struct();
result.risk = riskTbl;
result.stage_risk = stageRiskTbl;
result.mc_by_slice = mcTbl;
result.D_Hres3h_summary = dSummaryTbl;
result.P_node_load_kw = Pnode;
result.eta_FC = etaFC;
result.LHV_H2_kWh_per_kg = lhv;
result.P_node_load_total_kw = sum(Pnode);
result.load_source = "NearStageInput.Grid.P_load_base_kw";
result.Rmax_mode = "fixed_support_point_no_probability_no_resampling";
result.road_distance_mode = "point_to_segment";
end

function T = build_full_risk(config, foundation)
gridSeg = foundation.grid_segments;
roadSeg = foundation.road_segments;
locTbl = foundation.loc_table;
rows = cell(numel(config.RmaxValues) * numel(config.WstepValues) * ...
    numel(config.stageNames) * numel(config.aValues) * height(locTbl), 32);
rr = 0;
for rmax = config.RmaxValues(:).'
    for wstep = config.WstepValues(:).'
        for ss = 1:numel(config.stageNames)
            stage = config.stageNames(ss);
            y = foundation.y_base + config.stageOffsets(ss) * wstep;
            for a = config.aValues(:).'
                Vmax = intensity_to_vmax(a);
                for ll = 1:height(locTbl)
                    loc = double(locTbl.loc(ll));
                    x = double(locTbl.x_coord(ll));
                    lineDist = compute_point_to_segment_distance_h2(x, y, ...
                        gridSeg.x1, gridSeg.y1, gridSeg.x2, gridSeg.y2);
                    roadDist = compute_point_to_segment_distance_h2(x, y, ...
                        roadSeg.x1, roadSeg.y1, roadSeg.x2, roadSeg.y2);
                    lineWind = compute_wind_speed_radial_h2(lineDist, ...
                        Vmax, rmax, config.windDecayB);
                    roadWind = compute_wind_speed_radial_h2(roadDist, ...
                        Vmax, rmax, config.windDecayB);
                    lineP = compute_line_failure_prob_h2(lineWind, ...
                        config.designWindSpeedVN);
                    roadP = compute_line_failure_prob_h2(roadWind, ...
                        config.roadDesignWindVN);
                    rr = rr + 1;
                    rows(rr, :) = {rmax, wstep, stage, ss - 1, a, loc, ...
                        x, y, Vmax, min(lineDist), mean(lineDist), ...
                        pct(lineDist, 95), max(lineDist), min(roadDist), ...
                        mean(roadDist), pct(roadDist, 95), max(roadDist), ...
                        mean(lineWind), pct(lineWind, 95), max(lineWind), ...
                        mean(roadWind), pct(roadWind, 95), max(roadWind), ...
                        mean(lineP), pct(lineP, 50), pct(lineP, 95), ...
                        max(lineP), mean(roadP), pct(roadP, 50), ...
                        pct(roadP, 95), max(roadP), config.distanceMethod}; %#ok<AGROW>
                end
            end
        end
    end
end
T = cell2table(rows(1:rr, :), 'VariableNames', ...
    {'Rmax', 'Wstep', 'stage', 'stage_index', 'a', 'loc', ...
    'center_x', 'center_y', 'Vmax_mps', 'line_distance_min', ...
    'line_distance_mean', 'line_distance_p95', 'line_distance_max', ...
    'road_distance_min', 'road_distance_mean', 'road_distance_p95', ...
    'road_distance_max', 'line_wind_mean', 'line_wind_p95', ...
    'line_wind_max', 'road_wind_mean', 'road_wind_p95', ...
    'road_wind_max', 'line_pFail_mean', 'line_pFail_median', ...
    'line_pFail_p95', 'line_pFail_max', 'road_pClose_mean', ...
    'road_pClose_median', 'road_pClose_p95', 'road_pClose_max', ...
    'distance_method'});
end

function S = summarize_stage_risk(T)
groups = unique(T(:, {'Rmax', 'Wstep', 'stage', 'stage_index'}), 'rows');
groups = sortrows(groups, {'Rmax', 'Wstep', 'stage_index'});
rows = {};
for gg = 1:height(groups)
    mask = T.Rmax == groups.Rmax(gg) & T.Wstep == groups.Wstep(gg) & ...
        T.stage_index == groups.stage_index(gg);
    sub = T(mask, :);
    rows(end + 1, :) = {groups.Rmax(gg), groups.Wstep(gg), ...
        groups.stage(gg), groups.stage_index(gg), height(sub), ...
        mean(sub.line_wind_p95), pct(sub.line_wind_p95, 95), ...
        max(sub.line_wind_max), mean(sub.road_wind_p95), ...
        pct(sub.road_wind_p95, 95), max(sub.road_wind_max), ...
        mean(sub.line_pFail_p95), pct(sub.line_pFail_p95, 95), ...
        max(sub.line_pFail_max), mean(sub.road_pClose_p95), ...
        pct(sub.road_pClose_p95, 95), max(sub.road_pClose_max)}; %#ok<AGROW>
end
S = cell2table(rows, 'VariableNames', ...
    {'Rmax', 'Wstep', 'stage', 'stage_index', 'case_count', ...
    'line_wind_p95_mean', 'line_wind_p95_across_cases', ...
    'line_wind_max', 'road_wind_p95_mean', ...
    'road_wind_p95_across_cases', 'road_wind_max', ...
    'line_pFail_p95_mean', 'line_pFail_p95_across_cases', ...
    'line_pFail_max', 'road_pClose_p95_mean', ...
    'road_pClose_p95_across_cases', 'road_pClose_max'});
end

function T = run_comparable_smoke_mc(config, foundation, Pnode, etaFC, lhv)
gridSeg = foundation.grid_segments;
roadSeg = foundation.road_segments;
locTbl = foundation.loc_table;
nLines = height(gridSeg);
nRoad = height(roadSeg);
nNodes = numel(Pnode);
rows = cell(numel(config.RmaxValues) * numel(config.WstepValues) * ...
    numel(config.smokeAValues) * numel(config.smokeLocValues) * ...
    config.mcCount * numel(config.stageNames), 28);
rr = 0;

for rIdx = 1:numel(config.RmaxValues)
    rmax = config.RmaxValues(rIdx);
    for a = config.smokeAValues(:).'
        Vmax = intensity_to_vmax(a);
        for loc = config.smokeLocValues(:).'
            locRow = locTbl(locTbl.loc == loc, :);
            if height(locRow) ~= 1
                error('evaluate_foundation_fix_chain_h2:MissingSmokeLoc', ...
                    'Smoke loc=%g is not present exactly once.', loc);
            end
            x = double(locRow.x_coord);
            for ss = 1:numel(config.stageNames)
                commonSeed = config.mcSeed + 100000 * rIdx + ...
                    1000 * a + 10 * (loc + 3) + ss;
                rng(commonSeed, 'twister');
                lineUniform = rand(config.mcCount, nLines);
                roadUniform = rand(config.mcCount, nRoad);
                for wstep = config.WstepValues(:).'
                    y = foundation.y_base + config.stageOffsets(ss) * wstep;
                    lineDist = compute_point_to_segment_distance_h2(x, y, ...
                        gridSeg.x1, gridSeg.y1, gridSeg.x2, gridSeg.y2);
                    roadDist = compute_point_to_segment_distance_h2(x, y, ...
                        roadSeg.x1, roadSeg.y1, roadSeg.x2, roadSeg.y2);
                    lineWind = compute_wind_speed_radial_h2(lineDist, ...
                        Vmax, rmax, config.windDecayB);
                    roadWind = compute_wind_speed_radial_h2(roadDist, ...
                        Vmax, rmax, config.windDecayB);
                    pFail = compute_line_failure_prob_h2(lineWind, ...
                        config.designWindSpeedVN);
                    pClose = compute_line_failure_prob_h2(roadWind, ...
                        config.roadDesignWindVN);
                    failedSamples = lineUniform < pFail(:).';
                    closedSamples = roadUniform < pClose(:).';
                    slowEligible = pClose(:).' > ...
                        config.slowRoadPCloseThreshold;
                    for mm = 1:config.mcCount
                        connected = connected_to_source(nNodes, ...
                            gridSeg.from_node, gridSeg.to_node, ...
                            ~failedSamples(mm, :), config.sourceNode);
                        outage = ~connected(:);
                        outage(config.sourceNode) = false;
                        P_loss_node = double(outage) .* Pnode;
                        included = ss > 1;
                        if included
                            Dnode = compute_Hres3h_node_demand_h2( ...
                                P_loss_node, config.sliceDurationH, etaFC, lhv);
                        else
                            Dnode = zeros(size(P_loss_node));
                        end
                        rr = rr + 1;
                        rows(rr, :) = {rmax, wstep, config.stageNames(ss), ...
                            ss - 1, included, a, loc, x, y, mm, commonSeed, ...
                            sum(failedSamples(mm, :)), sum(outage), ...
                            sum(P_loss_node), sum(Dnode), ...
                            sum(closedSamples(mm, :)), ...
                            sum(~closedSamples(mm, :) & slowEligible), ...
                            mean(pFail), pct(pFail, 95), max(pFail), ...
                            mean(pClose), pct(pClose, 95), max(pClose), ...
                            config.sliceDurationH * double(included), etaFC, ...
                            lhv, config.sourceNode, config.distanceMethod}; %#ok<AGROW>
                    end
                end
            end
        end
    end
end
T = cell2table(rows(1:rr, :), 'VariableNames', ...
    {'Rmax', 'Wstep', 'stage', 'stage_index', 'included_in_Hres3h', ...
    'a', 'loc', 'center_x', 'center_y', 'mc_id', 'common_random_seed', ...
    'failed_line_count', 'outage_node_count', 'P_loss_total_kW', ...
    'D_slice_total_kg', 'closed_road_count', 'slow_road_count', ...
    'line_pFail_mean', 'line_pFail_p95', 'line_pFail_max', ...
    'road_pClose_mean', 'road_pClose_p95', 'road_pClose_max', ...
    'slice_duration_h', 'eta_FC', 'LHV_H2_kWh_per_kg', 'source_node', ...
    'distance_method'});
end

function S = summarize_hres3h(T, config)
groups = unique(T(:, {'Rmax', 'Wstep', 'a', 'loc'}), 'rows');
groups = sortrows(groups, {'Rmax', 'Wstep', 'a', 'loc'});
rows = {};
for gg = 1:height(groups)
    mask = T.Rmax == groups.Rmax(gg) & T.Wstep == groups.Wstep(gg) & ...
        T.a == groups.a(gg) & T.loc == groups.loc(gg);
    sub = T(mask, :);
    wide = zeros(config.mcCount, 3);
    pLoss = zeros(config.mcCount, 4);
    roadClosed = zeros(config.mcCount, 4);
    for mm = 1:config.mcCount
        for ss = 1:4
            row = sub(sub.mc_id == mm & sub.stage_index == ss - 1, :);
            if height(row) ~= 1
                error('evaluate_foundation_fix_chain_h2:BadMcGroup', ...
                    'Expected one row per MC and stage.');
            end
            pLoss(mm, ss) = row.P_loss_total_kW;
            roadClosed(mm, ss) = row.closed_road_count;
            if ss > 1
                wide(mm, ss - 1) = row.D_slice_total_kg;
            end
        end
    end
    dTotal = sum(wide, 2);
    identityError = max(abs(dTotal - sum(wide, 2)));
    rows(end + 1, :) = {groups.Rmax(gg), groups.Wstep(gg), ...
        groups.a(gg), groups.loc(gg), config.mcCount, config.mcSeed, ...
        mean(pLoss(:, 1)), mean(pLoss(:, 2)), mean(pLoss(:, 3)), ...
        mean(pLoss(:, 4)), mean(wide(:, 1)), mean(wide(:, 2)), ...
        mean(wide(:, 3)), mean(dTotal), pct(dTotal, 50), ...
        pct(dTotal, 90), pct(dTotal, 95), max(dTotal), ...
        mean(roadClosed(:, 1)), mean(roadClosed(:, 2)), ...
        mean(roadClosed(:, 3)), mean(roadClosed(:, 4)), ...
        identityError, config.sliceDurationH, config.HresTotalH}; %#ok<AGROW>
end
S = cell2table(rows, 'VariableNames', ...
    {'Rmax', 'Wstep', 'a', 'loc', 'Nmc', 'base_random_seed', ...
    'P_loss_lf7_mean_kW', 'P_loss_W1_mean_kW', ...
    'P_loss_W2_mean_kW', 'P_loss_W3_mean_kW', ...
    'D_W1_mean_kg', 'D_W2_mean_kg', 'D_W3_mean_kg', ...
    'D_total_mean_kg', 'D_total_p50_kg', 'D_total_p90_kg', ...
    'D_total_p95_kg', 'D_total_max_kg', ...
    'road_closed_lf7_mean', 'road_closed_W1_mean', ...
    'road_closed_W2_mean', 'road_closed_W3_mean', ...
    'D_sum_identity_max_abs_error', 'slice_duration_h', 'Hres_total_h'});
end

function connected = connected_to_source(Nj, fromNode, toNode, activeLine, sourceNode)
adj = false(Nj, Nj);
for ll = 1:numel(fromNode)
    if activeLine(ll)
        i = fromNode(ll);
        j = toNode(ll);
        adj(i, j) = true;
        adj(j, i) = true;
    end
end
connected = false(Nj, 1);
queue = zeros(Nj, 1);
head = 1;
tail = 1;
queue(tail) = sourceNode;
connected(sourceNode) = true;
while head <= tail
    cur = queue(head);
    head = head + 1;
    nbrs = find(adj(cur, :));
    for nn = nbrs
        if ~connected(nn)
            connected(nn) = true;
            tail = tail + 1;
            queue(tail) = nn;
        end
    end
end
end

function Vmax = intensity_to_vmax(a)
map = [0; 20.8; 28.55; 37.05; 46.20; 55.50];
if a < 1 || a > numel(map) || floor(a) ~= a
    error('evaluate_foundation_fix_chain_h2:BadIntensity', ...
        'Unsupported intensity a=%g.', a);
end
Vmax = map(a);
end

function value = pct(x, p)
x = sort(double(x(:)));
x = x(isfinite(x));
if isempty(x)
    value = NaN;
else
    idx = max(1, min(numel(x), ceil(p / 100 * numel(x))));
    value = x(idx);
end
end
