function result = evaluate_b3_smoke_fixed_resistance_h2( ...
    config, foundation, selection, captureDetailed)
%EVALUATE_B3_SMOKE_FIXED_RESISTANCE_H2 Path-specific persistent damage chain.

near=foundation.raw_near;
if ~isfield(near.Grid,'P_load_base_kw') || ...
        ~isfield(near.HydrogenDevice,'eta_FC') || ...
        ~isfield(near.HydrogenDevice,'h2_lhv_kWh_per_kg')
    error('evaluate_b3_smoke_fixed_resistance_h2:MissingPhysicalInput', ...
        'NearStageInput load and hydrogen conversion fields are required.');
end
Pnode=double(near.Grid.P_load_base_kw(:));
etaFC=double(near.HydrogenDevice.eta_FC);
lhv=double(near.HydrogenDevice.h2_lhv_kWh_per_kg);
gridSeg=foundation.grid_segments;
roadSeg=foundation.road_segments;
locTbl=foundation.loc_table;
siteNodes=readtable(config.siteNodeFile);
require_vars(siteNodes,{'site_id','grid_node'},'stage1_site_nodes.csv');
siteNodes=sortrows(siteNodes,'site_id');

nPaths=height(selection);nLines=height(gridSeg);nRoad=height(roadSeg);
nNodes=numel(Pnode);nSites=height(siteNodes);W=3;
if nPaths~=30 || nNodes~=33 || nSites~=4
    error('evaluate_b3_smoke_fixed_resistance_h2:UnexpectedDimensions', ...
        'Expected 30 paths, 33 nodes, and 4 sites; found %d/%d/%d.', ...
        nPaths,nNodes,nSites);
end
roadLength=hypot(roadSeg.x2-roadSeg.x1,roadSeg.y2-roadSeg.y1);
if any(~isfinite(roadLength)|roadLength<=0)
    error('evaluate_b3_smoke_fixed_resistance_h2:BadRoadLength', ...
        'Road lengths must be finite and positive.');
end

nScenarios=nPaths*config.resistanceRepeats;
nStageRows=nScenarios*W;
stageRows=cell(nStageRows,51);scenarioRows=cell(nScenarios,27);
resistanceRows=cell(nScenarios,14);persistenceRows=cell(nScenarios,20);
if captureDetailed
    lineRows=cell(nStageRows*nLines,17);
    roadRows=cell(nStageRows*nRoad,19);
    dacRows=cell(nStageRows*nSites*nNodes,18);
else
    lineRows={};roadRows={};dacRows={};
end
sr=0;cr=0;rr=0;pr=0;lr=0;er=0;dr=0;

for pp=1:nPaths
    path=selection(pp,:);
    stageData=build_path_stage_data(config,foundation,path,locTbl,gridSeg,roadSeg);
    for rep=1:config.resistanceRepeats
        scenarioId=(pp-1)*config.resistanceRepeats+rep;
        seed=config.rngSeed+1000*double(path.selection_path_id)+rep;
        rng(seed,'twister');
        fixedLineU=rand(nLines,1);fixedRoadU=rand(nRoad,1);
        lineChecksum=weighted_checksum(fixedLineU);
        roadChecksum=weighted_checksum(fixedRoadU);

        failedPrevious=false(nLines,1);closedPrevious=false(nRoad,1);
        slowdownPrevious=zeros(nRoad,1);
        failedHistory=false(nLines,W);closedHistory=false(nRoad,W);
        slowdownHistory=zeros(nRoad,W);outageHistory=false(nNodes,W);
        DHistory=zeros(nNodes,W);AHistory=false(nSites,nNodes,W);
        CHistory=zeros(nSites,nNodes,W);
        stageD=zeros(1,W);stagePLoss=zeros(1,W);stageFailed=zeros(1,W);
        stageClosed=zeros(1,W);stageUnreachable=zeros(1,W);
        structuralText="";fullText="";jointDamage=false;multiLine=false;

        for ss=1:W
            d=stageData(ss);
            rawFailed=fixedLineU<=d.pFail;
            rawClosed=fixedRoadU<=d.pClose;
            newlyFailed=rawFailed&~failedPrevious;
            newlyClosed=rawClosed&~closedPrevious;
            failed=failedPrevious|rawFailed;
            closed=closedPrevious|rawClosed;
            slowdownNew=config.roadSlowdownLambda.*d.pClose;
            slowdown=max(slowdownPrevious,slowdownNew);
            failedPrevious=failed;closedPrevious=closed;
            slowdownPrevious=slowdown;

            connected=connected_to_source(nNodes,gridSeg.from_node, ...
                gridSeg.to_node,~failed,config.sourceNode);
            outage=~connected(:);outage(config.sourceNode)=false;
            P_loss_node=double(outage).*Pnode;
            Dnode=compute_Hres3h_node_demand_h2(P_loss_node, ...
                config.sliceDurationH,etaFC,lhv);

            edgeCost=roadLength.*(1+slowdown);edgeCost(closed)=Inf;
            rawC=road_shortest_paths(nNodes,roadSeg.from_node,roadSeg.to_node, ...
                edgeCost,double(siteNodes.grid_node));
            A=isfinite(rawC);
            C=rawC;C(~A)=0;
            if any(~isfinite(C(:)))||any(C(:)<0)
                error('evaluate_b3_smoke_fixed_resistance_h2:BadMaskedC', ...
                    'Masked C must be finite and nonnegative.');
            end

            slowRoad=~closed&slowdown>config.slowRoadThreshold;
            finiteReachableC=C(A);
            failedHistory(:,ss)=failed;closedHistory(:,ss)=closed;
            slowdownHistory(:,ss)=slowdown;outageHistory(:,ss)=outage;
            DHistory(:,ss)=Dnode;AHistory(:,:,ss)=A;CHistory(:,:,ss)=C;
            stageD(ss)=sum(Dnode);stagePLoss(ss)=sum(P_loss_node);
            stageFailed(ss)=sum(failed);stageClosed(ss)=sum(closed);
            stageUnreachable(ss)=sum(~A(:));
            jointDamage=jointDamage||(any(failed)&&any(closed));
            multiLine=multiLine||(sum(failed)>=2);

            structuralPart=[logical_text(failed);logical_text(closed); ...
                logical_text(outage);logical_text(A(:))];
            structuralText=structuralText+"|"+join(structuralPart,"");
            fullText=fullText+"|"+join(structuralPart,"")+"|"+ ...
                numeric_text(Dnode,6)+"|"+numeric_text(C(:),6);

            sr=sr+1;
            stageRows(sr,:)={scenarioId,path.selection_path_id,rep,seed, ...
                path.source_category,path.nominal_inclusion_status, ...
                path.empirical_weight,path.path_probability,ss, ...
                "W"+string(ss),d.a,d.loc,d.lfw,d.x,d.y,d.Vmax, ...
                mean(d.lineWind),pct(d.lineWind,95),max(d.lineWind), ...
                mean(d.roadWind),pct(d.roadWind,95),max(d.roadWind), ...
                mean(d.pFail),pct(d.pFail,95),max(d.pFail), ...
                mean(d.pClose),pct(d.pClose,95),max(d.pClose), ...
                sum(rawFailed),sum(newlyFailed),sum(failed),sum(rawClosed), ...
                sum(newlyClosed),sum(closed),sum(slowRoad),sum(outage), ...
                sum(P_loss_node),sum(Dnode),sum(A(:)),numel(A), ...
                sum(A(:))/numel(A),mean(C(:)),max(C(:)), ...
                mean_or_zero(finiteReachableC),max_or_zero(finiteReachableC), ...
                sum(~A(:)),sum(failed)>=2,sum(~A(:))>0, ...
                config.sliceDurationH,"kg-H2",config.CDefinition};

            if captureDetailed
                for ll=1:nLines
                    lr=lr+1;
                    lineRows(lr,:)={scenarioId,path.selection_path_id,rep,seed, ...
                        path.source_category,ss,"W"+string(ss), ...
                        gridSeg.line_id(ll),gridSeg.from_node(ll), ...
                        gridSeg.to_node(ll),d.lineWind(ll),d.pFail(ll), ...
                        fixedLineU(ll),rawFailed(ll),newlyFailed(ll),failed(ll), ...
                        "persistent_fixed_resistance"};
                end
                for ee=1:nRoad
                    er=er+1;
                    roadRows(er,:)={scenarioId,path.selection_path_id,rep,seed, ...
                        path.source_category,ss,"W"+string(ss), ...
                        roadSeg.road_edge_id(ee),roadSeg.from_node(ee), ...
                        roadSeg.to_node(ee),d.roadWind(ee),d.pClose(ee), ...
                        fixedRoadU(ee),rawClosed(ee),newlyClosed(ee),closed(ee), ...
                        slowdownNew(ee),slowdown(ee), ...
                        "persistent_fixed_resistance"};
                end
                for site=1:nSites
                    for node=1:nNodes
                        dr=dr+1;
                        dacRows(dr,:)={scenarioId,path.selection_path_id,rep,seed, ...
                            path.source_category,path.nominal_inclusion_status, ...
                            ss,"W"+string(ss),siteNodes.site_id(site),node, ...
                            P_loss_node(node),Dnode(node),"kg-H2", ...
                            double(A(site,node)),C(site,node),"km", ...
                            config.CDefinition,config.sliceDurationH};
                    end
                end
            end
        end

        lineViolations=sum(failedHistory(:,1)&~failedHistory(:,2))+ ...
            sum(failedHistory(:,2)&~failedHistory(:,3));
        roadViolations=sum(closedHistory(:,1)&~closedHistory(:,2))+ ...
            sum(closedHistory(:,2)&~closedHistory(:,3));
        slowdownViolations=sum(slowdownHistory(:,2)+1e-15<slowdownHistory(:,1))+ ...
            sum(slowdownHistory(:,3)+1e-15<slowdownHistory(:,2));

        cr=cr+1;
        scenarioRows(cr,:)={scenarioId,path.selection_path_id,rep,seed, ...
            path.source_category,path.nominal_inclusion_status, ...
            path.empirical_weight,path.path_probability,sum(stageD), ...
            min(stageD),max(stageD),sum(stagePLoss),max(stagePLoss), ...
            stageFailed(1),stageFailed(2),stageFailed(3), ...
            stageClosed(1),stageClosed(2),stageClosed(3), ...
            mean(1-stageUnreachable/(nSites*nNodes)), ...
            mean(CHistory(:)),max(CHistory(:)),jointDamage,multiLine, ...
            any(stageUnreachable>0),sha256_text(structuralText), ...
            sha256_text(fullText)};

        rr=rr+1;
        resistanceRows(rr,:)={scenarioId,path.selection_path_id,rep,seed, ...
            path.source_category,nLines,nRoad,1,1,lineChecksum,roadChecksum, ...
            0,0,true};
        pr=pr+1;
        persistenceRows(pr,:)={scenarioId,path.selection_path_id,rep,seed, ...
            path.source_category,stageFailed(1),stageFailed(2),stageFailed(3), ...
            stageClosed(1),stageClosed(2),stageClosed(3), ...
            max(slowdownHistory(:,1)),max(slowdownHistory(:,2)), ...
            max(slowdownHistory(:,3)),lineViolations,roadViolations, ...
            slowdownViolations,lineViolations==0,roadViolations==0, ...
            slowdownViolations==0};
    end
end

stageResults=cell2table(stageRows(1:sr,:),'VariableNames', ...
    {'scenario_id','selection_path_id','resistance_repeat','random_seed', ...
    'source_category','nominal_inclusion_status','empirical_weight', ...
    'path_probability','stage_index','stage','a','loc','lfw','center_x', ...
    'center_y','Vmax_mps','line_wind_mean_mps','line_wind_p95_mps', ...
    'line_wind_max_mps','road_wind_mean_mps','road_wind_p95_mps', ...
    'road_wind_max_mps','line_pFail_mean','line_pFail_p95','line_pFail_max', ...
    'road_pClose_mean','road_pClose_p95','road_pClose_max', ...
    'raw_failed_line_count','newly_failed_line_count','failed_line_count', ...
    'raw_closed_road_count','newly_closed_road_count','closed_road_count', ...
    'slow_road_count','outage_node_count','P_loss_total_kW','D_total_kg', ...
    'reachable_pair_count','site_node_pair_count','reachable_pair_share', ...
    'C_masked_mean_km','C_masked_max_km','C_reachable_mean_km', ...
    'C_reachable_max_km','unreachable_pair_count','multi_line_failure', ...
    'road_disconnection','slice_duration_h','D_unit','C_definition'});
scenarioResults=cell2table(scenarioRows(1:cr,:),'VariableNames', ...
    {'scenario_id','selection_path_id','resistance_repeat','random_seed', ...
    'source_category','nominal_inclusion_status','empirical_weight', ...
    'path_probability','D_Hres3h_total_kg','D_stage_min_kg','D_stage_max_kg', ...
    'P_loss_stage_sum_kW','P_loss_stage_max_kW','failed_lines_W1', ...
    'failed_lines_W2','failed_lines_W3','closed_roads_W1','closed_roads_W2', ...
    'closed_roads_W3','reachable_pair_share_stage_mean','C_masked_mean_km', ...
    'C_masked_max_km','joint_line_road_damage_any','multi_line_failure_any', ...
    'road_disconnection_any','structural_pattern_signature', ...
    'full_consequence_signature'});
resistanceAudit=cell2table(resistanceRows(1:rr,:),'VariableNames', ...
    {'scenario_id','selection_path_id','resistance_repeat','random_seed', ...
    'source_category','line_component_count','road_component_count', ...
    'line_threshold_draws_per_component','road_threshold_draws_per_component', ...
    'fixed_line_threshold_checksum','fixed_road_threshold_checksum', ...
    'line_threshold_reuse_max_abs_error','road_threshold_reuse_max_abs_error', ...
    'fixed_resistance_pass'});
failureAudit=cell2table(persistenceRows(1:pr,:),'VariableNames', ...
    {'scenario_id','selection_path_id','resistance_repeat','random_seed', ...
    'source_category','failed_lines_W1','failed_lines_W2','failed_lines_W3', ...
    'closed_roads_W1','closed_roads_W2','closed_roads_W3', ...
    'slowdown_max_W1','slowdown_max_W2','slowdown_max_W3', ...
    'line_recovery_violation_count','road_recovery_violation_count', ...
    'slowdown_recovery_violation_count','line_persistence_pass', ...
    'road_persistence_pass','slowdown_persistence_pass'});

if captureDetailed
    lineStates=cell2table(lineRows(1:lr,:),'VariableNames', ...
        {'scenario_id','selection_path_id','resistance_repeat','random_seed', ...
        'source_category','stage_index','stage','line_id','from_node','to_node', ...
        'local_wind_mps','pFail','fixed_resistance_threshold','raw_failed', ...
        'newly_failed','failed','damage_mode'});
    roadStates=cell2table(roadRows(1:er,:),'VariableNames', ...
        {'scenario_id','selection_path_id','resistance_repeat','random_seed', ...
        'source_category','stage_index','stage','road_edge_id','from_node', ...
        'to_node','local_wind_mps','pClose','fixed_resistance_threshold', ...
        'raw_closed','newly_closed','closed','slowdown_new','slowdown_persistent', ...
        'damage_mode'});
    DAC=cell2table(dacRows(1:dr,:),'VariableNames', ...
        {'scenario_id','selection_path_id','resistance_repeat','random_seed', ...
        'source_category','nominal_inclusion_status','stage_index','stage', ...
        'site_id','node_id','P_loss_node_kW','D_node_kg','D_unit', ...
        'A_reachable','C_service_cost_km','C_unit','C_definition', ...
        'slice_duration_h'});
else
    lineStates=table();roadStates=table();DAC=table();
end

result=struct();result.stage_results=stageResults;
result.scenario_results=scenarioResults;result.resistance_audit=resistanceAudit;
result.failure_audit=failureAudit;result.line_states=lineStates;
result.road_states=roadStates;result.DAC=DAC;result.eta_FC=etaFC;
result.LHV_H2_kWh_per_kg=lhv;result.n_lines=nLines;result.n_roads=nRoad;
result.n_nodes=nNodes;result.n_sites=nSites;
end

function stageData=build_path_stage_data(config,foundation,path,locTbl,gridSeg,roadSeg)
stageData=repmat(struct('a',NaN,'loc',NaN,'lfw',NaN,'x',NaN,'y',NaN, ...
    'Vmax',NaN,'lineWind',[],'roadWind',[],'pFail',[],'pClose',[]),3,1);
for ss=1:3
    a=double(path.("a"+string(ss)));loc=double(path.("loc"+string(ss)));
    lfw=double(path.("lfw"+string(ss)));
    locRow=locTbl(locTbl.loc==loc,:);
    if height(locRow)~=1,error('loc=%g is not uniquely mapped.',loc);end
    x=double(locRow.x_coord);y=foundation.y_base+lfw*config.Wstep;
    Vmax=intensity_to_vmax(a);
    lineDist=compute_point_to_segment_distance_h2(x,y,gridSeg.x1,gridSeg.y1, ...
        gridSeg.x2,gridSeg.y2);
    roadDist=compute_point_to_segment_distance_h2(x,y,roadSeg.x1,roadSeg.y1, ...
        roadSeg.x2,roadSeg.y2);
    lineWind=compute_wind_speed_radial_h2(lineDist,Vmax,config.Rmax,config.windDecayB);
    roadWind=compute_wind_speed_radial_h2(roadDist,Vmax,config.Rmax,config.windDecayB);
    stageData(ss).a=a;stageData(ss).loc=loc;stageData(ss).lfw=lfw;
    stageData(ss).x=x;stageData(ss).y=y;stageData(ss).Vmax=Vmax;
    stageData(ss).lineWind=lineWind;stageData(ss).roadWind=roadWind;
    stageData(ss).pFail=compute_line_failure_prob_h2(lineWind,config.designWindSpeedVN);
    stageData(ss).pClose=compute_line_failure_prob_h2(roadWind,config.roadDesignWindVN);
end
end

function connected=connected_to_source(Nj,fromNode,toNode,activeLine,sourceNode)
adj=false(Nj,Nj);
for ll=1:numel(fromNode)
    if activeLine(ll),i=fromNode(ll);j=toNode(ll);adj(i,j)=true;adj(j,i)=true;end
end
connected=false(Nj,1);queue=zeros(Nj,1);head=1;tail=1;
queue(1)=sourceNode;connected(sourceNode)=true;
while head<=tail
    cur=queue(head);head=head+1;nbrs=find(adj(cur,:));
    for nn=nbrs
        if ~connected(nn),connected(nn)=true;tail=tail+1;queue(tail)=nn;end
    end
end
end

function D=road_shortest_paths(Nj,fromNode,toNode,edgeCost,sources)
adj=inf(Nj,Nj);adj(1:(Nj+1):end)=0;
for ee=1:numel(edgeCost)
    if ~isfinite(edgeCost(ee)),continue;end
    i=fromNode(ee);j=toNode(ee);
    if edgeCost(ee)<adj(i,j),adj(i,j)=edgeCost(ee);adj(j,i)=edgeCost(ee);end
end
D=inf(numel(sources),Nj);
for ii=1:numel(sources)
    dist=inf(1,Nj);visited=false(1,Nj);dist(sources(ii))=0;
    for iter=1:Nj
        candidate=dist;candidate(visited)=Inf;[best,u]=min(candidate);
        if ~isfinite(best),break;end
        visited(u)=true;dist=min(dist,best+adj(u,:));
    end
    D(ii,:)=dist;
end
end

function Vmax=intensity_to_vmax(a)
map=[0;20.8;28.55;37.05;46.20;55.50];
if a<1||a>numel(map)||floor(a)~=a,error('Unsupported intensity a=%g.',a);end
Vmax=map(a);
end

function value=weighted_checksum(x),value=sum(double(x(:)).*(1:numel(x)).');end
function value=mean_or_zero(x),if isempty(x),value=0;else,value=mean(x);end,end
function value=max_or_zero(x),if isempty(x),value=0;else,value=max(x);end,end

function value=pct(x,p)
x=sort(double(x(:)));x=x(isfinite(x));
if isempty(x),value=NaN;else
    idx=max(1,min(numel(x),ceil(p/100*numel(x))));value=x(idx);
end
end

function text=logical_text(x),text=string(char('0'+double(x(:).')));end
function text=numeric_text(x,digits)
format="%."+string(digits)+"f,";text=string(sprintf(format,double(x(:))));
end

function hash=sha256_text(text)
md=java.security.MessageDigest.getInstance('SHA-256');
bytes=uint8(unicode2native(char(text),'UTF-8'));
md.update(typecast(bytes,'int8'));
digest=typecast(md.digest(),'uint8');
hash=lower(string(reshape(dec2hex(digest,2).',1,[])));
end

function require_vars(T,names,fileName)
for ii=1:numel(names)
    if ~ismember(names{ii},T.Properties.VariableNames)
        error('%s missing required field %s.',fileName,names{ii});
    end
end
end
