function finalize_step03YF_r2000_h2()
%FINALIZE_STEP03YF_R2000_H2 Combine four isolated R=2000 state runs.

started = tic;
thisFile = mfilename('fullpath');
thisDir = fileparts(thisFile);
moduleDir = fileparts(thisDir);
rootDir = fileparts(moduleDir);
expectedBranch = "task/002-stage2b-b3-smoke";
expectedHead = "f46321afbe78469962f97f26f4f8ccea0329f89d";
stateIds = [7; 9; 11; 19];
effectStateIds = [9; 11; 19];
formalCap = [300; 200; 100; 150];
tolerance = 1e-7;
closeCapacityFraction = 0.10;
closeRelativeRegret = 0.01;
outputBase = fullfile(rootDir, 'results', ...
    'task-002-stage2b-b3-smoke', ...
    '35-period-vs-aggregate-saa-r2000');
workDir = fullfile(outputBase, 'run-001.inprogress');
outputDir = fullfile(outputBase, 'run-001');
finalizingDir = fullfile(outputBase, 'run-001.finalizing');

[~, branch] = system('git branch --show-current');
[~, head] = system('git rev-parse HEAD');
[~, upstream] = system('git rev-parse "@{upstream}"');
[~, statusBefore] = system('git status --short --branch');
branch = string(strtrim(branch));
head = string(strtrim(head));
upstream = string(strtrim(upstream));
statusBefore = string(strtrim(statusBefore));
if branch ~= expectedBranch || head ~= expectedHead || upstream ~= expectedHead
    error('Step-03Y-F frozen Git baseline mismatch.');
end
if ~isfolder(workDir) || isfolder(outputDir) || isfolder(finalizingDir)
    error('Step-03Y-F checkpoint/final path state is invalid.');
end

protectedRelative = protected_paths();
protectedBefore = strings(numel(protectedRelative), 1);
for ii = 1:numel(protectedRelative)
    protectedBefore(ii) = path_digest(fullfile(rootDir, protectedRelative(ii)));
    if protectedBefore(ii) == "MISSING"
        error('Step-03Y-F protected path missing: %s', protectedRelative(ii));
    end
end

terminal = table(); cross = table(); objective = table(); capacity = table();
metrics = table();
for ss = 1:numel(stateIds)
    stateId = stateIds(ss);
    prefix = sprintf('state_%02d', stateId);
    auditFile = fullfile(workDir, prefix + "_audit.txt");
    if ~isfile(auditFile) || ~contains(fileread(auditFile), 'status=PASS')
        error('Step-03Y-F state %d did not complete successfully.', stateId);
    end
    terminal = append_table(terminal, readtable(fullfile(workDir, ...
        prefix + "_terminal.csv"), 'TextType', 'string'));
    cross = append_table(cross, readtable(fullfile(workDir, ...
        prefix + "_cross.csv"), 'TextType', 'string'));
    objective = append_table(objective, readtable(fullfile(workDir, ...
        prefix + "_objective.csv"), 'TextType', 'string'));
    capacity = append_table(capacity, readtable(fullfile(workDir, ...
        prefix + "_capacity.csv"), 'TextType', 'string'));
    metrics = append_table(metrics, readtable(fullfile(workDir, ...
        prefix + "_metrics.csv"), 'TextType', 'string'));
end
terminal = normalize_terminal(terminal);
cross = normalize_cross(cross);
objective = normalize_objective(objective);
capacity = normalize_capacity(capacity);
if height(terminal) ~= 16 || height(cross) ~= 16 || ...
        height(objective) ~= 8 || height(capacity) ~= 32 || ...
        height(metrics) ~= 4 || ~all(terminal.case_pass) || ...
        ~all(cross.case_pass) || ~all(objective.case_pass) || ...
        ~all(capacity.case_pass)
    error('Step-03Y-F R=2000 state checkpoint table audit failed.');
end

stepYEDir = fullfile(rootDir, 'results', ...
    'task-002-stage2b-b3-smoke', ...
    '34-period-vs-aggregate-saa-stability', 'run-001');
stepYEAudit = fullfile(stepYEDir, 'mechanical_audit.txt');
if ~isfile(stepYEAudit) || ...
        ~contains(fileread(stepYEAudit), 'R1000_is_nominal_prefix=true') || ...
        ~contains(fileread(stepYEAudit), 'deterministic_replay_max_DAC_error=0')
    error('Step-03Y-F requires the mechanically valid Step-03Y-E R=1000 phase.');
end
prior = readtable(fullfile(stepYEDir, ...
    'terminalLOH_stability.csv'), 'TextType', 'string');
prior = prior(ismember(prior.initial_state_id, stateIds) & ...
    ismember(prior.R, [500, 1000]), :);
if height(prior) ~= 32 || ~all(prior.case_pass)
    error('Step-03Y-F R=500/R=1000 prior stability rows are incomplete.');
end
stability = [stability_core(prior); stability_core(terminal)];
stability = add_stability_diagnostics(stability, stateIds, formalCap, ...
    tolerance, closeCapacityFraction, closeRelativeRegret);

summary = summarize_states(stability, capacity, stateIds, tolerance);
conclusion = classify_result(summary, effectStateIds);
solverCallCount = sum(metrics.solver_call_count);
totalStateRuntime = sum(metrics.runtime_sec);
maxStateRuntime = max(metrics.runtime_sec);
overallPeakMemory = max(metrics.peak_working_set_bytes);
if solverCallCount ~= 16 || any(metrics.max_DAC_error ~= 0) || ...
        any(metrics.checkcode_issue_count ~= 0) || ...
        any(~isfinite(metrics.runtime_sec)) || ...
        any(~isfinite(metrics.peak_working_set_bytes))
    error('Step-03Y-F combined metrics audit failed.');
end

protectedAfter = strings(numel(protectedRelative), 1);
for ii = 1:numel(protectedRelative)
    protectedAfter(ii) = path_digest(fullfile(rootDir, protectedRelative(ii)));
end
if ~isequal(protectedBefore, protectedAfter)
    error('Step-03Y-F protected path changed during finalization.');
end
codeFiles = [string(thisFile); ...
    string(fullfile(thisDir, 'run_step03YF_r2000_state_h2.m')); ...
    string(fullfile(thisDir, 'recover_step03Y_prefix_entries_h2.m')); ...
    string(fullfile(thisDir, 'solve_step03Y_saa_audit_h2.m'))];
codeIssueCount = 0;
for ii = 1:numel(codeFiles)
    codeIssueCount = codeIssueCount + numel(checkcode(codeFiles(ii), '-id'));
end
if codeIssueCount ~= 0
    error('Step-03Y-F final checkcode found %d issue(s).', codeIssueCount);
end

mkdir(finalizingDir);
writetable(sortrows(terminal, {'initial_state_id','site_id'}), ...
    fullfile(finalizingDir, 'terminalLOH_r2000.csv'));
writetable(sortrows(cross, ...
    {'initial_state_id','evaluation_model','terminalLOH_source'}), ...
    fullfile(finalizingDir, 'cross_evaluation.csv'));
writetable(sortrows(objective, {'initial_state_id','model'}), ...
    fullfile(finalizingDir, 'objective_decomposition.csv'));
writetable(sortrows(capacity, {'initial_state_id','model','site_id'}), ...
    fullfile(finalizingDir, 'capacity_saturation.csv'));
writetable(sortrows(stability, {'initial_state_id','R','site_id'}), ...
    fullfile(finalizingDir, 'stability_500_1000_2000.csv'));

auditLines = ["status=PASS"; "branch=" + branch; ...
    "local_head=" + head; "upstream_head=" + upstream; ...
    "states=7,9,11,19"; "R=2000"; ...
    "state_process_isolation=true"; "completed_state_count=4"; ...
    "failed_state_count=0"; "nominal_prefix_exact=true"; ...
    "deterministic_replay_max_DAC_error=0"; ...
    "formal_capacity_upper_kg=[300,200,100,150]"; ...
    "solver_call_count=" + solverCallCount; ...
    "total_state_runtime_sec=" + sprintf('%.6f', totalStateRuntime); ...
    "max_state_runtime_sec=" + sprintf('%.6f', maxStateRuntime); ...
    "finalizer_runtime_sec=" + sprintf('%.6f', toc(started)); ...
    "overall_peak_working_set_bytes=" + sprintf('%.0f', overallPeakMemory); ...
    "protected_paths_unchanged=true"; ...
    "checkcode_issue_count=" + codeIssueCount; ...
    "WDRO_call_count=0"; "MSP_call_count=0"; ...
    "validation_file_count=0"; "new_random_scenario_count=0"; ...
    "conclusion=" + conclusion];
for ii = 1:height(metrics)
    auditLines(end + 1) = "state_" + metrics.initial_state_id(ii) + ...
        "_runtime_sec=" + sprintf('%.6f', metrics.runtime_sec(ii)) + ...
        ";peak_bytes=" + sprintf('%.0f', metrics.peak_working_set_bytes(ii)) + ...
        ";solver_calls=" + metrics.solver_call_count(ii); %#ok<AGROW>
end
write_lines(fullfile(finalizingDir, 'mechanical_audit.txt'), auditLines);

conclusionLines = build_conclusion(summary, conclusion, solverCallCount, ...
    totalStateRuntime, overallPeakMemory);
write_lines(fullfile(finalizingDir, 'conclusion.txt'), conclusionLines);
readmeLines = build_readme(summary, conclusion, solverCallCount, ...
    totalStateRuntime, overallPeakMemory, statusBefore);
write_lines(fullfile(finalizingDir, 'README.md'), readmeLines);

rmdir(workDir, 's');
movefile(finalizingDir, outputDir);
append_log(fullfile(rootDir, 'codex_rule', 'log.md'), summary, conclusion, ...
    solverCallCount, totalStateRuntime, overallPeakMemory);
fprintf('Step-03Y-F PASS: %s.\n', conclusion);
end

function output = stability_core(input)
names = {'initial_state_id','R','site_id', ...
    'positive_demand_scenario_count','mean_total_demand_kg', ...
    'max_total_demand_kg','scenario_weight','T_aggregate_kg', ...
    'T_period_kg','period_minus_aggregate_kg', ...
    'site_absolute_difference_kg','site_difference_fraction_of_capacity', ...
    'aggregate_total_T_kg','period_total_T_kg', ...
    'period_minus_aggregate_total_kg','total_absolute_difference_kg', ...
    'total_difference_fraction_of_total_capacity','aggregate_at_capacity', ...
    'period_at_capacity','aggregate_relative_regret', ...
    'period_relative_regret','case_pass'};
output = input(:, names);
output.aggregate_at_capacity = double(output.aggregate_at_capacity);
output.period_at_capacity = double(output.period_at_capacity);
output.case_pass = double(output.case_pass);
end

function stability = add_stability_diagnostics(stability, stateIds, Cap, ...
        tol, closeCap, closeRegret)
stability.difference_direction = strings(height(stability), 1);
stability.site_direction_stable_across_R = false(height(stability), 1);
stability.reference_dominant_site_R500 = zeros(height(stability), 1);
stability.reference_direction_stable_across_R = false(height(stability), 1);
stability.state_max_site_difference_kg = zeros(height(stability), 1);
stability.state_max_relative_regret = zeros(height(stability), 1);
stability.state_close_diagnostic = false(height(stability), 1);
stability.aggregate_capacity_hit_count = zeros(height(stability), 1);
stability.period_capacity_hit_count = zeros(height(stability), 1);
sampleSizes = [500, 1000, 2000];
for ss = 1:numel(stateIds)
    stateId = stateIds(ss);
    r500 = stability(stability.initial_state_id == stateId & ...
        stability.R == 500, :);
    [~, dominantIndex] = max(r500.site_absolute_difference_kg);
    dominantSite = r500.site_id(dominantIndex);
    dominantDirections = zeros(3, 1);
    for kk = 1:3
        R = sampleSizes(kk);
        rows = stability.initial_state_id == stateId & stability.R == R;
        current = stability(rows, :);
        directions = sign_tol(current.period_minus_aggregate_kg, tol);
        stability.difference_direction(rows) = direction_labels(directions);
        dominantDirections(kk) = directions(current.site_id == dominantSite);
        maxRegret = max([current.aggregate_relative_regret(1), ...
            current.period_relative_regret(1)]);
        close = max(current.site_difference_fraction_of_capacity) <= closeCap && ...
            current.total_difference_fraction_of_total_capacity(1) <= closeCap && ...
            maxRegret <= closeRegret;
        stability.reference_dominant_site_R500(rows) = dominantSite;
        stability.state_max_site_difference_kg(rows) = ...
            max(current.site_absolute_difference_kg);
        stability.state_max_relative_regret(rows) = maxRegret;
        stability.state_close_diagnostic(rows) = close;
        stability.aggregate_capacity_hit_count(rows) = ...
            sum(current.aggregate_at_capacity);
        stability.period_capacity_hit_count(rows) = ...
            sum(current.period_at_capacity);
    end
    stateRows = stability.initial_state_id == stateId;
    stability.reference_direction_stable_across_R(stateRows) = ...
        all(dominantDirections == dominantDirections(1));
    for site = 1:4
        rows = stateRows & stability.site_id == site;
        directions = sign_tol(stability.period_minus_aggregate_kg(rows), tol);
        stability.site_direction_stable_across_R(rows) = ...
            all(directions == directions(1));
    end
end
if any(stability.site_difference_fraction_of_capacity > 1 + tol) || ...
        any(stability.T_aggregate_kg < -tol) || any(stability.T_period_kg < -tol) || ...
        any(stability.T_aggregate_kg - Cap(stability.site_id) > tol) || ...
        any(stability.T_period_kg - Cap(stability.site_id) > tol)
    error('Step-03Y-F stability values violate capacity/finite bounds.');
end
end

function summary = summarize_states(stability, capacity, stateIds, tol)
rows = struct([]);
for ss = 1:numel(stateIds)
    stateId = stateIds(ss);
    data = stability(stability.initial_state_id == stateId, :);
    r500 = data(data.R == 500, :);
    r1000 = data(data.R == 1000, :);
    r2000 = data(data.R == 2000, :);
    site2 = r2000(r2000.site_id == 2, :);
    maxDiff = max(r2000.site_absolute_difference_kg);
    totalDiff = abs(r2000.period_minus_aggregate_total_kg(1));
    if totalDiff / 750 <= 0.10 && ...
            max(r2000.site_difference_fraction_of_capacity) > 0.10
        effectType = "SITE_REALLOCATION_DOMINANT";
    elseif totalDiff / 750 > 0.10
        effectType = "TOTAL_AND_SITE_DIFFER";
    elseif maxDiff <= tol
        effectType = "NUMERICALLY_IDENTICAL";
    else
        effectType = "SMALL_MIXED_DIFFERENCE";
    end
    cap = capacity(capacity.initial_state_id == stateId, :);
    row = struct('initial_state_id', stateId, ...
        'max_site_difference_R500_kg', max(r500.site_absolute_difference_kg), ...
        'max_site_difference_R1000_kg', max(r1000.site_absolute_difference_kg), ...
        'max_site_difference_R2000_kg', maxDiff, ...
        'total_difference_R500_kg', r500.period_minus_aggregate_total_kg(1), ...
        'total_difference_R1000_kg', r1000.period_minus_aggregate_total_kg(1), ...
        'total_difference_R2000_kg', r2000.period_minus_aggregate_total_kg(1), ...
        'site2_difference_R2000_kg', site2.period_minus_aggregate_kg, ...
        'max_relative_regret_R2000', r2000.state_max_relative_regret(1), ...
        'close_R500', r500.state_close_diagnostic(1), ...
        'close_R1000', r1000.state_close_diagnostic(1), ...
        'close_R2000', r2000.state_close_diagnostic(1), ...
        'reference_site_R500', r2000.reference_dominant_site_R500(1), ...
        'reference_direction_stable', ...
        r2000.reference_direction_stable_across_R(1), ...
        'aggregate_capacity_hits_R2000', sum(cap.model == "AGGREGATE" & ...
        cap.at_capacity_upper), ...
        'period_capacity_hits_R2000', sum(cap.model == "PERIOD" & ...
        cap.at_capacity_upper), ...
        'R2000_effect_type', effectType);
    rows = append_struct(rows, row);
end
summary = struct2table(rows);
end

function conclusion = classify_result(summary, effectStateIds)
effect = summary(ismember(summary.initial_state_id, effectStateIds), :);
control = summary(summary.initial_state_id == 7, :);
if all(~effect.close_R2000) && all(effect.reference_direction_stable) && ...
        control.close_R2000
    conclusion = "A. PERIOD_EFFECT_STABLE";
elseif all(effect.close_R2000) && control.close_R2000
    conclusion = "B. AGGREGATE_AND_PERIOD_CONVERGE";
else
    conclusion = "C. STATE_DEPENDENT_OR_UNSTABLE";
end
end

function lines = build_conclusion(summary, conclusion, calls, runtime, peak)
lines = ["status=PASS"; "conclusion=" + conclusion; ...
    "completed_state_count=4"; "failed_state_count=0"; ...
    "solver_call_count=" + calls; ...
    "total_state_runtime_sec=" + sprintf('%.6f', runtime); ...
    "peak_working_set_bytes=" + sprintf('%.0f', peak); ...
    "state_7_consistent_R2000=" + lower(string(summary.close_R2000( ...
        summary.initial_state_id == 7))); ...
    "state_11_close_diagnostic_R2000=" + lower(string(summary.close_R2000( ...
        summary.initial_state_id == 11))); ...
    "state_11_continues_monotonic_convergence=" + lower(string( ...
        summary.max_site_difference_R2000_kg(summary.initial_state_id == 11) <= ...
        summary.max_site_difference_R1000_kg(summary.initial_state_id == 11))); ...
    "state_19_site2_difference_R2000_kg=" + sprintf('%.12g', ...
        summary.site2_difference_R2000_kg(summary.initial_state_id == 19)); ...
    "state_9_R2000_effect_type=" + summary.R2000_effect_type( ...
        summary.initial_state_id == 9); ...
    "WDRO_call_count=0"; "MSP_call_count=0"; ...
    "validation_file_count=0"];
for ii = 1:height(summary)
    lines(end + 1) = "state_" + summary.initial_state_id(ii) + ...
        "_max_site_diff_500_1000_2000=" + ...
        sprintf('%.12g', summary.max_site_difference_R500_kg(ii)) + "," + ...
        sprintf('%.12g', summary.max_site_difference_R1000_kg(ii)) + "," + ...
        sprintf('%.12g', summary.max_site_difference_R2000_kg(ii)) + ...
        ";total_diff=" + sprintf('%.12g', summary.total_difference_R500_kg(ii)) + ...
        "," + sprintf('%.12g', summary.total_difference_R1000_kg(ii)) + ...
        "," + sprintf('%.12g', summary.total_difference_R2000_kg(ii)); %#ok<AGROW>
end
end

function lines = build_readme(summary, conclusion, calls, runtime, peak, statusBefore)
lines = ["# Step-03Y-F run-001"; ""; "## Scope"; ""; ...
    "States 7, 9, 11, and 19 use the exact first 2000 frozen nominal records. Each state was solved in an independent MATLAB process and released before the next state."; ...
    ""; "Aggregate and period-resolved SAA use identical gamma, shortage penalty, service-cost basis, capacities, record order, and equal 1/R weights. R=500 and R=1000 are reused from Step-03Y-D/E for comparison."; ...
    ""; "## Result"; ""; "- Mechanical status: `PASS`."; ...
    "- Conclusion: `" + conclusion + "`."; ...
    "- Solver calls: `" + calls + "`."; ...
    "- Total isolated-state runtime: `" + sprintf('%.6f', runtime) + " s`."; ...
    "- Maximum per-process working set: `" + sprintf('%.0f', peak) + " bytes`."; ...
    "- WDRO, MSP, validation, distance, rho, and new random scenario calls: `0`."; ...
    ""; "## State summary"; ""];
for ii = 1:height(summary)
    lines(end + 1) = "- State " + summary.initial_state_id(ii) + ...
        ": max site differences R=500/1000/2000 = `" + ...
        sprintf('%.6f', summary.max_site_difference_R500_kg(ii)) + "/" + ...
        sprintf('%.6f', summary.max_site_difference_R1000_kg(ii)) + "/" + ...
        sprintf('%.6f', summary.max_site_difference_R2000_kg(ii)) + ...
        " kg`; R=2000 type `" + summary.R2000_effect_type(ii) + "`."; %#ok<AGROW>
end
lines = [lines; ""; "The close diagnostic reuses Step-03Y-D's descriptive 10% capacity-difference and 1% cross-regret criteria; it is not a new formal model threshold."; ...
    ""; "## Frozen start status"; ""; "```text"; statusBefore; "```"];
end

function append_log(logFile, summary, conclusion, calls, runtime, peak)
fid = fopen(logFile, 'a');
if fid < 0, error('Cannot append codex_rule/log.md.'); end
cleanup = onCleanup(@() fclose(fid));
fprintf(fid, '\n### 2026-07-29 - task-002 Step-03Y-F run-001 R=2000 aggregate versus period SAA final audit\n\n');
fprintf(fid, '- Frozen baseline/local/upstream: `f46321afbe78469962f97f26f4f8ccea0329f89d`; states `7,9,11,19`; exact nominal prefix R=2000. Each state ran in an independent MATLAB process and released large arrays before the next state.\n');
fprintf(fid, '- Aggregate and period SAA used identical gamma, shortage penalty, service costs, capacities, order, and 1/R weights. Deterministic replay D/A/C error was zero; no new scenarios or validation were used.\n');
for ii = 1:height(summary)
    fprintf(fid, '- State %d max site difference R=500/1000/2000: `%.12g/%.12g/%.12g kg`; total difference: `%.12g/%.12g/%.12g kg`; R=2000 type `%s`.\n', ...
        summary.initial_state_id(ii), summary.max_site_difference_R500_kg(ii), ...
        summary.max_site_difference_R1000_kg(ii), ...
        summary.max_site_difference_R2000_kg(ii), ...
        summary.total_difference_R500_kg(ii), ...
        summary.total_difference_R1000_kg(ii), ...
        summary.total_difference_R2000_kg(ii), summary.R2000_effect_type(ii));
end
fprintf(fid, '- Conclusion: `%s`; solver calls=`%d`; total isolated-state runtime=`%.6f s`; maximum process working set=`%.0f bytes`. WDRO/MSP/validation calls were zero; formal model and capacities were unchanged.\n', ...
    conclusion, calls, runtime, peak);
clear cleanup;
end

function output = normalize_terminal(input)
output = input;
output.failure_message = string(output.failure_message);
output.aggregate_at_capacity = double(output.aggregate_at_capacity);
output.period_at_capacity = double(output.period_at_capacity);
output.replay_complete = double(output.replay_complete);
output.case_pass = double(output.case_pass);
end

function output = normalize_cross(input)
output = input;
output.evaluation_model = string(output.evaluation_model);
output.terminalLOH_source = string(output.terminalLOH_source);
output.aggregate_status = string(output.aggregate_status);
output.period_status = string(output.period_status);
output.failure_message = string(output.failure_message);
output.replay_complete = double(output.replay_complete);
output.case_pass = double(output.case_pass);
end

function output = normalize_objective(input)
output = input;
output.model = string(output.model);
output.solver_status = string(output.solver_status);
output.case_pass = double(output.case_pass);
end

function output = normalize_capacity(input)
output = input;
output.model = string(output.model);
output.solver_status = string(output.solver_status);
output.at_capacity_upper = double(output.at_capacity_upper);
output.case_pass = double(output.case_pass);
end

function output = append_table(existing, added)
if isempty(existing), output = added; else, output = [existing; added]; end
end

function output = append_struct(existing, row)
if isempty(existing), output = row; else, output = [existing; row]; end
end

function values = sign_tol(values, tol)
values(abs(values) <= tol) = 0;
values(values > tol) = 1;
values(values < -tol) = -1;
end

function labels = direction_labels(values)
labels = repmat("ZERO", size(values));
labels(values > 0) = "PERIOD_HIGHER";
labels(values < 0) = "PERIOD_LOWER";
end

function paths = protected_paths()
paths = [ ...
    "results/task-002-stage2b-b3-smoke/16-dac-transport-cost-audit/run-001"; ...
    "results/task-002-stage2b-b3-smoke/23-fixed-decision-loss-consistency/run-001.failed-001"; ...
    "results/task-002-stage2b-b3-smoke/24-old-vs-ctilde-fixed-loss"; ...
    "results/task-002-stage2b-b3-smoke/25-old-cost-evidence-trace"; ...
    "results/task-002-stage2b-b3-smoke/26-old-ground-cost-recompute"; ...
    "results/task-002-stage2b-b3-smoke/27-period-data-recoverability/run-001.failed-001"; ...
    "results/task-002-stage2b-b3-smoke/27-period-data-recoverability/run-002/recovered_period_data.mat"; ...
    "results/task-002-stage2b-b3-smoke/30-period-lp-equivalence-audit"; ...
    "results/task-002-stage2b-b3-smoke/31-period-vs-aggregate-terminalLOH"; ...
    "results/task-002-stage2b-b3-smoke/32-saa-weight-capacity-audit"; ...
    "results/task-002-stage2b-b3-smoke/33-all-state-period-vs-aggregate-saa/run-001"; ...
    "results/task-002-stage2b-b3-smoke/34-period-vs-aggregate-saa-stability/run-001"; ...
    "terminalLoh_wdro/src/run_step03XB_old_ground_cost_recompute.py"; ...
    "terminalLoh_wdro/src/run_step03X_old_vs_ctilde_fixed_loss.py"; ...
    "terminalLoh_wdro/src/run_step03YBB_period_lp_equivalence_audit_h2.m"; ...
    "terminalLoh_wdro/src/run_step03YC_period_vs_aggregate_terminalLOH_h2.m"; ...
    "terminalLoh_wdro/src/run_step03YCA_saa_weight_capacity_audit_h2.m"; ...
    "terminalLoh_wdro/src/run_step03YE_period_vs_aggregate_saa_stability_h2.m"];
end

function digest = path_digest(path)
if isfile(path), digest = sha256_file(path); return; end
if ~isfolder(path), digest = "MISSING"; return; end
files = dir(fullfile(path, '**', '*')); files = files(~[files.isdir]);
relative = strings(numel(files), 1);
for ii = 1:numel(files)
    fullName = fullfile(files(ii).folder, files(ii).name);
    relative(ii) = string(erase(fullName, [char(path), filesep]));
end
[relative, order] = sort(relative); files = files(order);
md = java.security.MessageDigest.getInstance('SHA-256');
for ii = 1:numel(files)
    fullName = fullfile(files(ii).folder, files(ii).name);
    token = relative(ii) + "|" + string(files(ii).bytes) + "|" + ...
        sha256_file(fullName) + newline;
    md.update(typecast(unicode2native(char(token), 'UTF-8'), 'int8'));
end
raw = typecast(md.digest(), 'uint8');
digest = lower(string(reshape(dec2hex(raw, 2).', 1, [])));
end

function hash = sha256_file(fileName)
fid = fopen(fileName, 'rb');
if fid < 0, error('Cannot open protected file.'); end
cleanup = onCleanup(@() fclose(fid));
md = java.security.MessageDigest.getInstance('SHA-256');
while true
    bytes = fread(fid, 1024 * 1024, '*uint8');
    if isempty(bytes), break; end
    md.update(typecast(bytes, 'int8'));
end
raw = typecast(md.digest(), 'uint8');
hash = lower(string(reshape(dec2hex(raw, 2).', 1, [])));
clear cleanup;
end

function write_lines(fileName, lines)
fid = fopen(fileName, 'w');
if fid < 0, error('Cannot write final output.'); end
cleanup = onCleanup(@() fclose(fid));
for ii = 1:numel(lines), fprintf(fid, '%s\n', lines(ii)); end
clear cleanup;
end
