function prepare_step04CC6_35state_inputs_h2(workDir,initializeOnly)
%PREPARE_STEP04CC6_35STATE_INPUTS_H2 Recover and freeze 35 state inputs.

if nargin<2,initializeOnly=false;end

started=tic;workDir=string(workDir);
thisDir=fileparts(mfilename('fullpath'));rootDir=fileparts(fileparts(thisDir));
addpath(rootDir);addpath(thisDir);
assert_git_gate("task/002-stage2b-b3-smoke", ...
    "6840dccd995cf87d9e348ce8090003c6a74b773d");
if ~isfolder(workDir),mkdir(workDir);end
for name=["state_mapping_audit.csv","frozen_parameter_table.csv", ...
        "frozen_input_manifest.csv","prepared_state_manifest.csv", ...
        "solve_case_grid.csv","prepare_summary.csv", ...
        "nojvm_hash_equivalence_audit.csv","saa_solver_method_audit.csv", ...
        "python_solver_architecture_audit.csv"]
    if isfile(fullfile(workDir,name)),error('Refusing to overwrite %s.',name);end
end
preparedDir=fullfile(workDir,'prepared_inputs');
if isfolder(preparedDir),error('Refusing to overwrite prepared_inputs.');end
mkdir(preparedDir);
diary(fullfile(workDir,'prepare_matlab_diary.txt'));
cleanupDiary=onCleanup(@()diary('off')); %#ok<NASGU>

nearFile=fullfile(rootDir,'data','yuanqi','near_stage_msp_input.mat');
nominalMat=fullfile(rootDir,'terminalLoh_wdro','output', ...
    'stage3j_wdro_input_freeze','run-001','wdro_nominal_input_DAC.mat');
nominalCsv=fullfile(rootDir,'terminalLoh_wdro','output', ...
    'stage3j_wdro_input_freeze','run-001','wdro_nominal_input.csv');
stateSummaryFile=fullfile(rootDir,'terminalLoh_wdro','output', ...
    'stage3l_exact_atom_aggregation','run-001','exact_equivalence_summary_by_state.csv');
c5cResult=fullfile(rootDir,'results','task-002-stage2b-b3-smoke', ...
    '52-eta-response-saturation-audit','run-003','eta_optimization_results.csv');
recoverFile=fullfile(thisDir,'recover_step03Y_prefix_entries_h2.m');
aggregateFile=fullfile(thisDir,'aggregate_exact_period_scenarios_h2.m');
c5cSolverFile=fullfile(thisDir,'solve_terminal_loh_flat_chi2_decomposition_c5c_h2.m');
recoverNoJvmFile=fullfile(thisDir,'recover_step03Y_prefix_entries_c6_nojvm_h2.m');
aggregateNoJvmFile=fullfile(thisDir,'aggregate_exact_period_scenarios_c6_nojvm_h2.m');
saaCoreFile=fullfile(thisDir,'solve_terminal_loh_flat_chi2_core_h2.m');
saaWrapperFile=fullfile(thisDir,'solve_terminal_loh_saa_h2.m');
pythonCaseFile=fullfile(thisDir,'run_step04CC6_35state_case.py');
pythonCaseDriverFile=fullfile(thisDir,'run_step04CC6_python_cases.ps1');
backgroundControllerFile=fullfile(thisDir,'run_step04CC6_background_controller.ps1');
cloneDriverFile=fullfile(thisDir,'run_step04CC6_isolated_processes.ps1');

paths=[string(nearFile);string(nominalMat);string(nominalCsv); ...
    string(stateSummaryFile);string(recoverFile);string(aggregateFile); ...
    string(c5cSolverFile);string(c5cResult);string(recoverNoJvmFile); ...
    string(aggregateNoJvmFile);string(saaCoreFile);string(saaWrapperFile); ...
    string(pythonCaseFile);string(pythonCaseDriverFile); ...
    string(backgroundControllerFile);string(cloneDriverFile)];
labels=["near_stage_msp_input";"frozen_nominal_DAC";"frozen_nominal_identity"; ...
    "frozen_35state_mapping";"formal_period_recovery_code"; ...
    "exact_period_aggregation_code";"C5C_single_thread_solver"; ...
    "C5C_state19_reference";"C6_noJVM_period_recovery_copy"; ...
    "C6_noJVM_exact_aggregation_copy";"accepted_SAA_core"; ...
    "accepted_SAA_wrapper";"C6_pure_Python_case_solver"; ...
    "C6_sequential_Python_case_driver";"C6_background_controller"; ...
    "C6_preparation_clone_driver"];
expected=["536b25868e6d7cc812a331c0d3e0ffbd5f6958e6883bd39bcae3901c372abf24"; ...
    "6936a696f5cde137aca483f8c32adee33b52cbd90559a8e6395f3686c0712945"; ...
    "366dc3c0b57bfd76aca92f51ae1db82b93c764c87fa15e8cb4dd32388d018168"; ...
    "adf2dda40666a9e47917cfd660851ba236a6f4127c707699f85896563040bbd2"; ...
    "28065046748e05d6ef8f1f7a5525b1b268f5d6447fcf7145ec513b7acfaf56ab"; ...
    "03045d397c6dbcc84c14b0ff31667b932b441accf7076cfc0075d4b34168a1de"; ...
    "e4b61b0ce5eacED49c50078e1781519cab6909e0fe2965be792537b06e6ce67e"; ...
    "717e509fbea64bea5904cfe0c03b2d9ca5ba084f07a8952112b80623577ac613"; ...
    "48fb676470dd6fb3465333aad24eab1e5d2bcc66c4f5d6da6770e5ee2be72156"; ...
    "a75b8a64dd3ecc442225af58a2c243ed80666543ac2439b3dff8fb27988b7ff0"; ...
    "6778b8c85c8c99c06a39a89616e0ba20147fa799b04f18f1183a022ee027e05e"; ...
    "60b020964f38c0aaa8a32b732107191ad0ce0931a93efb082855e33db78c0fa5"; ...
    "7f18983c6211dd6de10ab242fa94627eaded32d4401ba6ec920f809cd3ec2aab"; ...
    "7d901f6fd46b18f087bdd618d50b9de407217fea56ffc9393c175bae5e121dfd"; ...
    "ad22729eb492c3197556fef1b2365cff077add67f3f9c9e2666fe75507631341"; ...
    "278aa5f7e3e4ea80520ca2553255eac8ad2fa21907a05201ca3cec9bb31e4fde"];
expected=lower(expected);actual=strings(size(paths));bytes=zeros(size(paths));
for ii=1:numel(paths)
    if ~isfile(paths(ii)),error('Missing frozen input: %s',paths(ii));end
    actual(ii)=sha256_file(paths(ii));info=dir(paths(ii));bytes(ii)=info.bytes;
    if actual(ii)~=expected(ii),error('Frozen input hash mismatch: %s',labels(ii));end
end
hashPass=actual==expected;
inputManifest=table(labels,paths,bytes,actual,expected,hashPass, ...
    'VariableNames',{'input_label','path','bytes','sha256','expected_sha256','hash_pass'});
writetable(inputManifest,fullfile(workDir,'frozen_input_manifest.csv'));
component=["period_recovery";"exact_aggregation"];
accepted_source=[string(recoverFile);string(aggregateFile)];
c6_nojvm_source=[string(recoverNoJvmFile);string(aggregateNoJvmFile)];
accepted_sha256=[actual(5);actual(6)];c6_nojvm_sha256=[actual(9);actual(10)];
allowed_change=["top-level function name; redundant stream hashes omitted while 15000 path mappings and final D/A/C remain exact"; ...
    "top-level function name and candidate SHA buckets replaced by exact raw-byte row equality"];
formal_DAC_logic_changed=false(2,1);accepted_source_modified=false(2,1);
equivalence_gate="per-state frozen stream hashes plus exact byte aggregation"+strings(2,1);
equivalenceAudit=table(component,accepted_source,c6_nojvm_source,accepted_sha256, ...
    c6_nojvm_sha256,allowed_change,formal_DAC_logic_changed, ...
    accepted_source_modified,equivalence_gate);
writetable(equivalenceAudit,fullfile(workDir,'nojvm_hash_equivalence_audit.csv'));
saaMethodAudit=table("SAA_eta_zero",2,"barrier",true,false,false, ...
    actual(11),actual(12),actual(13), ...
    "Method=2 reproduces C5C accepted state19 T; auto/simplex select another degenerate primary optimum", ...
    'VariableNames',{'method_label','gurobi_method','gurobi_method_name', ...
    'same_SAA_LP','accepted_source_modified','objective_changed', ...
    'accepted_core_sha256','accepted_wrapper_sha256','python_case_solver_sha256', ...
    'reason'});
writetable(saaMethodAudit,fullfile(workDir,'saa_solver_method_audit.csv'));
pythonSolverAudit=table("all_70_C6_optimization_cases","Python_gurobipy_12.0.1", ...
    false,true,true,true,true,true, ...
    "Each state-method case is one isolated Python process; SAA, DRO decomposition, independent fixed-T audit, and strict two-phase lexicographic replay execute sequentially inside that process", ...
    actual(13),actual(14),actual(15),actual(16), ...
    'VariableNames',{'scope','solver_runtime','MATLAB_Gurobi_MEX_used', ...
    'one_isolated_process_per_case','LP_calls_inside_case_process', ...
    'case_processes_sequential','primal_solution_and_duals_audited', ...
    'case_process_released_before_next','model_preservation', ...
    'python_case_solver_sha256','case_driver_sha256', ...
    'background_controller_sha256','preparation_clone_driver_sha256'});
writetable(pythonSolverAudit,fullfile(workDir,'python_solver_architecture_audit.csv'));

raw=load(nearFile,'NearStageInput');n=raw.NearStageInput;
prices=double(n.Cost.electricity_price_yuan_per_kWh(:));
lhv=double(n.HydrogenDevice.h2_lhv_kWh_per_kg);
etaFC=double(n.HydrogenDevice.eta_FC);kH2=double(n.HydrogenDevice.k_H2_kg_per_kWh);
averagePrice=mean(prices);electricityPerKg=lhv*etaFC;sec=1/kH2;
cH2=sec*averagePrice;VOLL=70;M=VOLL*electricityPerKg;
Cap=double(n.HydrogenDevice.tank_cap_kg(:));
if numel(prices)~=24||abs(lhv-33.33)>1e-12||abs(etaFC-0.55)>1e-12|| ...
        abs(kH2-0.0195)>1e-12||abs(averagePrice-0.634166666666667)>1e-14|| ...
        abs(cH2-32.5213675213675)>1e-10||abs(M-1283.205)>1e-9|| ...
        max(abs(Cap(:).'-[300,200,100,150]))>1e-12
    error('Frozen C5B/C5C economic parameter gate failed.');
end
parameter_name=["LHV";"eta_FC";"electricity_per_kg_H2";"k_H2"; ...
    "SEC_H2";"average_electricity_price";"c_H2";"VOLL";"M_H2"; ...
    "eta_SAA";"eta_DRO";"nominal_record_weight"];
value=[lhv;etaFC;electricityPerKg;kH2;sec;averagePrice;cH2;VOLL;M;0;0.03;1/15000];
unit=["kWh/kg";"ratio";"kWh/kg-H2";"kg/kWh";"kWh/kg"; ...
    "yuan/kWh";"yuan/kg";"yuan/kWh";"yuan/kg-H2";"radius";"radius";"probability"];
source=repmat("C5B/C5C accepted frozen parameter",numel(value),1);
parameters=table(parameter_name,value,unit,source);
writetable(parameters,fullfile(workDir,'frozen_parameter_table.csv'));

mapping=readtable(stateSummaryFile,'TextType','string');
mapping=sortrows(mapping,'initial_state_id');
if height(mapping)~=35||~isequal(double(mapping.initial_state_id),(1:35).')
    error('Frozen state mapping must contain state IDs 1:35 exactly once.');
end
expectedA=repelem((2:6).',7);expectedLoc=repmat((1:7).',5,1);
if ~isequal(double(mapping.a0),expectedA)||~isequal(double(mapping.loc0),expectedLoc)|| ...
        any(double(mapping.lfw0)~=0)||any(double(mapping.R)~=15000)
    error('Frozen state mapping order/content gate failed.');
end
state_id=double(mapping.initial_state_id);intensity=double(mapping.a0);loc=double(mapping.loc0);
lfw=double(mapping.lfw0);state_label="a0="+intensity+"|loc0="+loc+"|lfw0="+lfw;
mapping_order=(1:35).';scenario_count=repmat(15000,35,1);
scenario_input_path=repmat(string(nominalMat),35,1);
scenario_row_start=(state_id-1)*15000+1;scenario_row_end=state_id*15000;
nominal_weight=repmat(1/15000,35,1);path_probability_used=false(35,1);
stateMap=table(state_id,state_label,intensity,loc,lfw,mapping_order, ...
    scenario_input_path,scenario_row_start,scenario_row_end,scenario_count, ...
    nominal_weight,path_probability_used, ...
    'VariableNames',{'state_id','state_label','intensity','loc','lfw', ...
    'mapping_order','scenario_input_path','scenario_row_start','scenario_row_end', ...
    'scenario_count','nominal_weight','path_probability_used'});
writetable(stateMap,fullfile(workDir,'state_mapping_audit.csv'));

case_id=(1:70).';case_state_id=ceil(case_id/2);method_index=mod(case_id-1,2)+1;
eta=zeros(70,1);eta(method_index==2)=0.03;
method_label=repmat("SAA",70,1);method_label(method_index==2)="ETA_0.03";
state_label_grid=state_label(case_state_id);intensity_grid=intensity(case_state_id);
loc_grid=loc(case_state_id);lfw_grid=lfw(case_state_id);
caseGrid=table(case_id,case_state_id,state_label_grid,intensity_grid,loc_grid, ...
    lfw_grid,method_index,method_label,eta,repmat(15000,70,1), ...
    repmat(1/15000,70,1),repmat(cH2,70,1),repmat(M,70,1), ...
    'VariableNames',{'case_id','state_id','state_label','intensity','loc','lfw', ...
    'method_index','method_label','eta','scenario_count','nominal_weight', ...
    'c_H2_yuan_per_kg','M_H2_yuan_per_kg'});
writetable(caseGrid,fullfile(workDir,'solve_case_grid.csv'));

if initializeOnly
    stateRowDir=fullfile(workDir,'prepared_state_rows');
    if isfolder(stateRowDir),error('Refusing to overwrite prepared_state_rows.');end
    mkdir(stateRowDir);
    fprintf('STEP04CC6_PREPARE_INITIALIZE_COMPLETE|states=35|cases=70|runtime=%.3f\n',toc(started));
    return
end

manifestRows=cell(35,13);
for ss=1:35
    sid=state_id(ss);stateStarted=tic;
    fprintf('STEP04CC6_PREPARE_STATE_START|state=%d\n',sid);
    [entry,context]=recover_step03Y_prefix_entries_h2(rootDir,sid,15000,false,"nominal");
    if ~entry.audit.all_final_DAC_exact||~entry.audit.all_stream_hashes_match|| ...
            entry.audit.max_DAC_error~=0||height(entry.identity)~=15000|| ...
            any(double(entry.identity.initial_state_id)~=sid)|| ...
            max(abs(double(entry.identity.frozen_nominal_weight)-1/15000))>1e-15
        error('Formal period recovery gate failed for state %d.',sid);
    end
    aggregation=aggregate_exact_period_scenarios_h2( ...
        entry.Dperiod,entry.Aperiod,entry.Cperiod);
    if aggregation.original_R~=15000||~aggregation.exact_verification_pass|| ...
            abs(sum(aggregation.nominal_probability)-1)>1e-12|| ...
            max(abs(aggregation.nominal_probability-aggregation.multiplicity/15000))>1e-15|| ...
            max(abs(double(context.Cap(:))-Cap))>1e-12
        error('Exact aggregation gate failed for state %d.',sid);
    end
    DperiodGroup=aggregation.Dperiod;AperiodGroup=aggregation.Aperiod;
    CperiodGroup=aggregation.Cperiod;qGroup=aggregation.nominal_probability;
    groupId=aggregation.group_id;multiplicity=aggregation.multiplicity;
    groupCount=aggregation.group_count;originalR=aggregation.original_R;
    stateId=sid;a0=intensity(ss);loc0=loc(ss);lfw0=lfw(ss);stateLabel=state_label(ss);
    payload=fullfile(preparedDir,sprintf('state-%03d-period-input.mat',sid));
    save(payload,'DperiodGroup','AperiodGroup','CperiodGroup','qGroup', ...
        'groupId','multiplicity','groupCount','originalR','Cap','stateId', ...
        'a0','loc0','lfw0','stateLabel','cH2','M','electricityPerKg','-v7');
    payloadHash=sha256_file(payload);info=dir(payload);
    manifestRows(ss,:)={sid,state_label(ss),intensity(ss),loc(ss),lfw(ss), ...
        string(payload),info.bytes,payloadHash,15000,groupCount, ...
        aggregation.duplicate_record_count,aggregation.maximum_multiplicity,toc(stateStarted)};
    preparedManifest=cell2table(manifestRows(1:ss,:), ...
        'VariableNames',{'state_id','state_label','intensity','loc','lfw', ...
        'local_payload_path','payload_bytes','payload_sha256','original_R', ...
        'exact_group_count','duplicate_record_count','maximum_multiplicity', ...
        'prepare_runtime_sec'});
    writetable(preparedManifest,fullfile(workDir,'prepared_state_manifest.csv'));
    fprintf('STEP04CC6_PREPARE_STATE_COMPLETE|state=%d|groups=%d|runtime=%.3f\n', ...
        sid,groupCount,toc(stateStarted));
    clear entry context aggregation DperiodGroup AperiodGroup CperiodGroup qGroup groupId multiplicity
end

preparedManifest=readtable(fullfile(workDir,'prepared_state_manifest.csv'),'TextType','string');
summary=table(35,70,35*15000,sum(double(preparedManifest.exact_group_count)), ...
    min(double(preparedManifest.exact_group_count)), ...
    max(double(preparedManifest.exact_group_count)),cH2,M,electricityPerKg, ...
    all(hashPass),toc(started), ...
    'VariableNames',{'state_count','optimization_case_count','total_original_records', ...
    'total_exact_groups','minimum_exact_groups','maximum_exact_groups', ...
    'c_H2','M_H2','electricity_per_kg_H2','all_frozen_hashes_pass', ...
    'prepare_runtime_sec'});
writetable(summary,fullfile(workDir,'prepare_summary.csv'));
fid=fopen(fullfile(workDir,'prepare_mechanical_audit.txt'),'w');
cleanup=onCleanup(@()fclose(fid)); %#ok<NASGU>
fprintf(fid,'status=PASS\nstate_count=35\ncase_count=70\neta_set=0,0.03\n');
fprintf(fid,'all_states_R15000=1\nall_nominal_weights_1_over_15000=1\n');
fprintf(fid,'path_probability_used=0\nall_period_DAC_replay_exact=1\n');
fprintf(fid,'C_y_in_primary=0\nMSP_called=0\nC5B_C5C_solver_modified=0\n');
fprintf('STEP04CC6_PREPARE_COMPLETE|states=35|cases=70|runtime=%.3f\n',toc(started));
end

function assert_git_gate(expectedBranch,expectedHead)
[s1,b]=system('git branch --show-current');[s2,h]=system('git rev-parse HEAD');
[s3,u]=system('git rev-parse @{upstream}');
if s1~=0||s2~=0||s3~=0||strtrim(string(b))~=expectedBranch|| ...
        strtrim(string(h))~=expectedHead||strtrim(string(u))~=expectedHead
    error('Step-04C-C6 frozen Git gate failed.');
end
end
function hash=sha256_file(fileName)
stream=System.IO.File.OpenRead(char(fileName));cleanup=onCleanup(@()stream.Dispose()); %#ok<NASGU>
md=System.Security.Cryptography.SHA256Managed;digest=uint8(md.ComputeHash(stream));md.Dispose();
hash=lower(string(reshape(dec2hex(digest,2).',1,[])));
end
