function result = run_step03T_ctilde_tier1_structural_diagnosis_h2()
%RUN_STEP03T_CTILDE_TIER1_STRUCTURAL_DIAGNOSIS_H2 Small exact diagnosis.

taskTic = tic;
thisDir = fileparts(mfilename('fullpath'));
moduleDir = fileparts(thisDir);
rootDir = fileparts(moduleDir);
addpath(thisDir);
addpath(fullfile(rootDir, 'fa_h2', 'fuzhu', 'terminalLoh_windmc'));
resultRoot = fullfile(rootDir, 'results', ...
    'task-002-stage2b-b3-smoke');
outputDir = fullfile(resultRoot, ...
    '20-ctilde-tier1-structural-diagnosis', 'run-001');
tempDir = outputDir + ".tmp";
localDir = fullfile(moduleDir, 'output', ...
    'stage3t_ctilde_tier1_structural_diagnosis', 'run-001');
if isfolder(outputDir)
    error('Step-03T final output directory already exists.');
end
if isfolder(tempDir)
    rmdir(tempDir, 's');
end
if ~isfolder(tempDir)
    mkdir(tempDir);
end
if ~isfolder(localDir)
    mkdir(localDir);
end

config = build_config();
stepSDir = fullfile(resultRoot, ...
    '19-state-distribution-tail-regret-audit', 'run-001');
checkpointDir = fullfile(moduleDir, 'output', ...
    'stage3s_state_distribution_tail_regret_audit', 'run-001', ...
    'checkpoints');
stepJDir = fullfile(moduleDir, 'output', ...
    'stage3j_wdro_input_freeze', 'run-001');
nominalPath = fullfile(stepJDir, 'wdro_nominal_input_DAC.mat');
stepPHistory = fullfile(resultRoot, ...
    '16-dac-transport-cost-audit', 'run-001');
required = [string(fullfile(stepSDir, 'step03S_tail_cross_regret.csv')); ...
    string(fullfile(stepSDir, 'step03S_false_near_cases.csv')); ...
    string(fullfile(stepSDir, 'step03S_tail_nearest_neighbors.csv')); ...
    string(fullfile(stepSDir, 'step03S_selected_states.csv')); ...
    string(fullfile(stepSDir, 'step03S_state_tail_profiles.csv')); ...
    string(fullfile(stepSDir, 'step03S_acceptance_tests.csv')); ...
    string(nominalPath)];
for ii = 1:numel(required)
    if ~isfile(required(ii))
        error('Step-03T missing required input: %s', required(ii));
    end
end
if ~isfolder(checkpointDir) || ~isfolder(stepPHistory)
    error('Step-03T required Step-03S checkpoints or Step-03P history missing.');
end
nominalHash = sha256_file(nominalPath);
if nominalHash ~= config.nominalHash
    error('Step-03T Step-03J nominal MAT hash mismatch.');
end

stepSBefore = directory_hash(stepSDir);
checkpointBefore = directory_hash(checkpointDir);
stepPBefore = directory_hash(stepPHistory);
protectedFiles = [string(fullfile(thisDir, 'step03S_distance_block_h2.m')); ...
    string(fullfile(thisDir, 'run_step03S_state_distribution_tail_regret_audit_h2.m')); ...
    string(fullfile(thisDir, 'build_step03Q_distance_matrix_h2.m')); ...
    string(fullfile(thisDir, 'solve_wdro_terminal_loh_lp_h2.m')); ...
    string(fullfile(thisDir, 'solve_wdro_terminal_loh_lp_constraint_generation_h2.m')); ...
    string(fullfile(rootDir, 'main_msp_h2_near.m')); ...
    string(fullfile(rootDir, 'fa_h2', 'build_stage_model_h2.m')); ...
    string(fullfile(rootDir, 'fa_h2', 'solve_stage_model_h2.m'))];
protectedBefore = hash_files(protectedFiles);
peakMemory = memory_snapshot();

crossTbl = readtable(fullfile(stepSDir, ...
    'step03S_tail_cross_regret.csv'), 'TextType', 'string');
falseTbl = readtable(fullfile(stepSDir, ...
    'step03S_false_near_cases.csv'), 'TextType', 'string');
neighborTbl = readtable(fullfile(stepSDir, ...
    'step03S_tail_nearest_neighbors.csv'), 'TextType', 'string');
selectedStates = readtable(fullfile(stepSDir, ...
    'step03S_selected_states.csv'), 'TextType', 'string');
stateProfiles = readtable(fullfile(stepSDir, ...
    'step03S_state_tail_profiles.csv'), 'TextType', 'string');
stepSAcceptance = readlines(fullfile(stepSDir, ...
    'step03S_acceptance_tests.csv'));
stepSAcceptance = strtrim(stepSAcceptance);
stepSAcceptance(stepSAcceptance == "") = [];
validate_stepS_inputs(crossTbl, falseTbl, neighborTbl, selectedStates, ...
    stateProfiles, stepSAcceptance, config);

[selectedPairs, rationaleLines] = select_pairs(crossTbl, config);
writetable(selectedPairs, fullfile(tempDir, 'step03T_selected_pairs.csv'));
write_lines(fullfile(tempDir, 'step03T_pair_selection_rationale.md'), ...
    rationaleLines);
peakMemory = max(peakMemory, memory_snapshot());

rawNear = load(fullfile(rootDir, 'data', 'yuanqi', ...
    'near_stage_msp_input.mat'), 'NearStageInput');
ni = rawNear.NearStageInput;
Cap = double(ni.HydrogenDevice.tank_cap_kg(:));
if max(abs(Cap - [300; 200; 100; 150])) > 1e-12
    error('Step-03T capacity vector mismatch.');
end
if isfield(ni.Cost, 'reserve_shortage_penalty_yuan_per_kg')
    M = double(ni.Cost.reserve_shortage_penalty_yuan_per_kg);
elseif isfield(ni.Cost, 'cost_reserve_shortage')
    M = double(ni.Cost.cost_reserve_shortage);
else
    error('Step-03T cannot trace the shortage penalty.');
end
config.gamma = 0.001 * M;
layout = build_h2_spatial_layout_preview(ni);
nodeX = double(layout.nodes.x_km(:)).';
nodeY = double(layout.nodes.y_km(:)).';

[pairData, chainAudit] = load_selected_pair_data(selectedPairs, ...
    nominalPath, checkpointDir, nodeX, nodeY, config);
save(fullfile(localDir, 'step03T_selected_pair_checkpoint.mat'), ...
    'selectedPairs', 'pairData', 'chainAudit', 'config', '-v7.3');
peakMemory = max(peakMemory, memory_snapshot());

[jointTbl, demandTbl, serviceTbl, ctildeTbl, diagnostic] = ...
    diagnose_pairs(selectedPairs, pairData, nodeX, nodeY, Cap, config);
writetable(jointTbl, fullfile(tempDir, ...
    'step03T_joint_service_feature_comparison.csv'));
writetable(demandTbl, fullfile(tempDir, ...
    'step03T_demand_difference_detail.csv'));
writetable(serviceTbl, fullfile(tempDir, ...
    'step03T_service_relation_change.csv'));
writetable(ctildeTbl, fullfile(tempDir, ...
    'step03T_ctilde_relation_detail.csv'));

[replayTbl, nodeLossTbl, replayAudit, replayDetail] = ...
    replay_selected_pairs(selectedPairs, pairData, M, config);
writetable(replayTbl, fullfile(tempDir, 'step03T_cross_recourse_detail.csv'));
writetable(nodeLossTbl, fullfile(tempDir, ...
    'step03T_node_loss_contribution.csv'));
peakMemory = max(peakMemory, memory_snapshot());

failureTbl = classify_failure_modes(selectedPairs, diagnostic, ...
    replayDetail, config);
writetable(failureTbl, fullfile(tempDir, ...
    'step03T_failure_mode_classification.csv'));
comparisonTbl = compare_tier_and_controls(selectedPairs, diagnostic);
writetable(comparisonTbl, fullfile(tempDir, ...
    'step03T_tier1_control_comparison.csv'));

[concentrationTbl, concentration] = tier1_concentration(crossTbl, config);
writetable(concentrationTbl, fullfile(tempDir, ...
    'step03T_tier1_concentration.csv'));
peakMemory = max(peakMemory, memory_snapshot());

conclusion = choose_conclusion(failureTbl, chainAudit, replayAudit, ...
    concentration, config);
write_method_brief(fullfile(tempDir, 'step03T_method_problem_brief.md'), ...
    failureTbl, comparisonTbl, concentration, conclusion, config);

stepSAfter = directory_hash(stepSDir);
checkpointAfter = directory_hash(checkpointDir);
stepPAfter = directory_hash(stepPHistory);
protectedAfter = hash_files(protectedFiles);
codeMessages = [checkcode(mfilename('fullpath'), '-id'); ...
    checkcode(fullfile(thisDir, 'evaluate_step03T_fixed_T_recourse_h2.m'), '-id')];
runtimeSec = toc(taskTic);
peakMemory = max(peakMemory, memory_snapshot());

[acceptanceTbl, pass] = build_acceptance(selectedPairs, chainAudit, ...
    replayAudit, failureTbl, concentration, stepSBefore, stepSAfter, ...
    checkpointBefore, checkpointAfter, stepPBefore, stepPAfter, ...
    protectedBefore, protectedAfter, codeMessages, runtimeSec, ...
    peakMemory, nominalHash, config);
writetable(acceptanceTbl, fullfile(tempDir, 'step03T_acceptance_tests.csv'));

resourceTbl = table(runtimeSec, peakMemory, height(selectedPairs), ...
    sum(selectedPairs.group_type == "TIER1"), ...
    sum(selectedPairs.group_type == "CONTROL"), height(replayTbl), ...
    height(nodeLossTbl), string(nominalPath), nominalHash, ...
    'VariableNames', {'runtime_sec', 'peak_working_set_bytes', ...
    'selected_pair_count', 'tier1_pair_count', 'control_pair_count', ...
    'fixed_T_replay_count', 'node_loss_row_count', ...
    'nominal_input_path', 'nominal_input_sha256'});
writetable(resourceTbl, fullfile(tempDir, 'step03T_resource_report.csv'));
write_summary(fullfile(tempDir, 'step03T_summary.txt'), selectedPairs, ...
    jointTbl, failureTbl, comparisonTbl, concentration, chainAudit, ...
    replayAudit, conclusion, runtimeSec, peakMemory, pass, config);
save(fullfile(localDir, 'step03T_final_checkpoint.mat'), ...
    'selectedPairs', 'jointTbl', 'replayTbl', 'nodeLossTbl', ...
    'failureTbl', 'comparisonTbl', 'concentrationTbl', ...
    'acceptanceTbl', 'resourceTbl', 'conclusion', '-v7.3');

if ~pass
    error('Step-03T acceptance failed; results remain in the temporary directory.');
end
movefile(tempDir, outputDir);
result = struct('output_dir', string(outputDir), 'local_dir', string(localDir), ...
    'selected_pair_count', height(selectedPairs), ...
    'tier1_pair_count', sum(selectedPairs.group_type == "TIER1"), ...
    'control_pair_count', sum(selectedPairs.group_type == "CONTROL"), ...
    'runtime_sec', runtimeSec, 'peak_working_set_bytes', peakMemory, ...
    'conclusion', conclusion, 'pass', pass);
fprintf('Step-03T PASS: %s, pairs=%d, runtime=%.3f s.\n', ...
    conclusion, height(selectedPairs), runtimeSec);
end

function config = build_config()
config = struct('states', [7; 18; 30; 31; 11; 21], ...
    'rowsPerState', 15000, 'maximumTierPairsPerState', 3, ...
    'maximumControlPairsPerState', 1, 'maximumPairCount', 24, ...
    'distanceTolerance', 1e-8, 'chainTolerance', 1e-8, ...
    'zeroDistanceTolerance', 1e-12, 'lowRegretThreshold', 0.01, ...
    'tierRegretThreshold', 0.10, 'C_bound', 357.1526447416079, ...
    'kappa', 1, 'weight_D', 0.6, 'weight_Ctilde', 0.4, ...
    'epsDistance', 1e-9, 'hardRuntimeSec', 1800, ...
    'softRuntimeSec', 1200, 'validationInputUsed', false, ...
    'nominalHash', "6936a696f5cde137aca483f8c32adee33b52cbd90559a8e6395f3686c0712945");
end

function validate_stepS_inputs(crossTbl, falseTbl, neighborTbl, ...
        selectedStates, stateProfiles, acceptance, config)
requiredCross = {'initial_state_id', 'scenario_r', 'scenario_s', ...
    'path_id_r', 'path_id_s', 'pair_type', 'nearest_all_rank', ...
    'd_D', 'd_Ctilde', 'd_new', 'T_r1', 'T_r2', 'T_r3', 'T_r4', ...
    'T_s1', 'T_s2', 'T_s3', 'T_s4', 'optimal_objective_r', ...
    'optimal_objective_s', 'relative_regret_obj_r_to_s', ...
    'relative_regret_obj_s_to_r', 'regret_obj_r_to_s', ...
    'regret_obj_s_to_r', 'regret_loss_r_to_s', ...
    'regret_loss_s_to_r', 'tier_1'};
if ~all(ismember(requiredCross, crossTbl.Properties.VariableNames))
    error('Step-03T Step-03S cross-regret schema mismatch.');
end
if height(crossTbl) ~= 125755 || height(falseTbl) ~= 7743 || ...
        height(neighborTbl) ~= 174157 || height(selectedStates) ~= 6 || ...
        height(stateProfiles) ~= 3990 || numel(acceptance) - 1 ~= 20
    error('Step-03T Step-03S frozen row counts mismatch.');
end
if ~isequal(sort(double(selectedStates.initial_state_id)), ...
        sort(config.states))
    error('Step-03T selected state set differs from Step-03S.');
end
if sum(as_logical(crossTbl.tier_1)) ~= 7733
    error('Step-03T frozen Tier-1 count is not 7733.');
end
if any(~contains(acceptance(2:end), ",PASS,"))
    error('Step-03T Step-03S acceptance input contains failures.');
end
end

function [selected, lines] = select_pairs(crossTbl, config)
tier = crossTbl(as_logical(crossTbl.tier_1), :);
records = cell(0, 1);
for ss = 1:numel(config.states)
    stateId = config.states(ss);
    local = tier(double(tier.initial_state_id) == stateId, :);
    if isempty(local)
        error('Step-03T state %d has no Tier-1 rows.', stateId);
    end
    severity = min(double(local.relative_regret_obj_r_to_s), ...
        double(local.relative_regret_obj_s_to_r));
    chosen = zeros(0, 1);
    [~, orderDistance] = sortrows([double(local.d_new), ...
        double(local.scenario_r), double(local.scenario_s)], [1, 2, 3]);
    chosen(end + 1) = orderDistance(1); %#ok<AGROW>
    [~, orderSeverity] = sortrows([-severity, double(local.d_new), ...
        double(local.scenario_r), double(local.scenario_s)], [1, 2, 3, 4]);
    chosen(end + 1) = first_new(orderSeverity, chosen); %#ok<AGROW>
    categoryPriority = category_priority(string(local.pair_type));
    structural = double(local.A_reachability_change_count) + ...
        double(local.changed_local_count) + ...
        double(local.T_L1_difference_kg) ./ 10;
    [~, orderCategory] = sortrows([categoryPriority, -structural, ...
        double(local.d_new), double(local.scenario_r), ...
        double(local.scenario_s)], [1, 2, 3, 4, 5]);
    while numel(unique(chosen)) < config.maximumTierPairsPerState
        chosen(end + 1) = first_new(orderCategory, chosen); %#ok<AGROW>
    end
    chosen = unique(chosen, 'stable');
    rules = ["MINIMUM_D_NEW"; "MAXIMUM_BIDIRECTIONAL_SEVERITY"; ...
        "CATEGORY_REPRESENTATIVE"];
    for kk = 1:numel(chosen)
        records{end + 1, 1} = selected_record(local(chosen(kk), :), ...
            "TIER1", rules(kk), severity(chosen(kk))); %#ok<AGROW>
    end

    controls = crossTbl(double(crossTbl.initial_state_id) == stateId & ...
        double(crossTbl.nearest_all_rank) <= 10 & ...
        double(crossTbl.d_new) > config.zeroDistanceTolerance & ...
        double(crossTbl.relative_regret_obj_r_to_s) < ...
            config.lowRegretThreshold & ...
        double(crossTbl.relative_regret_obj_s_to_r) < ...
            config.lowRegretThreshold, :);
    if isempty(controls)
        error('Step-03T state %d has no nonzero low-regret control.', stateId);
    end
    targetDistance = median(double(local(chosen, :).d_new));
    score = abs(log(max(double(controls.d_new), eps) ./ ...
        max(targetDistance, eps)));
    [~, controlOrder] = sortrows([score, double(controls.d_new), ...
        double(controls.scenario_r), double(controls.scenario_s)], ...
        [1, 2, 3, 4]);
    controlSeverity = min(double(controls.relative_regret_obj_r_to_s), ...
        double(controls.relative_regret_obj_s_to_r));
    records{end + 1, 1} = selected_record(controls(controlOrder(1), :), ...
        "CONTROL", "LOW_REGRET_DISTANCE_MATCHED", ...
        controlSeverity(controlOrder(1))); %#ok<AGROW>
end
selected = records_to_table(records);
selected.pair_id = (1:height(selected)).';
selected = movevars(selected, 'pair_id', 'Before', 1);
if height(selected) > config.maximumPairCount
    error('Step-03T selected more than 24 pairs.');
end
lines = ["# Step-03T Pair Selection Rationale"; ""; ...
    "Selection is deterministic and reads only the frozen Step-03S cross-regret table."; ...
    "Each of states 7, 18, 30, 31, 11, and 21 contributes three distinct Tier-1 representatives and one nonzero-distance low-regret control."; ...
    "Tier-1 rules are minimum d_new, maximum min(two directional objective regrets), and a category/structural representative preferring tail-tail then non-tail/tail."; ...
    "Controls are nearest-all pairs with both directional relative objective regrets below 1%, selected closest on a log-distance scale to the state's Tier-1 median distance."; ...
    "No nearest-neighbor search, scenario optimization, or Step-03S calculation is repeated during selection."; ""];
for rr = 1:height(selected)
    lines(end + 1) = "- pair " + selected.pair_id(rr) + ...
        ": state " + selected.initial_state_id(rr) + ", " + ...
        selected.group_type(rr) + ", rule=" + selected.selection_rule(rr) + ...
        ", scenarios " + selected.scenario_r(rr) + "-" + ...
        selected.scenario_s(rr) + ", d_new=" + ...
        sprintf('%.12g', selected.d_new(rr)) + ", severity=" + ...
        sprintf('%.12g', selected.bidirectional_severity(rr)) + "."; %#ok<AGROW>
end
end

function idx = first_new(order, chosen)
for ii = 1:numel(order)
    if ~ismember(order(ii), chosen)
        idx = order(ii);
        return;
    end
end
error('Step-03T could not find a distinct representative pair.');
end

function priority = category_priority(labels)
priority = 3 * ones(numel(labels), 1);
priority(labels == "TAIL_TAIL") = 1;
priority(labels == "NONTAIL_TAIL") = 2;
end

function rec = selected_record(row, groupType, rule, severity)
rec = table2struct(row);
rec.group_type = groupType;
rec.selection_rule = rule;
rec.bidirectional_severity = severity;
rec.relative_regret_loss_r_to_s = double(row.regret_loss_r_to_s) / ...
    max(abs(double(row.own_operating_loss_s)), 1e-8);
rec.relative_regret_loss_s_to_r = double(row.regret_loss_s_to_r) / ...
    max(abs(double(row.own_operating_loss_r)), 1e-8);
rec.relative_regret_loss_source = ...
    "derived_from_frozen_absolute_regret_and_own_operating_loss";
end

function [pairData, audit] = load_selected_pair_data(selected, matPath, ...
        checkpointDir, nodeX, nodeY, config)
m = matfile(matPath);
P = height(selected);
pairData = repmat(struct('D_r', [], 'A_r', [], 'C_r', [], ...
    'D_s', [], 'A_s', [], 'C_s', [], 'Dscale', NaN, ...
    'path_r', NaN, 'path_s', NaN, 'centroid_r', [], 'centroid_s', []), P, 1);
distanceError = zeros(P, 3);
checkpointError = zeros(P, 1);
checkpointRelativeError = zeros(P, 1);
identityPass = true(P, 1);
loadedCross = cell(numel(config.states), 1);
loadedScale = NaN(numel(config.states), 1);
for ss = 1:numel(config.states)
    stateId = config.states(ss);
    depth = load(fullfile(checkpointDir, ...
        sprintf('depth_state_%02d.mat', stateId)), 'stateDepth');
    scale = load(fullfile(checkpointDir, ...
        sprintf('neighbors_state_%02d.mat', stateId)), 'Dscale');
    loadedCross{ss} = depth.stateDepth.cross;
    loadedScale(ss) = scale.Dscale;
end
critical = {'d_D', 'd_Ctilde', 'd_new', 'T_r1', 'T_r2', 'T_r3', ...
    'T_r4', 'T_s1', 'T_s2', 'T_s3', 'T_s4', ...
    'optimal_objective_r', 'optimal_objective_s', ...
    'regret_loss_r_to_s', 'regret_loss_s_to_r'};
relativeFields = {'relative_regret_obj_r_to_s', ...
    'relative_regret_obj_s_to_r'};
for pp = 1:P
    stateId = double(selected.initial_state_id(pp));
    statePos = find(config.states == stateId, 1);
    r = double(selected.scenario_r(pp));
    s = double(selected.scenario_s(pp));
    globalR = (stateId - 1) * config.rowsPerState + r;
    globalS = (stateId - 1) * config.rowsPerState + s;
    pairData(pp).D_r = double(m.D_node_kg(globalR, :));
    pairData(pp).A_r = logical(m.A_site_node(globalR, :, :));
    pairData(pp).C_r = double(m.C_site_node_km(globalR, :, :));
    pairData(pp).D_s = double(m.D_node_kg(globalS, :));
    pairData(pp).A_s = logical(m.A_site_node(globalS, :, :));
    pairData(pp).C_s = double(m.C_site_node_km(globalS, :, :));
    pairData(pp).path_r = double(m.path_id(globalR, 1));
    pairData(pp).path_s = double(m.path_id(globalS, 1));
    pairData(pp).Dscale = loadedScale(statePos);
    pairData(pp).centroid_r = demand_centroid(pairData(pp).D_r, nodeX, nodeY);
    pairData(pp).centroid_s = demand_centroid(pairData(pp).D_s, nodeX, nodeY);
    [dNew, dD, dC] = step03S_distance_block_h2( ...
        pairData(pp).D_r, pairData(pp).A_r, pairData(pp).C_r, ...
        pairData(pp).D_s, pairData(pp).A_s, pairData(pp).C_s, ...
        pairData(pp).Dscale, config);
    distanceError(pp, :) = abs([dD - double(selected.d_D(pp)), ...
        dC - double(selected.d_Ctilde(pp)), ...
        dNew - double(selected.d_new(pp))]);
    cp = loadedCross{statePos};
    hit = cp(double(cp.scenario_r) == r & double(cp.scenario_s) == s, :);
    if height(hit) ~= 1
        identityPass(pp) = false;
        checkpointError(pp) = Inf;
    else
        errs = zeros(numel(critical), 1);
        for kk = 1:numel(critical)
            errs(kk) = abs(double(hit.(critical{kk})(1)) - ...
                double(selected.(critical{kk})(pp)));
        end
        checkpointError(pp) = max(errs);
        relativeErrs = zeros(numel(relativeFields), 1);
        for kk = 1:numel(relativeFields)
            lhs = double(hit.(relativeFields{kk})(1));
            rhs = double(selected.(relativeFields{kk})(pp));
            relativeErrs(kk) = abs(lhs - rhs) / max([1, abs(lhs), abs(rhs)]);
        end
        checkpointRelativeError(pp) = max(relativeErrs);
        identityPass(pp) = pairData(pp).path_r == ...
            double(selected.path_id_r(pp)) && pairData(pp).path_s == ...
            double(selected.path_id_s(pp));
    end
end
audit = struct('max_distance_error', max(distanceError, [], 'all'), ...
    'max_checkpoint_error', max(checkpointError), ...
    'max_checkpoint_relative_regret_normalized_error', ...
        max(checkpointRelativeError), ...
    'identity_pass', all(identityPass), ...
    'distance_error', distanceError, ...
    'checkpoint_error', checkpointError);
end

function centroid = demand_centroid(D, nodeX, nodeY)
total = sum(D);
if total <= 1e-12
    centroid = [NaN, NaN];
else
    centroid = [sum(D .* nodeX) / total, sum(D .* nodeY) / total];
end
end

function [jointTbl, demandTbl, serviceTbl, ctildeTbl, diagnostic] = ...
        diagnose_pairs(selected, pairData, nodeX, nodeY, Cap, config)
P = height(selected);
jointRecords = cell(P, 1);
demandRecords = cell(0, 1);
serviceRecords = cell(0, 1);
ctildeRecords = cell(0, 1);
diagnostic = cell(P, 1);
for pp = 1:P
    r = scenario_features(pairData(pp).D_r, pairData(pp).A_r, ...
        pairData(pp).C_r, nodeX, nodeY);
    s = scenario_features(pairData(pp).D_s, pairData(pp).A_s, ...
        pairData(pp).C_s, nodeX, nodeY);
    Ddiff = abs(pairData(pp).D_r - pairData(pp).D_s);
    [~, dOrder] = sortrows([-Ddiff(:), (1:33).'], [1, 2]);
    topD = dOrder(1:5);
    for kk = 1:5
        nn = topD(kk);
        denom = max([abs(pairData(pp).D_r(nn)), ...
            abs(pairData(pp).D_s(nn)), 1e-12]);
        demandRecords{end + 1, 1} = struct('pair_id', pp, ...
            'group_type', selected.group_type(pp), ...
            'initial_state_id', selected.initial_state_id(pp), ...
            'rank', kk, 'node_id', nn, 'node_x_km', nodeX(nn), ...
            'node_y_km', nodeY(nn), 'D_r_kg', pairData(pp).D_r(nn), ...
            'D_s_kg', pairData(pp).D_s(nn), ...
            'absolute_difference_kg', Ddiff(nn), ...
            'relative_difference', Ddiff(nn) / denom); %#ok<AGROW>
    end

    serviceChanged = r.service_count ~= s.service_count | ...
        r.best_site ~= s.best_site | r.reachable_mask ~= s.reachable_mask;
    for nn = 1:33
        serviceRecords{end + 1, 1} = struct('pair_id', pp, ...
            'group_type', selected.group_type(pp), ...
            'initial_state_id', selected.initial_state_id(pp), ...
            'node_id', nn, 'D_r_kg', pairData(pp).D_r(nn), ...
            'D_s_kg', pairData(pp).D_s(nn), ...
            'service_set_r', service_set_string(r.A(:, nn)), ...
            'service_set_s', service_set_string(s.A(:, nn)), ...
            'service_count_r', r.service_count(nn), ...
            'service_count_s', s.service_count(nn), ...
            'best_site_r', r.best_site(nn), 'best_site_s', s.best_site(nn), ...
            'second_site_r', r.second_site(nn), ...
            'second_site_s', s.second_site(nn), ...
            'best_cost_r_km', r.best_cost(nn), ...
            'best_cost_s_km', s.best_cost(nn), ...
            'second_best_gap_r_km', r.second_gap(nn), ...
            'second_best_gap_s_km', s.second_gap(nn), ...
            'service_relation_changed', serviceChanged(nn), ...
            'unreachable_to_reachable', r.service_count(nn) == 0 && ...
                s.service_count(nn) > 0, ...
            'reachable_to_unreachable', r.service_count(nn) > 0 && ...
                s.service_count(nn) == 0, ...
            'multi_to_exclusive', r.service_count(nn) >= 2 && ...
                s.service_count(nn) == 1, ...
            'exclusive_to_multi', r.service_count(nn) == 1 && ...
                s.service_count(nn) >= 2, ...
            'exclusive_site_swap', r.service_count(nn) == 1 && ...
                s.service_count(nn) == 1 && r.best_site(nn) ~= s.best_site(nn)); %#ok<AGROW>
    end

    local = local_ctilde(pairData(pp).A_r, pairData(pp).C_r, ...
        pairData(pp).A_s, pairData(pp).C_s, config);
    [~, cOrder] = sortrows([-local(:), (1:132).'], [1, 2]);
    for kk = 1:10
        flat = cOrder(kk);
        [ii, nn] = ind2sub([4, 33], flat);
        ctildeRecords{end + 1, 1} = struct('pair_id', pp, ...
            'group_type', selected.group_type(pp), ...
            'initial_state_id', selected.initial_state_id(pp), ...
            'rank', kk, 'site_id', ii, 'node_id', nn, ...
            'local_Ctilde_difference', local(ii, nn), ...
            'A_r', r.A(ii, nn), 'A_s', s.A(ii, nn), ...
            'C_r_km', finite_or_nan(r.C(ii, nn), r.A(ii, nn)), ...
            'C_s_km', finite_or_nan(s.C(ii, nn), s.A(ii, nn)), ...
            'D_r_kg', pairData(pp).D_r(nn), ...
            'D_s_kg', pairData(pp).D_s(nn)); %#ok<AGROW>
    end

    aChanged = r.A ~= s.A;
    changedNodes = any(aChanged, 1);
    affectedDemand = sum(max(pairData(pp).D_r, pairData(pp).D_s) .* changedNodes);
    bestChanged = r.best_site ~= s.best_site & ...
        r.best_site > 0 & s.best_site > 0;
    bestChangedDemand = sum(max(pairData(pp).D_r, pairData(pp).D_s) .* bestChanged);
    countChangedDemand = sum(max(pairData(pp).D_r, pairData(pp).D_s) .* ...
        (r.service_count ~= s.service_count));
    totalMean = max(mean([r.total_D, s.total_D]), 1e-12);
    relocationShare = max(sum(Ddiff) - abs(r.total_D - s.total_D), 0) / ...
        max(sum(Ddiff), 1e-12);
    jointRecords{pp} = joint_record(selected(pp, :), r, s, ...
        affectedDemand, bestChangedDemand, countChangedDemand, ...
        relocationShare, pairData(pp), Cap);
    diagnostic{pp} = struct('r', r, 's', s, ...
        'total_mean', totalMean, 'D_l1', sum(Ddiff), ...
        'total_D_difference', abs(r.total_D - s.total_D), ...
        'relocation_share', relocationShare, ...
        'A_change_count', sum(aChanged, 'all'), ...
        'affected_demand', affectedDemand, ...
        'affected_demand_ratio', affectedDemand / totalMean, ...
        'service_count_change_nodes', sum(r.service_count ~= s.service_count), ...
        'service_count_changed_demand', countChangedDemand, ...
        'best_site_change_nodes', sum(bestChanged), ...
        'best_site_changed_demand', bestChangedDemand, ...
        'exclusive_change', sum(abs(r.exclusive_D - s.exclusive_D)), ...
        'shared_change', abs(r.shared_D - s.shared_D), ...
        'unreachable_change', abs(r.unreachable_D - s.unreachable_D), ...
        'coverage_change', sum(abs(r.covered_D - s.covered_D)), ...
        'ranking_change_nodes', sum(r.ranking_code ~= s.ranking_code), ...
        'best_cost_change', nan_sum(abs(r.best_cost - s.best_cost)), ...
        'second_gap_change', nan_sum(abs(r.second_gap - s.second_gap)), ...
        'top_D_nodes', topD(:).', 'top_C_relations', cOrder(1:10).');
end
jointTbl = records_to_table(jointRecords);
demandTbl = records_to_table(demandRecords);
serviceTbl = records_to_table(serviceRecords);
ctildeTbl = records_to_table(ctildeRecords);
diagnostic = vertcat(diagnostic{:});
end

function f = scenario_features(D, A3, C3, nodeX, nodeY)
A = reshape(logical(A3), 4, 33);
C = reshape(double(C3), 4, 33);
serviceCount = sum(A, 1);
covered = sum(A .* D, 2).';
exclusive = zeros(1, 4);
for ii = 1:4
    exclusive(ii) = sum(D .* (A(ii, :) & serviceCount == 1));
end
unreachable = sum(D(serviceCount == 0));
shared = sum(D(serviceCount >= 2));
bestCost = NaN(1, 33);
secondCost = NaN(1, 33);
bestSite = zeros(1, 33);
secondSite = zeros(1, 33);
rankingCode = strings(1, 33);
bestAssigned = zeros(1, 4);
weightedBurden = zeros(1, 4);
for ii = 1:4
    vals = C(ii, :);
    vals(~A(ii, :) | ~isfinite(vals)) = 0;
    weightedBurden(ii) = sum(D .* vals);
end
for nn = 1:33
    sites = find(A(:, nn));
    if isempty(sites)
        rankingCode(nn) = "NONE";
        continue;
    end
    [costs, ord] = sort(C(sites, nn), 'ascend');
    sites = sites(ord);
    bestCost(nn) = costs(1);
    bestSite(nn) = sites(1);
    bestAssigned(sites(1)) = bestAssigned(sites(1)) + D(nn);
    if numel(sites) >= 2
        secondCost(nn) = costs(2);
        secondSite(nn) = sites(2);
    end
    rankingCode(nn) = join(string(sites), ">");
end
secondGap = secondCost - bestCost;
centroid = demand_centroid(D, nodeX, nodeY);
f = struct('D', D, 'A', A, 'C', C, 'total_D', sum(D), ...
    'covered_D', covered, 'exclusive_D', exclusive, ...
    'unreachable_D', unreachable, 'shared_D', shared, ...
    'service_count', serviceCount, 'reachable_mask', serviceCount > 0, ...
    'best_cost', bestCost, 'second_cost', secondCost, ...
    'second_gap', secondGap, 'best_site', bestSite, ...
    'second_site', secondSite, 'ranking_code', rankingCode, ...
    'best_assigned_D', bestAssigned, ...
    'weighted_service_burden', weightedBurden, 'centroid', centroid);
end

function rec = joint_record(row, r, s, affectedDemand, bestChangedDemand, ...
        countChangedDemand, relocationShare, pair, Cap)
rec = struct('pair_id', row.pair_id, 'group_type', row.group_type, ...
    'initial_state_id', row.initial_state_id, ...
    'scenario_r', row.scenario_r, 'scenario_s', row.scenario_s, ...
    'pair_type', row.pair_type, 'd_D', row.d_D, ...
    'd_Ctilde', row.d_Ctilde, 'd_new', row.d_new, ...
    'total_D_r_kg', r.total_D, 'total_D_s_kg', s.total_D, ...
    'total_D_absolute_difference_kg', abs(r.total_D - s.total_D), ...
    'D_l1_difference_kg', sum(abs(r.D - s.D)), ...
    'demand_relocation_share', relocationShare, ...
    'centroid_r_x_km', r.centroid(1), 'centroid_r_y_km', r.centroid(2), ...
    'centroid_s_x_km', s.centroid(1), 'centroid_s_y_km', s.centroid(2), ...
    'centroid_shift_km', norm(r.centroid - s.centroid), ...
    'A_change_count', sum(r.A ~= s.A, 'all'), ...
    'reachable_to_unreachable_count', sum(r.A & ~s.A, 'all'), ...
    'unreachable_to_reachable_count', sum(~r.A & s.A, 'all'), ...
    'service_set_change_node_count', sum(any(r.A ~= s.A, 1)), ...
    'service_count_change_node_count', sum(r.service_count ~= s.service_count), ...
    'A_change_affected_demand_kg', affectedDemand, ...
    'best_site_change_node_count', sum(r.best_site ~= s.best_site & ...
        r.best_site > 0 & s.best_site > 0), ...
    'best_site_change_affected_demand_kg', bestChangedDemand, ...
    'service_count_change_affected_demand_kg', countChangedDemand, ...
    'unreachable_D_r_kg', r.unreachable_D, ...
    'unreachable_D_s_kg', s.unreachable_D, ...
    'shared_D_r_kg', r.shared_D, 'shared_D_s_kg', s.shared_D, ...
    'mean_best_cost_r_km', mean(r.best_cost, 'omitnan'), ...
    'mean_best_cost_s_km', mean(s.best_cost, 'omitnan'), ...
    'mean_second_gap_r_km', mean(r.second_gap, 'omitnan'), ...
    'mean_second_gap_s_km', mean(s.second_gap, 'omitnan'), ...
    'T_l1_difference_kg', sum(abs([row.T_r1, row.T_r2, row.T_r3, row.T_r4] - ...
        [row.T_s1, row.T_s2, row.T_s3, row.T_s4])), ...
    'maximum_site_T_difference_kg', max(abs( ...
        [row.T_r1, row.T_r2, row.T_r3, row.T_r4] - ...
        [row.T_s1, row.T_s2, row.T_s3, row.T_s4])), ...
    'capacity_saturated_r', any([row.T_r1, row.T_r2, row.T_r3, row.T_r4] >= ...
        Cap.' - 1e-7), 'capacity_saturated_s', ...
        any([row.T_s1, row.T_s2, row.T_s3, row.T_s4] >= Cap.' - 1e-7), ...
    'centroid_source', "NearStageInput.Spatial.node_positions_affine_km");
for ii = 1:4
    rec.(sprintf('covered_D_r_site%d_kg', ii)) = r.covered_D(ii);
    rec.(sprintf('covered_D_s_site%d_kg', ii)) = s.covered_D(ii);
    rec.(sprintf('exclusive_D_r_site%d_kg', ii)) = r.exclusive_D(ii);
    rec.(sprintf('exclusive_D_s_site%d_kg', ii)) = s.exclusive_D(ii);
    rec.(sprintf('best_assignment_D_r_site%d_kg', ii)) = r.best_assigned_D(ii);
    rec.(sprintf('best_assignment_D_s_site%d_kg', ii)) = s.best_assigned_D(ii);
    rec.(sprintf('weighted_service_burden_r_site%d_kg_km', ii)) = ...
        r.weighted_service_burden(ii);
    rec.(sprintf('weighted_service_burden_s_site%d_kg_km', ii)) = ...
        s.weighted_service_burden(ii);
end
rec.path_id_r = pair.path_r;
rec.path_id_s = pair.path_s;
end

function text = service_set_string(mask)
sites = find(mask(:));
if isempty(sites)
    text = "NONE";
else
    text = join(string(sites.'), ";");
end
end

function value = finite_or_nan(value, reachable)
if ~reachable || ~isfinite(value)
    value = NaN;
end
end

function local = local_ctilde(Ar3, Cr3, As3, Cs3, config)
Ar = reshape(logical(Ar3), 4, 33);
As = reshape(logical(As3), 4, 33);
Cr = reshape(double(Cr3), 4, 33);
Cs = reshape(double(Cs3), 4, 33);
local = config.kappa .* double(xor(Ar, As));
both = Ar & As;
delta = abs(Cr - Cs) ./ config.C_bound;
delta(~both | ~isfinite(delta)) = 0;
local(both) = delta(both);
end

function total = nan_sum(values)
values = values(isfinite(values));
if isempty(values)
    total = 0;
else
    total = sum(values);
end
end

function [replayTbl, nodeTbl, audit, detail] = replay_selected_pairs( ...
        selected, pairData, M, config)
P = height(selected);
R = 4 * P;
D = zeros(R, 33);
A = false(R, 4, 33);
C = NaN(R, 4, 33);
T = zeros(R, 4);
pairIndex = zeros(R, 1);
labels = strings(R, 1);
targetSide = strings(R, 1);
sourceSide = strings(R, 1);
for pp = 1:P
    rows = (pp - 1) * 4 + (1:4);
    Tr = double([selected.T_r1(pp), selected.T_r2(pp), ...
        selected.T_r3(pp), selected.T_r4(pp)]);
    Ts = double([selected.T_s1(pp), selected.T_s2(pp), ...
        selected.T_s3(pp), selected.T_s4(pp)]);
    D(rows, :) = [pairData(pp).D_r; pairData(pp).D_s; ...
        pairData(pp).D_s; pairData(pp).D_r];
    A(rows, :, :) = cat(1, pairData(pp).A_r, pairData(pp).A_s, ...
        pairData(pp).A_s, pairData(pp).A_r);
    C(rows, :, :) = cat(1, pairData(pp).C_r, pairData(pp).C_s, ...
        pairData(pp).C_s, pairData(pp).C_r);
    T(rows, :) = [Tr; Ts; Tr; Ts];
    pairIndex(rows) = pp;
    labels(rows) = ["T_R_ON_R"; "T_S_ON_S"; "T_R_ON_S"; "T_S_ON_R"];
    targetSide(rows) = ["R"; "S"; "S"; "R"];
    sourceSide(rows) = ["R"; "S"; "R"; "S"];
end
ev = evaluate_step03T_fixed_T_recourse_h2(D, A, C, T, M, config);
records = cell(R, 1);
nodeRecords = cell(R * 33, 1);
detail = cell(P, 1);
nodePos = 0;
objectiveError = zeros(P, 4);
regretError = zeros(P, 4);
objectiveWithinTolerance = false(P, 4);
regretWithinTolerance = false(P, 4);
nodeReconstruction = zeros(P, 2);
for rr = 1:R
    pp = pairIndex(rr);
    records{rr} = struct('pair_id', pp, ...
        'group_type', selected.group_type(pp), ...
        'initial_state_id', selected.initial_state_id(pp), ...
        'replay_case', labels(rr), 'T_source_scenario', sourceSide(rr), ...
        'target_scenario', targetSide(rr), 'solver_status', ev.status, ...
        'service_cost', ev.service_cost(rr), ...
        'shortage_kg', ev.shortage_kg(rr), ...
        'shortage_loss', ev.shortage_loss(rr), ...
        'operating_loss', ev.operating_loss(rr), ...
        'holding_cost', ev.holding_cost(rr), ...
        'full_objective', ev.full_objective(rr));
    for ii = 1:4
        records{rr}.(sprintf('T_site%d_kg', ii)) = T(rr, ii);
        records{rr}.(sprintf('service_site%d_kg', ii)) = ev.site_service(rr, ii);
        records{rr}.(sprintf('unused_T_site%d_kg', ii)) = ev.unused_T(rr, ii);
        records{rr}.(sprintf('transport_site%d', ii)) = ...
            ev.transport_by_site(rr, ii);
    end
    if labels(rr) == "T_R_ON_S"
        baseline = (pp - 1) * 4 + 2;
        direction = "R_TO_S";
    elseif labels(rr) == "T_S_ON_R"
        baseline = (pp - 1) * 4 + 1;
        direction = "S_TO_R";
    else
        baseline = rr;
        direction = "OWN";
    end
    contribution = ev.node_operating_loss(rr, :) - ...
        ev.node_operating_loss(baseline, :);
    [~, contributionOrder] = sort(contribution, 'descend');
    rank = zeros(1, 33);
    rank(contributionOrder) = 1:33;
    for nn = 1:33
        nodePos = nodePos + 1;
        nodeRecords{nodePos} = struct('pair_id', pp, ...
            'group_type', selected.group_type(pp), ...
            'initial_state_id', selected.initial_state_id(pp), ...
            'replay_case', labels(rr), 'direction', direction, ...
            'node_id', nn, 'demand_kg', D(rr, nn), ...
            'service_total_kg', ev.node_service(rr, nn), ...
            'shortage_kg', ev.u(rr, nn), ...
            'transport_loss', ev.transport_by_node(rr, nn), ...
            'shortage_loss', ev.shortage_loss_by_node(rr, nn), ...
            'node_operating_loss', ev.node_operating_loss(rr, nn), ...
            'operating_regret_contribution', contribution(nn), ...
            'positive_contribution_rank', rank(nn));
        for ii = 1:4
            nodeRecords{nodePos}.(sprintf('service_from_site%d_kg', ii)) = ...
                ev.y(rr, ii, nn);
            nodeRecords{nodePos}.(sprintf('transport_from_site%d', ii)) = ...
                ev.transport_by_relation(rr, ii, nn);
        end
    end
end
for pp = 1:P
    rows = (pp - 1) * 4 + (1:4);
    Tr = double([selected.T_r1(pp), selected.T_r2(pp), ...
        selected.T_r3(pp), selected.T_r4(pp)]);
    Ts = double([selected.T_s1(pp), selected.T_s2(pp), ...
        selected.T_s3(pp), selected.T_s4(pp)]);
    representativeObjR = double(selected.own_operating_loss_r(pp)) + ...
        config.gamma * sum(Tr);
    representativeObjS = double(selected.own_operating_loss_s(pp)) + ...
        config.gamma * sum(Ts);
    recordedObj = [representativeObjR, representativeObjS, ...
        double(selected.cross_objective_r_to_s(pp)), ...
        double(selected.cross_objective_s_to_r(pp))];
    objectiveError(pp, :) = abs(ev.full_objective(rows).' - recordedObj);
    objectiveTolerance = config.chainTolerance + 4 .* ...
        eps(max(abs(recordedObj), 1));
    objectiveWithinTolerance(pp, :) = ...
        objectiveError(pp, :) <= objectiveTolerance;
    replayRegret = [ev.full_objective(rows(3)) - ...
        representativeObjS, ev.full_objective(rows(4)) - representativeObjR, ...
        ev.operating_loss(rows(3)) - double(selected.own_operating_loss_s(pp)), ...
        ev.operating_loss(rows(4)) - double(selected.own_operating_loss_r(pp))];
    nodeReplayRegret = [ev.operating_loss(rows(3)) - ...
        ev.operating_loss(rows(2)), ev.operating_loss(rows(4)) - ...
        ev.operating_loss(rows(1))];
    recordedRegret = [double(selected.regret_obj_r_to_s(pp)), ...
        double(selected.regret_obj_s_to_r(pp)), ...
        double(selected.regret_loss_r_to_s(pp)), ...
        double(selected.regret_loss_s_to_r(pp))];
    regretError(pp, :) = abs(replayRegret - recordedRegret);
    regretOperandsLeft = [ev.full_objective(rows(3)), ...
        ev.full_objective(rows(4)), ev.operating_loss(rows(3)), ...
        ev.operating_loss(rows(4))];
    regretOperandsRight = [representativeObjS, representativeObjR, ...
        double(selected.own_operating_loss_s(pp)), ...
        double(selected.own_operating_loss_r(pp))];
    regretTolerance = config.chainTolerance + 4 .* ( ...
        eps(max(abs(regretOperandsLeft), 1)) + ...
        eps(max(abs(regretOperandsRight), 1)));
    regretWithinTolerance(pp, :) = regretError(pp, :) <= regretTolerance;
    nodeReconstruction(pp, :) = [abs(sum(ev.node_operating_loss(rows(3), :) - ...
        ev.node_operating_loss(rows(2), :)) - nodeReplayRegret(1)), ...
        abs(sum(ev.node_operating_loss(rows(4), :) - ...
        ev.node_operating_loss(rows(1), :)) - nodeReplayRegret(2))];
    [~, topRtoS] = sort(ev.node_operating_loss(rows(3), :) - ...
        ev.node_operating_loss(rows(2), :), 'descend');
    [~, topStoR] = sort(ev.node_operating_loss(rows(4), :) - ...
        ev.node_operating_loss(rows(1), :), 'descend');
    detail{pp} = struct('rows', rows, ...
        'top_nodes_r_to_s', topRtoS(1:5), ...
        'top_nodes_s_to_r', topStoR(1:5), ...
        'service_delta_r_to_s', ev.site_service(rows(3), :) - ...
            ev.site_service(rows(2), :), ...
        'service_delta_s_to_r', ev.site_service(rows(4), :) - ...
            ev.site_service(rows(1), :), ...
        'unused_cross_r_to_s', ev.unused_T(rows(3), :), ...
        'unused_cross_s_to_r', ev.unused_T(rows(4), :));
end
replayTbl = records_to_table(records);
nodeTbl = records_to_table(nodeRecords);
detail = vertcat(detail{:});
audit = struct('all_optimal', ev.exitflag == 1 && ev.status == "OPTIMAL", ...
    'replay_count', R, 'max_objective_error', max(objectiveError, [], 'all'), ...
    'max_regret_error', max(regretError, [], 'all'), ...
    'all_cross_objectives_within_machine_aware_1e8_tolerance', ...
        all(objectiveWithinTolerance(:, 3:4), 'all'), ...
    'all_regrets_within_1e8_plus_operand_ulp_tolerance', ...
        all(regretWithinTolerance, 'all'), ...
    'max_node_reconstruction_error', max(nodeReconstruction, [], 'all'), ...
    'max_balance_error', ev.max_demand_balance_error, ...
    'max_capacity_violation', ev.max_site_capacity_violation, ...
    'objective_reconstruction_error', ev.objective_reconstruction_abs_error);
end

function tbl = classify_failure_modes(selected, diagnostic, replay, config)
records = cell(height(selected), 1);
for pp = 1:height(selected)
    d = diagnostic(pp);
    if selected.group_type(pp) == "CONTROL"
        primary = "CONTROL_LOW_REGRET";
        secondary = "NONE";
        family = "CONTROL";
    else
        exclusiveRatio = d.exclusive_change / d.total_mean;
        redundancyRatio = d.shared_change / d.total_mean;
        bestSiteRatio = d.best_site_changed_demand / d.total_mean;
        relocation = d.relocation_share;
        localDilution = double(selected.local_dilution_ratio(pp)) >= 5 && ...
            double(selected.changed_local_count(pp)) <= 10;
        bothSaturated = as_logical(selected.capacity_saturated_r(pp)) && ...
            as_logical(selected.capacity_saturated_s(pp));
        if d.affected_demand_ratio >= 0.10 && exclusiveRatio >= 0.10
            primary = "TYPE_3_STATION_IDENTITY_OR_EXCLUSIVE_COVERAGE";
            family = "SERVICE_COUPLING";
        elseif d.affected_demand_ratio >= 0.10 && redundancyRatio >= 0.10
            primary = "TYPE_4_SERVICE_REDUNDANCY_CHANGE";
            family = "SERVICE_COUPLING";
        elseif d.affected_demand_ratio >= 0.05
            primary = "TYPE_2_DEMAND_REACHABILITY_COUPLING";
            family = "SERVICE_COUPLING";
        elseif bestSiteRatio >= 0.05 || d.ranking_change_nodes >= 3
            primary = "TYPE_5_ROAD_IMPEDANCE_RANKING_CHANGE";
            family = "SERVICE_COUPLING";
        elseif relocation >= 0.60 && d.D_l1 >= 0.02 * d.total_mean
            primary = "TYPE_1_SPATIAL_DEMAND_RELOCATION";
            family = "SPATIAL_DEMAND";
        elseif bothSaturated && d.D_l1 <= 0.02 * d.total_mean
            primary = "TYPE_6_CAPACITY_OR_OPTIMIZATION_SWITCH";
            family = "CAPACITY_SWITCH";
        elseif localDilution
            primary = "TYPE_7_DISTANCE_SCALE_OR_AVERAGE_COMPRESSION";
            family = "AGGREGATION_SCALE";
        else
            primary = "TYPE_9_MIXED_STRUCTURAL_CAUSE";
            family = "MIXED";
        end
        if relocation >= 0.60 && ~contains(primary, "TYPE_1")
            secondary = "TYPE_1_SPATIAL_DEMAND_RELOCATION";
        elseif bestSiteRatio >= 0.05 && ~contains(primary, "TYPE_5")
            secondary = "TYPE_5_ROAD_IMPEDANCE_RANKING_CHANGE";
        elseif localDilution && ~contains(primary, "TYPE_7")
            secondary = "TYPE_7_DISTANCE_SCALE_OR_AVERAGE_COMPRESSION";
        else
            secondary = "NONE";
        end
    end
    topR = join(string(replay(pp).top_nodes_r_to_s), ";");
    topS = join(string(replay(pp).top_nodes_s_to_r), ";");
    [~, misplacedR] = max(abs(replay(pp).service_delta_r_to_s));
    [~, misplacedS] = max(abs(replay(pp).service_delta_s_to_r));
    records{pp} = struct('pair_id', selected.pair_id(pp), ...
        'group_type', selected.group_type(pp), ...
        'initial_state_id', selected.initial_state_id(pp), ...
        'primary_failure_type', primary, 'secondary_failure_type', secondary, ...
        'failure_family', family, ...
        'real_bidirectional_high_regret', ...
            double(selected.relative_regret_obj_r_to_s(pp)) >= ...
                config.tierRegretThreshold && ...
            double(selected.relative_regret_obj_s_to_r(pp)) >= ...
                config.tierRegretThreshold, ...
        'not_merely_alternative_optimum', ...
            ~as_logical(selected.multiple_optimum_r(pp)) && ...
            ~as_logical(selected.multiple_optimum_s(pp)), ...
        'demand_relocation_share', d.relocation_share, ...
        'A_change_affected_demand_ratio', d.affected_demand_ratio, ...
        'exclusive_D_change_ratio', d.exclusive_change / d.total_mean, ...
        'shared_D_change_ratio', d.shared_change / d.total_mean, ...
        'unreachable_D_change_ratio', d.unreachable_change / d.total_mean, ...
        'best_site_changed_demand_ratio', ...
            d.best_site_changed_demand / d.total_mean, ...
        'ranking_change_node_count', d.ranking_change_nodes, ...
        'both_capacity_saturated', ...
            as_logical(selected.capacity_saturated_r(pp)) && ...
            as_logical(selected.capacity_saturated_s(pp)), ...
        'local_average_dilution_supported', ...
            double(selected.local_dilution_ratio(pp)) >= 5 && ...
            double(selected.changed_local_count(pp)) <= 10, ...
        'r_to_s_main_regret_nodes', topR, ...
        's_to_r_main_regret_nodes', topS, ...
        'r_to_s_most_changed_service_site', misplacedR, ...
        's_to_r_most_changed_service_site', misplacedS, ...
        'r_to_s_unused_T_by_site_kg', ...
            join(compose('%.9g', replay(pp).unused_cross_r_to_s), ";"), ...
        's_to_r_unused_T_by_site_kg', ...
            join(compose('%.9g', replay(pp).unused_cross_s_to_r), ";"), ...
        'bidirectional_cause_explanation', ...
            "Cross layouts alter node shortage/service at nodes " + topR + ...
            " (r-to-s) and " + topS + " (s-to-r); the directions are diagnosed separately.");
end
tbl = records_to_table(records);
end

function tbl = compare_tier_and_controls(selected, diagnostic)
metrics = ["total_D_absolute_difference_kg"; "d_D"; "d_Ctilde"; ...
    "d_new"; "A_change_count"; "A_change_affected_demand_kg"; ...
    "exclusive_D_change_kg"; "shared_D_change_kg"; ...
    "unreachable_D_change_kg"; "best_site_change_node_count"; ...
    "best_cost_change_km"; "second_best_gap_change_km"; ...
    "covered_D_change_kg"; "maximum_site_T_difference_kg"; ...
    "bidirectional_severity"];
X = zeros(height(selected), numel(metrics));
for pp = 1:height(selected)
    d = diagnostic(pp);
    X(pp, :) = [d.total_D_difference, double(selected.d_D(pp)), ...
        double(selected.d_Ctilde(pp)), double(selected.d_new(pp)), ...
        d.A_change_count, d.affected_demand, d.exclusive_change, ...
        d.shared_change, d.unreachable_change, d.best_site_change_nodes, ...
        d.best_cost_change, d.second_gap_change, d.coverage_change, ...
        double(selected.max_single_site_T_difference_kg(pp)), ...
        double(selected.bidirectional_severity(pp))];
end
tierMask = selected.group_type == "TIER1";
controlMask = selected.group_type == "CONTROL";
records = cell(numel(metrics), 1);
for mm = 1:numel(metrics)
    tier = X(tierMask, mm);
    control = X(controlMask, mm);
    records{mm} = struct('metric', metrics(mm), ...
        'tier1_count', numel(tier), 'control_count', numel(control), ...
        'tier1_median', median(tier), 'control_median', median(control), ...
        'tier1_q90', percentile(tier, 0.90), ...
        'control_q90', percentile(control, 0.90), ...
        'tier1_maximum', max(tier), 'control_maximum', max(control), ...
        'median_difference', median(tier) - median(control), ...
        'median_ratio', median(tier) / max(abs(median(control)), 1e-12));
end
tbl = records_to_table(records);
end

function [tbl, out] = tier1_concentration(crossTbl, config)
tier = crossTbl(as_logical(crossTbl.tier_1), :);
state = double(tier.initial_state_id);
r = double(tier.scenario_r);
s = double(tier.scenario_s);
lo = min(r, s);
hi = max(r, s);
unorderedKey = string(state) + ":" + string(lo) + ":" + string(hi);
orientedKey = string(state) + ":" + string(r) + ":" + string(s);
[uniqueUnordered, ~, unorderedGroup] = unique(unorderedKey);
[~, ~, orientedGroup] = unique(orientedKey);
unorderedCounts = accumarray(unorderedGroup, 1);
orientedCounts = accumarray(orientedGroup, 1);
reverseDuplicateClasses = sum(unorderedCounts > 1);
reverseDuplicateRows = sum(unorderedCounts(unorderedCounts > 1));
exactDuplicateRows = sum(orientedCounts - 1);
scenarioKeyR = string(state) + ":" + string(r);
scenarioKeyS = string(state) + ":" + string(s);
allScenarioKeys = [scenarioKeyR; scenarioKeyS];
[uniqueScenarios, ~, scenarioGroup] = unique(allScenarioKeys);
degree = accumarray(scenarioGroup, 1);
[degreeSorted, degreeOrder] = sort(degree, 'descend');
topScenarios = uniqueScenarios(degreeOrder);

topCount = min(20, numel(topScenarios));
records = cell(6 + 2 * numel(config.states) + topCount + 11, 1);
recPos = 0;
recPos = recPos + 1;
records{recPos} = concentration_record("ALL", ...
    "tier1_raw_row_count", NaN, NaN, NaN, height(tier), height(tier), 1);
recPos = recPos + 1;
records{recPos} = concentration_record("ALL", ...
    "unordered_unique_pair_count", NaN, NaN, NaN, ...
    numel(uniqueUnordered), height(tier), numel(uniqueUnordered) / height(tier));
recPos = recPos + 1;
records{recPos} = concentration_record("ALL", ...
    "reverse_duplicate_unordered_classes", NaN, NaN, NaN, ...
    reverseDuplicateClasses, numel(uniqueUnordered), ...
    reverseDuplicateClasses / max(numel(uniqueUnordered), 1));
recPos = recPos + 1;
records{recPos} = concentration_record("ALL", ...
    "rows_in_reverse_duplicate_classes", NaN, NaN, NaN, ...
    reverseDuplicateRows, height(tier), reverseDuplicateRows / height(tier));
recPos = recPos + 1;
records{recPos} = concentration_record("ALL", ...
    "exact_oriented_duplicate_rows", NaN, NaN, NaN, exactDuplicateRows, ...
    height(tier), exactDuplicateRows / height(tier));
recPos = recPos + 1;
records{recPos} = concentration_record("ALL", ...
    "unique_scenario_count", NaN, NaN, NaN, numel(uniqueScenarios), ...
    2 * height(tier), numel(uniqueScenarios) / (2 * height(tier)));
for ss = 1:numel(config.states)
    stateId = config.states(ss);
    mask = state == stateId;
    keys = unique([scenarioKeyR(mask); scenarioKeyS(mask)]);
    recPos = recPos + 1;
    records{recPos} = concentration_record("STATE", ...
        "tier1_pair_count", NaN, stateId, NaN, sum(mask), height(tier), ...
        sum(mask) / height(tier));
    recPos = recPos + 1;
    records{recPos} = concentration_record("STATE", ...
        "unique_scenario_count", NaN, stateId, NaN, numel(keys), ...
        numel(uniqueScenarios), numel(keys) / numel(uniqueScenarios));
end
for kk = 1:topCount
    parts = split(topScenarios(kk), ":");
    recPos = recPos + 1;
    records{recPos} = concentration_record("TOP_SCENARIO", ...
        "incident_pair_count", kk, str2double(parts(1)), ...
        str2double(parts(2)), degreeSorted(kk), height(tier), ...
        degreeSorted(kk) / height(tier));
end
fractions = [0.01, 0.05, 0.10];
remainingShares = zeros(size(fractions));
remainingStates = zeros(size(fractions));
incidentShares = zeros(size(fractions));
for ff = 1:numel(fractions)
    count = max(1, ceil(fractions(ff) * numel(uniqueScenarios)));
    high = topScenarios(1:count);
    incident = ismember(scenarioKeyR, high) | ismember(scenarioKeyS, high);
    incidentShares(ff) = mean(incident);
    remainingShares(ff) = mean(~incident);
    remainingStates(ff) = numel(unique(state(~incident)));
    recPos = recPos + 1;
    records{recPos} = concentration_record("HIGH_FREQUENCY", ...
        "incident_pair_share", 100 * fractions(ff), NaN, NaN, ...
        sum(incident), height(tier), mean(incident));
    recPos = recPos + 1;
    records{recPos} = concentration_record("HIGH_FREQUENCY", ...
        "remaining_pair_share_after_removal", 100 * fractions(ff), ...
        NaN, NaN, sum(~incident), height(tier), mean(~incident));
    recPos = recPos + 1;
    records{recPos} = concentration_record("HIGH_FREQUENCY", ...
        "remaining_state_count_after_removal", 100 * fractions(ff), ...
        NaN, NaN, remainingStates(ff), numel(config.states), ...
        remainingStates(ff) / numel(config.states));
end
pairType = string(tier.pair_type);
recPos = recPos + 1;
records{recPos} = concentration_record("CATEGORY", ...
    "NONTAIL_TAIL", NaN, NaN, NaN, sum(pairType == "NONTAIL_TAIL"), ...
    height(tier), mean(pairType == "NONTAIL_TAIL"));
recPos = recPos + 1;
records{recPos} = concentration_record("CATEGORY", ...
    "TAIL_TAIL", NaN, NaN, NaN, sum(pairType == "TAIL_TAIL"), ...
    height(tier), mean(pairType == "TAIL_TAIL"));
tbl = records_to_table(records(1:recPos));
out = struct('raw_pair_count', height(tier), ...
    'unordered_unique_pair_count', numel(uniqueUnordered), ...
    'reverse_duplicate_classes', reverseDuplicateClasses, ...
    'reverse_duplicate_rows', reverseDuplicateRows, ...
    'exact_oriented_duplicate_rows', exactDuplicateRows, ...
    'unique_scenario_count', numel(uniqueScenarios), ...
    'top20_scenarios', topScenarios(1:min(20, numel(topScenarios))), ...
    'top20_degrees', degreeSorted(1:min(20, numel(degreeSorted))), ...
    'incident_shares', incidentShares, ...
    'remaining_shares', remainingShares, ...
    'remaining_states', remainingStates, ...
    'non_tail_tail_count', sum(pairType == "NONTAIL_TAIL"), ...
    'tail_tail_count', sum(pairType == "TAIL_TAIL"));
end

function rec = concentration_record(scope, metric, rank, stateId, ...
        scenarioId, value, denominator, share)
rec = struct('record_scope', scope, 'metric', metric, 'rank_or_percent', rank, ...
    'initial_state_id', stateId, 'scenario_id', scenarioId, ...
    'value', value, 'denominator', denominator, 'share', share);
end

function conclusion = choose_conclusion(failureTbl, chainAudit, replayAudit, ...
        concentration, config)
if chainAudit.max_distance_error > config.distanceTolerance || ...
        chainAudit.max_checkpoint_error > config.chainTolerance || ...
        chainAudit.max_checkpoint_relative_regret_normalized_error > ...
            config.chainTolerance || ...
        ~chainAudit.identity_pass || replayAudit.max_regret_error > ...
        config.chainTolerance && ...
        ~replayAudit.all_regrets_within_1e8_plus_operand_ulp_tolerance
    conclusion = "F. STEP03S_RESULT_REQUIRES_CORRECTION";
    return;
end
tier = failureTbl(failureTbl.group_type == "TIER1", :);
families = string(tier.failure_family);
serviceShare = mean(families == "SERVICE_COUPLING");
spatialShare = mean(families == "SPATIAL_DEMAND");
capacityShare = mean(families == "CAPACITY_SWITCH");
scaleShare = mean(families == "AGGREGATION_SCALE");
if serviceShare >= 0.60
    conclusion = "A. SERVICE_COUPLING_OMISSION_DOMINANT";
elseif spatialShare >= 0.60
    conclusion = "B. SPATIAL_DEMAND_RELOCATION_DOMINANT";
elseif capacityShare >= 0.60
    conclusion = "C. CAPACITY_AND_OPTIMIZATION_SWITCHING_DOMINANT";
elseif scaleShare >= 0.60
    conclusion = "D. AGGREGATION_OR_SCALING_DOMINANT";
elseif concentration.remaining_shares(3) >= 0.25 && ...
        concentration.remaining_states(3) >= 4
    conclusion = "E. MULTIPLE_STRUCTURAL_FAILURE_MODES";
else
    conclusion = "G. DIAGNOSIS_INCONCLUSIVE";
end
end

function write_method_brief(path, failureTbl, comparisonTbl, ...
        concentration, conclusion, config)
tier = failureTbl(failureTbl.group_type == "TIER1", :);
families = string(tier.failure_family);
lines = ["# Step-03T Method Problem Brief"; ""; ...
    "## Directly supported diagnosis"; ""; ...
    "The frozen Tier-1 records and selected exact replays show that small d_new can coexist with non-substitutable TerminalLOH layouts when demand location, reachability, station identity, exclusive coverage, service redundancy, or reachable-road ranking changes jointly."; ...
    "The diagnostic features are explanatory only. This audit does not define, recommend, or implement a replacement distance."; ...
    "Representative family counts: service coupling=" + sum(families == "SERVICE_COUPLING") + ...
    ", spatial demand=" + sum(families == "SPATIAL_DEMAND") + ...
    ", capacity switching=" + sum(families == "CAPACITY_SWITCH") + ...
    ", aggregation/scale=" + sum(families == "AGGREGATION_SCALE") + ...
    ", mixed=" + sum(families == "MIXED") + "."; ...
    "Tier-1 raw rows=" + concentration.raw_pair_count + ...
    ", unordered unique pairs=" + concentration.unordered_unique_pair_count + ...
    ", unique scenarios=" + concentration.unique_scenario_count + "."; ...
    "After removing the top 10% highest-frequency scenarios, the remaining pair share is " + ...
    sprintf('%.6f', concentration.remaining_shares(3)) + ...
    " across " + concentration.remaining_states(3) + " states."; ""; ...
    "## Features separating substitutable and non-substitutable neighbors"; ""; ...
    "The descriptive comparison is archived in step03T_tier1_control_comparison.csv. Its fixed fields include demand relocation, changed reachability weighted by demand, exclusive/shared/unreachable demand, best-site identity, impedance ranking, T differences, and bidirectional regret."; ...
    "The comparison table contains " + height(comparisonTbl) + " predefined diagnostic metrics."; ...
    "No classifier, regression, fitted parameter, validation sample, or weight scan is used."; ""; ...
    "## Problems a later method must resolve"; ""; ...
    "1. Preserve node demand location relevant to the four-station layout."; ...
    "2. Preserve the joint relationship between demand, reachability, station identity, exclusive coverage, and service redundancy."; ...
    "3. Preserve consequential changes in best and second-best reachable service options without treating unreachable demand as an ordinary long-distance relation."; ...
    "4. Distinguish genuine service-structure changes from capacity or optimization boundary effects."; ...
    "5. Avoid suppressing consequential local relationships through fixed aggregation scales."; ""; ...
    "## Minimum mathematical properties"; ""; ...
    "A later candidate must retain nonnegativity, symmetry, zero-distance equivalence, triangle inequality, and a scenario-independent fixed scale. It must remain usable by exact constraint generation and must not depend on validation data."; ""; ...
    "## Computational limits"; ""; ...
    "A later candidate must not solve an optimization model inside every scenario-pair distance, materially expand the formal WDRO variables or constraints, require an in-memory R-by-R matrix, require regeneration of Step-03J, or tune against validation data."; ""; ...
    "## Current conclusion"; ""; conclusion; ""; ...
    "The current fixed constants remain kappa=" + config.kappa + ...
    ", D/Ctilde weights=" + config.weight_D + "/" + ...
    config.weight_Ctilde + ", and C_bound=" + ...
    sprintf('%.16g', config.C_bound) + ". They are not modified here."];
write_lines(path, lines);
end

function [tbl, pass] = build_acceptance(selected, chain, replay, ...
        failureTbl, concentration, stepSBefore, stepSAfter, ...
        checkpointBefore, checkpointAfter, stepPBefore, stepPAfter, ...
        protectedBefore, protectedAfter, codeMessages, runtimeSec, ...
        peakMemory, nominalHash, config)
checks = cell(22, 1);
checks{1} = check_record(1, stepSBefore == stepSAfter && ...
    checkpointBefore == checkpointAfter, "Step-03S files/checkpoints unchanged", ...
    "unchanged");
checks{2} = check_record(2, height(selected) <= 24, height(selected), "<=24");
tierStates = unique(double(selected.initial_state_id(selected.group_type == "TIER1")));
controlStates = unique(double(selected.initial_state_id(selected.group_type == "CONTROL")));
checks{3} = check_record(3, isequal(sort(tierStates), sort(config.states)), ...
    join(string(sort(tierStates).'), ";"), join(string(sort(config.states).'), ";"));
checks{4} = check_record(4, isequal(sort(controlStates), sort(config.states)), ...
    join(string(sort(controlStates).'), ";"), join(string(sort(config.states).'), ";"));
checks{5} = check_record(5, chain.max_distance_error <= config.distanceTolerance, ...
    chain.max_distance_error, config.distanceTolerance);
checks{6} = check_record(6, chain.max_checkpoint_error <= config.chainTolerance && ...
    chain.max_checkpoint_relative_regret_normalized_error <= ...
        config.chainTolerance && ...
    replay.all_cross_objectives_within_machine_aware_1e8_tolerance && ...
    replay.all_regrets_within_1e8_plus_operand_ulp_tolerance, ...
    max([chain.max_checkpoint_error, replay.max_objective_error, ...
    replay.max_regret_error]), "1e-8 plus at most four floating-point ULPs");
checks{7} = check_record(7, replay.all_optimal, replay.all_optimal, true);
checks{8} = check_record(8, replay.max_node_reconstruction_error <= ...
    config.chainTolerance, replay.max_node_reconstruction_error, ...
    config.chainTolerance);
tierFailure = failureTbl(failureTbl.group_type == "TIER1", :);
checks{9} = check_record(9, all(strlength(tierFailure.primary_failure_type) > 0), ...
    sum(strlength(tierFailure.primary_failure_type) > 0), height(tierFailure));
checks{10} = check_record(10, all(strlength( ...
    tierFailure.bidirectional_cause_explanation) > 0), ...
    sum(strlength(tierFailure.bidirectional_cause_explanation) > 0), ...
    height(tierFailure));
checks{11} = check_record(11, sum(failureTbl.group_type == "CONTROL") == 6, ...
    sum(failureTbl.group_type == "CONTROL"), 6);
checks{12} = check_record(12, concentration.raw_pair_count == 7733, ...
    concentration.raw_pair_count, 7733);
zeroMask = double(selected.d_new) <= config.zeroDistanceTolerance;
if any(zeroMask)
    zeroRegret = max([double(selected.regret_obj_r_to_s(zeroMask)); ...
        double(selected.regret_obj_s_to_r(zeroMask))]);
else
    zeroRegret = 0;
end
checks{13} = check_record(13, zeroRegret <= config.chainTolerance, ...
    zeroRegret, config.chainTolerance);
checks{14} = check_record(14, isequal(protectedBefore, protectedAfter), ...
    "protected hashes unchanged", "unchanged");
checks{15} = check_record(15, true, "diagnostic features only", ...
    "no replacement distance implemented");
checks{16} = check_record(16, true, "no external search or citation code", ...
    "no literature retrieval/recommendation");
checks{17} = check_record(17, config.kappa == 1 && ...
    config.weight_D == 0.6 && config.weight_Ctilde == 0.4, ...
    sprintf('kappa=%g,weights=%g/%g', config.kappa, config.weight_D, ...
    config.weight_Ctilde), "1,0.6/0.4");
checks{18} = check_record(18, isequal(protectedBefore, protectedAfter) && ...
    nominalHash == config.nominalHash, "formal model and Step-03J unchanged", ...
    "unchanged");
checks{19} = check_record(19, ~config.validationInputUsed, ...
    "nominal selected rows only", "no validation input");
checks{20} = check_record(20, isempty(codeMessages), numel(codeMessages), 0);
checks{21} = check_record(21, runtimeSec <= config.hardRuntimeSec, ...
    runtimeSec, config.hardRuntimeSec);
checks{22} = check_record(22, peakMemory > 0 && isfinite(peakMemory) && ...
    stepPBefore == stepPAfter, peakMemory, ">0 and Step-03P unchanged");
tbl = records_to_table(checks);
pass = all(tbl.status == "PASS");
end

function rec = check_record(id, passed, observed, expected)
if passed
    status = "PASS";
else
    status = "FAIL";
end
rec = struct('check_id', id, 'status', status, ...
    'observed', string(observed), 'expected', string(expected));
end

function write_summary(path, selected, jointTbl, failureTbl, comparisonTbl, ...
        concentration, chain, replay, conclusion, runtimeSec, peakMemory, ...
        pass, config)
tier = failureTbl(failureTbl.group_type == "TIER1", :);
families = string(tier.failure_family);
stateCounts = groupsummary(selected(selected.group_type == "TIER1", :), ...
    'initial_state_id');
if pass
    passText = "PASS";
else
    passText = "FAIL";
end
lines = ["Step-03T Ctilde Tier-1 structural diagnosis"; ...
    "status=" + passText; "conclusion=" + conclusion; ...
    "selected_pairs=" + height(selected); ...
    "tier1_representatives=" + sum(selected.group_type == "TIER1"); ...
    "low_regret_controls=" + sum(selected.group_type == "CONTROL"); ...
    "represented_states=" + join(string(stateCounts.initial_state_id.'), ","); ...
    "max_distance_chain_error=" + sprintf('%.16g', chain.max_distance_error); ...
    "max_checkpoint_chain_error=" + sprintf('%.16g', chain.max_checkpoint_error); ...
    "max_checkpoint_relative_regret_normalized_error=" + ...
        sprintf('%.16g', chain.max_checkpoint_relative_regret_normalized_error); ...
    "max_replay_objective_error=" + sprintf('%.16g', replay.max_objective_error); ...
    "max_replay_regret_error=" + sprintf('%.16g', replay.max_regret_error); ...
    "replay_regret_machine_aware_tolerance_pass=" + ...
        replay.all_regrets_within_1e8_plus_operand_ulp_tolerance; ...
    "max_node_regret_reconstruction_error=" + ...
        sprintf('%.16g', replay.max_node_reconstruction_error); ...
    "tier1_raw_rows=" + concentration.raw_pair_count; ...
    "tier1_unordered_unique_pairs=" + concentration.unordered_unique_pair_count; ...
    "tier1_reverse_duplicate_classes=" + concentration.reverse_duplicate_classes; ...
    "tier1_rows_in_reverse_duplicate_classes=" + concentration.reverse_duplicate_rows; ...
    "tier1_exact_oriented_duplicate_rows=" + concentration.exact_oriented_duplicate_rows; ...
    "tier1_unique_scenarios=" + concentration.unique_scenario_count; ...
    "tier1_nontail_tail=" + concentration.non_tail_tail_count; ...
    "tier1_tail_tail=" + concentration.tail_tail_count; ...
    "top1pct_incident_pair_share=" + sprintf('%.9g', concentration.incident_shares(1)); ...
    "top5pct_incident_pair_share=" + sprintf('%.9g', concentration.incident_shares(2)); ...
    "top10pct_incident_pair_share=" + sprintf('%.9g', concentration.incident_shares(3)); ...
    "remaining_after_top10pct_share=" + sprintf('%.9g', concentration.remaining_shares(3)); ...
    "remaining_after_top10pct_states=" + concentration.remaining_states(3); ...
    "service_coupling_representatives=" + sum(families == "SERVICE_COUPLING"); ...
    "spatial_demand_representatives=" + sum(families == "SPATIAL_DEMAND"); ...
    "capacity_switch_representatives=" + sum(families == "CAPACITY_SWITCH"); ...
    "aggregation_scale_representatives=" + sum(families == "AGGREGATION_SCALE"); ...
    "mixed_representatives=" + sum(families == "MIXED"); ...
    "representative_multiple_optimum_count=" + sum(~tier.not_merely_alternative_optimum); ...
    "representative_both_capacity_saturated_count=" + sum(tier.both_capacity_saturated); ...
    "representative_local_dilution_count=" + sum(tier.local_average_dilution_supported); ...
    "runtime_sec=" + sprintf('%.6f', runtimeSec); ...
    "peak_working_set_bytes=" + sprintf('%.0f', peakMemory); ...
    "fixed_constants=kappa:" + config.kappa + ",weights:" + ...
        config.weight_D + "/" + config.weight_Ctilde + ...
        ",C_bound:" + sprintf('%.16g', config.C_bound); ...
    "Step-03S was not rerun; all 7733 concentration statistics use its frozen rows."; ...
    "Only selected Step-03J nominal D/A/C rows were reread; validation was not used."; ...
    "Formal distance, loss, rho, WDRO, service constraints, MSP, and old runs remain unchanged."; ...
    "Diagnostic comparison rows=" + height(comparisonTbl) + ...
        ", joint feature rows=" + height(jointTbl) + "."];
write_lines(path, lines);
end

function value = percentile(x, probability)
x = sort(double(x(:)));
if isempty(x)
    value = NaN;
    return;
end
position = 1 + (numel(x) - 1) * probability;
lo = floor(position);
hi = ceil(position);
if lo == hi
    value = x(lo);
else
    value = x(lo) + (position - lo) * (x(hi) - x(lo));
end
end

function tf = as_logical(value)
if islogical(value)
    tf = value;
elseif isnumeric(value)
    tf = value ~= 0;
else
    tf = lower(string(value)) == "true" | string(value) == "1";
end
end

function tbl = records_to_table(records)
if isempty(records)
    tbl = table();
    return;
end
tbl = struct2table(vertcat(records{:}), 'AsArray', true);
end

function write_lines(path, lines)
fid = fopen(path, 'w');
if fid < 0
    error('Step-03T could not open %s for writing.', path);
end
cleanup = onCleanup(@() fclose(fid));
for ii = 1:numel(lines)
    fprintf(fid, '%s\n', lines(ii));
end
clear cleanup;
end

function bytes = memory_snapshot()
try
    process = System.Diagnostics.Process.GetCurrentProcess();
    bytes = double(process.WorkingSet64);
catch
    info = memory;
    bytes = double(info.MemUsedMATLAB);
end
end

function hashes = hash_files(paths)
hashes = strings(numel(paths), 1);
for ii = 1:numel(paths)
    if ~isfile(paths(ii))
        error('Step-03T protected file missing: %s', paths(ii));
    end
    hashes(ii) = sha256_file(paths(ii));
end
end

function digest = directory_hash(folder)
listing = dir(fullfile(folder, '**', '*'));
listing = listing(~[listing.isdir]);
relative = strings(numel(listing), 1);
hashes = strings(numel(listing), 1);
for ii = 1:numel(listing)
    fullPath = fullfile(listing(ii).folder, listing(ii).name);
    relative(ii) = erase(string(fullPath), string(folder) + filesep);
    hashes(ii) = sha256_file(fullPath);
end
[relative, order] = sort(relative);
hashes = hashes(order);
payload = join(relative + "|" + hashes, newline);
md = java.security.MessageDigest.getInstance('SHA-256');
md.update(unicode2native(char(payload), 'UTF-8'));
digest = lower(string(reshape(dec2hex( ...
    typecast(md.digest(), 'uint8'), 2).', 1, [])));
end

function digest = sha256_file(path)
fid = fopen(path, 'rb');
if fid < 0
    error('Step-03T cannot open file for SHA-256: %s', path);
end
cleanup = onCleanup(@() fclose(fid));
md = java.security.MessageDigest.getInstance('SHA-256');
while true
    bytes = fread(fid, 1024 * 1024, '*uint8');
    if isempty(bytes)
        break;
    end
    md.update(bytes);
end
clear cleanup;
digest = lower(string(reshape(dec2hex( ...
    typecast(md.digest(), 'uint8'), 2).', 1, [])));
end
