function run_step04CB_isolated_case_h2(preparedFile,caseId,caseDir)
%RUN_STEP04CB_ISOLATED_CASE_H2 Optimize one parameter combination only.

started=tic;preparedFile=string(preparedFile);caseDir=string(caseDir);
thisDir=fileparts(mfilename('fullpath'));rootDir=fileparts(fileparts(thisDir));
addpath(rootDir);addpath(thisDir);add_gurobi_path();
assert_git_gate("task/002-stage2b-b3-smoke", ...
    "2661960674675b2b15c9ca81cf1827d0dd0df1f6");
if ~isscalar(caseId)||caseId<1||caseId>30||caseId~=floor(caseId),error('caseId must be 1..30.');end
if ~isfile(preparedFile),error('Prepared input is missing.');end
workDir=caseDir+".work";if isfolder(caseDir),error('Case output already exists.');end
if ~isfolder(workDir),mkdir(workDir);end
existingStatus=dir(fullfile(workDir,'batch-*_status.csv'));batchId=numel(existingStatus)+1;
diary(fullfile(workDir,sprintf('batch-%03d_matlab_diary.txt',batchId)));
cleanupDiary=onCleanup(@()diary('off')); %#ok<NASGU>

P=load(preparedFile,'DnomGroup','AnomGroup','CnomGroup','q','Dext','Aext','Cext', ...
    'pathId','replicaRank','Cap','M','gamma','etas','design','riskType','topKs', ...
    'kappas','baseT','baseJ','baseR','nPaths','nReplicas');
[ee,dd,kk]=decode_case(caseId);eta=P.etas(ee);design=P.design(dd);riskType=P.riskType(dd);
topK=P.topKs(dd);kappa=P.kappas(kk);betaExt=kappa*P.baseJ(ee)/P.baseR(ee,dd);
if P.nPaths~=27||P.nReplicas~=135||numel(unique(P.pathId))~=27
    error('Prepared state19 extreme set gate failed.');
end

config=struct('gurobiOutputFlag',0,'gurobiFeasibilityTol',1e-9, ...
    'gurobiOptimalityTol',1e-9,'gurobiThreads',1,'objectiveScale',1e5, ...
    'maximumIterations',80,'absoluteGapTolerance',1e-4,'relativeGapTolerance',1e-8, ...
    'pointTolerance',1e-8,'subgradientSignTolerance',1e-6, ...
    'totalTimeLimit',3600,'recourseTimeLimit',1800,'masterTimeLimit',120, ...
    'batchIterationLimit',2,'initialT',P.baseT(ee,:));
checkpointFiles=dir(fullfile(workDir,'batch-*_checkpoint.mat'));
if ~isempty(checkpointFiles)
    [~,order]=sort({checkpointFiles.name});checkpointFile=fullfile(workDir,checkpointFiles(order(end)).name);
    checkpoint=load(checkpointFile,'resumeState');config.resumeState=checkpoint.resumeState;
end
fprintf('CASE_BATCH_START|case=%d|batch=%d|eta=%.4g|design=%s|kappa=%.4g|beta=%.12g\n', ...
    caseId,batchId,eta,design,kappa,betaExt);
if kappa<=1e-14&&eta<=1e-14
    sol=solve_zero_kappa_case(P,eta,riskType,topK,config);
else
    sol=solve_terminal_loh_extreme_aware_decomposition_h2(P.DnomGroup,P.AnomGroup,P.CnomGroup,P.q, ...
        P.Dext,P.Aext,P.Cext,P.pathId,P.replicaRank,P.Cap,P.M,P.gamma,eta,betaExt, ...
        riskType,topK,config);
end

if sol.status=="BATCH_LIMIT"
    resumeState=sol.resume_state; %#ok<NASGU>
    checkpointFile=fullfile(workDir,sprintf('batch-%03d_checkpoint.mat',batchId));
    save(checkpointFile,'resumeState','-v7.3');
    batchStatus=table(batchId,caseId,sol.decomposition_iteration_count, ...
        sol.decomposition_cut_count,sol.decomposition_lower_bound, ...
        sol.decomposition_upper_bound,sol.decomposition_absolute_gap, ...
        sol.decomposition_relative_gap,sol.master_solver_calls, ...
        sol.recourse_solver_calls,sol.status, ...
        'VariableNames',{'batch_id','case_id','iterations','cut_count','lower_bound', ...
        'upper_bound','absolute_gap','relative_gap','master_solver_calls', ...
        'recourse_solver_calls','status'});
    writetable(batchStatus,fullfile(workDir,sprintf('batch-%03d_status.csv',batchId)));
    finalGap=sol.decomposition_absolute_gap;finalIterations=sol.decomposition_iteration_count;
    diary off;cleanupDiary=[]; %#ok<NASGU>
    fprintf('CASE_BATCH_COMPLETE|case=%d|batch=%d|status=BATCH_LIMIT|gap=%.9g|iterations=%d\n', ...
        caseId,batchId,finalGap,finalIterations);
    return;
end

gapPass=sol.decomposition_absolute_gap<=config.absoluteGapTolerance|| ...
    sol.decomposition_relative_gap<=config.relativeGapTolerance;
mechanicalResidual=max([sol.objective_reconstruction_error,sol.nominal_cut_max_violation, ...
    sol.extreme_cut_max_violation,abs(sol.nominal_fixed.max_demand_balance_error), ...
    max(0,sol.nominal_fixed.max_site_capacity_violation), ...
    abs(sol.extreme_fixed.max_demand_balance_error), ...
    max(0,sol.extreme_fixed.max_site_capacity_violation)]);
mechanicalPass=sol.exitflag==1&&sol.status=="OPTIMAL"&&gapPass&& ...
    mechanicalResidual<=1e-6&&sol.objective_reconstruction_error<=1e-5&& ...
    sol.nominal_cut_max_violation<=1e-6&&sol.extreme_cut_max_violation<=1e-6;
if ~mechanicalPass
    error('Case %d audit failed: status=%s gap=%.9g rel=%.9g residual=%.9g', ...
        caseId,sol.status,sol.decomposition_absolute_gap,sol.decomposition_relative_gap,mechanicalResidual);
end

activePaths=join(string(sol.active_path_ids),';');activeRows=join(string(sol.active_replica_rows),';');
summary=table(caseId,eta,design,riskType,topK,kappa,betaExt,P.baseJ(ee),P.baseR(ee,dd), ...
    sol.T(1),sol.T(2),sol.T(3),sol.T(4),sum(sol.T),sum(P.Cap(:)-sol.T<=1e-5), ...
    sol.first_stage_cost,sol.nominal_risk_value,sol.extreme_risk_value,sol.objective_value, ...
    sol.decomposition_lower_bound,sol.decomposition_upper_bound,sol.decomposition_absolute_gap, ...
    sol.decomposition_relative_gap,sol.decomposition_iteration_count,sol.decomposition_cut_count, ...
    sol.master_solver_calls,sol.recourse_solver_calls,sol.solve_runtime_sec, ...
    sol.objective_reconstruction_error,sol.nominal_cut_max_violation,sol.extreme_cut_max_violation, ...
    sol.nominal_fixed.max_demand_balance_error,sol.nominal_fixed.max_site_capacity_violation, ...
    sol.extreme_fixed.max_demand_balance_error,sol.extreme_fixed.max_site_capacity_violation, ...
    mechanicalResidual,mechanicalPass,sol.status,activePaths,activeRows, ...
    'VariableNames',{'case_id','eta','design','risk_type','top_k','kappa','beta_ext', ...
    'J_base_at_baseline','R_ext_at_baseline','T1','T2','T3','T4','TerminalLOH_total', ...
    'capacity_binding_count','first_stage_cost','nominal_risk','extreme_risk', ...
    'enhanced_objective','lower_bound','upper_bound','absolute_gap','relative_gap', ...
    'iterations','cut_count','master_solver_calls','recourse_solver_calls','runtime_sec', ...
    'objective_reconstruction_error','nominal_cut_max_violation','extreme_cut_max_violation', ...
    'nominal_demand_balance_error','nominal_capacity_violation','extreme_demand_balance_error', ...
    'extreme_capacity_violation','maximum_mechanical_residual','mechanical_pass', ...
    'solver_status','active_path_ids','active_replica_rows'});
writetable(summary,fullfile(workDir,'case_summary.csv'));
conv=sol.convergence_history;conv.case_id=repmat(caseId,height(conv),1);conv.eta=repmat(eta,height(conv),1);
conv.design=repmat(design,height(conv),1);conv.risk_type=repmat(riskType,height(conv),1);
conv.top_k=repmat(topK,height(conv),1);conv.kappa=repmat(kappa,height(conv),1);conv.beta_ext=repmat(betaExt,height(conv),1);
writetable(conv,fullfile(workDir,'convergence_and_bounds.csv'));
cuts=sol.cut_history;cuts.case_id=repmat(caseId,height(cuts),1);cuts.eta=repmat(eta,height(cuts),1);
cuts.design=repmat(design,height(cuts),1);cuts.risk_type=repmat(riskType,height(cuts),1);
cuts.top_k=repmat(topK,height(cuts),1);cuts.kappa=repmat(kappa,height(cuts),1);cuts.beta_ext=repmat(betaExt,height(cuts),1);
writetable(cuts,fullfile(workDir,'active_extreme_cuts.csv'));
fid=fopen(fullfile(workDir,'case_mechanical_audit.txt'),'w');cleanupFid=onCleanup(@()fclose(fid));
fprintf(fid,'status=PASS\ncase_id=%d\nsolver_status=%s\n',caseId,sol.status);
fprintf(fid,'LB=%.15g\nUB=%.15g\nabsolute_gap=%.15g\nrelative_gap=%.15g\n', ...
    sol.decomposition_lower_bound,sol.decomposition_upper_bound,sol.decomposition_absolute_gap,sol.decomposition_relative_gap);
fprintf(fid,'iterations=%d\nmaximum_mechanical_residual=%.15g\n',sol.decomposition_iteration_count,mechanicalResidual);
cleanupFid=[];diary off;cleanupDiary=[]; %#ok<NASGU>
movefile(workDir,caseDir);
finalGap=sol.decomposition_absolute_gap;finalIterations=sol.decomposition_iteration_count;
fprintf('CASE_COMPLETE|case=%d|status=PASS|gap=%.9g|iterations=%d|runtime=%.3f\n', ...
    caseId,finalGap,finalIterations,toc(started));
end

function sol=solve_zero_kappa_case(P,eta,riskType,topK,config)
% beta_ext=0 is exactly the Step-04B nominal problem.  Solve it through the
% already certified production interface, then evaluate the requested
% frozen state19 extreme statistic at the newly optimized T.
started=tic;
if eta<=1e-14
    base=solve_terminal_loh_saa_h2(P.DnomGroup,P.AnomGroup,P.CnomGroup,P.q, ...
        P.Cap,P.M,P.gamma,config);
    iterations=1;cutCount=0;masterCalls=0;nominalCalls=1;
    lowerBound=base.objective_value;upperBound=base.objective_value;
else
    base=solve_terminal_loh_flat_chi2_decomposition_h2(P.DnomGroup,P.AnomGroup, ...
        P.CnomGroup,P.q,P.Cap,P.M,P.gamma,eta,config);
    iterations=base.decomposition_iteration_count;
    cutCount=base.decomposition_cut_count;masterCalls=base.master_solver_calls;
    nominalCalls=base.recourse_solver_calls;
    lowerBound=base.decomposition_lower_bound;upperBound=base.decomposition_upper_bound;
end
if base.exitflag~=1||string(base.status)~="OPTIMAL"
    error('Step-04B zero-kappa nominal solve failed: %s',string(base.status));
end
evalConfig=config;evalConfig.gurobiTimeLimit=min(config.recourseTimeLimit,config.totalTimeLimit);
ext=evaluate_terminal_loh_period_fixed_T_sparse_h2(P.Dext,P.Aext,P.Cext, ...
    repmat(base.T.',P.nReplicas,1),P.M,evalConfig);
if ext.exitflag~=1||any(~isfinite(ext.site_capacity_dual),'all')
    error('Zero-kappa frozen extreme evaluation failed: %s',string(ext.status));
end
[extRisk,activePaths,activeRows,extGradient]=extreme_value_gradient( ...
    ext.operating_loss,ext.site_capacity_dual,P.pathId,riskType,topK);
nomRisk=base.model_risk_value;firstStage=P.gamma*sum(base.T);objective=firstStage+nomRisk;
absoluteGap=max(0,upperBound-lowerBound);relativeGap=absoluteGap/max(1,abs(upperBound));
nomFixed=struct('max_demand_balance_error',base.max_demand_balance_error, ...
    'max_site_capacity_violation',base.max_site_capacity_violation);
extFixed=struct('max_demand_balance_error',ext.max_demand_balance_error, ...
    'max_site_capacity_violation',ext.max_site_capacity_violation);
convergence=table(iterations,cutCount,lowerBound,upperBound,absoluteGap,relativeGap, ...
    base.T(1),base.T(2),base.T(3),base.T(4), ...
    'VariableNames',{'iteration','cut_count','lower_bound','upper_bound', ...
    'absolute_gap','relative_gap','master_T1','master_T2','master_T3','master_T4'});
cutHistory=table(1,base.T(1),base.T(2),base.T(3),base.T(4),nomRisk,extRisk, ...
    NaN,NaN,NaN,NaN,extGradient(1),extGradient(2),extGradient(3),extGradient(4), ...
    join(string(activePaths),';'),join(string(activeRows),';'), ...
    'VariableNames',{'cut_id','T1','T2','T3','T4','nominal_risk','extreme_risk', ...
    'nominal_g1','nominal_g2','nominal_g3','nominal_g4','extreme_g1','extreme_g2', ...
    'extreme_g3','extreme_g4','active_path_ids','active_replica_rows'});
sol=struct('mode',"STEP04B_ZERO_KAPPA_CERTIFIED",'status',"OPTIMAL",'exitflag',1, ...
    'T',base.T,'first_stage_cost',firstStage,'nominal_risk_value',nomRisk, ...
    'extreme_risk_value',extRisk,'objective_value',objective, ...
    'decomposition_lower_bound',lowerBound,'decomposition_upper_bound',upperBound, ...
    'decomposition_absolute_gap',absoluteGap,'decomposition_relative_gap',relativeGap, ...
    'decomposition_iteration_count',iterations,'decomposition_cut_count',cutCount, ...
    'master_solver_calls',masterCalls,'recourse_solver_calls',nominalCalls+1, ...
    'solve_runtime_sec',toc(started),'objective_reconstruction_error', ...
    abs(objective-(firstStage+nomRisk)),'nominal_cut_max_violation',0, ...
    'extreme_cut_max_violation',0,'nominal_fixed',nomFixed,'extreme_fixed',extFixed, ...
    'active_path_ids',activePaths,'active_replica_rows',activeRows, ...
    'convergence_history',convergence,'cut_history',cutHistory);
end

function [value,activePaths,activeRows,gradient]=extreme_value_gradient(loss,dual,pathId,riskType,topK)
paths=unique(pathId,'sorted');pathLoss=zeros(numel(paths),1);active=zeros(numel(paths),1);
for pp=1:numel(paths)
    members=find(pathId==paths(pp));[pathLoss(pp),ii]=max(loss(members));active(pp)=members(ii);
end
if riskType=="R1_MAX"
    [value,selected]=max(pathLoss);selected=selected(:);
else
    [~,order]=sortrows([-pathLoss,paths],[1,2]);selected=order(1:topK);value=mean(pathLoss(selected));
end
activePaths=paths(selected).';activeRows=active(selected).';gradient=mean(dual(activeRows,:),1);
end

function [ee,dd,kk]=decode_case(caseId)
z=caseId-1;ee=floor(z/15)+1;within=mod(z,15);dd=floor(within/5)+1;kk=mod(within,5)+1;
end

function assert_git_gate(expectedBranch,expectedHead)
[s1,b]=system('git branch --show-current');[s2,h]=system('git rev-parse HEAD');[s3,u]=system('git rev-parse @{upstream}');
if s1~=0||s2~=0||s3~=0||strtrim(string(b))~=expectedBranch||strtrim(string(h))~=expectedHead||strtrim(string(u))~=expectedHead
    error('Step-04C-B isolated case Git gate failed.');
end
end

function add_gurobi_path()
for candidate={fullfile(getenv('GUROBI_HOME'),'matlab'),'D:\gurobi1201\win64\matlab','C:\gurobi1201\win64\matlab'}
    if ~isempty(candidate{1})&&isfolder(candidate{1}),addpath(candidate{1});end
end
end
