function run_step05B5_existing_cut_value_audit_h2(runId)
%RUN_STEP05B5_EXISTING_CUT_VALUE_AUDIT_H2 Read saved cuts without solving/training.

if nargin < 1 || strlength(string(runId)) == 0
    runId = "run-001";
end
repo = fileparts(fileparts(fileparts(mfilename('fullpath'))));
outDir = fullfile(repo, 'results', 'task-002-stage2b-b3-smoke', ...
    '62-terminal-loh-information-revelation-audit', char(runId));
requestFile = fullfile(outDir, 'cut_audit_request.csv');
outputFile = fullfile(outDir, 'existing_cut_value_signal_audit.csv');
integrityFile = fullfile(outDir, 'cut_value_signal_integrity_audit.txt');
if ~isfile(requestFile)
    error('run_step05B5_existing_cut_value_audit_h2:MissingRequest', ...
        'Missing request file: %s', requestFile);
end
if isfile(outputFile) || isfile(integrityFile)
    error('run_step05B5_existing_cut_value_audit_h2:RefuseOverwrite', ...
        'Refusing to overwrite existing cut audit output in %s.', outDir);
end

sourceRun = fullfile(repo, 'results', 'task-002-stage2b-b3-smoke', ...
    '57-main-msp-converged-terminal-loh-ab', 'run-003');
workspaces = struct();
workspaces.saa = fullfile(sourceRun, 'case-saa', 'native_output', 'h2_workspace.mat');
workspaces.chi2_eta003 = fullfile(sourceRun, 'case-chi2_eta003', ...
    'native_output', 'h2_workspace.mat');
request = readtable(requestFile, 'TextType', 'string');
required = ["method","path_id","state","decision_stage","current_k", ...
    "current_a","current_loc","current_lf","history_node_id", ...
    "selection_reason","terminal_gap_kg","node_oos_path_count", ...
    "future_terminal_state_count","realized_terminal_state_probability", ...
    "positive_target_modal_top_site","positive_target_modal_top_site_probability", ...
    "conditional_max_site_target_range_kg", ...
    "inventory_vs_realized_target_distribution_l1", ...
    "x1_kg","x2_kg","x3_kg","x4_kg", ...
    "realized_target_site1_kg","realized_target_site2_kg", ...
    "realized_target_site3_kg","realized_target_site4_kg", ...
    "node_conditional_mean_target_site1_kg", ...
    "node_conditional_mean_target_site2_kg", ...
    "node_conditional_mean_target_site3_kg", ...
    "node_conditional_mean_target_site4_kg"];
if ~all(ismember(required, string(request.Properties.VariableNames)))
    error('run_step05B5_existing_cut_value_audit_h2:RequestSchema', ...
        'Cut request schema is incomplete.');
end

allRows = cell(0, 37);
methodOrder = ["saa","chi2_eta003"];
loadedMethods = strings(0,1);
for method = methodOrder
    subset = request(request.method == method, :);
    if isempty(subset)
        error('run_step05B5_existing_cut_value_audit_h2:MissingMethod', ...
            'No cut requests for method %s.', method);
    end
    workspaceFile = workspaces.(char(method));
    if ~isfile(workspaceFile)
        error('run_step05B5_existing_cut_value_audit_h2:MissingWorkspace', ...
            'Missing workspace: %s', workspaceFile);
    end
    loaded = load(workspaceFile, 'modelLib', 'params');
    if ~isfield(loaded, 'modelLib') || ~isfield(loaded, 'params')
        error('run_step05B5_existing_cut_value_audit_h2:WorkspaceSchema', ...
            'Workspace lacks modelLib or params: %s', workspaceFile);
    end
    loadedMethods(end+1,1) = method; %#ok<AGROW>

    for rowId = 1:height(subset)
        meta = subset(rowId,:);
        t = double(meta.decision_stage);
        k = double(meta.current_k);
        if t < 1 || t > loaded.params.T || k < 1 || k > loaded.params.K
            error('run_step05B5_existing_cut_value_audit_h2:IndexRange', ...
                'Invalid model index t=%d,k=%d.', t, k);
        end
        model = loaded.modelLib.models{t,k};
        if isempty(model)
            error('run_step05B5_existing_cut_value_audit_h2:MissingModel', ...
                'No saved ordinary model at t=%d,k=%d.', t, k);
        end
        x = [double(meta.x1_kg); double(meta.x2_kg); ...
            double(meta.x3_kg); double(meta.x4_kg)];
        if numel(model.idx.x) ~= 4
            error('run_step05B5_existing_cut_value_audit_h2:StationCount', ...
                'Expected four inventory states.');
        end
        baseRows = max(model.rowMap.htt_capacity);
        cutRows = (baseRows+1):size(model.A,1);
        if isempty(cutRows)
            error('run_step05B5_existing_cut_value_audit_h2:NoCuts', ...
                'No saved cuts at t=%d,k=%d.', t, k);
        end
        slopes = model.A(cutRows, model.idx.x);
        rhs = -model.b(cutRows) + slopes*x;
        activeRhs = max(rhs);
        tol = 1e-6*max(1,abs(activeRhs));
        activeLocal = find(abs(rhs-activeRhs) <= tol);
        chosenLocal = activeLocal(1);
        chosenCutRow = cutRows(chosenLocal);
        chosenSlope = slopes(chosenLocal,:).';
        chosenMarginal = -chosenSlope;
        activeMarginals = -slopes(activeLocal,:);
        activeMarginalMin = min(activeMarginals,[],1).';
        activeMarginalMax = max(activeMarginals,[],1).';
        activeMarginalMean = mean(activeMarginals,1).';
        [~, order] = sort(chosenMarginal, 'descend');
        marginalRank = zeros(4,1);
        marginalRank(order) = 1:4;
        target = [double(meta.realized_target_site1_kg); ...
            double(meta.realized_target_site2_kg); ...
            double(meta.realized_target_site3_kg); ...
            double(meta.realized_target_site4_kg)];
        nodeMeanTarget = [double(meta.node_conditional_mean_target_site1_kg); ...
            double(meta.node_conditional_mean_target_site2_kg); ...
            double(meta.node_conditional_mean_target_site3_kg); ...
            double(meta.node_conditional_mean_target_site4_kg)];
        [~, targetOrder] = sort(target,'descend');
        targetRank = zeros(4,1);
        targetRank(targetOrder) = 1:4;
        [~, nodeTargetOrder] = sort(nodeMeanTarget,'descend');
        nodeTargetRank = zeros(4,1);
        nodeTargetRank(nodeTargetOrder) = 1:4;
        for site = 1:4
            allRows(end+1,:) = {method, double(meta.path_id), double(meta.state), ...
                t, k, double(meta.current_a), double(meta.current_loc), ...
                double(meta.current_lf), meta.history_node_id, meta.selection_reason, ...
                double(meta.terminal_gap_kg), double(meta.node_oos_path_count), ...
                double(meta.future_terminal_state_count), ...
                double(meta.realized_terminal_state_probability), ...
                double(meta.positive_target_modal_top_site), ...
                double(meta.positive_target_modal_top_site_probability), ...
                double(meta.conditional_max_site_target_range_kg), ...
                double(meta.inventory_vs_realized_target_distribution_l1), ...
                site, x(site), target(site), nodeMeanTarget(site), ...
                numel(cutRows), numel(activeLocal), activeRhs, chosenCutRow, ...
                chosenSlope(site), chosenMarginal(site), marginalRank(site), ...
                activeMarginalMin(site), activeMarginalMax(site), ...
                activeMarginalMean(site), targetRank(site), nodeTargetRank(site), ...
                chosenMarginal(site) - mean(chosenMarginal(setdiff(1:4,site))), ...
                chosenMarginal(site) > 1e-9, ...
                abs(activeRhs-max(rhs))}; %#ok<AGROW>
        end
    end
    clear loaded;
end

names = {'method','path_id','state','decision_stage','current_k','current_a', ...
    'current_loc','current_lf','history_node_id','selection_reason', ...
    'terminal_gap_kg','node_oos_path_count','future_terminal_state_count', ...
    'realized_terminal_state_probability','positive_target_modal_top_site', ...
    'positive_target_modal_top_site_probability', ...
    'conditional_max_site_target_range_kg', ...
    'inventory_vs_realized_target_distribution_l1','site','x_site_kg', ...
    'realized_target_kg','node_conditional_mean_target_kg','total_cut_count', ...
    'active_cut_count','active_cut_rhs','chosen_cut_row','chosen_cut_slope', ...
    'chosen_marginal_value_of_1kg_inventory','chosen_marginal_value_rank', ...
    'active_marginal_value_min','active_marginal_value_max', ...
    'active_marginal_value_mean','realized_target_rank', ...
    'node_conditional_mean_target_rank', ...
    'chosen_marginal_minus_other_sites_mean','positive_marginal_value_flag', ...
    'active_rhs_reconstruction_residual'};
output = cell2table(allRows, 'VariableNames', names);
if height(output) ~= 4*height(request)
    error('run_step05B5_existing_cut_value_audit_h2:OutputRows', ...
        'Expected %d output rows, got %d.', 4*height(request), height(output));
end
if max(output.active_rhs_reconstruction_residual) > 1e-10
    error('run_step05B5_existing_cut_value_audit_h2:ActiveRhs', ...
        'Active-cut RHS reconstruction failed.');
end
writetable(output, outputFile);

fid = fopen(integrityFile,'w');
if fid < 0
    error('run_step05B5_existing_cut_value_audit_h2:IntegrityWrite', ...
        'Cannot write %s.', integrityFile);
end
cleanupObj = onCleanup(@() fclose(fid));
fprintf(fid, 'Step-05B-5 existing saved-cut value-signal audit\n\n');
fprintf(fid, 'Request rows: %d\n', height(request));
fprintf(fid, 'Output site rows: %d\n', height(output));
fprintf(fid, 'Loaded methods: %s\n', strjoin(cellstr(loadedMethods), ', '));
fprintf(fid, 'All requested models contain saved cuts: 1\n');
fprintf(fid, 'Minimum total cut count: %d\n', min(output.total_cut_count));
fprintf(fid, 'Maximum total cut count: %d\n', max(output.total_cut_count));
fprintf(fid, 'Maximum active RHS reconstruction residual: %.12g\n', ...
    max(output.active_rhs_reconstruction_residual));
fprintf(fid, 'No Gurobi solve, forward pass, backward pass, cut generation, or training was called.\n');
fprintf(fid, 'The active saved cut is identified as the maximum existing affine cut RHS at the archived replay inventory x.\n');
fprintf(fid, 'When multiple cuts tie within tolerance, the first is reported and the min/max/mean marginal values across all tied cuts are retained.\n');
fprintf(fid, 'Cut audit PASS: 1\n');
clear cleanupObj;
fprintf('Step-05B-5 saved-cut audit PASS: %s\n', outputFile);
end
