function result = run_flat_chi2_terminal_case_h2( ...
        stateId, R, eta, timeLimitSec, outputDir)
%RUN_FLAT_CHI2_TERMINAL_CASE_H2 Unified production state/R/eta entry.

if nargin < 4 || isempty(timeLimitSec), timeLimitSec = 1800; end
if nargin < 5, outputDir = ""; end
thisDir = fileparts(mfilename('fullpath'));
rootDir = fileparts(fileparts(thisDir));
addpath(rootDir); addpath(thisDir);
add_gurobi_path();
assert_git_gate("task/002-stage2b-b3-smoke", ...
    "e9cea80b0f8743a94b1e791095158b5bf82d1f8e");
if ~isscalar(stateId) || ~ismember(stateId, 1:35) || ...
        ~isscalar(R) || R < 1 || R > 15000 || R ~= floor(R) || ...
        ~isscalar(eta) || ~isfinite(eta) || eta < 0 || ...
        ~isscalar(timeLimitSec) || ~isfinite(timeLimitSec) || timeLimitSec <= 0
    error('run_flat_chi2_terminal_case_h2:BadInput', ...
        'stateId, R, eta, and time limit are invalid.');
end
outputDir = string(outputDir);
if strlength(outputDir) > 0
    if isfolder(outputDir) && ~isempty(dir(fullfile(outputDir, '*')))
        entries = dir(fullfile(outputDir, '*'));
        entries = entries(~ismember({entries.name}, {'.', '..'}));
        if ~isempty(entries)
            error('run_flat_chi2_terminal_case_h2:OutputExists', ...
                'Refusing to overwrite nonempty output directory: %s', outputDir);
        end
    end
    if ~isfolder(outputDir), mkdir(outputDir); end
end

[entry, context] = recover_step03Y_prefix_entries_h2( ...
    rootDir, stateId, R, false);
if ~entry.audit.all_final_DAC_exact || ...
        ~entry.audit.all_stream_hashes_match || entry.audit.max_DAC_error ~= 0
    error('run_flat_chi2_terminal_case_h2:ReplayFailure', ...
        'Frozen formal period D/A/C replay failed.');
end
aggregation = aggregate_exact_period_scenarios_h2( ...
    entry.Dperiod, entry.Aperiod, entry.Cperiod);
config = struct('gurobiOutputFlag', 0, 'gurobiTimeLimit', timeLimitSec, ...
    'objectiveScale', 1e5);
if eta <= 1e-14
    solution = solve_terminal_loh_saa_h2(aggregation.Dperiod, ...
        aggregation.Aperiod, aggregation.Cperiod, ...
        aggregation.nominal_probability, context.Cap, context.M, ...
        context.gamma, config);
elseif aggregation.group_count <= 500
    solution = solve_terminal_loh_flat_chi2_qcp_h2(aggregation.Dperiod, ...
        aggregation.Aperiod, aggregation.Cperiod, ...
        aggregation.nominal_probability, context.Cap, context.M, ...
        context.gamma, eta, config);
else
    config.totalTimeLimit = timeLimitSec;
    solution = solve_terminal_loh_flat_chi2_decomposition_h2( ...
        aggregation.Dperiod, aggregation.Aperiod, aggregation.Cperiod, ...
        aggregation.nominal_probability, context.Cap, context.M, ...
        context.gamma, eta, config);
end
if solution.exitflag ~= 1
    error('run_flat_chi2_terminal_case_h2:OptimizationFailure', ...
        'TerminalLOH model status: %s', solution.status);
end
audit = audit_flat_chi2_terminal_solution_h2( ...
    solution, aggregation, context.M, context.gamma, config);
result = struct('state_id', stateId, 'R', R, 'eta', eta, ...
    'aggregation', aggregation, 'solution', solution, 'audit', audit, ...
    'context', context);

if strlength(outputDir) > 0
    summary = table(stateId, R, aggregation.group_count, eta, ...
        solution.T(1), solution.T(2), solution.T(3), solution.T(4), ...
        sum(solution.T), audit.first_stage_cost, ...
        audit.nominal_expected_recourse, audit.worst_expected_recourse, ...
        audit.robust_total_objective, solution.solve_runtime_sec, ...
        audit.fixed_T.solve_runtime_sec, audit.strong_duality_gap, ...
        audit.record_divergence_used, audit.record_effective_sample_size, ...
        audit.maximum_mechanical_residual, solution.status, audit.status, ...
        'VariableNames', {'initial_state_id','R','exact_group_count','eta', ...
        'T1_kg','T2_kg','T3_kg','T4_kg','TerminalLOH_total_kg', ...
        'first_stage_cost','nominal_expected_recourse', ...
        'worst_expected_recourse','robust_total_objective', ...
        'optimization_runtime_sec','fixed_T_audit_runtime_sec', ...
        'strong_duality_gap','divergence_used','worst_probability_ESS', ...
        'maximum_mechanical_residual','solver_status','audit_status'});
    writetable(summary, fullfile(outputDir, 'case_summary.csv'));
    probability = table((1:R).', audit.original_record_operating_loss, ...
        ones(R, 1) ./ R, audit.original_record_worst_probability, ...
        audit.original_record_worst_probability - 1 / R, ...
        'VariableNames', {'scenario_id','operating_loss', ...
        'nominal_probability','worst_probability','probability_shift'});
    writetable(probability, fullfile(outputDir, 'worst_probability.csv'));
end
end

function assert_git_gate(expectedBranch, expectedHead)
[s1, branch] = system('git branch --show-current');
[s2, head] = system('git rev-parse HEAD');
[s3, upstream] = system('git rev-parse @{upstream}');
if s1 ~= 0 || s2 ~= 0 || s3 ~= 0 || ...
        strtrim(string(branch)) ~= expectedBranch || ...
        strtrim(string(head)) ~= expectedHead || ...
        strtrim(string(upstream)) ~= expectedHead
    error('run_flat_chi2_terminal_case_h2:FrozenGitGate', ...
        'Frozen branch/HEAD/upstream gate failed.');
end
end

function add_gurobi_path()
for candidate = {fullfile(getenv('GUROBI_HOME'), 'matlab'), ...
        'D:\gurobi1201\win64\matlab', 'C:\gurobi1201\win64\matlab'}
    if ~isempty(candidate{1}) && isfolder(candidate{1})
        addpath(candidate{1});
    end
end
end
