function run_step03YF_r2000_state_h2(stateId)
%RUN_STEP03YF_R2000_STATE_H2 Solve one state in an isolated MATLAB process.

allowedStates = [7, 9, 11, 19];
if nargin ~= 1 || ~isscalar(stateId) || ~ismember(stateId, allowedStates)
    error('Step-03Y-F stateId must be one of 7, 9, 11, or 19.');
end

started = tic;
solverCallCount = 0;
peakMemory = memory_snapshot();
thisFile = mfilename('fullpath');
thisDir = fileparts(thisFile);
moduleDir = fileparts(thisDir);
rootDir = fileparts(moduleDir);
addpath(rootDir); addpath(thisDir);

expectedBranch = "task/002-stage2b-b3-smoke";
expectedHead = "f46321afbe78469962f97f26f4f8ccea0329f89d";
R = 2000;
formalCap = [300; 200; 100; 150];
objectiveTolerance = 1e-6;
outputBase = fullfile(rootDir, 'results', ...
    'task-002-stage2b-b3-smoke', ...
    '35-period-vs-aggregate-saa-r2000');
outputDir = fullfile(outputBase, 'run-001');
workDir = fullfile(outputBase, 'run-001.inprogress');
prefix = sprintf('state_%02d', stateId);
auditFile = fullfile(workDir, prefix + "_audit.txt");

[~, branch] = system('git branch --show-current');
[~, head] = system('git rev-parse HEAD');
[~, upstream] = system('git rev-parse "@{upstream}"');
branch = string(strtrim(branch));
head = string(strtrim(head));
upstream = string(strtrim(upstream));
if branch ~= expectedBranch || head ~= expectedHead || upstream ~= expectedHead
    error('Step-03Y-F frozen Git baseline mismatch.');
end
if isfolder(outputDir)
    error('Step-03Y-F final output already exists.');
end
if ~isfolder(workDir), mkdir(workDir); end
if isfile(auditFile)
    error('Step-03Y-F state %d checkpoint already exists.', stateId);
end

protectedRelative = protected_paths();
protectedBefore = strings(numel(protectedRelative), 1);
for ii = 1:numel(protectedRelative)
    protectedBefore(ii) = path_digest(fullfile(rootDir, protectedRelative(ii)));
    if protectedBefore(ii) == "MISSING"
        error('Step-03Y-F protected path missing: %s', protectedRelative(ii));
    end
end

try
    fprintf('Step-03Y-F state %d deterministic R=2000 replay start.\n', stateId);
    [entries, context] = recover_step03Y_prefix_entries_h2( ...
        rootDir, stateId, R, false);
    entry = entries(1);
    peakMemory = max(peakMemory, memory_snapshot());
    if ~entry.audit.all_final_DAC_exact || entry.audit.max_DAC_error ~= 0 || ...
            ~entry.audit.all_stream_hashes_match
        error('Deterministic period replay did not exactly reproduce final D/A/C.');
    end
    if ~isequal(context.Cap, formalCap) || context.M ~= 2000 || context.gamma ~= 2
        error('Frozen model parameters changed.');
    end
    identity = entry.identity;
    [~, order] = sort(identity.scenario_id);
    identity = identity(order, :);
    if height(identity) ~= R || ...
            ~isequal(double(identity.scenario_id), (1:R).') || ...
            ~all(identity.replay_state_pass) || ...
            any(identity.initial_state_id ~= stateId)
        error('Scenario identity/order/replay audit failed.');
    end
    Dagg = entry.Dagg(order, :);
    Aagg = entry.Aagg(order, :, :);
    Cagg = entry.Cagg(order, :, :);
    Dperiod = entry.Dperiod(order, :, :);
    Aperiod = entry.Aperiod(order, :, :, :);
    Cperiod = entry.Cperiod(order, :, :, :);
    totalDemand = sum(Dagg, 2);
    positiveCount = sum(totalDemand > 1e-10);
    meanDemand = mean(totalDemand);
    maxDemand = max(totalDemand);

    config = struct('gurobiOutputFlag', 0, ...
        'gurobiFeasibilityTol', 1e-9, 'gurobiOptimalityTol', 1e-9, ...
        'gurobiTimeLimit', 600, 'objectiveScale', 1, ...
        'gamma', context.gamma);
    fprintf('Step-03Y-F state %d aggregate SAA start.\n', stateId); drawnow;
    aggregate = solve_step03Y_saa_audit_h2("AGGREGATE", ...
        Dagg, Aagg, Cagg, formalCap, context.M, context.gamma, config);
    solverCallCount = solverCallCount + 1;
    fprintf('Step-03Y-F state %d period SAA start.\n', stateId); drawnow;
    period = solve_step03Y_saa_audit_h2("PERIOD", ...
        Dperiod, Aperiod, Cperiod, formalCap, context.M, context.gamma, config);
    solverCallCount = solverCallCount + 1;
    if aggregate.status ~= "OPTIMAL" || period.status ~= "OPTIMAL"
        error('Aggregate or period SAA was not OPTIMAL.');
    end

    fprintf('Step-03Y-F state %d period-T in aggregate evaluation start.\n', stateId);
    aggregateCross = evaluate_step03T_fixed_T_recourse_h2( ...
        Dagg, Aagg, Cagg, repmat(period.T.', R, 1), context.M, config);
    solverCallCount = solverCallCount + 1;
    if aggregateCross.status ~= "OPTIMAL"
        error('Period-T in aggregate fixed-T evaluation was not OPTIMAL.');
    end
    aggregateCrossSummary = summarize_fixed_eval(aggregateCross);
    clear aggregateCross;
    peakMemory = max(peakMemory, memory_snapshot());

    fprintf('Step-03Y-F state %d aggregate-T in period evaluation start.\n', stateId);
    periodCross = evaluate_step03Y_period_fixed_T_recourse_h2( ...
        Dperiod, Aperiod, Cperiod, repmat(aggregate.T.', R, 1), ...
        context.M, config);
    solverCallCount = solverCallCount + 1;
    if periodCross.status ~= "OPTIMAL"
        error('Aggregate-T in period fixed-T evaluation was not OPTIMAL.');
    end
    periodCrossSummary = summarize_fixed_eval(periodCross);
    clear periodCross;
    peakMemory = max(peakMemory, memory_snapshot());

    periodTInAggregate = period.holding_cost + ...
        aggregateCrossSummary.mean_operating_loss;
    aggregateTInPeriod = aggregate.holding_cost + ...
        periodCrossSummary.mean_operating_loss;
    aggregateRegretOfPeriodT = periodTInAggregate - aggregate.objective_value;
    periodRegretOfAggregateT = aggregateTInPeriod - period.objective_value;
    aggregateRelativeRegret = aggregateRegretOfPeriodT / ...
        max(1, abs(aggregate.objective_value));
    periodRelativeRegret = periodRegretOfAggregateT / ...
        max(1, abs(period.objective_value));

    casePass = aggregate.objective_reconstruction_error <= objectiveTolerance && ...
        period.objective_reconstruction_error <= objectiveTolerance && ...
        aggregate.objective_weight_sum == 1 && period.objective_weight_sum == 1 && ...
        aggregateRegretOfPeriodT >= -objectiveTolerance && ...
        periodRegretOfAggregateT >= -objectiveTolerance && ...
        all(isfinite([aggregate.T; period.T])) && solverCallCount == 4;
    if ~casePass
        error('Objective, weights, finite values, or cross regret audit failed.');
    end

    terminal = make_terminal_table(stateId, R, positiveCount, meanDemand, ...
        maxDemand, aggregate, period, formalCap, aggregateRegretOfPeriodT, ...
        periodRegretOfAggregateT, aggregateRelativeRegret, ...
        periodRelativeRegret);
    cross = make_cross_table(stateId, R, positiveCount, meanDemand, maxDemand, ...
        aggregate, period, aggregateCrossSummary, periodCrossSummary, ...
        periodTInAggregate, aggregateTInPeriod);
    objective = make_objective_table(stateId, R, aggregate, period);
    capacity = make_capacity_table(stateId, R, aggregate, period, formalCap);

    protectedAfter = strings(numel(protectedRelative), 1);
    for ii = 1:numel(protectedRelative)
        protectedAfter(ii) = path_digest(fullfile(rootDir, protectedRelative(ii)));
    end
    if ~isequal(protectedBefore, protectedAfter)
        error('Protected path changed during state run.');
    end
    codeIssueCount = numel(checkcode(thisFile, '-id')) + ...
        numel(checkcode(fullfile(thisDir, ...
        'recover_step03Y_prefix_entries_h2.m'), '-id')) + ...
        numel(checkcode(fullfile(thisDir, ...
        'solve_step03Y_saa_audit_h2.m'), '-id'));
    if codeIssueCount ~= 0
        error('Step-03Y-F checkcode found %d issue(s).', codeIssueCount);
    end

    runtimeSec = toc(started);
    peakMemory = max(peakMemory, memory_snapshot());
    writetable(terminal, fullfile(workDir, prefix + "_terminal.csv"));
    writetable(cross, fullfile(workDir, prefix + "_cross.csv"));
    writetable(objective, fullfile(workDir, prefix + "_objective.csv"));
    writetable(capacity, fullfile(workDir, prefix + "_capacity.csv"));
    metrics = table(stateId, R, solverCallCount, runtimeSec, peakMemory, ...
        entry.audit.max_DAC_error, positiveCount, meanDemand, maxDemand, ...
        codeIssueCount, 'VariableNames', {'initial_state_id','R', ...
        'solver_call_count','runtime_sec','peak_working_set_bytes', ...
        'max_DAC_error','positive_demand_scenario_count', ...
        'mean_total_demand_kg','max_total_demand_kg','checkcode_issue_count'});
    writetable(metrics, fullfile(workDir, prefix + "_metrics.csv"));
    auditLines = ["status=PASS"; "initial_state_id=" + stateId; ...
        "R=2000"; "scenario_prefix_exact=true"; ...
        "deterministic_replay_max_DAC_error=0"; ...
        "aggregate_status=" + aggregate.status; ...
        "period_status=" + period.status; ...
        "solver_call_count=" + solverCallCount; ...
        "runtime_sec=" + sprintf('%.6f', runtimeSec); ...
        "peak_working_set_bytes=" + sprintf('%.0f', peakMemory); ...
        "protected_paths_unchanged=true"; ...
        "checkcode_issue_count=" + codeIssueCount; ...
        "WDRO_call_count=0"; "MSP_call_count=0"; ...
        "validation_file_count=0"; "new_random_scenario_count=0"];
    write_lines(auditFile, auditLines);
    fprintf('Step-03Y-F state %d PASS, runtime %.3f s.\n', stateId, runtimeSec);
catch exception
    runtimeSec = toc(started);
    peakMemory = max(peakMemory, memory_snapshot());
    failureLines = ["status=FAIL"; "initial_state_id=" + stateId; ...
        "R=2000"; "solver_call_count=" + solverCallCount; ...
        "runtime_sec=" + sprintf('%.6f', runtimeSec); ...
        "peak_working_set_bytes=" + sprintf('%.0f', peakMemory); ...
        "failure_identifier=" + string(exception.identifier); ...
        "failure_message=" + replace(string(exception.message), newline, " ")];
    write_lines(auditFile, failureLines);
    rethrow(exception);
end
end

function summary = summarize_fixed_eval(result)
summary = struct('mean_service_cost', mean(result.service_cost), ...
    'mean_shortage_kg', mean(result.shortage_kg), ...
    'mean_shortage_loss', mean(result.shortage_loss), ...
    'mean_operating_loss', mean(result.operating_loss));
end

function output = make_terminal_table(stateId, R, positiveCount, meanDemand, ...
        maxDemand, aggregate, period, Cap, aggregateRegret, periodRegret, ...
        aggregateRelativeRegret, periodRelativeRegret)
rows = struct([]);
for site = 1:4
    row = struct('initial_state_id', stateId, 'R', R, 'site_id', site, ...
        'positive_demand_scenario_count', positiveCount, ...
        'mean_total_demand_kg', meanDemand, 'max_total_demand_kg', maxDemand, ...
        'scenario_weight', 1 / R, ...
        'T_aggregate_kg', aggregate.T(site), 'T_period_kg', period.T(site), ...
        'period_minus_aggregate_kg', period.T(site) - aggregate.T(site), ...
        'site_absolute_difference_kg', abs(period.T(site) - aggregate.T(site)), ...
        'site_difference_fraction_of_capacity', ...
        abs(period.T(site) - aggregate.T(site)) / Cap(site), ...
        'aggregate_total_T_kg', sum(aggregate.T), ...
        'period_total_T_kg', sum(period.T), ...
        'period_minus_aggregate_total_kg', sum(period.T) - sum(aggregate.T), ...
        'total_absolute_difference_kg', abs(sum(period.T) - sum(aggregate.T)), ...
        'total_difference_fraction_of_total_capacity', ...
        abs(sum(period.T) - sum(aggregate.T)) / sum(Cap), ...
        'aggregate_at_capacity', aggregate.T_at_upper_bound(site), ...
        'period_at_capacity', period.T_at_upper_bound(site), ...
        'aggregate_objective', aggregate.objective_value, ...
        'period_objective', period.objective_value, ...
        'aggregate_TerminalLOH_cost', aggregate.holding_cost, ...
        'period_TerminalLOH_cost', period.holding_cost, ...
        'aggregate_mean_service_cost', aggregate.mean_service_cost, ...
        'period_mean_service_cost', period.mean_service_cost, ...
        'aggregate_mean_shortage_loss', aggregate.mean_shortage_loss, ...
        'period_mean_shortage_loss', period.mean_shortage_loss, ...
        'aggregate_mean_operating_loss', aggregate.mean_operating_loss, ...
        'period_mean_operating_loss', period.mean_operating_loss, ...
        'aggregate_regret_of_period_T', aggregateRegret, ...
        'period_regret_of_aggregate_T', periodRegret, ...
        'aggregate_relative_regret', aggregateRelativeRegret, ...
        'period_relative_regret', periodRelativeRegret, ...
        'replay_complete', true, 'failure_message', "", 'case_pass', true);
    rows = append_struct(rows, row);
end
output = struct2table(rows);
end

function output = make_cross_table(stateId, R, positiveCount, meanDemand, ...
        maxDemand, aggregate, period, aggregateCross, periodCross, ...
        periodTInAggregate, aggregateTInPeriod)
spec = { ...
    "AGGREGATE", "T_AGGREGATE", aggregate.T, aggregate.holding_cost, ...
        aggregate.mean_service_cost, aggregate.mean_shortage_loss, ...
        aggregate.mean_operating_loss, aggregate.objective_value, ...
        aggregate.objective_value; ...
    "AGGREGATE", "T_PERIOD", period.T, period.holding_cost, ...
        aggregateCross.mean_service_cost, aggregateCross.mean_shortage_loss, ...
        aggregateCross.mean_operating_loss, periodTInAggregate, ...
        aggregate.objective_value; ...
    "PERIOD", "T_PERIOD", period.T, period.holding_cost, ...
        period.mean_service_cost, period.mean_shortage_loss, ...
        period.mean_operating_loss, period.objective_value, ...
        period.objective_value; ...
    "PERIOD", "T_AGGREGATE", aggregate.T, aggregate.holding_cost, ...
        periodCross.mean_service_cost, periodCross.mean_shortage_loss, ...
        periodCross.mean_operating_loss, aggregateTInPeriod, ...
        period.objective_value};
rows = struct([]);
for ii = 1:4
    T = spec{ii, 3};
    totalObjective = spec{ii, 8};
    targetOptimum = spec{ii, 9};
    row = struct('initial_state_id', stateId, 'R', R, ...
        'evaluation_model', spec{ii, 1}, 'terminalLOH_source', spec{ii, 2}, ...
        'T1', T(1), 'T2', T(2), 'T3', T(3), 'T4', T(4), ...
        'TerminalLOH_cost', spec{ii, 4}, ...
        'mean_service_cost', spec{ii, 5}, ...
        'mean_shortage_loss', spec{ii, 6}, ...
        'mean_operating_loss', spec{ii, 7}, ...
        'total_objective', totalObjective, ...
        'target_model_optimum', targetOptimum, ...
        'objective_regret', totalObjective - targetOptimum, ...
        'relative_objective_regret', (totalObjective - targetOptimum) / ...
        max(1, abs(targetOptimum)), ...
        'positive_demand_scenario_count', positiveCount, ...
        'mean_total_demand_kg', meanDemand, ...
        'max_total_demand_kg', maxDemand, ...
        'aggregate_status', aggregate.status, 'period_status', period.status, ...
        'replay_complete', true, 'failure_message', "", 'case_pass', true);
    rows = append_struct(rows, row);
end
output = struct2table(rows);
end

function output = make_objective_table(stateId, R, aggregate, period)
rows = struct([]);
solutions = {aggregate, period};
names = ["AGGREGATE"; "PERIOD"];
for ii = 1:2
    sol = solutions{ii};
    row = struct('initial_state_id', stateId, 'R', R, 'model', names(ii), ...
        'TerminalLOH_cost', sol.holding_cost, ...
        'mean_service_cost', sol.mean_service_cost, ...
        'mean_shortage_kg', sol.mean_shortage_kg, ...
        'mean_shortage_loss', sol.mean_shortage_loss, ...
        'mean_operating_loss', sol.mean_operating_loss, ...
        'total_objective', sol.objective_value, ...
        'objective_reconstruction_error', sol.objective_reconstruction_error, ...
        'scenario_weight', 1 / R, 'scenario_weight_sum', 1, ...
        'solver_status', sol.status, 'case_pass', true);
    rows = append_struct(rows, row);
end
output = struct2table(rows);
end

function output = make_capacity_table(stateId, R, aggregate, period, Cap)
rows = struct([]);
solutions = {aggregate, period};
names = ["AGGREGATE"; "PERIOD"];
for model = 1:2
    sol = solutions{model};
    for site = 1:4
        row = struct('initial_state_id', stateId, 'R', R, ...
            'model', names(model), 'site_id', site, ...
            'TerminalLOH_kg', sol.T(site), 'capacity_upper_kg', Cap(site), ...
            'capacity_slack_kg', Cap(site) - sol.T(site), ...
            'at_capacity_upper', sol.T_at_upper_bound(site), ...
            'T_reduced_cost', sol.T_reduced_cost(site), ...
            'solver_status', sol.status, 'case_pass', true);
        rows = append_struct(rows, row);
    end
end
output = struct2table(rows);
end

function output = append_struct(existing, row)
if isempty(existing), output = row; else, output = [existing; row]; end
end

function paths = protected_paths()
paths = [ ...
    "results/task-002-stage2b-b3-smoke/16-dac-transport-cost-audit/run-001"; ...
    "results/task-002-stage2b-b3-smoke/23-fixed-decision-loss-consistency/run-001.failed-001"; ...
    "results/task-002-stage2b-b3-smoke/24-old-vs-ctilde-fixed-loss"; ...
    "results/task-002-stage2b-b3-smoke/25-old-cost-evidence-trace"; ...
    "results/task-002-stage2b-b3-smoke/26-old-ground-cost-recompute"; ...
    "results/task-002-stage2b-b3-smoke/27-period-data-recoverability/run-001.failed-001"; ...
    "results/task-002-stage2b-b3-smoke/27-period-data-recoverability/run-002/recovered_period_data.mat"; ...
    "results/task-002-stage2b-b3-smoke/30-period-lp-equivalence-audit"; ...
    "results/task-002-stage2b-b3-smoke/31-period-vs-aggregate-terminalLOH"; ...
    "results/task-002-stage2b-b3-smoke/32-saa-weight-capacity-audit"; ...
    "results/task-002-stage2b-b3-smoke/33-all-state-period-vs-aggregate-saa/run-001"; ...
    "results/task-002-stage2b-b3-smoke/34-period-vs-aggregate-saa-stability/run-001"; ...
    "terminalLoh_wdro/src/run_step03XB_old_ground_cost_recompute.py"; ...
    "terminalLoh_wdro/src/run_step03X_old_vs_ctilde_fixed_loss.py"; ...
    "terminalLoh_wdro/src/run_step03YBB_period_lp_equivalence_audit_h2.m"; ...
    "terminalLoh_wdro/src/run_step03YC_period_vs_aggregate_terminalLOH_h2.m"; ...
    "terminalLoh_wdro/src/run_step03YCA_saa_weight_capacity_audit_h2.m"; ...
    "terminalLoh_wdro/src/run_step03YE_period_vs_aggregate_saa_stability_h2.m"];
end

function bytes = memory_snapshot()
try
    process = System.Diagnostics.Process.GetCurrentProcess();
    bytes = double(process.WorkingSet64);
catch
    info = memory;
    bytes = double(info.MemUsedMATLAB);
end
end

function digest = path_digest(path)
if isfile(path), digest = sha256_file(path); return; end
if ~isfolder(path), digest = "MISSING"; return; end
files = dir(fullfile(path, '**', '*')); files = files(~[files.isdir]);
relative = strings(numel(files), 1);
for ii = 1:numel(files)
    fullName = fullfile(files(ii).folder, files(ii).name);
    relative(ii) = string(erase(fullName, [char(path), filesep]));
end
[relative, order] = sort(relative); files = files(order);
md = java.security.MessageDigest.getInstance('SHA-256');
for ii = 1:numel(files)
    fullName = fullfile(files(ii).folder, files(ii).name);
    token = relative(ii) + "|" + string(files(ii).bytes) + "|" + ...
        sha256_file(fullName) + newline;
    md.update(typecast(unicode2native(char(token), 'UTF-8'), 'int8'));
end
raw = typecast(md.digest(), 'uint8');
digest = lower(string(reshape(dec2hex(raw, 2).', 1, [])));
end

function hash = sha256_file(fileName)
fid = fopen(fileName, 'rb');
if fid < 0, error('Cannot open protected file.'); end
cleanup = onCleanup(@() fclose(fid));
md = java.security.MessageDigest.getInstance('SHA-256');
while true
    bytes = fread(fid, 1024 * 1024, '*uint8');
    if isempty(bytes), break; end
    md.update(typecast(bytes, 'int8'));
end
raw = typecast(md.digest(), 'uint8');
hash = lower(string(reshape(dec2hex(raw, 2).', 1, [])));
clear cleanup;
end

function write_lines(fileName, lines)
fid = fopen(fileName, 'w');
if fid < 0, error('Cannot write audit output.'); end
cleanup = onCleanup(@() fclose(fid));
for ii = 1:numel(lines), fprintf(fid, '%s\n', lines(ii)); end
clear cleanup;
end
