%% Step-03Y-B: compare frozen aggregate Q with fixed-T three-period Q.
clear; clc;
started = tic;
thisFile = mfilename('fullpath'); thisDir = fileparts(thisFile);
moduleDir = fileparts(thisDir); rootDir = fileparts(moduleDir);
addpath(rootDir); addpath(thisDir);
addpath(fullfile(rootDir, 'fa_h2', 'fuzhu', 'terminalLoh_windmc'));

expectedBranch = "task/002-stage2b-b3-smoke";
expectedHead = "2ae3d68a52c044086f37d21fd264005e796e1c9e";
states = [7; 11; 18; 21; 30; 31]; rowsPerState = 15000;
baseSeed = 20260723; windSeedOffset = 330000000;
demandToleranceKg = 1e-10; numericalTolerance = 1e-8;
largeDifferenceThreshold = 0.10; runName = "run-001";
outputDir = fullfile(rootDir, 'results', 'task-002-stage2b-b3-smoke', ...
    '28-period-vs-aggregate-loss', runName);
tempDir = outputDir + ".tmp";
if isfolder(outputDir) || isfolder(tempDir), error('Step-03Y-B output path exists.'); end

[~, branch] = system('git branch --show-current');
[~, head] = system('git rev-parse HEAD');
[~, upstream] = system('git rev-parse "@{upstream}"');
branch = string(strtrim(branch)); head = string(strtrim(head));
upstream = string(strtrim(upstream));
if branch ~= expectedBranch || head ~= expectedHead || upstream ~= expectedHead
    error('Frozen Git baseline mismatch.');
end
[status, trackedDiff] = system('git status --porcelain --untracked-files=no');
if status ~= 0 || strlength(strtrim(string(trackedDiff))) > 0
    error('Tracked or staged worktree changes are present.');
end

protectedRelative = [ ...
    "results/task-002-stage2b-b3-smoke/16-dac-transport-cost-audit/run-001"; ...
    "results/task-002-stage2b-b3-smoke/23-fixed-decision-loss-consistency/run-001.failed-001"; ...
    "results/task-002-stage2b-b3-smoke/24-old-vs-ctilde-fixed-loss"; ...
    "results/task-002-stage2b-b3-smoke/25-old-cost-evidence-trace"; ...
    "results/task-002-stage2b-b3-smoke/26-old-ground-cost-recompute"; ...
    "results/task-002-stage2b-b3-smoke/27-period-data-recoverability"; ...
    "terminalLoh_wdro/src/run_step03XB_old_ground_cost_recompute.py"; ...
    "terminalLoh_wdro/src/run_step03X_old_vs_ctilde_fixed_loss.py"; ...
    "terminalLoh_wdro/src/run_step03YA_period_data_recoverability_h2.m"];
protectedBefore = strings(numel(protectedRelative), 1);
for ii = 1:numel(protectedRelative)
    protectedBefore(ii) = path_digest(fullfile(rootDir, protectedRelative(ii)));
    if protectedBefore(ii) == "MISSING", error('Protected path missing.'); end
end

config = build_config(rootDir, moduleDir, thisDir);
inputs = [string(config.pairFile); string(config.mainSampleFile); ...
    string(config.nominalCsv); string(config.nominalMat); ...
    string(config.seedMapFile); string(config.nearInputFile); ...
    string(config.formalWindConfigFile); string(config.warningSolutionFile); ...
    string(config.locCoordinateFile); string(config.roadEdgeFile); ...
    string(config.siteNodeFile); string(config.stepYAReadme); ...
    string(config.stepYAAudit); ...
    string(fullfile(thisDir, 'evaluate_step03T_fixed_T_recourse_h2.m')); ...
    string(fullfile(thisDir, 'evaluate_step03Y_period_fixed_T_recourse_h2.m'))];
for ii = 1:numel(inputs)
    if ~isfile(inputs(ii)), error('Required input missing: %s', inputs(ii)); end
end
inputBefore = strings(numel(inputs), 1);
for ii = 1:numel(inputs), inputBefore(ii) = sha256_file(inputs(ii)); end
if inputBefore(1) ~= "39717c789739a112c7af651a733df1475a58b9905d08bd8773bc242b82d6baa7" || ...
        inputBefore(2) ~= "972a8c58620c09ac19cfcfb29e8d6a3ed2819ef1a22dbd522043436418eb805d" || ...
        inputBefore(3) ~= "366dc3c0b57bfd76aca92f51ae1db82b93c764c87fa15e8cb4dd32388d018168" || ...
        inputBefore(4) ~= "6936a696f5cde137aca483f8c32adee33b52cbd90559a8e6395f3686c0712945"
    error('Frozen Step-03W/Step-03J input SHA-256 mismatch.');
end
if ~contains(fileread(config.stepYAAudit), 'status=PASS') || ...
        ~contains(fileread(config.stepYAAudit), ...
        'conclusion=B. PERIOD_DATA_DETERMINISTICALLY_RECOVERABLE')
    error('Step-03Y-A run-002 is not an accepted recovery input.');
end

rawNear = load(config.nearInputFile, 'NearStageInput');
ni = rawNear.NearStageInput;
if isfield(ni.Cost, 'reserve_shortage_penalty_yuan_per_kg')
    M = double(ni.Cost.reserve_shortage_penalty_yuan_per_kg);
elseif isfield(ni.Cost, 'cost_reserve_shortage')
    M = double(ni.Cost.cost_reserve_shortage);
else
    error('Cannot trace the frozen shortage penalty.');
end
if abs(M - 2000) > 1e-12, error('Frozen shortage penalty changed.'); end

% Mechanical LP tests run before the frozen-scenario comparison.
[mechanicalTests, testSolverCalls] = run_mechanical_tests(M, numericalTolerance);
if any(~mechanicalTests.passed)
    error('Step-03Y-B period-LP mechanical tests failed.');
end

pairs = readtable(config.pairFile, 'TextType', 'string');
if height(pairs) ~= 36 || ~isequal(sort(unique(double(pairs.initial_state_id))), states)
    error('Expected 36 frozen Step-03W pairs over the six requested states.');
end
request = table([double(pairs.initial_state_id); double(pairs.initial_state_id)], ...
    [double(pairs.scenario_r); double(pairs.scenario_s)], ...
    [double(pairs.path_id_r); double(pairs.path_id_s)], ...
    'VariableNames', {'initial_state_id', 'scenario_id', 'path_id'});
request = sortrows(unique(request, 'rows'), {'initial_state_id', 'scenario_id'});

nominalOptions = detectImportOptions(config.nominalCsv);
nominalOptions = setvartype(nominalOptions, 'initial_state', 'string');
nominal = readtable(config.nominalCsv, nominalOptions);
mainSample = readtable(config.mainSampleFile);
seedMap = readtable(config.seedMapFile, 'TextType', 'string');
seedMap = seedMap(seedMap.dataset_role == "nominal" & ...
    ismember(double(seedMap.initial_state_id), states), :);
windConfig = load_formal_b3_wind_config_h2(config.formalWindConfigFile);
model = build_replay_model(config, rawNear.NearStageInput);
[recovered, recoveryAudit] = recover_requested_scenarios(request, nominal, ...
    mainSample, seedMap, windConfig, model, config, baseSeed, ...
    windSeedOffset, rowsPerState, demandToleranceKg);
if ~recoveryAudit.all_final_DAC_exact || ~recoveryAudit.all_stream_hashes_match
    error('Step-03Y-B scenario recovery failed.');
end

evaluationCount = 4 * height(pairs);
Dperiod = zeros(evaluationCount, 3, model.nNodes);
Aperiod = false(evaluationCount, 3, model.nSites, model.nNodes);
Cperiod = inf(evaluationCount, 3, model.nSites, model.nNodes);
Trows = zeros(evaluationCount, model.nSites);
evalRows = cell(evaluationCount, 15); er = 0;
for pp = 1:height(pairs)
    stateId = double(pairs.initial_state_id(pp));
    r = double(pairs.scenario_r(pp)); s = double(pairs.scenario_s(pp));
    ir = find(recovered.identity.initial_state_id == stateId & ...
        recovered.identity.scenario_id == r, 1);
    is = find(recovered.identity.initial_state_id == stateId & ...
        recovered.identity.scenario_id == s, 1);
    if isempty(ir) || isempty(is), error('Recovered pair endpoint missing.'); end
    Tr = double([pairs.T_r1(pp), pairs.T_r2(pp), pairs.T_r3(pp), pairs.T_r4(pp)]);
    Ts = double([pairs.T_s1(pp), pairs.T_s2(pp), pairs.T_s3(pp), pairs.T_s4(pp)]);
    sceneIndices = [ir, is, ir, is]; labels = ["T_R_ON_R", "T_R_ON_S", "T_S_ON_R", "T_S_ON_S"];
    layouts = [Tr; Tr; Ts; Ts]; qAgg = double([pairs.Q_Tr_xi_r(pp); ...
        pairs.Q_Tr_xi_s(pp); pairs.Q_Ts_xi_r(pp); pairs.Q_Ts_xi_s(pp)]);
    scenarioRoles = ["xi_r"; "xi_s"; "xi_r"; "xi_s"];
    layoutSources = ["T_r"; "T_r"; "T_s"; "T_s"];
    for kk = 1:4
        er = er + 1; idx = sceneIndices(kk);
        Dperiod(er, :, :) = recovered.Dperiod(idx, :, :);
        Aperiod(er, :, :, :) = recovered.Aperiod(idx, :, :, :);
        Cperiod(er, :, :, :) = recovered.Cperiod(idx, :, :, :);
        Trows(er, :) = layouts(kk, :);
        evalRows(er, :) = {er, double(pairs.evaluation_pair_id(pp)), ...
            string(pairs.pair_group(pp)), stateId, recovered.identity.scenario_id(idx), ...
            recovered.identity.path_id(idx), scenarioRoles(kk), layoutSources(kk), ...
            labels(kk), qAgg(kk), layouts(kk, 1), layouts(kk, 2), ...
            layouts(kk, 3), layouts(kk, 4), idx};
    end
end
evaluationIdentity = cell2table(evalRows, 'VariableNames', ...
    {'evaluation_id', 'pair_id', 'pair_group', 'initial_state_id', ...
    'scenario_id', 'path_id', 'scenario_role', 'T_source', 'replay_case', ...
    'Q_agg', 'T1', 'T2', 'T3', 'T4', 'recovered_index'});

periodConfig = struct('gurobiOutputFlag', 0, 'gurobiFeasibilityTol', 1e-9, ...
    'gurobiOptimalityTol', 1e-9, 'gurobiTimeLimit', 300, 'objectiveScale', 1);
periodResult = evaluate_step03Y_period_fixed_T_recourse_h2( ...
    Dperiod, Aperiod, Cperiod, Trows, M, periodConfig);
mainSolverCalls = 1;
if periodResult.exitflag ~= 1 || periodResult.status ~= "OPTIMAL"
    error('Main fixed-T period LP batch was not OPTIMAL.');
end

scenarioRows = cell(evaluationCount, 39);
for rr = 1:evaluationCount
    idx = evaluationIdentity.recovered_index(rr);
    Dp = squeeze(recovered.Dperiod(idx, :, :));
    Ap = squeeze(recovered.Aperiod(idx, :, :, :));
    Cp = squeeze(recovered.Cperiod(idx, :, :, :));
    Aagg = squeeze(recovered.Aagg(idx, :, :));
    y = squeeze(periodResult.y(rr, :, :, :));
    criticalRelation = false(size(Ap));
    for tau = 1:3
        criticalRelation(tau, :, :) = repmat( ...
            reshape(Dp(tau, :) > demandToleranceKg, [1, 1, model.nNodes]), ...
            [1, model.nSites, 1]);
    end
    aggFalse = repmat(reshape(~Aagg, [1, model.nSites, model.nNodes]), 3, 1, 1);
    maskedReach = Ap & aggFalse & criticalRelation;
    serviceOnMasked = sum(y(maskedReach));
    costOnMasked = sum(Cp(maskedReach) .* y(maskedReach));
    maskedRelationCount = sum(maskedReach, 'all');
    maskedDemand = 0;
    for tau = 1:3
        for nn = 1:model.nNodes
            if Dp(tau, nn) > demandToleranceKg && any(Ap(tau, :, nn), 'all') && ...
                    ~any(Aagg(:, nn))
                maskedDemand = maskedDemand + Dp(tau, nn);
            end
        end
    end
    brokenPairs = 0;
    for nn = 1:model.nNodes
        critical = find(Dp(:, nn) > demandToleranceKg);
        if isempty(critical), critical = (1:3).'; end
        for ii = 1:model.nSites
            pattern = squeeze(Ap(critical, ii, nn));
            brokenPairs = brokenPairs + double(any(pattern) && ~all(pattern));
        end
    end
    qAgg = evaluationIdentity.Q_agg(rr); qPeriod = periodResult.operating_loss(rr);
    signed = qPeriod - qAgg; absDiff = abs(signed);
    relative = absDiff / max([1, abs(qAgg), abs(qPeriod)]);
    if qAgg > qPeriod + numericalTolerance
        direction = "AGGREGATE_OVERESTIMATES";
    elseif qPeriod > qAgg + numericalTolerance
        direction = "AGGREGATE_UNDERESTIMATES";
    else
        direction = "NUMERICALLY_EQUAL";
    end
    scenarioRows(rr, :) = {evaluationIdentity.evaluation_id(rr), ...
        evaluationIdentity.pair_id(rr), evaluationIdentity.pair_group(rr), ...
        evaluationIdentity.initial_state_id(rr), evaluationIdentity.scenario_id(rr), ...
        evaluationIdentity.path_id(rr), evaluationIdentity.scenario_role(rr), ...
        evaluationIdentity.T_source(rr), evaluationIdentity.replay_case(rr), ...
        evaluationIdentity.T1(rr), evaluationIdentity.T2(rr), ...
        evaluationIdentity.T3(rr), evaluationIdentity.T4(rr), qAgg, qPeriod, ...
        signed, absDiff, relative, relative >= largeDifferenceThreshold, direction, ...
        periodResult.service_cost(rr), periodResult.shortage_kg(rr), ...
        periodResult.shortage_loss(rr), periodResult.stage_service_kg(rr, 1), ...
        periodResult.stage_service_kg(rr, 2), periodResult.stage_service_kg(rr, 3), ...
        periodResult.stage_shortage_kg(rr, 1), periodResult.stage_shortage_kg(rr, 2), ...
        periodResult.stage_shortage_kg(rr, 3), periodResult.stage_service_cost(rr, 1), ...
        periodResult.stage_service_cost(rr, 2), periodResult.stage_service_cost(rr, 3), ...
        maskedRelationCount, brokenPairs, maskedDemand, serviceOnMasked, ...
        costOnMasked, serviceOnMasked > numericalTolerance, ...
        relative >= largeDifferenceThreshold && serviceOnMasked > numericalTolerance};
end
scenarioLoss = cell2table(scenarioRows, 'VariableNames', ...
    {'evaluation_id', 'pair_id', 'pair_group', 'initial_state_id', ...
    'scenario_id', 'path_id', 'scenario_role', 'T_source', 'replay_case', ...
    'T1', 'T2', 'T3', 'T4', 'Q_agg', 'Q_period', ...
    'Q_period_minus_Q_agg', 'absolute_difference', 'relative_difference', ...
    'relative_difference_ge_10pct', 'direction', 'period_service_cost', ...
    'period_shortage_kg', 'period_shortage_loss', 'W1_service_kg', ...
    'W2_service_kg', 'W3_service_kg', 'W1_shortage_kg', 'W2_shortage_kg', ...
    'W3_shortage_kg', 'W1_service_cost', 'W2_service_cost', ...
    'W3_service_cost', 'period_reachable_agg_masked_relation_count', ...
    'partially_reachable_critical_site_node_count', ...
    'period_reachable_but_agg_node_unreachable_demand_kg', ...
    'period_service_on_agg_unreachable_relations_kg', ...
    'period_service_cost_on_agg_unreachable_relations', ...
    'temporal_masking_used_by_solution', 'large_difference_with_temporal_masking'});

pairRows = cell(height(pairs), 21);
for pp = 1:height(pairs)
    local = scenarioLoss(scenarioLoss.pair_id == double(pairs.evaluation_pair_id(pp)), :);
    trR = local(local.replay_case == "T_R_ON_R", :);
    trS = local(local.replay_case == "T_R_ON_S", :);
    tsR = local(local.replay_case == "T_S_ON_R", :);
    tsS = local(local.replay_case == "T_S_ON_S", :);
    dAggTr = abs(trR.Q_agg - trS.Q_agg); dPeriodTr = abs(trR.Q_period - trS.Q_period);
    dAggTs = abs(tsR.Q_agg - tsS.Q_agg); dPeriodTs = abs(tsR.Q_period - tsS.Q_period);
    relTr = abs(dPeriodTr - dAggTr) / max([1, dPeriodTr, dAggTr]);
    relTs = abs(dPeriodTs - dAggTs) / max([1, dPeriodTs, dAggTs]);
    pairRows(pp, :) = {double(pairs.evaluation_pair_id(pp)), string(pairs.pair_group(pp)), ...
        double(pairs.initial_state_id(pp)), double(pairs.scenario_r(pp)), ...
        double(pairs.scenario_s(pp)), double(pairs.path_id_r(pp)), ...
        double(pairs.path_id_s(pp)), dAggTr, dPeriodTr, dPeriodTr - dAggTr, ...
        relTr, relTr >= largeDifferenceThreshold, dAggTs, dPeriodTs, ...
        dPeriodTs - dAggTs, relTs, relTs >= largeDifferenceThreshold, ...
        max(dAggTr, dAggTs), max(dPeriodTr, dPeriodTs), ...
        max(relTr, relTs), any(local.temporal_masking_used_by_solution)};
end
pairLoss = cell2table(pairRows, 'VariableNames', ...
    {'pair_id', 'pair_group', 'initial_state_id', 'scenario_r', 'scenario_s', ...
    'path_id_r', 'path_id_s', 'DeltaQ_agg_Tr', 'DeltaQ_period_Tr', ...
    'DeltaQ_period_minus_agg_Tr', 'relative_gap_change_Tr', ...
    'relative_gap_change_Tr_ge_10pct', 'DeltaQ_agg_Ts', 'DeltaQ_period_Ts', ...
    'DeltaQ_period_minus_agg_Ts', 'relative_gap_change_Ts', ...
    'relative_gap_change_Ts_ge_10pct', 'max_DeltaQ_agg', ...
    'max_DeltaQ_period', 'max_relative_gap_change', ...
    'any_temporal_masking_used_by_solution'});

stateRows = cell(numel(states), 20);
for ss = 1:numel(states)
    stateId = states(ss); local = scenarioLoss(scenarioLoss.initial_state_id == stateId, :);
    localPair = pairLoss(pairLoss.initial_state_id == stateId, :);
    over = local.direction == "AGGREGATE_OVERESTIMATES";
    under = local.direction == "AGGREGATE_UNDERESTIMATES";
    large = local.relative_difference_ge_10pct;
    stateRows(ss, :) = {stateId, height(local), mean(local.Q_agg), mean(local.Q_period), ...
        mean(local.Q_period_minus_Q_agg), median(local.absolute_difference), ...
        qvalue(local.absolute_difference, 0.90), max(local.absolute_difference), ...
        median(local.relative_difference), qvalue(local.relative_difference, 0.90), ...
        max(local.relative_difference), sum(large), mean(large), sum(over), ...
        sum(under), sum(local.direction == "NUMERICALLY_EQUAL"), ...
        sum(large & local.temporal_masking_used_by_solution), ...
        mean(local.period_service_on_agg_unreachable_relations_kg), ...
        mean(localPair.max_relative_gap_change), ...
        sum(localPair.max_relative_gap_change >= largeDifferenceThreshold)};
end
stateSummary = cell2table(stateRows, 'VariableNames', ...
    {'initial_state_id', 'evaluation_count', 'Q_agg_mean', 'Q_period_mean', ...
    'signed_difference_mean', 'absolute_difference_median', ...
    'absolute_difference_q90', 'absolute_difference_max', ...
    'relative_difference_median', 'relative_difference_q90', ...
    'relative_difference_max', 'relative_difference_ge_10pct_count', ...
    'relative_difference_ge_10pct_share', 'aggregate_overestimate_count', ...
    'aggregate_underestimate_count', 'numerically_equal_count', ...
    'large_difference_with_temporal_masking_count', ...
    'period_service_on_agg_unreachable_mean_kg', ...
    'pair_gap_relative_change_mean', 'pair_gap_change_ge_10pct_count'});

largeMask = scenarioLoss.relative_difference_ge_10pct;
largeCount = sum(largeMask); largeShare = mean(largeMask);
overCount = sum(scenarioLoss.direction == "AGGREGATE_OVERESTIMATES");
underCount = sum(scenarioLoss.direction == "AGGREGATE_UNDERESTIMATES");
equalCount = sum(scenarioLoss.direction == "NUMERICALLY_EQUAL");
maskingLargeCount = sum(largeMask & scenarioLoss.temporal_masking_used_by_solution);
maskingLargeShare = maskingLargeCount / max(largeCount, 1);
pairChanged = sum(pairLoss.max_relative_gap_change >= largeDifferenceThreshold);
if largeShare <= 0.10
    closenessText = "Aggregate and period losses are generally close under the 10% diagnostic.";
else
    closenessText = "Aggregate and period losses are not generally close under the 10% diagnostic.";
end
if overCount > underCount
    directionText = "The aggregate model generally overestimates operating loss.";
elseif underCount > overCount
    directionText = "The aggregate model generally underestimates operating loss.";
else
    directionText = "The aggregate model has no dominant signed direction.";
end
if maskingLargeShare >= 0.50
    sourceText = "Temporal reachability compression is an important source of the observed loss differences.";
else
    sourceText = "Temporal reachability compression does not explain a majority of large differences in this audit.";
end
worthFurther = largeShare > 0.10 || pairChanged > 0;
if worthFurther
    nextText = "A small fixed-sample TerminalLOH comparison is worth performing.";
else
    nextText = "The current evidence does not require a TerminalLOH comparison.";
end

mkdir(tempDir);
writetable(scenarioLoss, fullfile(tempDir, 'scenario_loss_comparison.csv'));
writetable(pairLoss, fullfile(tempDir, 'pair_loss_comparison.csv'));
writetable(stateSummary, fullfile(tempDir, 'state_summary.csv'));
writetable(mechanicalTests, fullfile(tempDir, 'mechanical_tests.csv'));
writetable(recovered.identity, fullfile(tempDir, 'recovered_scenario_audit.csv'));

protectedAfter = strings(numel(protectedRelative), 1);
for ii = 1:numel(protectedRelative)
    protectedAfter(ii) = path_digest(fullfile(rootDir, protectedRelative(ii)));
end
inputAfter = strings(numel(inputs), 1);
for ii = 1:numel(inputs), inputAfter(ii) = sha256_file(inputs(ii)); end
solverCallCount = testSolverCalls + mainSolverCalls;
checks = { ...
    "branch_matches_frozen", branch == expectedBranch, branch; ...
    "local_HEAD_matches_frozen", head == expectedHead, head; ...
    "upstream_matches_frozen", upstream == expectedHead, upstream; ...
    "tracked_worktree_clean", strlength(strtrim(string(trackedDiff))) == 0, strtrim(string(trackedDiff)); ...
    "Step03YA_run002_PASS", true, "B.PERIOD_DATA_DETERMINISTICALLY_RECOVERABLE"; ...
    "mechanical_tests_pass", all(mechanicalTests.passed), string(sum(mechanicalTests.passed)); ...
    "six_states_only", isequal(sort(unique(recovered.identity.initial_state_id)), states), mat2str(sort(unique(recovered.identity.initial_state_id)).'); ...
    "frozen_pair_count_36", height(pairs) == 36, string(height(pairs)); ...
    "fixed_T_evaluation_count_144", height(scenarioLoss) == 144, string(height(scenarioLoss)); ...
    "recovered_final_DAC_exact", recoveryAudit.all_final_DAC_exact, string(recoveryAudit.max_DAC_error); ...
    "random_stream_hashes_match", recoveryAudit.all_stream_hashes_match, string(recoveryAudit.stream_match_count); ...
    "all_period_LPs_OPTIMAL", periodResult.exitflag == 1 && periodResult.status == "OPTIMAL", periodResult.status; ...
    "period_demand_balance", periodResult.max_demand_balance_error <= numericalTolerance, string(periodResult.max_demand_balance_error); ...
    "period_cumulative_T_capacity", periodResult.max_site_capacity_violation <= numericalTolerance, string(periodResult.max_site_capacity_violation); ...
    "no_T_optimization_variables", true, "T supplied as RHS only"; ...
    "Q_agg_reused_not_resolved", true, "Step03W frozen columns"; ...
    "input_files_unchanged", isequal(inputBefore, inputAfter), string(sum(inputBefore == inputAfter)); ...
    "protected_untracked_paths_unchanged", isequal(protectedBefore, protectedAfter), string(sum(protectedBefore == protectedAfter)); ...
    "validation_file_count_zero", true, "0"; ...
    "WDRO_call_count_zero", true, "0"; ...
    "MSP_call_count_zero", true, "0"; ...
    "solver_calls_within_allowed_scope", solverCallCount == 5, string(solverCallCount)};
allPass = all(cell2mat(checks(:, 2)));
auditLines = ["Step-03Y-B mechanical audit"; ...
    "status=" + string(ternary(allPass, 'PASS', 'FAIL')); ...
    "solver_call_count=" + string(solverCallCount); ...
    "gurobi_call_count=" + string(solverCallCount); ...
    "wdro_call_count=0"; "msp_call_count=0"; ...
    "validation_file_count=0"; ...
    "fixed_T_period_evaluation_count=144"; ...
    ""; "Checks:"];
for ii = 1:size(checks, 1)
    auditLines(end + 1) = string(checks{ii, 1}) + "|" + ...
        string(ternary(checks{ii, 2}, 'PASS', 'FAIL')) + ...
        "|observed=" + string(checks{ii, 3}); %#ok<SAGROW>
end
write_lines(fullfile(tempDir, 'mechanical_audit.txt'), auditLines);

conclusionLines = [ ...
    "1. " + closenessText; ...
    "2. " + directionText; ...
    "3. " + sourceText; ...
    "4. " + nextText; ...
    "large_relative_difference_count=" + string(largeCount) + "/144"; ...
    "aggregate_overestimate_count=" + string(overCount); ...
    "aggregate_underestimate_count=" + string(underCount); ...
    "numerically_equal_count=" + string(equalCount); ...
    "large_difference_temporal_masking_count=" + string(maskingLargeCount); ...
    "pair_gap_change_ge_10pct_count=" + string(pairChanged) + "/36"];
write_lines(fullfile(tempDir, 'conclusion.txt'), conclusionLines);

readmeLines = [ ...
    "# Step-03Y-B period versus aggregate operating-loss audit"; ""; ...
    "## Scope"; ""; ...
    "The audit uses only the 36 frozen Step-03W pairs, their fixed T_r/T_s layouts, frozen aggregate operating losses, and deterministic Step-03Y-A recovery of the pair endpoints. It does not optimize TerminalLOH or compute a distance."; ""; ...
    "## Period model"; ""; ...
    "Each W1/W2/W3 demand is balanced separately by period service and period shortage. Period reachTau controls service feasibility and costTau is the service coefficient. For each site, service summed over all three periods and all nodes is bounded by the supplied fixed TerminalLOH. There is no advance service and no shortage carryover. Operating loss remains service cost plus M times shortage, with M=" + string(M) + "."; ""; ...
    "## Mechanical tests"; ""; ...
    "All required tests pass: T=0 produces shortage equal to total three-period demand; identical period A/C reproduces the static total-demand LP; reachability (1,1,0) serves periods 1 and 2 and forbids period 3; period-3 unreachability does not remove the first two periods' service cost."; ""; ...
    "## Results"; ""; ...
    "- Fixed-T evaluations: 144 from 36 pairs."; ...
    "- Relative difference >=10%: " + string(largeCount) + "/144 (" + string(sprintf('%.6f', largeShare)) + ")."; ...
    "- Aggregate overestimate/underestimate/equal: " + string(overCount) + "/" + string(underCount) + "/" + string(equalCount) + "."; ...
    "- Large differences using service relations hidden by aggregate A/C: " + string(maskingLargeCount) + "/" + string(largeCount) + "."; ...
    "- Pair loss-gap changes >=10%: " + string(pairChanged) + "/36."; ""; ...
    "## Interpretation"; ""; ...
    closenessText; directionText; sourceText; nextText; ""; ...
    "## Boundaries"; ""; ...
    "Only five Gurobi invocations were made: four small mechanical-test calls and one block-diagonal batch of 144 independent fixed-T period LPs. No T variable, WDRO, MSP, validation input, new scenario, Q_agg recomputation, or formal-model modification was used. Existing untracked paths were hash-checked and unchanged."; ""; ...
    "runtime_sec=" + string(sprintf('%.6f', toc(started)))];
write_lines(fullfile(tempDir, 'README.md'), readmeLines);

if ~allPass, error('Step-03Y-B mechanical audit failed; temporary output retained.'); end
movefile(tempDir, outputDir);
fprintf('Step-03Y-B PASS. Output: %s\n', outputDir);
fprintf('large_difference=%d/144 over=%d under=%d equal=%d pair_changed=%d/36\n', ...
    largeCount, overCount, underCount, equalCount, pairChanged);
fprintf('solver_call_count=%d validation_file_count=0 runtime=%.6f s\n', ...
    solverCallCount, toc(started));

function [tests, calls] = run_mechanical_tests(M, tol)
cfg = struct('gurobiOutputFlag', 0, 'gurobiFeasibilityTol', 1e-9, ...
    'gurobiOptimalityTol', 1e-9, 'gurobiTimeLimit', 300, 'objectiveScale', 1);
rows = cell(4, 5); calls = 0;
D = reshape([2, 1, 3, 4, 1, 2], [1, 3, 2]);
A = true(1, 3, 2, 2); C = ones(1, 3, 2, 2); T = zeros(1, 2);
o = evaluate_step03Y_period_fixed_T_recourse_h2(D, A, C, T, M, cfg); calls = calls + 1;
expected = sum(D, 'all'); pass = o.status == "OPTIMAL" && ...
    abs(o.shortage_kg - expected) <= tol && abs(o.operating_loss - M * expected) <= tol;
rows(1, :) = {"T_ZERO_SHORTAGE_EQUALS_TOTAL_DEMAND", pass, o.shortage_kg, expected, "period fixed-T LP"};

D = reshape([2, 1, 1, 2, 3, 0], [1, 3, 2]);
A = true(1, 3, 2, 2); C = zeros(1, 3, 2, 2);
C(1, :, 1, :) = repmat(reshape([1, 3], [1, 1, 1, 2]), 1, 3, 1, 1);
C(1, :, 2, :) = repmat(reshape([2, 1], [1, 1, 1, 2]), 1, 3, 1, 1);
T = [3, 2]; op = evaluate_step03Y_period_fixed_T_recourse_h2(D, A, C, T, M, cfg); calls = calls + 1;
Dstatic = reshape(sum(D, 2), [1, 2]); Astatic = squeeze(A(1, 1, :, :));
Cstatic = squeeze(C(1, 1, :, :));
os = evaluate_step03T_fixed_T_recourse_h2(Dstatic, reshape(Astatic, [1, 2, 2]), ...
    reshape(Cstatic, [1, 2, 2]), T, M, cfg); calls = calls + 1;
pass = op.status == "OPTIMAL" && os.status == "OPTIMAL" && ...
    abs(op.operating_loss - os.operating_loss) <= tol;
rows(2, :) = {"IDENTICAL_PERIOD_AC_EQUALS_STATIC_TOTAL_MODEL", pass, ...
    op.operating_loss, os.operating_loss, "period LP versus existing static fixed-T LP"};

D = ones(1, 3, 1); A = reshape([1, 1, 0], [1, 3, 1, 1]);
C = reshape([2, 2, Inf], [1, 3, 1, 1]); T = 3;
o = evaluate_step03Y_period_fixed_T_recourse_h2(D, A, C, T, M, cfg); calls = calls + 1;
pass = o.status == "OPTIMAL" && max(abs(o.stage_service_kg - [1, 1, 0])) <= tol && ...
    max(abs(o.stage_shortage_kg - [0, 0, 1])) <= tol;
rows(3, :) = {"REACH_SEQUENCE_110_SERVES_ONLY_FIRST_TWO", pass, ...
    string(mat2str(o.stage_service_kg, 12)), "[1 1 0]", "one site and one node"};
pass = abs(o.service_cost - 4) <= tol && abs(o.operating_loss - (4 + M)) <= tol;
rows(4, :) = {"THIRD_PERIOD_UNREACHABLE_RETAINS_PRIOR_COST", pass, ...
    o.service_cost, 4, "cost 2 in each of periods 1 and 2"};
tests = cell2table(rows, 'VariableNames', ...
    {'test_name', 'passed', 'observed', 'expected', 'note'});
end

function [recovered, audit] = recover_requested_scenarios(request, nominal, ...
        mainSample, seedMap, windConfig, model, config, baseSeed, ...
        windSeedOffset, rowsPerState, demandToleranceKg)
R = height(request); Dperiod = zeros(R, 3, model.nNodes);
Aperiod = false(R, 3, model.nSites, model.nNodes);
Cperiod = inf(R, 3, model.nSites, model.nNodes);
AaggAll = false(R, model.nSites, model.nNodes);
CaggAll = inf(R, model.nSites, model.nNodes);
DaggAll = zeros(R, model.nNodes); identity = request;
identity.joint_stream_position = zeros(R, 1);
identity.wind_seed = zeros(R, 1); identity.resistance_seed = zeros(R, 1);
identity.final_D_exact = false(R, 1); identity.final_A_exact = false(R, 1);
identity.final_C_exact = false(R, 1); identity.max_DAC_error = inf(R, 1);
streamMatches = 0; sidecar = matfile(config.nominalMat);
for ss = 1:numel(unique(request.initial_state_id))
    stateId = unique(request.initial_state_id); stateId = stateId(ss);
    meta = nominal(double(nominal.initial_state_id) == stateId, :);
    if height(meta) ~= rowsPerState, error('Nominal state block mismatch.'); end
    a0 = double(meta.a0(1)); loc0 = double(meta.loc0(1)); lfw0 = double(meta.lfw0(1));
    stateSample = mainSample(double(mainSample.a0) == a0 & ...
        double(mainSample.loc0) == loc0 & double(mainSample.lfw0) == lfw0, :);
    if height(stateSample) ~= rowsPerState, error('Main-sample state block mismatch.'); end
    resistanceSeed = baseSeed + 100003 * stateId;
    rng(resistanceSeed, 'twister'); permutation = randperm(rowsPerState).';
    lineU = rand(rowsPerState, model.nLines); roadU = rand(rowsPerState, model.nRoads);
    selected = stateSample(permutation, :);
    windSeed = windSeedOffset + baseSeed + 100019 * stateId;
    stream = RandStream('mt19937ar', 'Seed', windSeed); qAll = rand(stream, rowsPerState, 3);
    seedRow = seedMap(double(seedMap.initial_state_id) == stateId, :);
    streamPass = sha256_uint32(permutation) == string(seedRow.step3i_permutation_sha256) && ...
        sha256_double(qAll(:, 1)) == string(seedRow.q_W1_sha256) && ...
        sha256_double(qAll(:, 2)) == string(seedRow.q_W2_sha256) && ...
        sha256_double(qAll(:, 3)) == string(seedRow.q_W3_sha256);
    streamMatches = streamMatches + double(streamPass);
    if ~streamPass, error('Random-stream hash mismatch.'); end
    localIdx = find(request.initial_state_id == stateId);
    for jj = 1:numel(localIdx)
        rr = localIdx(jj); scenarioId = request.scenario_id(rr);
        row = meta(double(meta.scenario_id_in_state) == scenarioId, :);
        if height(row) ~= 1 || double(row.path_id) ~= request.path_id(rr)
            error('Frozen scenario identity mismatch.');
        end
        pos = double(row.joint_stream_position); sample = selected(pos, :);
        if double(sample.path_id) ~= request.path_id(rr), error('Stream mapping mismatch.'); end
        aStage = double([sample.a_W1, sample.a_W2, sample.a_W3]);
        locStage = double([sample.loc_W1, sample.loc_W2, sample.loc_W3]);
        lfwStage = double([sample.lfw_W1, sample.lfw_W2, sample.lfw_W3]);
        pFail = cell(3, 1); pClose = cell(3, 1);
        for tau = 1:3
            vmax = triangular_by_level(aStage(tau), qAll(pos, tau), ...
                windConfig.randomLower, windConfig.randomMode, windConfig.randomUpper);
            idx = state_index(model, aStage(tau), locStage(tau), lfwStage(tau));
            pFail{tau} = compute_line_failure_prob_h2(model.lineFactor(idx, :) .* vmax, model.designWindSpeedVN);
            pClose{tau} = compute_line_failure_prob_h2(model.roadFactor(idx, :) .* vmax, model.roadDesignWindVN);
        end
        failed = false(3, model.nLines); closed = false(3, model.nRoads); slow = zeros(3, model.nRoads);
        failed(1, :) = lineU(pos, :) <= pFail{1};
        failed(2, :) = failed(1, :) | lineU(pos, :) <= pFail{2};
        failed(3, :) = failed(2, :) | lineU(pos, :) <= pFail{3};
        closed(1, :) = roadU(pos, :) <= pClose{1};
        closed(2, :) = closed(1, :) | roadU(pos, :) <= pClose{2};
        closed(3, :) = closed(2, :) | roadU(pos, :) <= pClose{3};
        slow(1, :) = pClose{1}; slow(2, :) = max(slow(1, :), pClose{2});
        slow(3, :) = max(slow(2, :), pClose{3});
        outage = false(3, model.nNodes);
        for tau = 1:3
            outage(tau, :) = double(failed(tau, :)) * model.nodePathIncidence.' > 0;
            outage(tau, model.sourceNode) = false;
        end
        Dtau = double(outage) .* model.Pnode_kW.' * model.DFactorKgPerKWh;
        reachTau = false(3, model.nSites, model.nNodes);
        costTau = inf(3, model.nSites, model.nNodes);
        for tau = 1:3
            edgeCost = model.roadLength .* (1 + slow(tau, :).');
            edgeCost(closed(tau, :).') = Inf;
            [reach, cost] = road_state(model.nNodes, model.roadFrom, model.roadTo, edgeCost, model.siteNodes);
            reachTau(tau, :, :) = reach; costTau(tau, :, :) = cost;
        end
        Dagg = sum(Dtau, 1); Aagg = false(model.nSites, model.nNodes);
        Cagg = inf(model.nSites, model.nNodes);
        for nn = 1:model.nNodes
            critical = find(Dtau(:, nn) > demandToleranceKg);
            if isempty(critical), critical = (1:3).'; end
            for ii = 1:model.nSites
                reach = squeeze(reachTau(critical, ii, nn));
                if all(reach)
                    Aagg(ii, nn) = true;
                    Cagg(ii, nn) = mean(squeeze(costTau(critical, ii, nn)));
                end
            end
        end
        globalRow = (stateId - 1) * rowsPerState + scenarioId;
        Dnom = double(sidecar.D_node_kg(globalRow, :));
        Anom = logical(squeeze(sidecar.A_site_node(globalRow, :, :)));
        Cnom = double(squeeze(sidecar.C_site_node_km(globalRow, :, :)));
        dExact = isequal(Dagg, Dnom); aExact = isequal(Aagg, Anom); cExact = isequaln(Cagg, Cnom);
        finiteBoth = isfinite(Cagg) & isfinite(Cnom); cError = 0;
        if any(finiteBoth, 'all'), cError = max(abs(Cagg(finiteBoth) - Cnom(finiteBoth))); end
        Dperiod(rr, :, :) = Dtau; Aperiod(rr, :, :, :) = reachTau;
        Cperiod(rr, :, :, :) = costTau; DaggAll(rr, :) = Dagg;
        AaggAll(rr, :, :) = Aagg; CaggAll(rr, :, :) = Cagg;
        identity.joint_stream_position(rr) = pos; identity.wind_seed(rr) = windSeed;
        identity.resistance_seed(rr) = resistanceSeed; identity.final_D_exact(rr) = dExact;
        identity.final_A_exact(rr) = aExact; identity.final_C_exact(rr) = cExact;
        identity.max_DAC_error(rr) = max([max(abs(Dagg - Dnom)), cError, ...
            double(sum(Aagg ~= Anom, 'all')), double(sum(isinf(Cagg) ~= isinf(Cnom), 'all'))]);
        if ~(dExact && aExact && cExact), error('Recovered final D/A/C mismatch.'); end
    end
end
recovered = struct('identity', identity, 'Dperiod', Dperiod, 'Aperiod', Aperiod, ...
    'Cperiod', Cperiod, 'Dagg', DaggAll, 'Aagg', AaggAll, 'Cagg', CaggAll);
audit = struct('all_final_DAC_exact', all(identity.final_D_exact & identity.final_A_exact & identity.final_C_exact), ...
    'max_DAC_error', max(identity.max_DAC_error), ...
    'all_stream_hashes_match', streamMatches == numel(unique(request.initial_state_id)), ...
    'stream_match_count', streamMatches);
end

function config = build_config(rootDir, moduleDir, thisDir)
config.pairFile = fullfile(rootDir, 'results', 'task-002-stage2b-b3-smoke', '23-fixed-decision-loss-consistency', 'run-001', 'step03W_pair_results.csv');
config.mainSampleFile = fullfile(moduleDir, 'output', 'stage2a2_W3_path_sampling', 'run-002', 'main_path_samples.csv');
config.nominalCsv = fullfile(moduleDir, 'output', 'stage3j_wdro_input_freeze', 'run-001', 'wdro_nominal_input.csv');
config.nominalMat = fullfile(moduleDir, 'output', 'stage3j_wdro_input_freeze', 'run-001', 'wdro_nominal_input_DAC.mat');
config.seedMapFile = fullfile(moduleDir, 'output', 'stage3j_wdro_input_freeze', 'run-001', 'dataset_role_and_seed_map.csv');
config.nearInputFile = fullfile(rootDir, 'data', 'yuanqi', 'near_stage_msp_input.mat');
config.formalWindConfigFile = fullfile(moduleDir, 'config', 'formal_b3_wind_modes.csv');
config.warningSolutionFile = fullfile(moduleDir, 'output', 'stage2_foundation_warning100_Rmax30_40_50_Wstep_sweep', 'warning_y_base_solution.csv');
config.locCoordinateFile = fullfile(moduleDir, 'output', 'stage2_foundation_audit', 'loc_lf_coordinate_table.csv');
config.roadEdgeFile = fullfile(rootDir, 'data', 'yuanqi', 'stage1_road_edges.csv');
config.siteNodeFile = fullfile(rootDir, 'data', 'yuanqi', 'stage1_site_nodes.csv');
config.stepYAReadme = fullfile(rootDir, 'results', 'task-002-stage2b-b3-smoke', '27-period-data-recoverability', 'run-002', 'README.md');
config.stepYAAudit = fullfile(rootDir, 'results', 'task-002-stage2b-b3-smoke', '27-period-data-recoverability', 'run-002', 'mechanical_audit.txt');
config.Rmax = 40; config.Wstep = 40; config.windDecayB = 0.6;
config.designWindSpeedVN = 25; config.roadDesignWindVN = 30; config.sourceNode = 1; config.thisDir = thisDir;
end

function model = build_replay_model(config, near)
warning = readtable(config.warningSolutionFile); yBase = double(warning.y_base(1));
locRaw = readtable(config.locCoordinateFile); locTable = sortrows(unique(locRaw(:, {'loc', 'x_coord'}), 'rows', 'stable'), 'loc');
layout = build_h2_spatial_layout_preview(near); nodes = sortrows(layout.nodes, 'node_id'); lines = sortrows(layout.lines, 'line_id');
grid = table(lines.line_id, lines.source_edge_id, lines.from_node, lines.to_node, ...
    nodes.x_km(lines.from_node), nodes.y_km(lines.from_node), nodes.x_km(lines.to_node), nodes.y_km(lines.to_node), ...
    'VariableNames', {'line_id', 'source_edge_id', 'from_node', 'to_node', 'x1', 'y1', 'x2', 'y2'});
roadRaw = readtable(config.roadEdgeFile);
road = table(double(roadRaw.road_edge_id), double(roadRaw.from_node), double(roadRaw.to_node), ...
    nodes.x_km(double(roadRaw.from_node)), nodes.y_km(double(roadRaw.from_node)), ...
    nodes.x_km(double(roadRaw.to_node)), nodes.y_km(double(roadRaw.to_node)), ...
    'VariableNames', {'road_edge_id', 'from_node', 'to_node', 'x1', 'y1', 'x2', 'y2'});
site = sortrows(readtable(config.siteNodeFile), 'site_id'); Pnode = double(near.Grid.P_load_base_kw(:));
eta = double(near.HydrogenDevice.eta_FC); lhv = double(near.HydrogenDevice.h2_lhv_kWh_per_kg);
locValues = sort(double(locTable.loc)); lineFactor = zeros(6 * numel(locValues) * 4, height(grid));
roadFactor = zeros(6 * numel(locValues) * 4, height(road)); stateIndex = zeros(6, numel(locValues), 4); rr = 0;
for a = 1:6
    for loc = locValues(:).'
        locRow = locTable(locTable.loc == loc, :);
        for lfw = 0:3
            rr = rr + 1; x = double(locRow.x_coord); y = yBase + lfw * config.Wstep;
            ld = compute_point_to_segment_distance_h2(x, y, grid.x1, grid.y1, grid.x2, grid.y2);
            rd = compute_point_to_segment_distance_h2(x, y, road.x1, road.y1, road.x2, road.y2);
            lineFactor(rr, :) = compute_wind_speed_radial_h2(ld, 1, config.Rmax, config.windDecayB).';
            roadFactor(rr, :) = compute_wind_speed_radial_h2(rd, 1, config.Rmax, config.windDecayB).';
            stateIndex(a, loc - min(locValues) + 1, lfw + 1) = rr;
        end
    end
end
model = struct('lineFactor', lineFactor, 'roadFactor', roadFactor, 'stateIndex', stateIndex, ...
    'locMin', min(locValues), 'nLines', height(grid), 'nRoads', height(road), ...
    'nNodes', numel(Pnode), 'nSites', height(site), 'sourceNode', config.sourceNode, ...
    'Pnode_kW', Pnode, 'nodePathIncidence', radial_node_path_incidence(numel(Pnode), grid.from_node, grid.to_node, config.sourceNode), ...
    'roadFrom', double(road.from_node), 'roadTo', double(road.to_node), ...
    'roadLength', hypot(road.x2 - road.x1, road.y2 - road.y1), ...
    'siteNodes', double(site.grid_node), 'DFactorKgPerKWh', 1 / (eta * lhv), ...
    'designWindSpeedVN', config.designWindSpeedVN, 'roadDesignWindVN', config.roadDesignWindVN);
end

function incidence = radial_node_path_incidence(nNodes, fromNode, toNode, sourceNode)
nLines = numel(fromNode); adj = cell(nNodes, 1); edgeAdj = cell(nNodes, 1);
for ll = 1:nLines, i = fromNode(ll); j = toNode(ll); adj{i}(end+1)=j; edgeAdj{i}(end+1)=ll; adj{j}(end+1)=i; edgeAdj{j}(end+1)=ll; end
parent=zeros(nNodes,1); parentEdge=zeros(nNodes,1); visited=false(nNodes,1); queue=zeros(nNodes,1); h=1; t=1; queue(1)=sourceNode; visited(sourceNode)=true;
while h<=t, u=queue(h); h=h+1; for kk=1:numel(adj{u}), v=adj{u}(kk); if visited(v),continue;end; visited(v)=true; parent(v)=u; parentEdge(v)=edgeAdj{u}(kk); t=t+1; queue(t)=v; end,end
incidence=false(nNodes,nLines); for node=1:nNodes, cur=node; while cur~=sourceNode, incidence(node,parentEdge(cur))=true; cur=parent(cur); end,end
end

function idx = state_index(model, a, loc, lfw), idx=model.stateIndex(sub2ind(size(model.stateIndex),a,loc-model.locMin+1,lfw+1)); if idx<=0,error('Missing state.');end,end
function vmax = triangular_by_level(a,q,lo,mode,hi), if a==1,vmax=0;return;end; x=lo(a);c=mode(a);b=hi(a);fc=(c-x)/(b-x);if q<=fc,vmax=x+sqrt(q*(b-x)*(c-x));else,vmax=b-sqrt((1-q)*(b-x)*(b-c));end,end
function [reach,cost]=road_state(nNodes,fromNode,toNode,edgeCost,sources),adj=inf(nNodes);adj(1:nNodes+1:end)=0;for ee=1:numel(edgeCost),if ~isfinite(edgeCost(ee)),continue;end;i=fromNode(ee);j=toNode(ee);if edgeCost(ee)<adj(i,j),adj(i,j)=edgeCost(ee);adj(j,i)=edgeCost(ee);end,end;reach=false(numel(sources),nNodes);cost=inf(numel(sources),nNodes);for ii=1:numel(sources),dist=inf(1,nNodes);vis=false(1,nNodes);dist(sources(ii))=0;for it=1:nNodes,cand=dist;cand(vis)=Inf;[best,u]=min(cand);if ~isfinite(best),break;end;vis(u)=true;dist=min(dist,best+adj(u,:));end;reach(ii,:)=isfinite(dist);cost(ii,:)=dist;end,end
function value=qvalue(x,p),x=sort(double(x(:)));if isempty(x),value=NaN;return;end;pos=numel(x)*p+0.5;if pos<=1,value=x(1);elseif pos>=numel(x),value=x(end);else,lo=floor(pos);f=pos-lo;value=x(lo)+f*(x(lo+1)-x(lo));end,end
function hash=sha256_file(fileName),fid=fopen(fileName,'rb');if fid<0,error('Cannot open file.');end;c=onCleanup(@()fclose(fid));md=java.security.MessageDigest.getInstance('SHA-256');while true,b=fread(fid,1024*1024,'*uint8');if isempty(b),break;end;md.update(typecast(b,'int8'));end;d=typecast(md.digest(),'uint8');hash=lower(string(reshape(dec2hex(d,2).',1,[])));end
function hash=sha256_uint32(x),md=java.security.MessageDigest.getInstance('SHA-256');b=typecast(uint32(x(:)),'uint8');md.update(typecast(b,'int8'));d=typecast(md.digest(),'uint8');hash=lower(string(reshape(dec2hex(d,2).',1,[])));end
function hash=sha256_double(x),md=java.security.MessageDigest.getInstance('SHA-256');b=typecast(double(x(:)),'uint8');md.update(typecast(b,'int8'));d=typecast(md.digest(),'uint8');hash=lower(string(reshape(dec2hex(d,2).',1,[])));end
function digest=path_digest(p),if isfile(p),digest=sha256_file(p);return;end;if ~isfolder(p),digest="MISSING";return;end;f=dir(fullfile(p,'**','*'));f=f(~[f.isdir]);rel=strings(numel(f),1);for i=1:numel(f),full=fullfile(f(i).folder,f(i).name);rel(i)=string(erase(full,[char(p),filesep]));end;[rel,o]=sort(rel);f=f(o);md=java.security.MessageDigest.getInstance('SHA-256');for i=1:numel(f),full=fullfile(f(i).folder,f(i).name);token=rel(i)+"|"+string(f(i).bytes)+"|"+sha256_file(full)+newline;md.update(typecast(unicode2native(char(token),'UTF-8'),'int8'));end;d=typecast(md.digest(),'uint8');digest=lower(string(reshape(dec2hex(d,2).',1,[])));end
function write_lines(fileName,lines),fid=fopen(fileName,'w');if fid<0,error('Cannot write.');end;c=onCleanup(@()fclose(fid));for i=1:numel(lines),fprintf(fid,'%s\n',lines(i));end,end
function value=ternary(condition,a,b),if condition,value=a;else,value=b;end,end
