function run_step04CC1_eta_case_h2(workDir, caseId)
%RUN_STEP04CC1_ETA_CASE_H2 Optimize and audit one isolated eta case.

started = tic;
workDir = string(workDir); caseId = double(caseId);
thisDir = fileparts(mfilename('fullpath'));
rootDir = fileparts(fileparts(thisDir));
addpath(rootDir); addpath(thisDir); add_gurobi_path();
assert_git_gate("task/002-stage2b-b3-smoke", ...
    "175c26f5ecefefef541b0769a28a3ab1972b804e");
preparedFile = fullfile(workDir, 'prepared_inputs.mat');
if ~isfile(preparedFile), error('Prepared C1 input is missing.'); end
S = load(preparedFile);
if ~isscalar(caseId) || caseId < 1 || caseId > numel(S.etaGrid) || ...
        caseId ~= floor(caseId)
    error('caseId is outside the frozen eta grid.');
end
eta = double(S.etaGrid(caseId));
caseDir = fullfile(workDir, 'cases', sprintf('case-%03d', caseId));
if isfolder(caseDir)
    entries = dir(fullfile(caseDir, '*'));
    entries = entries(~ismember({entries.name}, {'.','..'}));
    if ~isempty(entries), error('Refusing to overwrite nonempty eta case directory.'); end
else
    mkdir(caseDir);
end
diaryFile = fullfile(caseDir, 'matlab_diary.txt');
diary(diaryFile); cleanupDiary = onCleanup(@()diary('off')); %#ok<NASGU>
fprintf('STEP04CC1_CASE_START|case=%d|eta=%.12g\n', caseId, eta);

config = struct('gurobiOutputFlag',0,'gurobiFeasibilityTol',1e-9, ...
    'gurobiOptimalityTol',1e-9,'gurobiThreads',1,'objectiveScale',1e5, ...
    'gurobiTimeLimit',1800,'totalTimeLimit',3600,'recourseTimeLimit',1800, ...
    'masterTimeLimit',60,'maximumIterations',100,'absoluteGapTolerance',1e-4, ...
    'relativeGapTolerance',1e-8);
if eta <= 1e-14
    solution = solve_terminal_loh_saa_h2(S.DnominalGroup, ...
        S.AnominalGroup,S.CnominalGroup,S.qNominalGroup,S.Cap,S.M,S.gamma,config);
else
    solution = solve_terminal_loh_flat_chi2_decomposition_h2( ...
        S.DnominalGroup,S.AnominalGroup,S.CnominalGroup,S.qNominalGroup, ...
        S.Cap,S.M,S.gamma,eta,config);
end
if solution.exitflag ~= 1
    error('Eta %.12g optimization failed: %s', eta, solution.status);
end
audit = audit_flat_chi2_terminal_solution_h2( ...
    solution, make_aggregation(S), S.M, S.gamma, config);
if ~audit.pass, error('Eta %.12g nominal robust audit failed.', eta); end

T = solution.T(:).'; Trows = repmat(T,15000,1);
nominalEval = evaluate_terminal_loh_period_fixed_T_sparse_h2( ...
    S.Dnominal,S.Anominal,S.Cnominal,Trows,S.M,config);
validation1Eval = evaluate_terminal_loh_period_fixed_T_sparse_h2( ...
    S.Dvalidation1,S.Avalidation1,S.Cvalidation1,Trows,S.M,config);
validation2Eval = evaluate_terminal_loh_period_fixed_T_sparse_h2( ...
    S.Dvalidation2,S.Avalidation2,S.Cvalidation2,Trows,S.M,config);
stressEval = evaluate_terminal_loh_period_fixed_T_sparse_h2( ...
    S.Dstress,S.Astress,S.Cstress,repmat(T,135,1),S.M,config);
assert_optimal(nominalEval,'nominal fixed-T');
assert_optimal(validation1Eval,'validation-1 fixed-T');
assert_optimal(validation2Eval,'validation-2 fixed-T');
assert_optimal(stressEval,'state19 stress fixed-T');

datasetMetrics = [dataset_row(caseId,eta,"nominal",nominalEval, ...
    S.Dnominal,T,S.gamma); dataset_row(caseId,eta,"validation-1", ...
    validation1Eval,S.Dvalidation1,T,S.gamma); ...
    dataset_row(caseId,eta,"validation-2",validation2Eval, ...
    S.Dvalidation2,T,S.gamma)];
writetable(datasetMetrics, fullfile(caseDir, 'dataset_metrics.csv'));
stressMetrics = stress_row(caseId,eta,stressEval,S.Dstress,T,S.gamma);
writetable(stressMetrics, fullfile(caseDir, 'stress_metrics.csv'));

bindingTolerance = 1e-6;
binding = abs(T - S.Cap) <= bindingTolerance;
if eta <= 1e-14
    lowerBound = solution.objective_value; upperBound = solution.objective_value;
    absoluteGap = 0; relativeGap = 0; iterations = 1; cuts = 0;
else
    lowerBound = solution.decomposition_lower_bound;
    upperBound = solution.decomposition_upper_bound;
    absoluteGap = solution.decomposition_absolute_gap;
    relativeGap = solution.decomposition_relative_gap;
    iterations = solution.decomposition_iteration_count;
    cuts = solution.decomposition_cut_count;
end
referenceT = [294.589913536808,138.832065024684,93.0093009300931,150];
referenceObjective = 11444.8775967693;
if eta <= 1e-14
    etaZeroTError = max(abs(T-referenceT));
    etaZeroObjectiveError = abs(solution.objective_value-referenceObjective);
    etaZeroDirectSaaPass = etaZeroTError <= 1e-6 && etaZeroObjectiveError <= 1e-5 && ...
        audit.adversary.method_used == "eta_zero_direct_saa";
else
    etaZeroTError = NaN; etaZeroObjectiveError = NaN; etaZeroDirectSaaPass = true;
end
roleResiduals = [recourse_residual(nominalEval), ...
    recourse_residual(validation1Eval),recourse_residual(validation2Eval)];
stressResidual = recourse_residual(stressEval);
maximumMechanicalResidual = max([audit.maximum_mechanical_residual, ...
    roleResiduals,stressResidual],[],'omitnan');
probability = audit.original_record_worst_probability;
divergenceFraction = NaN;
if eta > 0, divergenceFraction = audit.record_divergence_used/eta; end
certificatePass = solution.status == "OPTIMAL" && audit.status == "PASS" && ...
    (absoluteGap <= 1e-4 + 1e-10 || relativeGap <= 1e-8 + 1e-12) && ...
    audit.strong_duality_gap <= 1e-3 && ...
    audit.record_probability_sum_residual <= 1e-10 && ...
    audit.record_minimum_probability >= -1e-10 && ...
    audit.record_divergence_used <= eta + 1e-8 && ...
    all(roleResiduals <= 1e-7) && stressResidual <= 1e-5 && ...
    etaZeroDirectSaaPass && ~solution.constructed_R_by_R_matrix;
certificate = table(caseId,eta,string(solution.mode),string(solution.status), ...
    string(audit.status),lowerBound,upperBound,absoluteGap,relativeGap, ...
    iterations,cuts,solution.solve_runtime_sec,audit.fixed_T.solve_runtime_sec, ...
    audit.strong_duality_gap,audit.strong_duality_relative_gap, ...
    audit.total_objective_reconstruction_gap, ...
    audit.record_divergence_used,eta-audit.record_divergence_used, ...
    divergenceFraction,audit.record_probability_sum_residual, ...
    audit.record_minimum_probability,max(probability), ...
    audit.record_effective_sample_size,sum(probability>1e-15), ...
    audit.maximum_mechanical_residual,roleResiduals(1),roleResiduals(2), ...
    roleResiduals(3),stressResidual,maximumMechanicalResidual, ...
    etaZeroTError,etaZeroObjectiveError,etaZeroDirectSaaPass, ...
    solution.constructed_R_by_R_matrix,certificatePass, ...
    'VariableNames', {'case_id','eta','solver_mode','solver_status', ...
    'robust_audit_status','LB','UB','absolute_gap','relative_gap', ...
    'iteration_count','cut_count','optimization_runtime_sec', ...
    'grouped_fixed_T_audit_runtime_sec','strong_duality_gap', ...
    'strong_duality_relative_gap','objective_reconstruction_gap', ...
    'divergence_used','divergence_slack','divergence_fraction', ...
    'probability_sum_residual','minimum_worst_probability', ...
    'maximum_worst_probability','effective_support_size_ESS', ...
    'positive_probability_support_count','robust_audit_mechanical_residual', ...
    'nominal_fixed_T_mechanical_residual', ...
    'validation_1_fixed_T_mechanical_residual', ...
    'validation_2_fixed_T_mechanical_residual', ...
    'stress_fixed_T_mechanical_residual','maximum_mechanical_residual', ...
    'eta_zero_T_reference_error','eta_zero_objective_reference_error', ...
    'eta_zero_direct_SAA_pass','constructed_R_by_R_matrix','certificate_pass'});
writetable(certificate, fullfile(caseDir, 'solver_certificate.csv'));

summary = table(caseId,eta,T(1),T(2),T(3),T(4),sum(T), ...
    binding(1),binding(2),binding(3),binding(4),sum(binding), ...
    audit.first_stage_cost,audit.nominal_expected_recourse, ...
    audit.worst_expected_recourse,audit.robust_total_objective, ...
    nominalEval.solve_runtime_sec,validation1Eval.solve_runtime_sec, ...
    validation2Eval.solve_runtime_sec,stressEval.solve_runtime_sec,toc(started), ...
    string(solution.status),string(audit.status),certificatePass, ...
    'VariableNames', {'case_id','eta','T1_kg','T2_kg','T3_kg','T4_kg', ...
    'TerminalLOH_total_kg','T1_capacity_binding','T2_capacity_binding', ...
    'T3_capacity_binding','T4_capacity_binding','capacity_binding_count', ...
    'first_stage_cost','nominal_expected_recourse', ...
    'nominal_worst_expected_recourse','nominal_robust_objective', ...
    'nominal_fixed_T_runtime_sec','validation_1_fixed_T_runtime_sec', ...
    'validation_2_fixed_T_runtime_sec','stress_fixed_T_runtime_sec', ...
    'case_total_runtime_sec','solver_status','audit_status','case_pass'});
writetable(summary, fullfile(caseDir, 'case_summary.csv'));

fid = fopen(fullfile(caseDir, 'mechanical_audit.txt'), 'w');
cleanup = onCleanup(@()fclose(fid)); %#ok<NASGU>
fprintf(fid,'status=%s\ncase_id=%d\neta=%.12g\n', ...
    pass_fail(certificatePass),caseId,eta);
fprintf(fid,'solver_status=%s\nrobust_audit_status=%s\n', ...
    solution.status,audit.status);
fprintf(fid,'LB=%.15g\nUB=%.15g\nabsolute_gap=%.15g\nrelative_gap=%.15g\n', ...
    lowerBound,upperBound,absoluteGap,relativeGap);
fprintf(fid,'strong_duality_gap=%.15g\ndivergence_used=%.15g\n', ...
    audit.strong_duality_gap,audit.record_divergence_used);
fprintf(fid,'probability_sum_residual=%.15g\nmaximum_mechanical_residual=%.15g\n', ...
    audit.record_probability_sum_residual,maximumMechanicalResidual);
fprintf(fid,'validation_interpretation=same_typhoon_paths_second_layer_wind_and_resistance_redraw\n');
fprintf(fid,'stress_interpretation=fixed_reproducible_isolated_stress_set_no_empirical_probability\n');
fprintf(fid,'old_WDRO_called=0\nextreme_aware_solver_called=0\nMSP_called=0\n');
if ~certificatePass, error('Eta %.12g certificate failed.', eta); end
fprintf('STEP04CC1_CASE_COMPLETE|case=%d|eta=%.12g|T=[%.9f %.9f %.9f %.9f]|runtime=%.3f\n', ...
    caseId,eta,T,toc(started));
end

function aggregation = make_aggregation(S)
aggregation = struct('Dperiod',S.DnominalGroup,'Aperiod',S.AnominalGroup, ...
    'Cperiod',S.CnominalGroup,'nominal_probability',S.qNominalGroup, ...
    'group_id',S.nominalGroupId,'multiplicity',S.nominalMultiplicity, ...
    'group_count',numel(S.qNominalGroup),'original_R',15000);
end

function row = dataset_row(caseId,eta,role,ev,D,T,gamma)
totalDemand = reshape(sum(D,[2,3]),[],1);
serviceRate = ones(size(totalDemand)); positive = totalDemand > 0;
serviceRate(positive) = 1-ev.shortage_kg(positive)./totalDemand(positive);
serviceRate = max(0,min(1,serviceRate));
firstStage = gamma*sum(T); loss = ev.operating_loss; shortage = ev.shortage_kg;
row = table(caseId,eta,role,firstStage+mean(loss),mean(loss), ...
    mean(ev.service_cost),mean(shortage),pct(loss,.95),pct(loss,.99), ...
    pct(loss,.995),tail_mean(loss,.95),tail_mean(loss,.99), ...
    tail_mean(loss,.995),max(loss),pct(shortage,.95),pct(shortage,.99), ...
    pct(shortage,.995),max(shortage),mean(serviceRate),sum(shortage<=1e-9)/numel(shortage), ...
    'VariableNames', {'case_id','eta','dataset_role','mean_total_cost', ...
    'mean_operating_loss','mean_service_cost','mean_shortage_kg', ...
    'operating_loss_q95','operating_loss_q99','operating_loss_q995', ...
    'operating_loss_CVaR95','operating_loss_CVaR99','operating_loss_CVaR995', ...
    'maximum_operating_loss','shortage_q95_kg','shortage_q99_kg', ...
    'shortage_q995_kg','maximum_shortage_kg','mean_service_rate', ...
    'zero_shortage_service_share'});
end

function row = stress_row(caseId,eta,ev,D,T,gamma)
totalDemand = reshape(sum(D,[2,3]),[],1); serviceRate = ones(size(totalDemand));
positive = totalDemand>0; serviceRate(positive)=1-ev.shortage_kg(positive)./totalDemand(positive);
serviceRate=max(0,min(1,serviceRate)); firstStage=gamma*sum(T);
row = table(caseId,eta,135,27,firstStage+mean(ev.operating_loss), ...
    mean(ev.operating_loss),pct(ev.operating_loss,.95),max(ev.operating_loss), ...
    mean(ev.shortage_kg),pct(ev.shortage_kg,.95),max(ev.shortage_kg), ...
    mean(serviceRate),"DESCRIPTIVE_EQUAL_REPLICA_SUMMARY_NOT_EMPIRICAL_PROBABILITY", ...
    'VariableNames', {'case_id','eta','stress_replica_count','stress_path_count', ...
    'mean_total_cost','mean_operating_loss','operating_loss_q95', ...
    'maximum_operating_loss','mean_shortage_kg','shortage_q95_kg', ...
    'maximum_shortage_kg','mean_service_rate','weighting_interpretation'});
end

function value = pct(x,p)
x=sort(double(x(:))); x=x(isfinite(x));
value=x(max(1,min(numel(x),ceil(p*numel(x)))));
end

function value = tail_mean(x,p)
x=double(x(:)); threshold=pct(x,p); value=mean(x(x>=threshold));
end

function value = recourse_residual(ev)
value=max([ev.max_demand_balance_error,max(0,ev.max_site_capacity_violation), ...
    ev.objective_reconstruction_abs_error/max(1,sum(abs(ev.operating_loss)))], ...
    [],'omitnan');
end

function assert_optimal(out,label)
if out.exitflag~=1,error('%s failed: %s',label,out.status);end
end

function value=pass_fail(passed)
if passed,value="PASS";else,value="FAIL";end
end

function assert_git_gate(expectedBranch,expectedHead)
[s1,b]=system('git branch --show-current');[s2,h]=system('git rev-parse HEAD');
[s3,u]=system('git rev-parse @{upstream}');
if s1~=0||s2~=0||s3~=0||strtrim(string(b))~=expectedBranch|| ...
        strtrim(string(h))~=expectedHead||strtrim(string(u))~=expectedHead
    error('Step-04C-C1 eta-case Git gate failed.');
end
end

function add_gurobi_path()
for candidate={fullfile(getenv('GUROBI_HOME'),'matlab'), ...
        'D:\gurobi1201\win64\matlab','C:\gurobi1201\win64\matlab'}
    if ~isempty(candidate{1})&&isfolder(candidate{1}),addpath(candidate{1});end
end
end
