clear; clc;

thisDir = fileparts(mfilename('fullpath'));
moduleDir = fileparts(thisDir);
rootDir = fileparts(moduleDir);
if isempty(rootDir) || isempty(moduleDir)
    rootDir = pwd;
    moduleDir = fullfile(rootDir, 'terminalLoh_wdro');
end
addpath(rootDir);
addpath(thisDir);
addpath(fullfile(rootDir, 'fa_h2', 'fuzhu', 'terminalLoh_windmc'));

config = struct();
config.rootDir = rootDir;
config.moduleDir = moduleDir;
config.taskStartTime = datetime(2026, 7, 14, 0, 44, 42);
config.v1OutputDir = fullfile(moduleDir, 'output', ...
    'stage2_foundation_fix_Hres3h_Wstep40_reaudit');
config.outputDir = fullfile(moduleDir, 'output', ...
    'stage2_foundation_fix_Hres3h_Wstep40_reaudit_v2');
config.riskFile = fullfile(config.v1OutputDir, ...
    'foundation_fix_wind_risk_summary.csv');
config.sliceFile = fullfile(config.v1OutputDir, ...
    'foundation_fix_D_by_slice.csv');
config.DSummaryFile = fullfile(config.v1OutputDir, ...
    'foundation_fix_D_Hres3h_summary.csv');

config.warningSweepDir = fullfile(moduleDir, 'output', ...
    'stage2_foundation_warning100_Rmax30_40_50_Wstep_sweep');
config.warningSolutionFile = fullfile(config.warningSweepDir, ...
    'warning_y_base_solution.csv');
config.warningGeometryFile = fullfile(config.warningSweepDir, ...
    'warning_geometry_by_loc.csv');
config.warningRankingFile = fullfile(config.warningSweepDir, ...
    'Wstep_candidate_ranking.csv');
config.warningStageSummaryFile = fullfile(config.warningSweepDir, ...
    'Rmax_Wstep_stage_summary.csv');
config.warningDiagnosticsFile = fullfile(config.warningSweepDir, ...
    'diagnostics_summary.txt');
config.warningRankingSourceFile = fullfile(thisDir, ...
    'rank_Wstep_candidates_h2.m');
config.locCoordinateFile = fullfile(moduleDir, 'output', ...
    'stage2_foundation_audit', 'loc_lf_coordinate_table.csv');
config.nearInputFile = fullfile(rootDir, 'data', 'yuanqi', ...
    'near_stage_msp_input.mat');
config.roadEdgeFile = fullfile(rootDir, 'data', 'yuanqi', ...
    'stage1_road_edges.csv');
config.siteNodeFile = fullfile(rootDir, 'data', 'yuanqi', ...
    'stage1_site_nodes.csv');

config.warningDistanceKmEq = 100;
config.RmaxValues = [30, 40, 50];
config.RmaxRef = 40;
config.WstepValues = [40, 45];
% Legacy fields are used only to verify the prior ranking CSV order.
% The v2 recommendation function ignores them and evaluates both candidates.
config.recommendedWstep = 40;
config.comparisonWstep = 45;
config.W = 3;
config.sliceDurationH = 1;
config.HresTotalH = 3;
config.stageNames = ["lf7", "W1", "W2", "W3"];
config.stageOffsets = [0, 1, 2, 3];
config.mcSeed = 20260713;
config.distanceMethod = "point_to_segment";
config.auditTolerance = 1e-9;

config.protectedOutputDirs = {
    fullfile(moduleDir, 'output', 'stage2_lookahead_W3'), ...
    fullfile(moduleDir, 'output', 'stage2_lookahead_W3_B1_DAC_samples'), ...
    fullfile(moduleDir, 'output', 'stage2_lookahead_W3_B2_DAC_samples_R200'), ...
    fullfile(moduleDir, 'output', 'stage2_foundation_audit'), ...
    fullfile(moduleDir, 'output', 'stage2_foundation_yStep_calibration'), ...
    config.warningSweepDir, config.v1OutputDir};

config.protectedMSPFiles = {
    fullfile(rootDir, 'main_msp_h2_near.m'), ...
    fullfile(rootDir, 'h2_default_options.m'), ...
    fullfile(rootDir, 'run_h2_with_options.m'), ...
    fullfile(rootDir, 'run_h2_ablation_suite.m'), ...
    fullfile(rootDir, 'load_data_h2_near.m'), ...
    fullfile(rootDir, 'fa_h2', 'build_stage_model_h2.m'), ...
    fullfile(rootDir, 'fa_h2', 'update_rhs_h2.m'), ...
    fullfile(rootDir, 'fa_h2', 'solve_stage_model_h2.m'), ...
    fullfile(rootDir, 'fa_h2', 'forward_pass_h2.m'), ...
    fullfile(rootDir, 'fa_h2', 'backward_pass_h2.m'), ...
    fullfile(rootDir, 'fa_h2', 'add_cut_h2.m'), ...
    fullfile(rootDir, 'fa_h2', 'train_models_h2.m'), ...
    fullfile(rootDir, 'fa_h2', 'eval_h2.m'), ...
    config.nearInputFile};

config.expectedModifiedCodeFiles = {
    fullfile(thisDir, 'compare_Wstep40_45_foundation_h2.m'), ...
    fullfile(thisDir, 'run_stage2_foundation_reaudit_h2.m'), ...
    fullfile(thisDir, 'select_foundation_Wstep_recommendation_h2.m'), ...
    fullfile(thisDir, 'load_foundation_fix_reaudit_inputs_h2.m'), ...
    fullfile(thisDir, 'independent_recheck_foundation_D_Hres3h_h2.m'), ...
    fullfile(thisDir, 'build_foundation_fix_scope_audit_v2_h2.m'), ...
    fullfile(thisDir, 'run_stage2_foundation_fix_reaudit_v2_h2.m'), ...
    fullfile(thisDir, 'write_foundation_fix_reaudit_v2_h2.m')};
config.expectedModifiedFiles = [config.expectedModifiedCodeFiles(:); ...
    {fullfile(rootDir, 'codex_rule', 'log.md')}];
config.executedSourceFiles = [config.expectedModifiedCodeFiles(:); ...
    {fullfile(thisDir, 'build_foundation_fix_coordinates_h2.m')}];
config.mcSourceFile = fullfile(thisDir, 'evaluate_foundation_fix_chain_h2.m');
config.allowedV2OutputNames = [ ...
    "Wstep40_45_recommendation_v2.csv"; ...
    "foundation_fix_reaudit_checks_v2.csv"; ...
    "D_Hres3h_independent_recheck.csv"; ...
    "modified_file_audit.csv"; ...
    "output_directory_audit.csv"; ...
    "diagnostics_summary_v2.txt"; ...
    "implementation_audit_v2.md"];

if isfolder(config.outputDir)
    existing = dir(config.outputDir);
    existing = existing(~ismember({existing.name}, {'.', '..'}));
    if ~isempty(existing)
        error('run_stage2_foundation_fix_reaudit_v2_h2:OutputExists', ...
            'Refusing to overwrite nonempty v2 output directory: %s', ...
            config.outputDir);
    end
else
    mkdir(config.outputDir);
end

protectedBefore = snapshot_protected_outputs_v2(config.protectedOutputDirs);
foundation = build_foundation_fix_coordinates_h2(config);
result = load_foundation_fix_reaudit_inputs_h2(config);
dAudit = independent_recheck_foundation_D_Hres3h_h2( ...
    config.sliceFile, config.DSummaryFile, config.auditTolerance);
[comparisonTbl, recommendation] = compare_Wstep40_45_foundation_h2( ...
    result, config);

scopeAudit = build_foundation_fix_scope_audit_v2_h2( ...
    config, protectedBefore, result.mc_by_slice);
config.audit = scopeAudit;
config.audit.D_recheck = dAudit;
checks = run_stage2_foundation_reaudit_h2(result, foundation, ...
    comparisonTbl, recommendation, config, protectedBefore);

write_foundation_fix_reaudit_v2_h2(result, recommendation, dAudit, ...
    checks, scopeAudit, config);

required = checks.passed(~isnan(checks.passed));
fprintf('\nFoundation Fix re-audit v2 finished.\n');
fprintf('Output directory:\n%s\n', config.outputDir);
fprintf('Recommendation: %s\n', recommendation.status);
fprintf('Automatic checks passed: %d/%d; warnings: %d\n', ...
    sum(required == 1), numel(required), sum(strlength(checks.warning) > 0));

function snap = snapshot_protected_outputs_v2(paths)
snap = table(strings(numel(paths), 1), zeros(numel(paths), 1), ...
    zeros(numel(paths), 1), zeros(numel(paths), 1), ...
    'VariableNames', {'path', 'file_count', 'latest_datenum', 'total_bytes'});
for ii = 1:numel(paths)
    p = paths{ii};
    snap.path(ii) = string(p);
    if ~isfolder(p)
        snap.file_count(ii) = -1;
        snap.latest_datenum(ii) = NaN;
        snap.total_bytes(ii) = -1;
        continue;
    end
    items = dir(fullfile(p, '**', '*'));
    items = items(~[items.isdir]);
    snap.file_count(ii) = numel(items);
    if isempty(items)
        snap.latest_datenum(ii) = 0;
        snap.total_bytes(ii) = 0;
    else
        snap.latest_datenum(ii) = max([items.datenum]);
        snap.total_bytes(ii) = sum([items.bytes]);
    end
end
end
