function run_step04CC5B_unified_optimization_case_h2(workDir,caseId)
%RUN_STEP04CC5B_UNIFIED_OPTIMIZATION_CASE_H2 One isolated economic solve.

started=tic;workDir=string(workDir);caseId=double(caseId);
thisDir=fileparts(mfilename('fullpath'));rootDir=fileparts(fileparts(thisDir));
addpath(rootDir);addpath(thisDir);add_gurobi_path();
assert_git_gate("task/002-stage2b-b3-smoke", ...
    "bb298d52ee5143bc2c60e2f2fc1e31e8d1c3d1a2");
if ~isscalar(caseId)||caseId<1||caseId>3||caseId~=floor(caseId)
    error('caseId must be 1, 2, or 3.');
end
etaGrid=[0,0.003,0.01];labels=["SAA";"ETA_0.003";"ETA_0.01"];
eta=etaGrid(caseId);caseDir=fullfile(workDir,'optimization_cases',sprintf('case-%03d',caseId));
if isfolder(caseDir)
    entries=dir(caseDir);entries=entries(~ismember({entries.name},{'.','..'}));
    if ~isempty(entries),error('Refusing to overwrite nonempty optimization case.');end
else,mkdir(caseDir);end
diary(fullfile(caseDir,'matlab_diary.txt'));cleanupDiary=onCleanup(@()diary('off')); %#ok<NASGU>

c1Prepared=fullfile(rootDir,'results','task-002-stage2b-b3-smoke', ...
    '46-flat-chi2-eta-calibration','run-003','prepared_inputs.mat');
if sha256_file(c1Prepared)~="5914afb37254ae908c5a8b10f24bc0ae01520e56b35b928a1afc13cf4602f19b"
    error('C1 prepared input hash gate failed.');
end
S=load(c1Prepared,'DnominalGroup','AnominalGroup','CnominalGroup', ...
    'qNominalGroup','nominalGroupId','nominalMultiplicity','Cap');
if numel(S.qNominalGroup)~=7334||numel(S.nominalGroupId)~=15000|| ...
        max(abs(double(S.Cap(:).')-[300,200,100,150]))>1e-12
    error('C1 grouped nominal structure gate failed.');
end
P=read_parameters(rootDir);M=P.M_H2;cH2=P.c_H2;
config=struct('gurobiOutputFlag',0,'gurobiFeasibilityTol',1e-9, ...
    'gurobiOptimalityTol',1e-9,'gurobiThreads',1,'objectiveScale',1e5, ...
    'gurobiTimeLimit',1800,'totalTimeLimit',3600,'recourseTimeLimit',1800, ...
    'masterTimeLimit',60,'maximumIterations',150,'absoluteGapTolerance',1e-4, ...
    'relativeGapTolerance',1e-8);
Czero=zeros(size(S.CnominalGroup));
fprintf('STEP04CC5B_OPT_START|case=%d|eta=%.12g|cH2=%.12f|M=%.6f\n', ...
    caseId,eta,cH2,M);
if eta<=1e-14
    solution=solve_terminal_loh_saa_h2(S.DnominalGroup,S.AnominalGroup,Czero, ...
        S.qNominalGroup,S.Cap,M,cH2,config);
else
    solution=solve_terminal_loh_flat_chi2_decomposition_h2( ...
        S.DnominalGroup,S.AnominalGroup,Czero,S.qNominalGroup,S.Cap,M,cH2,eta,config);
end
if solution.exitflag~=1,error('Unified optimization failed: %s',solution.status);end
aggregation=struct('Dperiod',S.DnominalGroup,'Aperiod',S.AnominalGroup, ...
    'Cperiod',Czero,'nominal_probability',S.qNominalGroup, ...
    'group_id',S.nominalGroupId,'multiplicity',S.nominalMultiplicity, ...
    'group_count',numel(S.qNominalGroup),'original_R',15000);
audit=audit_flat_chi2_terminal_solution_h2(solution,aggregation,M,cH2,config);
if ~audit.pass,error('Unified robust audit failed.');end
T=solution.T(:).';G=numel(S.qNominalGroup);
lex=evaluate_terminal_loh_period_fixed_T_lexicographic_h2( ...
    S.DnominalGroup,S.AnominalGroup,S.CnominalGroup,repmat(T,G,1),M,config);
if lex.exitflag~=1,error('Grouped lexicographic replay failed: %s',lex.status);end

q=double(S.qNominalGroup(:));q=q/sum(q);
nominalMeanShortage=sum(q.*lex.shortage_kg);
nominalMeanEENS=nominalMeanShortage*P.electricity_per_kg;
productionCost=cH2*sum(T);nominalShortageLoss=M*nominalMeanShortage;
nominalEconomicTotal=productionCost+nominalShortageLoss;
secondaryExpected=sum(q.*lex.service_distance);
binding=abs(T-double(S.Cap(:).'))<=1e-6;
if eta<=1e-14
    LB=solution.objective_value;UB=solution.objective_value;absoluteGap=0;relativeGap=0;
    iterations=1;cuts=0;
else
    LB=solution.decomposition_lower_bound;UB=solution.decomposition_upper_bound;
    absoluteGap=solution.decomposition_absolute_gap;relativeGap=solution.decomposition_relative_gap;
    iterations=solution.decomposition_iteration_count;cuts=solution.decomposition_cut_count;
end
primaryConsistency=abs(solution.objective_value-(productionCost+audit.worst_expected_recourse));
fixedConsistency=abs(audit.nominal_expected_recourse-M*nominalMeanShortage);
lexResidual=max([lex.max_demand_balance_error,max(0,lex.max_site_capacity_violation), ...
    lex.max_shortage_preservation_error_kg, ...
    lex.primary_objective_reconstruction_abs_error/max(1,lex.primary_objective_yuan), ...
    lex.secondary_objective_reconstruction_abs_error/max(1,lex.secondary_objective_distance)],[],'omitnan');
maximumResidual=max([audit.maximum_mechanical_residual,lexResidual],[],'omitnan');
etaZeroPass=eta>1e-14||audit.adversary.method_used=="eta_zero_direct_saa";
gapPass=absoluteGap<=1e-4+1e-9||relativeGap<=1e-8+1e-12;
certificatePass=solution.status=="OPTIMAL"&&audit.status=="PASS"&&gapPass&& ...
    audit.strong_duality_gap<=1e-3&&audit.record_probability_sum_residual<=1e-10&& ...
    audit.record_minimum_probability>=-1e-10&&audit.record_divergence_used<=eta+1e-8&& ...
    primaryConsistency<=1e-3&&fixedConsistency<=1e-5&& ...
    lex.max_shortage_preservation_error_kg<=1e-7&& ...
    lex.primary_objective_preservation_error_yuan<=1e-3&& ...
    lexResidual<=1e-7&&etaZeroPass&&~solution.constructed_R_by_R_matrix;

summary=table(caseId,labels(caseId),eta,T(1),T(2),T(3),T(4),sum(T), ...
    binding(1),binding(2),binding(3),binding(4),sum(binding),cH2,productionCost,M, ...
    nominalMeanShortage,nominalMeanEENS,nominalShortageLoss,nominalEconomicTotal, ...
    audit.nominal_expected_recourse,audit.worst_expected_recourse, ...
    solution.objective_value,secondaryExpected,lex.secondary_objective_distance, ...
    solution.solve_runtime_sec,lex.primary_solve_runtime_sec,lex.secondary_solve_runtime_sec, ...
    toc(started),string(solution.status),string(audit.status),certificatePass, ...
    'VariableNames',{'case_id','decision_label','eta','T1_kg','T2_kg','T3_kg','T4_kg', ...
    'TerminalLOH_total_kg','T1_capacity_binding','T2_capacity_binding', ...
    'T3_capacity_binding','T4_capacity_binding','capacity_binding_count', ...
    'c_H2_yuan_per_kg','production_cost_yuan','M_H2_yuan_per_kg', ...
    'nominal_mean_shortage_kg','nominal_mean_EENS_kWh', ...
    'nominal_mean_unserved_cost_yuan','nominal_mean_economic_total_yuan', ...
    'nominal_expected_recourse_yuan','nominal_worst_recourse_yuan', ...
    'robust_primary_objective_yuan','secondary_expected_service_distance', ...
    'secondary_group_sum_service_distance','optimization_runtime_sec', ...
    'lex_primary_runtime_sec','lex_secondary_runtime_sec','case_total_runtime_sec', ...
    'solver_status','audit_status','case_pass'});
writetable(summary,fullfile(caseDir,'optimization_result.csv'));

probability=audit.original_record_worst_probability;
certificate=table(caseId,labels(caseId),eta,LB,UB,absoluteGap,relativeGap, ...
    iterations,cuts,audit.strong_duality_gap,audit.strong_duality_relative_gap, ...
    primaryConsistency,fixedConsistency,audit.record_divergence_used, ...
    eta-audit.record_divergence_used,audit.record_probability_sum_residual, ...
    audit.record_minimum_probability,max(probability),audit.record_effective_sample_size, ...
    sum(probability>1e-15),lex.max_shortage_preservation_error_kg, ...
    lex.primary_objective_preservation_error_yuan,lexResidual,maximumResidual, ...
    etaZeroPass,false,false,false,solution.constructed_R_by_R_matrix,certificatePass, ...
    'VariableNames',{'case_id','decision_label','eta','LB_yuan','UB_yuan', ...
    'absolute_gap_yuan','relative_gap','iteration_count','cut_count', ...
    'strong_duality_gap_yuan','strong_duality_relative_gap', ...
    'primary_objective_reconstruction_error_yuan', ...
    'fixed_T_nominal_reconstruction_error_yuan','divergence_used','divergence_slack', ...
    'probability_sum_residual','minimum_worst_probability','maximum_worst_probability', ...
    'effective_support_size_ESS','positive_probability_support_count', ...
    'lex_shortage_preservation_error_kg','lex_primary_preservation_error_yuan', ...
    'lex_mechanical_residual','maximum_mechanical_residual','eta_zero_direct_SAA_pass', ...
    'C_y_in_primary_objective','C_y_in_Pearson_loss','secondary_changed_T', ...
    'constructed_R_by_R_matrix','certificate_pass'});
writetable(certificate,fullfile(caseDir,'solver_certificate.csv'));
lexAudit=table(caseId,labels(caseId),eta,lex.primary_objective_yuan, ...
    lex.secondary_objective_distance,secondaryExpected, ...
    lex.max_shortage_preservation_error_kg,lex.primary_objective_preservation_error_yuan, ...
    lex.max_demand_balance_error,lex.max_site_capacity_violation, ...
    lex.primary_objective_reconstruction_abs_error, ...
    lex.secondary_objective_reconstruction_abs_error,string(lex.primary_status), ...
    string(lex.secondary_status),lexResidual,certificatePass, ...
    'VariableNames',{'case_id','decision_label','eta','primary_group_sum_yuan', ...
    'secondary_group_sum_service_distance','secondary_expected_service_distance', ...
    'shortage_preservation_error_kg','primary_objective_preservation_error_yuan', ...
    'max_demand_balance_error','max_site_capacity_violation', ...
    'primary_reconstruction_error_yuan','secondary_reconstruction_error', ...
    'primary_status','secondary_status','maximum_mechanical_residual','lexicographic_pass'});
writetable(lexAudit,fullfile(caseDir,'lexicographic_audit.csv'));

fid=fopen(fullfile(caseDir,'mechanical_audit.txt'),'w');cleanup=onCleanup(@()fclose(fid)); %#ok<NASGU>
fprintf(fid,'status=%s\ncase_id=%d\neta=%.12g\nsolver_status=%s\n', ...
    pass_fail(certificatePass),caseId,eta,solution.status);
fprintf(fid,'LB_yuan=%.15g\nUB_yuan=%.15g\nabsolute_gap_yuan=%.15g\nrelative_gap=%.15g\n', ...
    LB,UB,absoluteGap,relativeGap);
fprintf(fid,'strong_duality_gap_yuan=%.15g\ndivergence_used=%.15g\n', ...
    audit.strong_duality_gap,audit.record_divergence_used);
fprintf(fid,'probability_sum_residual=%.15g\nlex_shortage_preservation_error_kg=%.15g\n', ...
    audit.record_probability_sum_residual,lex.max_shortage_preservation_error_kg);
fprintf(fid,'primary_unit=yuan\nC_y_in_primary=0\nC_y_in_Pearson_loss=0\n');
fprintf(fid,'secondary_changed_T=0\nMSP_called=0\nold_Wasserstein_called=0\n');
if ~certificatePass,error('Unified optimization certificate failed for eta %.12g.',eta);end
fprintf('STEP04CC5B_OPT_COMPLETE|case=%d|eta=%.12g|T=[%.9f %.9f %.9f %.9f]|runtime=%.3f\n', ...
    caseId,eta,T,toc(started));
end

function P=read_parameters(rootDir)
raw=load(fullfile(rootDir,'data','yuanqi','near_stage_msp_input.mat'),'NearStageInput');
n=raw.NearStageInput;prices=double(n.Cost.electricity_price_yuan_per_kWh(:));
P.eta_FC=double(n.HydrogenDevice.eta_FC);P.LHV=double(n.HydrogenDevice.h2_lhv_kWh_per_kg);
P.k_H2=double(n.HydrogenDevice.k_H2_kg_per_kWh);P.average_price=mean(prices);
P.SEC_H2=1/P.k_H2;P.c_H2=P.SEC_H2*P.average_price;
P.electricity_per_kg=P.eta_FC*P.LHV;P.M_H2=70*P.electricity_per_kg;
end
function value=pass_fail(passed),if passed,value="PASS";else,value="FAIL";end,end
function assert_git_gate(expectedBranch,expectedHead)
[s1,b]=system('git branch --show-current');[s2,h]=system('git rev-parse HEAD');[s3,u]=system('git rev-parse @{upstream}');
if s1~=0||s2~=0||s3~=0||strtrim(string(b))~=expectedBranch||strtrim(string(h))~=expectedHead||strtrim(string(u))~=expectedHead,error('Step-04C-C5B optimization Git gate failed.');end
end
function add_gurobi_path()
for candidate={fullfile(getenv('GUROBI_HOME'),'matlab'),'D:\gurobi1201\win64\matlab','C:\gurobi1201\win64\matlab'}
    if ~isempty(candidate{1})&&isfolder(candidate{1}),addpath(candidate{1});end
end
end
function hash=sha256_file(fileName)
fid=fopen(fileName,'rb');if fid<0,error('Could not open %s.',fileName);end;cleanup=onCleanup(@()fclose(fid));
md=java.security.MessageDigest.getInstance('SHA-256');while true,bytes=fread(fid,1024*1024,'*uint8');if isempty(bytes),break;end;md.update(typecast(bytes,'int8'));end
digest=typecast(md.digest(),'uint8');hash=lower(string(reshape(dec2hex(digest,2).',1,[])));
end
