%% Step-03Y-D: compare aggregate and period SAA TerminalLOH for all states.
clear; clc;
started = tic;
thisFile = mfilename('fullpath');
thisDir = fileparts(thisFile);
moduleDir = fileparts(thisDir);
rootDir = fileparts(moduleDir);
addpath(rootDir); addpath(thisDir);

expectedBranch = "task/002-stage2b-b3-smoke";
expectedHead = "3942bda1f2f4e8b8620c31ca07a0cc0bf5cdf8c6";
stateIds = (1:35).';
sampleSizes = [100, 500];
formalCap = [300; 200; 100; 150];
tolerance = 1e-7;
objectiveTolerance = 1e-6;
closeCapacityFraction = 0.10;
closeRelativeRegret = 0.01;
runName = "run-001";
outputDir = fullfile(rootDir, 'results', ...
    'task-002-stage2b-b3-smoke', ...
    '33-all-state-period-vs-aggregate-saa', runName);
tempDir = outputDir + ".tmp";
if isfolder(outputDir) || isfolder(tempDir)
    error('Step-03Y-D output path already exists.');
end

[~, branch] = system('git branch --show-current');
[~, head] = system('git rev-parse HEAD');
[~, upstream] = system('git rev-parse "@{upstream}"');
[~, statusBefore] = system('git status --short --branch');
branch = string(strtrim(branch));
head = string(strtrim(head));
upstream = string(strtrim(upstream));
statusBefore = string(strtrim(statusBefore));
if branch ~= expectedBranch || head ~= expectedHead || upstream ~= expectedHead
    error('Step-03Y-D frozen Git baseline mismatch.');
end

protectedRelative = [ ...
    "results/task-002-stage2b-b3-smoke/16-dac-transport-cost-audit/run-001"; ...
    "results/task-002-stage2b-b3-smoke/23-fixed-decision-loss-consistency/run-001.failed-001"; ...
    "results/task-002-stage2b-b3-smoke/24-old-vs-ctilde-fixed-loss"; ...
    "results/task-002-stage2b-b3-smoke/25-old-cost-evidence-trace"; ...
    "results/task-002-stage2b-b3-smoke/26-old-ground-cost-recompute"; ...
    "results/task-002-stage2b-b3-smoke/27-period-data-recoverability/run-001.failed-001"; ...
    "results/task-002-stage2b-b3-smoke/27-period-data-recoverability/run-002/recovered_period_data.mat"; ...
    "results/task-002-stage2b-b3-smoke/30-period-lp-equivalence-audit"; ...
    "results/task-002-stage2b-b3-smoke/31-period-vs-aggregate-terminalLOH"; ...
    "results/task-002-stage2b-b3-smoke/32-saa-weight-capacity-audit"; ...
    "terminalLoh_wdro/src/run_step03XB_old_ground_cost_recompute.py"; ...
    "terminalLoh_wdro/src/run_step03X_old_vs_ctilde_fixed_loss.py"; ...
    "terminalLoh_wdro/src/run_step03YBB_period_lp_equivalence_audit_h2.m"; ...
    "terminalLoh_wdro/src/run_step03YC_period_vs_aggregate_terminalLOH_h2.m"; ...
    "terminalLoh_wdro/src/run_step03YCA_saa_weight_capacity_audit_h2.m"];
protectedBefore = strings(numel(protectedRelative), 1);
for ii = 1:numel(protectedRelative)
    protectedBefore(ii) = path_digest(fullfile(rootDir, protectedRelative(ii)));
    if protectedBefore(ii) == "MISSING"
        error('Step-03Y-D protected path missing: %s', protectedRelative(ii));
    end
end

requiredPrior = [ ...
    string(fullfile(rootDir, 'results', 'task-002-stage2b-b3-smoke', ...
    '27-period-data-recoverability', 'run-002', 'mechanical_audit.txt')); ...
    string(fullfile(rootDir, 'results', 'task-002-stage2b-b3-smoke', ...
    '28-period-vs-aggregate-loss', 'run-001', 'mechanical_audit.txt')); ...
    string(fullfile(rootDir, 'results', 'task-002-stage2b-b3-smoke', ...
    '30-period-lp-equivalence-audit', 'run-001', 'mechanical_audit.txt')); ...
    string(fullfile(rootDir, 'results', 'task-002-stage2b-b3-smoke', ...
    '31-period-vs-aggregate-terminalLOH', 'run-001', 'mechanical_audit.txt')); ...
    string(fullfile(rootDir, 'results', 'task-002-stage2b-b3-smoke', ...
    '32-saa-weight-capacity-audit', 'run-001', 'mechanical_audit.txt'))];
for ii = 1:numel(requiredPrior)
    if ~isfile(requiredPrior(ii)) || ...
            ~contains(fileread(requiredPrior(ii)), 'status=PASS')
        error('Step-03Y-D required prior audit is missing or failed.');
    end
end

peakMemory = memory_snapshot();
[entries, context] = recover_step03Y_prefix_entries_h2( ...
    rootDir, stateIds, 500, true);
entry = entries(1);
peakMemory = max(peakMemory, memory_snapshot());
if ~isequal(context.Cap, formalCap) || context.M ~= 2000 || context.gamma ~= 2
    error('Step-03Y-D frozen model parameters changed.');
end

solverConfig = struct('gurobiOutputFlag', 0, ...
    'gurobiFeasibilityTol', 1e-9, 'gurobiOptimalityTol', 1e-9, ...
    'gurobiTimeLimit', 600, 'objectiveScale', 1, ...
    'gamma', context.gamma);
cases = cell(numel(stateIds), numel(sampleSizes));
solverCallCount = 0;

for ss = 1:numel(stateIds)
    stateId = stateIds(ss);
    stateIdentity = entry.identity(entry.identity.initial_state_id == stateId, :);
    replayPass = height(stateIdentity) == 500 && ...
        all(stateIdentity.replay_state_pass);
    if ~replayPass
        message = "Deterministic period replay failed.";
        if ~isempty(stateIdentity)
            failures = unique(stateIdentity.replay_failure_message( ...
                strlength(stateIdentity.replay_failure_message) > 0));
            if ~isempty(failures)
                message = strjoin(failures, " | ");
            end
        end
        for rr = 1:numel(sampleSizes)
            cases{ss, rr} = failed_case(stateId, sampleSizes(rr), message);
        end
        fprintf('Step-03Y-D state %d replay failed; skipped.\n', stateId);
        continue;
    end

    stateRows = find(entry.identity.initial_state_id == stateId);
    [~, order] = sort(entry.identity.scenario_id(stateRows));
    stateRows = stateRows(order);
    for rr = 1:numel(sampleSizes)
        R = sampleSizes(rr);
        selectedRows = stateRows(1:R);
        caseData = build_case_data(entry, selectedRows, stateId, R);
        try
            aggregate = solve_step03Y_saa_audit_h2("AGGREGATE", ...
                caseData.Dagg, caseData.Aagg, caseData.Cagg, formalCap, ...
                context.M, context.gamma, solverConfig);
            solverCallCount = solverCallCount + 1;
            period = solve_step03Y_saa_audit_h2("PERIOD", ...
                caseData.Dperiod, caseData.Aperiod, caseData.Cperiod, ...
                formalCap, context.M, context.gamma, solverConfig);
            solverCallCount = solverCallCount + 1;
            cases{ss, rr} = build_solved_case(caseData, aggregate, period, ...
                formalCap, tolerance, objectiveTolerance);
        catch exception
            cases{ss, rr} = failed_case(stateId, R, string(exception.message));
        end
    end

    successful = cellfun(@(x) x.pass, cases(ss, :));
    if any(successful)
        try
            [cases(ss, :), crossCalls] = run_state_cross_evaluation( ...
                cases(ss, :), context, solverConfig, objectiveTolerance);
            solverCallCount = solverCallCount + crossCalls;
        catch exception
            for rr = find(successful)
                cases{ss, rr}.pass = false;
                cases{ss, rr}.failure_message = ...
                    "Cross evaluation failed: " + string(exception.message);
            end
        end
    end
    peakMemory = max(peakMemory, memory_snapshot());
    fprintf('Step-03Y-D state %d complete (%d/%d cases passed).\n', ...
        stateId, sum(cellfun(@(x) x.pass, cases(ss, :))), numel(sampleSizes));
end

[comparison, crossEvaluation, stability, screening] = ...
    build_output_tables(cases, stateIds, sampleSizes, formalCap, ...
    closeCapacityFraction, closeRelativeRegret, tolerance);
[screening, recommendationLines] = select_recommended_states( ...
    screening, tolerance);

stateComplete = screening.state_complete;
completedStateCount = sum(stateComplete);
failedStateCount = numel(stateIds) - completedStateCount;
allPass = completedStateCount == numel(stateIds) && ...
    all(comparison.case_pass) && all(crossEvaluation.case_pass) && ...
    all(stability.case_pass);

protectedAfter = strings(numel(protectedRelative), 1);
for ii = 1:numel(protectedRelative)
    protectedAfter(ii) = path_digest(fullfile(rootDir, protectedRelative(ii)));
end
protectedUnchanged = isequal(protectedBefore, protectedAfter);
if ~protectedUnchanged
    error('Step-03Y-D protected path changed during execution.');
end

codeFiles = [string(thisFile); ...
    string(fullfile(thisDir, 'recover_step03Y_prefix_entries_h2.m')); ...
    string(fullfile(thisDir, 'solve_step03Y_saa_audit_h2.m'))];
codeIssueCount = 0;
for ii = 1:numel(codeFiles)
    codeIssueCount = codeIssueCount + numel(checkcode(codeFiles(ii), '-id'));
end
if codeIssueCount ~= 0
    error('Step-03Y-D checkcode found %d issue(s).', codeIssueCount);
end

runtimeSec = toc(started);
peakMemory = max(peakMemory, memory_snapshot());
mkdir(tempDir);
writetable(comparison, ...
    fullfile(tempDir, 'all_state_terminalLOH_comparison.csv'));
writetable(crossEvaluation, ...
    fullfile(tempDir, 'all_state_cross_evaluation.csv'));
writetable(screening, ...
    fullfile(tempDir, 'all_state_screening_summary.csv'));
writetable(stability, fullfile(tempDir, 'sample_size_stability.csv'));
write_lines(fullfile(tempDir, 'recommended_states.txt'), recommendationLines);

auditLines = [ ...
    "status=" + ternary(allPass, "PASS", "PARTIAL_FAIL"); ...
    "branch=" + branch; ...
    "local_head=" + head; ...
    "upstream_head=" + upstream; ...
    "requested_state_count=35"; ...
    "completed_state_count=" + completedStateCount; ...
    "failed_state_count=" + failedStateCount; ...
    "requested_sample_sizes=100,500"; ...
    "R100_is_prefix_of_R500=true"; ...
    "formal_capacity_upper_kg=[300,200,100,150]"; ...
    "shortage_penalty_M=" + context.M; ...
    "holding_coefficient_gamma=" + context.gamma; ...
    "solver_call_count=" + solverCallCount; ...
    "expected_solver_call_count_if_all_states_complete=210"; ...
    "WDRO_call_count=0"; ...
    "MSP_call_count=0"; ...
    "validation_file_count=0"; ...
    "new_random_scenario_count=0"; ...
    "protected_paths_unchanged=" + lower(string(protectedUnchanged)); ...
    "checkcode_issue_count=" + codeIssueCount; ...
    "runtime_sec=" + sprintf('%.6f', runtimeSec); ...
    "peak_working_set_bytes=" + sprintf('%.0f', peakMemory)];
write_lines(fullfile(tempDir, 'mechanical_audit.txt'), auditLines);

conclusionLines = build_conclusion(screening, completedStateCount, ...
    failedStateCount, solverCallCount, runtimeSec, peakMemory, allPass);
write_lines(fullfile(tempDir, 'conclusion.txt'), conclusionLines);
readmeLines = build_readme(screening, completedStateCount, ...
    failedStateCount, solverCallCount, runtimeSec, peakMemory, allPass, ...
    statusBefore, closeCapacityFraction, closeRelativeRegret);
write_lines(fullfile(tempDir, 'README.md'), readmeLines);
movefile(tempDir, outputDir);

append_log(fullfile(rootDir, 'codex_rule', 'log.md'), screening, ...
    completedStateCount, failedStateCount, solverCallCount, ...
    runtimeSec, peakMemory, allPass);
fprintf('Step-03Y-D %s: %d completed, %d failed.\n', ...
    ternary(allPass, "PASS", "PARTIAL_FAIL"), ...
    completedStateCount, failedStateCount);

function data = build_case_data(entry, rows, stateId, R)
data = struct('state_id', stateId, 'R', R, ...
    'identity', entry.identity(rows, :), ...
    'Dagg', entry.Dagg(rows, :), ...
    'Aagg', entry.Aagg(rows, :, :), ...
    'Cagg', entry.Cagg(rows, :, :), ...
    'Dperiod', entry.Dperiod(rows, :, :), ...
    'Aperiod', entry.Aperiod(rows, :, :, :), ...
    'Cperiod', entry.Cperiod(rows, :, :, :));
totalDemand = sum(data.Dagg, 2);
data.positive_demand_count = sum(totalDemand > 1e-10);
data.mean_total_demand = mean(totalDemand);
data.max_total_demand = max(totalDemand);
end

function output = build_solved_case(data, aggregate, period, Cap, tol, objTol)
output = data;
output.aggregate = aggregate;
output.period = period;
output.aggregate_T_in_period = NaN;
output.period_T_in_aggregate = NaN;
output.aggregate_cross_service_cost = NaN;
output.aggregate_cross_shortage_loss = NaN;
output.period_cross_service_cost = NaN;
output.period_cross_shortage_loss = NaN;
output.period_regret_of_aggregate_T = NaN;
output.aggregate_regret_of_period_T = NaN;
output.period_relative_regret = NaN;
output.aggregate_relative_regret = NaN;
output.cross_complete = false;
output.failure_message = "";
output.pass = aggregate.status == "OPTIMAL" && period.status == "OPTIMAL" && ...
    aggregate.objective_weight_sum == 1 && period.objective_weight_sum == 1 && ...
    aggregate.objective_reconstruction_error <= objTol && ...
    period.objective_reconstruction_error <= objTol && ...
    aggregate.max_demand_balance_error <= tol && ...
    period.max_demand_balance_error <= tol && ...
    aggregate.max_site_capacity_violation <= tol && ...
    period.max_site_capacity_violation <= tol && ...
    all(aggregate.T >= -tol & aggregate.T <= Cap + tol) && ...
    all(period.T >= -tol & period.T <= Cap + tol);
if ~output.pass
    output.failure_message = "SAA solve or mechanical reconstruction failed.";
end
end

function output = failed_case(stateId, R, message)
output = struct('state_id', stateId, 'R', R, 'identity', table(), ...
    'Dagg', [], 'Aagg', [], 'Cagg', [], 'Dperiod', [], ...
    'Aperiod', [], 'Cperiod', [], 'positive_demand_count', NaN, ...
    'mean_total_demand', NaN, 'max_total_demand', NaN, ...
    'aggregate', struct(), 'period', struct(), ...
    'aggregate_T_in_period', NaN, 'period_T_in_aggregate', NaN, ...
    'aggregate_cross_service_cost', NaN, ...
    'aggregate_cross_shortage_loss', NaN, ...
    'period_cross_service_cost', NaN, ...
    'period_cross_shortage_loss', NaN, ...
    'period_regret_of_aggregate_T', NaN, ...
    'aggregate_regret_of_period_T', NaN, ...
    'period_relative_regret', NaN, 'aggregate_relative_regret', NaN, ...
    'cross_complete', false, 'pass', false, ...
    'failure_message', string(message));
end

function [caseRow, solverCalls] = run_state_cross_evaluation( ...
        caseRow, context, config, objTol)
successful = find(cellfun(@(x) x.pass, caseRow));
aggD = []; aggA = []; aggC = []; aggT = [];
periodD = []; periodA = []; periodC = []; periodT = [];
segments = zeros(numel(successful), 2);
offset = 0;
for kk = 1:numel(successful)
    index = successful(kk);
    current = caseRow{index};
    R = current.R;
    segments(kk, :) = [offset + 1, offset + R];
    if kk == 1
        aggD = current.Dagg;
        aggA = current.Aagg;
        aggC = current.Cagg;
        aggT = repmat(current.period.T.', R, 1);
        periodD = current.Dperiod;
        periodA = current.Aperiod;
        periodC = current.Cperiod;
        periodT = repmat(current.aggregate.T.', R, 1);
    else
        aggD = cat(1, aggD, current.Dagg);
        aggA = cat(1, aggA, current.Aagg);
        aggC = cat(1, aggC, current.Cagg);
        aggT = cat(1, aggT, repmat(current.period.T.', R, 1));
        periodD = cat(1, periodD, current.Dperiod);
        periodA = cat(1, periodA, current.Aperiod);
        periodC = cat(1, periodC, current.Cperiod);
        periodT = cat(1, periodT, repmat(current.aggregate.T.', R, 1));
    end
    offset = offset + R;
end
aggregateCross = evaluate_step03T_fixed_T_recourse_h2( ...
    aggD, aggA, aggC, aggT, context.M, config);
periodCross = evaluate_step03Y_period_fixed_T_recourse_h2( ...
    periodD, periodA, periodC, periodT, context.M, config);
solverCalls = 2;
if aggregateCross.status ~= "OPTIMAL" || periodCross.status ~= "OPTIMAL"
    error('State cross-evaluation batch was not OPTIMAL.');
end
for kk = 1:numel(successful)
    index = successful(kk);
    current = caseRow{index};
    rows = segments(kk, 1):segments(kk, 2);
    current.period_T_in_aggregate = context.gamma * sum(current.period.T) + ...
        mean(aggregateCross.operating_loss(rows));
    current.aggregate_T_in_period = context.gamma * sum(current.aggregate.T) + ...
        mean(periodCross.operating_loss(rows));
    current.aggregate_cross_service_cost = mean(aggregateCross.service_cost(rows));
    current.aggregate_cross_shortage_loss = mean(aggregateCross.shortage_loss(rows));
    current.period_cross_service_cost = mean(periodCross.service_cost(rows));
    current.period_cross_shortage_loss = mean(periodCross.shortage_loss(rows));
    current.aggregate_regret_of_period_T = ...
        current.period_T_in_aggregate - current.aggregate.objective_value;
    current.period_regret_of_aggregate_T = ...
        current.aggregate_T_in_period - current.period.objective_value;
    current.aggregate_relative_regret = current.aggregate_regret_of_period_T / ...
        max(1, abs(current.aggregate.objective_value));
    current.period_relative_regret = current.period_regret_of_aggregate_T / ...
        max(1, abs(current.period.objective_value));
    current.cross_complete = current.aggregate_regret_of_period_T >= -objTol && ...
        current.period_regret_of_aggregate_T >= -objTol;
    current.pass = current.pass && current.cross_complete;
    if ~current.cross_complete
        current.failure_message = "Cross objective regret is numerically invalid.";
    end
    caseRow{index} = current;
end
end

function [comparison, cross, stability, screening] = build_output_tables( ...
        cases, stateIds, sampleSizes, Cap, closeCapFraction, closeRegret, tol)
comparisonRows = cell(numel(stateIds) * numel(sampleSizes) * 4, 36);
crossRows = cell(numel(stateIds) * numel(sampleSizes) * 4, 24);
stabilityRows = cell(numel(stateIds) * 2 * 5, 15);
comparisonIndex = 0;
crossIndex = 0;
stabilityIndex = 0;
for ss = 1:numel(stateIds)
    for rr = 1:numel(sampleSizes)
        current = cases{ss, rr};
        if current.pass
            totalAgg = sum(current.aggregate.T);
            totalPeriod = sum(current.period.T);
            totalDiff = abs(totalPeriod - totalAgg);
            for site = 1:4
                comparisonIndex = comparisonIndex + 1;
                comparisonRows(comparisonIndex, :) = {current.state_id, current.R, ...
                    site, current.positive_demand_count, current.mean_total_demand, ...
                    current.max_total_demand, 1/current.R, current.aggregate.T(site), ...
                    current.period.T(site), current.period.T(site)-current.aggregate.T(site), ...
                    abs(current.period.T(site)-current.aggregate.T(site)), ...
                    abs(current.period.T(site)-current.aggregate.T(site))/Cap(site), ...
                    totalAgg, totalPeriod, totalPeriod-totalAgg, totalDiff, ...
                    totalDiff/sum(Cap), current.aggregate.T_at_upper_bound(site), ...
                    current.period.T_at_upper_bound(site), ...
                    current.aggregate.objective_value, current.period.objective_value, ...
                    current.aggregate.holding_cost, current.period.holding_cost, ...
                    current.aggregate.mean_service_cost, current.period.mean_service_cost, ...
                    current.aggregate.mean_shortage_loss, current.period.mean_shortage_loss, ...
                    current.aggregate.mean_operating_loss, current.period.mean_operating_loss, ...
                    current.aggregate_regret_of_period_T, current.period_regret_of_aggregate_T, ...
                    current.aggregate_relative_regret, current.period_relative_regret, ...
                    true, "", current.pass};
            end
            target = ["AGGREGATE"; "PERIOD"; "PERIOD"; "AGGREGATE"];
            source = ["T_AGGREGATE"; "T_PERIOD"; "T_AGGREGATE"; "T_PERIOD"];
            Tmatrix = [current.aggregate.T.'; current.period.T.'; ...
                current.aggregate.T.'; current.period.T.'];
            holding = [current.aggregate.holding_cost; current.period.holding_cost; ...
                current.aggregate.holding_cost; current.period.holding_cost];
            operating = [current.aggregate.mean_operating_loss; ...
                current.period.mean_operating_loss; ...
                current.aggregate_T_in_period-current.aggregate.holding_cost; ...
                current.period_T_in_aggregate-current.period.holding_cost];
            service = [current.aggregate.mean_service_cost; current.period.mean_service_cost; ...
                current.period_cross_service_cost; current.aggregate_cross_service_cost];
            shortage = [current.aggregate.mean_shortage_loss; current.period.mean_shortage_loss; ...
                current.period_cross_shortage_loss; current.aggregate_cross_shortage_loss];
            objective = [current.aggregate.objective_value; current.period.objective_value; ...
                current.aggregate_T_in_period; current.period_T_in_aggregate];
            optimum = [current.aggregate.objective_value; current.period.objective_value; ...
                current.period.objective_value; current.aggregate.objective_value];
            for kk = 1:4
                crossIndex = crossIndex + 1;
                regret = objective(kk)-optimum(kk);
                crossRows(crossIndex, :) = {current.state_id, current.R, ...
                    target(kk), source(kk), Tmatrix(kk,1), Tmatrix(kk,2), ...
                    Tmatrix(kk,3), Tmatrix(kk,4), holding(kk), service(kk), ...
                    shortage(kk), operating(kk), objective(kk), optimum(kk), ...
                    regret, regret/max(1,abs(optimum(kk))), ...
                    current.positive_demand_count, current.mean_total_demand, ...
                    current.max_total_demand, current.aggregate.status, ...
                    current.period.status, true, "", current.pass};
            end
        else
            for site = 1:4
                comparisonIndex = comparisonIndex + 1;
                comparisonRows(comparisonIndex, :) = {current.state_id, current.R, ...
                    site, NaN, NaN, NaN, 1/current.R, NaN, NaN, NaN, NaN, ...
                    NaN, NaN, NaN, NaN, NaN, NaN, false, false, NaN, NaN, ...
                    NaN, NaN, NaN, NaN, NaN, NaN, NaN, NaN, NaN, NaN, ...
                    NaN, NaN, false, current.failure_message, false};
            end
        end
    end
    if cases{ss,1}.pass && cases{ss,2}.pass
        for mode = ["AGGREGATE", "PERIOD"]
            if mode == "AGGREGATE"
                T100 = cases{ss,1}.aggregate.T;
                T500 = cases{ss,2}.aggregate.T;
                z100 = cases{ss,1}.aggregate.objective_value;
                z500 = cases{ss,2}.aggregate.objective_value;
            else
                T100 = cases{ss,1}.period.T;
                T500 = cases{ss,2}.period.T;
                z100 = cases{ss,1}.period.objective_value;
                z500 = cases{ss,2}.period.objective_value;
            end
            for site = 1:5
                stabilityIndex = stabilityIndex + 1;
                if site <= 4
                    a = T100(site); b = T500(site); denominator = Cap(site);
                else
                    a = sum(T100); b = sum(T500); denominator = sum(Cap);
                end
                stabilityRows(stabilityIndex, :) = {stateIds(ss), mode, ...
                    site, a, b, b-a, abs(b-a), abs(b-a)/denominator, ...
                    z100, z500, z500-z100, abs(z500-z100)/max(1,abs(z500)), ...
                    true, "", true};
            end
        end
    end
end
comparisonRows = comparisonRows(1:comparisonIndex,:);
crossRows = crossRows(1:crossIndex,:);
stabilityRows = stabilityRows(1:stabilityIndex,:);
comparison = cell2table(comparisonRows, 'VariableNames', ...
    {'initial_state_id','R','site_id','positive_demand_scenario_count', ...
    'mean_total_demand_kg','max_total_demand_kg','scenario_weight', ...
    'T_aggregate_kg','T_period_kg','period_minus_aggregate_kg', ...
    'site_absolute_difference_kg','site_difference_fraction_of_capacity', ...
    'aggregate_total_T_kg','period_total_T_kg','period_minus_aggregate_total_kg', ...
    'total_absolute_difference_kg','total_difference_fraction_of_total_capacity', ...
    'aggregate_at_capacity','period_at_capacity','aggregate_objective', ...
    'period_objective','aggregate_TerminalLOH_cost','period_TerminalLOH_cost', ...
    'aggregate_mean_service_cost','period_mean_service_cost', ...
    'aggregate_mean_shortage_loss','period_mean_shortage_loss', ...
    'aggregate_mean_operating_loss','period_mean_operating_loss', ...
    'aggregate_regret_of_period_T','period_regret_of_aggregate_T', ...
    'aggregate_relative_regret','period_relative_regret', ...
    'replay_complete','failure_message','case_pass'});
cross = cell2table(crossRows, 'VariableNames', ...
    {'initial_state_id','R','evaluation_model','terminalLOH_source', ...
    'T1','T2','T3','T4','TerminalLOH_cost','mean_service_cost', ...
    'mean_shortage_loss','mean_operating_loss','total_objective', ...
    'target_model_optimum','objective_regret','relative_objective_regret', ...
    'positive_demand_scenario_count','mean_total_demand_kg', ...
    'max_total_demand_kg','aggregate_status','period_status', ...
    'replay_complete','failure_message','case_pass'});
stability = cell2table(stabilityRows, 'VariableNames', ...
    {'initial_state_id','model','site_id_5_means_total','T_R100_kg', ...
    'T_R500_kg','R500_minus_R100_kg','absolute_difference_kg', ...
    'difference_fraction_of_capacity','objective_R100','objective_R500', ...
    'objective_change','relative_objective_change','replay_complete', ...
    'failure_message','case_pass'});
screening = build_screening(cases, stateIds, Cap, closeCapFraction, closeRegret, tol);
end

function screening = build_screening(cases, stateIds, Cap, closeCap, closeRegret, ~)
rows = cell(numel(stateIds), 29);
for ss = 1:numel(stateIds)
    c100 = cases{ss,1}; c500 = cases{ss,2}; complete = c100.pass && c500.pass;
    if complete
        maxSiteDiff = max(abs(c500.period.T-c500.aggregate.T));
        maxSiteFraction = max(abs(c500.period.T-c500.aggregate.T)./Cap);
        totalDiff = abs(sum(c500.period.T)-sum(c500.aggregate.T));
        aggregateSat = sum(c500.aggregate.T_at_upper_bound);
        periodSat = sum(c500.period.T_at_upper_bound);
        maxRegret = max(c500.aggregate_relative_regret,c500.period_relative_regret);
        close = maxSiteFraction <= closeCap && totalDiff/sum(Cap) <= closeCap && maxRegret <= closeRegret;
        stableAgg = max(abs(c500.aggregate.T-c100.aggregate.T)./Cap);
        stablePeriod = max(abs(c500.period.T-c100.period.T)./Cap);
        aggregateRel = c500.aggregate_relative_regret;
        periodRel = c500.period_relative_regret;
        aggregateTotal = sum(c500.aggregate.T);
        periodTotal = sum(c500.period.T);
        aggregateObjective = c500.aggregate.objective_value;
        periodObjective = c500.period.objective_value;
        aggregateShortage = c500.aggregate.mean_shortage_loss;
        periodShortage = c500.period.mean_shortage_loss;
        message = "";
    else
        maxSiteDiff=NaN;maxSiteFraction=NaN;totalDiff=NaN;aggregateSat=NaN;periodSat=NaN;maxRegret=NaN;
        close=false;stableAgg=NaN;stablePeriod=NaN;
        aggregateRel=NaN;periodRel=NaN;aggregateTotal=NaN;periodTotal=NaN;
        aggregateObjective=NaN;periodObjective=NaN;aggregateShortage=NaN;periodShortage=NaN;
        message=strjoin(unique([c100.failure_message;c500.failure_message])," | ");
    end
    rows(ss,:)={stateIds(ss),complete,c100.positive_demand_count,c500.positive_demand_count, ...
        c100.mean_total_demand,c500.mean_total_demand,c100.max_total_demand,c500.max_total_demand, ...
        maxSiteDiff,maxSiteFraction,totalDiff,aggregateSat,periodSat, ...
        aggregateRel,periodRel,maxRegret,close, ...
        stableAgg,stablePeriod,aggregateTotal,periodTotal, ...
        aggregateObjective,periodObjective,aggregateShortage,periodShortage, ...
        false,false,false,message};
end
screening=cell2table(rows,'VariableNames',{'initial_state_id','state_complete', ...
    'positive_demand_count_R100','positive_demand_count_R500','mean_demand_R100_kg', ...
    'mean_demand_R500_kg','max_demand_R100_kg','max_demand_R500_kg', ...
    'max_site_T_difference_R500_kg','max_site_T_difference_fraction_R500', ...
    'total_T_difference_R500_kg','aggregate_capacity_hits_R500', ...
    'period_capacity_hits_R500','aggregate_relative_regret_R500', ...
    'period_relative_regret_R500','max_relative_regret_R500','close_diagnostic_R500', ...
    'aggregate_max_R100_R500_site_fraction','period_max_R100_R500_site_fraction', ...
    'aggregate_total_T_R500','period_total_T_R500','aggregate_objective_R500', ...
    'period_objective_R500','aggregate_shortage_loss_R500','period_shortage_loss_R500', ...
    'recommended_attention_state','recommended_control_state','recommendation_eligible', ...
    'failure_message'});
end

function [screening, lines] = select_recommended_states(screening, tol)
complete = screening.state_complete;
eligible = complete & screening.positive_demand_count_R500 > 0 & ...
    screening.aggregate_capacity_hits_R500 < 4 & screening.period_capacity_hits_R500 < 4;
screening.recommendation_eligible = eligible;
positiveThreshold = qvalue(screening.positive_demand_count_R500(complete),0.75);
if any(eligible)
    differenceThreshold = qvalue(screening.max_site_T_difference_R500_kg(eligible),0.75);
else
    differenceThreshold = Inf;
end
attention = eligible & screening.positive_demand_count_R500 >= positiveThreshold & ...
    screening.max_site_T_difference_R500_kg >= differenceThreshold & ...
    screening.max_site_T_difference_R500_kg > tol;
screening.recommended_attention_state = attention;
control = false(height(screening),1);
if any(eligible)
    candidates=find(eligible);
    score=screening.max_site_T_difference_fraction_R500(candidates)+ ...
        screening.max_relative_regret_R500(candidates);
    [~,order]=sortrows([score,-screening.positive_demand_count_R500(candidates)],[1,2]);
    control(candidates(order(1)))=true;
end
screening.recommended_control_state=control;
attentionIds=screening.initial_state_id(attention);
controlIds=screening.initial_state_id(control);
lines=["selection_basis=R500 actual results only"; ...
    "attention_positive_demand_q75_threshold="+sprintf('%.10g',positiveThreshold); ...
    "attention_T_difference_q75_among_unsaturated_states_kg="+sprintf('%.10g',differenceThreshold); ...
    "attention_states="+id_list(attentionIds); ...
    "control_state="+id_list(controlIds); ...
    "attention_rule=positive count at or above all-state q75; neither model fully capacity-saturated; T difference at or above eligible-state q75"; ...
    "control_rule=eligible state minimizing capacity-normalized T difference plus maximum cross relative regret; ties favor more positive-demand samples"; ...
    "no_forced_state_count=true"];
end

function lines = build_conclusion(screening, completed, failed, calls, runtime, memoryBytes, pass)
attention=screening.initial_state_id(screening.recommended_attention_state);
control=screening.initial_state_id(screening.recommended_control_state);
complete=screening.state_complete;
closeCount=sum(screening.close_diagnostic_R500 & complete);
identicalCount=sum(screening.max_site_T_difference_R500_kg<=1e-7 & complete);
fullySaturatedBoth=sum(screening.aggregate_capacity_hits_R500==4 & screening.period_capacity_hits_R500==4 & complete);
lines=["status="+ternary(pass,"PASS","PARTIAL_FAIL"); ...
    "completed_state_count="+completed;"failed_state_count="+failed; ...
    "R500_close_diagnostic_count="+closeCount; ...
    "R500_numerically_identical_T_count="+identicalCount; ...
    "R500_both_models_fully_saturated_count="+fullySaturatedBoth; ...
    "recommended_attention_states="+id_list(attention); ...
    "recommended_control_state="+id_list(control); ...
    "solver_call_count="+calls;"runtime_sec="+sprintf('%.6f',runtime); ...
    "peak_working_set_bytes="+sprintf('%.0f',memoryBytes); ...
    "WDRO_call_count=0";"MSP_call_count=0";"validation_file_count=0"];
end

function lines = build_readme(screening, completed, failed, calls, runtime, memoryBytes, pass, statusBefore, closeCap, closeRegret)
attention=screening.initial_state_id(screening.recommended_attention_state);
control=screening.initial_state_id(screening.recommended_control_state);
complete=screening.state_complete;
closeCount=sum(screening.close_diagnostic_R500 & complete);
identicalCount=sum(screening.max_site_T_difference_R500_kg<=1e-7 & complete);
lines=["# Step-03Y-D run-001";"";"## Scope";""; ...
    "All 35 initial states use the first 100 and first 500 frozen nominal records. Period D/reachability/cost are deterministically replayed from the accepted Step-03Y-A random streams; no new random scenarios are generated.";""; ...
    "## Result";"";"- Mechanical status: `"+ternary(pass,"PASS","PARTIAL_FAIL")+"`."; ...
    "- Completed states: `"+completed+"`; failed states: `"+failed+"`."; ...
    "- R=500 numerically identical aggregate/period T states: `"+identicalCount+"`."; ...
    "- R=500 close diagnostic states: `"+closeCount+"/"+completed+"`. The diagnostic uses maximum site and total capacity fractions <= `"+closeCap+"` and maximum cross relative regret <= `"+closeRegret+"`; it is descriptive, not a formal model threshold."; ...
    "- Recommended attention states: `"+id_list(attention)+"`."; ...
    "- Recommended weak-time-compression control state: `"+id_list(control)+"`."; ...
    "- Solver calls: `"+calls+"`; runtime: `"+sprintf('%.6f',runtime)+" s`; peak working set: `"+sprintf('%.0f',memoryBytes)+" bytes`."; ...
    "- WDRO, MSP, validation, distance, and rho calls: `0`.";""; ...
    "## Frozen start status";"";"```text";statusBefore;"```";""; ...
    "See the CSV files for site-level T, objective decomposition, cross regret, saturation, demand counts, and R=100-to-R=500 stability."];
end

function append_log(logFile, screening, completed, failed, calls, runtime, memoryBytes, pass)
attention=screening.initial_state_id(screening.recommended_attention_state);
control=screening.initial_state_id(screening.recommended_control_state);
complete=screening.state_complete;
closeCount=sum(screening.close_diagnostic_R500 & complete);
identicalCount=sum(screening.max_site_T_difference_R500_kg<=1e-7 & complete);
fid=fopen(logFile,'a');if fid<0,error('Cannot append Step-03Y-D log.');end;cleanup=onCleanup(@()fclose(fid));
fprintf(fid,'\n### 2026-07-28 - task-002 Step-03Y-D run-001 all-state aggregate versus period SAA\n\n');
fprintf(fid,'- Deterministically replayed nominal first R=500 period data for all 35 states and used its exact first-100 prefix for R=100; no new random scenarios, validation, WDRO, MSP, distance, or rho calls.\n');
fprintf(fid,'- Completed states=`%d`, failed states=`%d`; R=500 aggregate/period T is numerically identical in `%d` states and passes the declared close diagnostic in `%d/%d` completed states.\n',completed,failed,identicalCount,closeCount,completed);
fprintf(fid,'- Attention states selected from actual R=500 results: `%s`; weak-time-compression control state: `%s`. Selection requires substantial positive-demand support, no full four-site saturation in either model, and upper-quartile T difference; no count is forced.\n',id_list(attention),id_list(control));
fprintf(fid,'- Mechanical `%s`; solver_call_count=`%d`, runtime=`%.6f s`, peak working set=`%.0f bytes`. Formal capacities and models remain unchanged.\n',ternary(pass,"PASS","PARTIAL_FAIL"),calls,runtime,memoryBytes);
clear cleanup;
end

function value=qvalue(x,p)
x=sort(double(x(:)));x=x(isfinite(x));if isempty(x),value=NaN;return;end
position=numel(x)*p+0.5;if position<=1,value=x(1);elseif position>=numel(x),value=x(end);else,lo=floor(position);fraction=position-lo;value=x(lo)+fraction*(x(lo+1)-x(lo));end
end

function value=id_list(ids)
ids=double(ids(:));if isempty(ids),value="NONE";else,value=strjoin(string(ids.'),",");end
end

function bytes=memory_snapshot()
try
    process=System.Diagnostics.Process.GetCurrentProcess();
    bytes=double(process.WorkingSet64);
catch
    info=memory;
    bytes=double(info.MemUsedMATLAB);
end
end

function digest=path_digest(path)
if isfile(path),digest=sha256_file(path);return;end
if ~isfolder(path),digest="MISSING";return;end
files=dir(fullfile(path,'**','*'));files=files(~[files.isdir]);relative=strings(numel(files),1);
for ii=1:numel(files),fullName=fullfile(files(ii).folder,files(ii).name);relative(ii)=string(erase(fullName,[char(path),filesep]));end
[relative,order]=sort(relative);files=files(order);md=java.security.MessageDigest.getInstance('SHA-256');
for ii=1:numel(files),fullName=fullfile(files(ii).folder,files(ii).name);token=relative(ii)+"|"+string(files(ii).bytes)+"|"+sha256_file(fullName)+newline;md.update(typecast(unicode2native(char(token),'UTF-8'),'int8'));end
raw=typecast(md.digest(),'uint8');digest=lower(string(reshape(dec2hex(raw,2).',1,[])));
end

function hash=sha256_file(fileName)
fid=fopen(fileName,'rb');if fid<0,error('Cannot open protected file.');end;cleanup=onCleanup(@()fclose(fid));md=java.security.MessageDigest.getInstance('SHA-256');
while true,bytes=fread(fid,1024*1024,'*uint8');if isempty(bytes),break;end;md.update(typecast(bytes,'int8'));end
raw=typecast(md.digest(),'uint8');hash=lower(string(reshape(dec2hex(raw,2).',1,[])));clear cleanup;
end

function write_lines(fileName,lines)
fid=fopen(fileName,'w');if fid<0,error('Cannot write output.');end;cleanup=onCleanup(@()fclose(fid));for ii=1:numel(lines),fprintf(fid,'%s\n',lines(ii));end;clear cleanup;
end

function value=ternary(condition,trueValue,falseValue)
if condition,value=trueValue;else,value=falseValue;end
end
