function checks = run_stage2_foundation_reaudit_h2(result, foundation, ...
    comparisonTbl, recommendation, config, protectedBefore)
%RUN_STAGE2_FOUNDATION_REAUDIT_H2 Evidence-based Foundation pass checks.

protectedAfter = snapshot_paths(config.protectedOutputDirs);
protectedSame = isequal(protectedBefore.file_count, protectedAfter.file_count) && ...
    all((isnan(protectedBefore.latest_datenum) & ...
    isnan(protectedAfter.latest_datenum)) | ...
    abs(protectedBefore.latest_datenum - protectedAfter.latest_datenum) < 1e-12);

coord40 = foundation.stage_coordinates( ...
    foundation.stage_coordinates.Wstep == 40, :);
coord40 = sortrows(coord40, 'stage_index');
expected40 = foundation.y_base + [0; 40; 80; 120];
risk = result.risk;
mc = result.mc_by_slice;

dEvidence = independent_D_evidence(config, result);
rngEvidence = common_rng_evidence(config, mc);
oldOutputEvidence = configured_evidence(config, ...
    'no_old_output_overwritten', protectedSame, ...
    'automatic_directory_snapshot_fallback', ...
    'protected output file counts and latest timestamps unchanged');
b3Evidence = configured_or_manual(config, 'no_formal_B3_generated');
wdroEvidence = configured_or_manual(config, 'no_WDRO_run');
mspEvidence = configured_or_manual(config, 'no_MSP_modified');
selectorEvidence = configured_or_manual(config, 'selector_three_way_test');
workspaceEvidence = configured_or_manual(config, ...
    'workspace_complete_change_list');

rows = {};
rows(end + 1, :) = check_row('y_base_source_verified', ...
    abs(foundation.warning_file.y_base(1) - ...
    foundation.recomputed_solution.y_base) <= 1e-5, foundation.y_base, ...
    'automatic_geometry_recompute', ...
    'read warning CSV and independently recomputed with segment distance', '');
rows(end + 1, :) = check_row('closest_point_verified', ...
    foundation.recomputed_solution.closest_loc == 3 && ...
    foundation.recomputed_solution.closest_object_type == "grid_line" && ...
    foundation.recomputed_solution.closest_object_id == 17 && ...
    abs(foundation.recomputed_solution.closest_y - 10) <= 1e-8, ...
    foundation.recomputed_solution.minimum_actual_distance, ...
    'automatic_geometry_recompute', ...
    'closest loc=3, grid_line=17, closest point y=10', '');
rows(end + 1, :) = check_row('lf7_W1_position_different', ...
    coord40.y_coord(1) ~= coord40.y_coord(2), ...
    coord40.y_coord(2) - coord40.y_coord(1), ...
    'automatic_coordinate_check', 'W1 minus lf7 y coordinate', '');
rows(end + 1, :) = check_row('Wstep40_coordinates_correct', ...
    max(abs(coord40.y_coord - expected40)) <= 1e-8, ...
    max(abs(coord40.y_coord - expected40)), ...
    'automatic_coordinate_check', 'compared with y_base+[0,40,80,120]', '');
rows(end + 1, :) = check_row('tau_y_enters_grid_distance', ...
    has_stage_variation(risk, 'line_distance_min'), NaN, ...
    'automatic_table_check', 'line segment distances vary by stage', '');
rows(end + 1, :) = check_row('tau_y_enters_road_distance', ...
    has_stage_variation(risk, 'road_distance_min'), NaN, ...
    'automatic_table_check', 'road segment distances vary by stage', '');
rows(end + 1, :) = check_row('tau_y_enters_wind', ...
    has_stage_variation(risk, 'line_wind_max'), NaN, ...
    'automatic_table_check', 'local line wind varies by stage', '');
rows(end + 1, :) = check_row('tau_y_enters_line_pFail', ...
    has_stage_variation(risk, 'line_pFail_max'), NaN, ...
    'automatic_table_check', 'line failure probabilities vary by stage', '');
rows(end + 1, :) = check_row('tau_y_enters_road_pClose', ...
    has_stage_variation(risk, 'road_pClose_max'), NaN, ...
    'automatic_table_check', 'road closure probabilities vary by stage', '');
rows(end + 1, :) = check_row('tau_y_enters_D', ...
    has_stage_variation_mc(mc, 'D_slice_total_kg'), NaN, ...
    'automatic_table_check', 'MC H2 demand varies across W1/W2/W3', '');
rows(end + 1, :) = check_row('slice_duration_is_1h', ...
    dEvidence.slice_duration_pass, 1, dEvidence.mode, ...
    dEvidence.evidence, '');
rows(end + 1, :) = check_row('Hres_total_is_3h', ...
    dEvidence.Hres_pass, 3, dEvidence.mode, ...
    dEvidence.evidence, '');
rows(end + 1, :) = check_row('D_sum_identity_independent_csv', ...
    dEvidence.pass, dEvidence.max_error, dEvidence.mode, ...
    dEvidence.evidence, dEvidence.warning);
rows(end + 1, :) = check_row('lf7_excluded_from_Hres3h', ...
    dEvidence.lf7_pass, NaN, dEvidence.mode, ...
    dEvidence.evidence, '');
rows(end + 1, :) = check_row('no_duplicate_W_stages', ...
    dEvidence.no_duplicate_pass, NaN, dEvidence.mode, ...
    dEvidence.evidence, '');
rows(end + 1, :) = check_row('old_a_to_Rmax_mapping_disabled', ...
    strcmp(result.Rmax_mode, 'fixed_support_point_no_probability_no_resampling'), ...
    NaN, 'automatic_configuration_check', ...
    'Rmax supplied directly from [30,40,50], independent of a', '');
rows(end + 1, :) = check_row('Rmax_constant_across_stages', ...
    verify_rmax_constant(mc), NaN, 'automatic_table_check', ...
    'Rmax is a fixed test support point for all four stages', '');
rows(end + 1, :) = check_row('Rmax_not_resampled', ...
    verify_rmax_not_resampled(mc), NaN, 'automatic_table_check', ...
    'no Rmax random draw exists in the smoke MC output', '');
rows(end + 1, :) = check_row('common_random_numbers_pass', ...
    rngEvidence.pass, config.mcSeed, rngEvidence.verification_mode, ...
    rngEvidence.evidence, rngEvidence.warning);
rows(end + 1, :) = check_row('recommendation_three_way_capable', ...
    selectorEvidence.pass, NaN, selectorEvidence.verification_mode, ...
    selectorEvidence.evidence, selectorEvidence.warning);
rows(end + 1, :) = check_row('recommendation_not_default_40', ...
    recommendation_not_default(recommendation), ...
    recommendation.recommended_Wstep, 'automatic_recommendation_evidence', ...
    recommendation.reason, '');
rows(end + 1, :) = check_row('recommendation_direction_consistent', ...
    recommendation_direction_consistent(recommendation), NaN, ...
    'automatic_candidate_dominance_check', recommendation.reason, '');
rows(end + 1, :) = check_row('no_old_output_overwritten', ...
    oldOutputEvidence.pass, NaN, oldOutputEvidence.verification_mode, ...
    oldOutputEvidence.evidence, oldOutputEvidence.warning);
rows(end + 1, :) = check_row('no_formal_B3_generated', ...
    b3Evidence.pass, NaN, b3Evidence.verification_mode, ...
    b3Evidence.evidence, b3Evidence.warning);
rows(end + 1, :) = check_row('no_WDRO_run', wdroEvidence.pass, NaN, ...
    wdroEvidence.verification_mode, wdroEvidence.evidence, wdroEvidence.warning);
rows(end + 1, :) = check_row('no_MSP_modified', mspEvidence.pass, NaN, ...
    mspEvidence.verification_mode, mspEvidence.evidence, mspEvidence.warning);
rows(end + 1, :) = check_row('workspace_complete_change_list', ...
    workspaceEvidence.pass, NaN, workspaceEvidence.verification_mode, ...
    workspaceEvidence.evidence, workspaceEvidence.warning);
rows(end + 1, :) = check_row('recommendation_rule_executed', ...
    ismember(recommendation.status, ...
    ["recommend_40", "recommend_45", "inconclusive_40_45"]), ...
    recommendation.relative_D_signal, 'automatic_status_check', ...
    recommendation.status, '');

checks = cell2table(rows, 'VariableNames', ...
    {'check_name', 'passed', 'numeric_value', 'verification_mode', ...
    'evidence', 'warning'});
end

function row = check_row(name, pass, value, mode, evidence, warningText)
if isempty(pass)
    pass = NaN;
end
row = {string(name), double(pass), double(value), string(mode), ...
    string(evidence), string(warningText)};
end

function out = independent_D_evidence(config, result)
if isfield(config, 'audit') && isfield(config.audit, 'D_recheck')
    d = config.audit.D_recheck;
    out = struct('pass', d.reported_vs_recomputed_pass && ...
        d.exact_W123_pass, 'slice_duration_pass', ...
        d.slice_duration_1h_pass, 'Hres_pass', d.Hres_total_3h_pass, ...
        'lf7_pass', d.lf7_excluded_pass, 'no_duplicate_pass', ...
        d.no_duplicate_stage_pass, 'max_error', ...
        d.max_reported_abs_error, 'mode', ...
        "automatic_independent_csv_recompute", ...
        'evidence', compose("scenarios=%d; groups=%d; tolerance=%.3g", ...
        d.scenario_count, d.group_count, d.tolerance), ...
        'warning', d.schema_warning);
else
    err = max(result.D_Hres3h_summary.D_sum_identity_max_abs_error);
    out = struct('pass', err <= 1e-10, ...
        'slice_duration_pass', all(result.mc_by_slice.slice_duration_h( ...
        result.mc_by_slice.included_in_Hres3h > 0.5) == 1), ...
        'Hres_pass', all(result.D_Hres3h_summary.Hres_total_h == 3), ...
        'lf7_pass', NaN, 'no_duplicate_pass', NaN, 'max_error', err, ...
        'mode', "summary_fallback_not_independent", ...
        'evidence', "Independent CSV recomputation evidence was not supplied.", ...
        'warning', "manual verification required");
end
end

function out = common_rng_evidence(config, mc)
if isfield(config, 'audit') && isfield(config.audit, 'common_random_numbers')
    out = config.audit.common_random_numbers;
else
    out = struct('pass', verify_common_random_numbers(mc), ...
        'verification_mode', "automatic_seed_pair_fallback", ...
        'evidence', "matching Rmax/a/loc/stage/mc rows use the same seed", ...
        'warning', "source loop order not independently scanned");
end
end

function out = configured_evidence(config, fieldName, fallbackPass, mode, detail)
if isfield(config, 'audit') && isfield(config.audit, fieldName)
    out = config.audit.(fieldName);
else
    out = struct('pass', logical(fallbackPass), ...
        'verification_mode', string(mode), 'evidence', string(detail), ...
        'warning', "");
end
end

function out = configured_or_manual(config, fieldName)
if isfield(config, 'audit') && isfield(config.audit, fieldName)
    out = config.audit.(fieldName);
else
    out = struct('pass', NaN, ...
        'verification_mode', "manual_verification_required", ...
        'evidence', compose("No automated evidence supplied for %s.", fieldName), ...
        'warning', "manual verification required");
end
end

function tf = recommendation_not_default(rec)
validStatus = ismember(rec.status, ...
    ["recommend_40", "recommend_45", "inconclusive_40_45"]);
hasBoth = height(rec.candidate_summary) == 2 && ...
    isequal(sort(rec.candidate_summary.candidate_Wstep), [40;45]);
tf = validStatus && hasBoth && ...
    strlength(rec.reason) > 0;
end

function tf = recommendation_direction_consistent(rec)
S = rec.candidate_summary;
switch rec.status
    case "recommend_40"
        chosen = S(S.candidate_Wstep == 40, :);
        other = S(S.candidate_Wstep == 45, :);
        tf = chosen.physically_valid && ...
            chosen.joint_support_Rmax_count > other.joint_support_Rmax_count;
    case "recommend_45"
        chosen = S(S.candidate_Wstep == 45, :);
        other = S(S.candidate_Wstep == 40, :);
        tf = chosen.physically_valid && ...
            chosen.joint_support_Rmax_count > other.joint_support_Rmax_count;
    case "inconclusive_40_45"
        tf = true;
    otherwise
        tf = false;
end
end

function tf = has_stage_variation(T, fieldName)
tf = false;
groups = unique(T(:, {'Rmax', 'Wstep', 'a', 'loc'}), 'rows');
for gg = 1:height(groups)
    sub = T(T.Rmax == groups.Rmax(gg) & T.Wstep == groups.Wstep(gg) & ...
        T.a == groups.a(gg) & T.loc == groups.loc(gg), :);
    x = sub.(fieldName);
    if max(x) - min(x) > 1e-10
        tf = true;
        return;
    end
end
end

function tf = has_stage_variation_mc(T, fieldName)
sub = T(T.included_in_Hres3h > 0.5, :);
means = groupsummary(sub, {'Rmax', 'Wstep', 'a', 'loc', 'stage_index'}, ...
    'mean', fieldName);
tf = false;
groups = unique(means(:, {'Rmax', 'Wstep', 'a', 'loc'}), 'rows');
meanName = ['mean_' fieldName];
for gg = 1:height(groups)
    x = means.(meanName)(means.Rmax == groups.Rmax(gg) & ...
        means.Wstep == groups.Wstep(gg) & means.a == groups.a(gg) & ...
        means.loc == groups.loc(gg));
    if max(x) - min(x) > 1e-10
        tf = true;
        return;
    end
end
end

function tf = verify_rmax_constant(T)
groups = unique(T(:, {'Rmax', 'Wstep', 'a', 'loc', 'mc_id'}), 'rows');
tf = height(groups) * 4 == height(T);
end

function tf = verify_rmax_not_resampled(T)
tf = all(ismember(unique(T.Rmax), [30; 40; 50]));
end

function tf = verify_common_random_numbers(T)
tf = true;
groups = unique(T(:, {'Rmax', 'a', 'loc', 'stage_index', 'mc_id'}), 'rows');
for gg = 1:height(groups)
    sub = T(T.Rmax == groups.Rmax(gg) & T.a == groups.a(gg) & ...
        T.loc == groups.loc(gg) & T.stage_index == groups.stage_index(gg) & ...
        T.mc_id == groups.mc_id(gg), :);
    if height(sub) ~= 2 || numel(unique(sub.common_random_seed)) ~= 1
        tf = false;
        return;
    end
end
end

function snap = snapshot_paths(paths)
snap = table(strings(numel(paths), 1), zeros(numel(paths), 1), ...
    zeros(numel(paths), 1), 'VariableNames', ...
    {'path', 'file_count', 'latest_datenum'});
for ii = 1:numel(paths)
    p = paths{ii};
    snap.path(ii) = string(p);
    if ~isfolder(p)
        snap.file_count(ii) = -1;
        snap.latest_datenum(ii) = NaN;
        continue;
    end
    items = dir(fullfile(p, '**', '*'));
    items = items(~[items.isdir]);
    snap.file_count(ii) = numel(items);
    if isempty(items)
        snap.latest_datenum(ii) = 0;
    else
        snap.latest_datenum(ii) = max([items.datenum]);
    end
end
end
