clear; clc;

thisDir=fileparts(mfilename('fullpath'));
moduleDir=fileparts(thisDir);
rootDir=fileparts(moduleDir);

taskId="task-001";
stepId="03-stage2b-tail-candidate-design";
runId="run-005";
outputDir=fullfile(moduleDir,'output','stage2b_tail_candidate_design','run-005');
observedFile=fullfile(moduleDir,'output','stage2b_tail_candidate_design', ...
    'run-002','tail_pareto_candidate_paths.csv');
observedArchiveFile=fullfile(rootDir,'results','task-001-stage2a2-path-prob', ...
    '03-stage2b-tail-candidate-design','run-002','tail_pareto_candidate_paths.csv');
unobservedFile=fullfile(moduleDir,'output','stage2b_tail_candidate_design', ...
    'run-004','reexported_unobserved_pareto_paths.csv');
unobservedArchiveFile=fullfile(rootDir,'results','task-001-stage2a2-path-prob', ...
    '03-stage2b-tail-candidate-design','run-004', ...
    'reexported_unobserved_pareto_paths.csv');
mainSampleFile=fullfile(moduleDir,'output','stage2a2_W3_path_sampling', ...
    'run-002','main_path_samples.csv');

expectedObservedRows=1595;
expectedUnobservedLevelCounts=[858;788;764];
expectedUnobservedRows=sum(expectedUnobservedLevelCounts);
expectedMainRows=525000;
expectedMainHash= ...
    "972a8c58620c09ac19cfcfb29e8d6a3ed2819ef1a22dbd522043436418eb805d";
probabilityTolerance=1e-12;
levels=[0.95;0.99;0.995];
levelLabels=["q95";"q99";"q995"];
proxyNames=["grid_max_wind_mps";"grid_cumulative_excess_mps"; ...
    "road_max_wind_mps";"road_cumulative_excess_mps"];
proxyShort=["grid_max";"grid_excess";"road_max";"road_excess"];

inputFiles={observedFile,observedArchiveFile,unobservedFile, ...
    unobservedArchiveFile,mainSampleFile};
for ii=1:numel(inputFiles)
    if ~isfile(inputFiles{ii})
        error('run_stage2b_deduplicate_tail_paths_h2:MissingInput', ...
            'Missing required input: %s',inputFiles{ii});
    end
end
if isfolder(outputDir)
    existing=dir(outputDir);
    existing=existing(~ismember({existing.name},{'.','..'}));
    if ~isempty(existing)
        error('run_stage2b_deduplicate_tail_paths_h2:OutputExists', ...
            'Refusing to overwrite nonempty output directory: %s',outputDir);
    end
else
    mkdir(outputDir);
end

observed=readtable(observedFile,'TextType','string');
observedArchive=readtable(observedArchiveFile,'TextType','string');
unobserved=readtable(unobservedFile,'TextType','string');
unobservedArchive=readtable(unobservedArchiveFile,'TextType','string');

observedRequired={'risk_proxy','quantile_level','a0','loc0','lfw0', ...
    'unique_path_id','a_W1','a_W2','a_W3','loc_W1','loc_W2','loc_W3', ...
    'lfw_W1','lfw_W2','lfw_W3','frequency','empirical_mass', ...
    'path_probability','grid_max_wind_mps','grid_cumulative_excess_mps', ...
    'road_max_wind_mps','road_cumulative_excess_mps'};
unobservedRequired={'quantile_level','a0','loc0','lfw0','path_code', ...
    'a_W1','a_W2','a_W3','loc_W1','loc_W2','loc_W3','lfw_W1','lfw_W2', ...
    'lfw_W3','path_probability','grid_max_wind_mps', ...
    'grid_cumulative_excess_mps','road_max_wind_mps', ...
    'road_cumulative_excess_mps','pareto_grid_max','pareto_grid_excess', ...
    'pareto_road_max','pareto_road_excess','pareto_only_output'};
require_vars(observed,observedRequired,observedFile);
require_vars(observedArchive,observedRequired,observedArchiveFile);
require_vars(unobserved,unobservedRequired,unobservedFile);
require_vars(unobservedArchive,unobservedRequired,unobservedArchiveFile);

observedHash=sha256_file(observedFile);
observedArchiveHash=sha256_file(observedArchiveFile);
unobservedHash=sha256_file(unobservedFile);
unobservedArchiveHash=sha256_file(unobservedArchiveFile);
[mainRows,mainFields]=count_csv_rows_and_fields(mainSampleFile);
mainHash=sha256_file(mainSampleFile);

print_table_input(observedFile,observed,observedHash);
print_table_input(observedArchiveFile,observedArchive,observedArchiveHash);
print_table_input(unobservedFile,unobserved,unobservedHash);
print_table_input(unobservedArchiveFile,unobservedArchive,unobservedArchiveHash);
fprintf('INPUT|path=%s|rows=%d|fields=%s|sha256=%s\n',mainSampleFile, ...
    mainRows,strjoin(mainFields,','),mainHash);
fprintf('BEGIN_PHYSICAL_PATH_DEDUPLICATION\n');

observedProxy=string(observed.risk_proxy);
unknownObservedProxy=~ismember(observedProxy,proxyNames);
if any(unknownObservedProxy)
    error('run_stage2b_deduplicate_tail_paths_h2:UnknownProxy', ...
        'Observed input has unknown risk_proxy values: %s', ...
        strjoin(unique(observedProxy(unknownObservedProxy)),', '));
end

nObserved=height(observed);nUnobserved=height(unobserved);
records=table( ...
    [repmat("observed",nObserved,1);repmat("unobserved",nUnobserved,1)], ...
    [(1:nObserved).';(1:nUnobserved).'], ...
    [string(observed.unique_path_id);string(unobserved.path_code)], ...
    [double(observed.a0);double(unobserved.a0)], ...
    [double(observed.loc0);double(unobserved.loc0)], ...
    [double(observed.lfw0);double(unobserved.lfw0)], ...
    [double(observed.a_W1);double(unobserved.a_W1)], ...
    [double(observed.loc_W1);double(unobserved.loc_W1)], ...
    [double(observed.lfw_W1);double(unobserved.lfw_W1)], ...
    [double(observed.a_W2);double(unobserved.a_W2)], ...
    [double(observed.loc_W2);double(unobserved.loc_W2)], ...
    [double(observed.lfw_W2);double(unobserved.lfw_W2)], ...
    [double(observed.a_W3);double(unobserved.a_W3)], ...
    [double(observed.loc_W3);double(unobserved.loc_W3)], ...
    [double(observed.lfw_W3);double(unobserved.lfw_W3)], ...
    [double(observed.quantile_level);double(unobserved.quantile_level)], ...
    [double(observed.path_probability);double(unobserved.path_probability)], ...
    [double(observed.frequency);zeros(nUnobserved,1)], ...
    [double(observed.empirical_mass);zeros(nUnobserved,1)], ...
    [double(observed.grid_max_wind_mps);double(unobserved.grid_max_wind_mps)], ...
    [double(observed.grid_cumulative_excess_mps); ...
        double(unobserved.grid_cumulative_excess_mps)], ...
    [double(observed.road_max_wind_mps);double(unobserved.road_max_wind_mps)], ...
    [double(observed.road_cumulative_excess_mps); ...
        double(unobserved.road_cumulative_excess_mps)], ...
    [observedProxy==proxyNames(1);as_logical(unobserved.pareto_grid_max)], ...
    [observedProxy==proxyNames(2);as_logical(unobserved.pareto_grid_excess)], ...
    [observedProxy==proxyNames(3);as_logical(unobserved.pareto_road_max)], ...
    [observedProxy==proxyNames(4);as_logical(unobserved.pareto_road_excess)], ...
    'VariableNames',{'candidate_source','source_row_id','source_path_id', ...
    'a0','loc0','lfw0','a1','loc1','lfw1','a2','loc2','lfw2', ...
    'a3','loc3','lfw3','quantile_level','path_probability', ...
    'observed_frequency','observed_empirical_mass','grid_max_wind_mps', ...
    'grid_cumulative_excess_mps','road_max_wind_mps', ...
    'road_cumulative_excess_mps','hit_grid_max','hit_grid_excess', ...
    'hit_road_max','hit_road_excess'});

keyNames={'a0','loc0','lfw0','a1','loc1','lfw1','a2','loc2','lfw2', ...
    'a3','loc3','lfw3'};
records=sortrows(records,[keyNames,{'candidate_source','quantile_level', ...
    'source_row_id'}]);
[groupId,keyTable]=findgroups(records(:,keyNames));
nUnique=height(keyTable);
records.unique_path_id=groupId;

isObserved=false(nUnique,1);isUnobserved=false(nUnique,1);
observedFrequency=zeros(nUnique,1);observedMass=zeros(nUnique,1);
listed=false(nUnique,3);paretoLevel=false(nUnique,3);
proxyLevel=false(nUnique,4,3);proxyAny=false(nUnique,4);
sourceRecordCount=zeros(nUnique,1);observedRecordCount=zeros(nUnique,1);
unobservedRecordCount=zeros(nUnique,1);probability=zeros(nUnique,1);
probMin=zeros(nUnique,1);probMax=zeros(nUnique,1);probRange=zeros(nUnique,1);
frequencyRange=zeros(nUnique,1);massRange=zeros(nUnique,1);
observedSourceId=strings(nUnique,1);unobservedSourceId=strings(nUnique,1);
riskValues=zeros(nUnique,4);

for gg=1:nUnique
    mask=groupId==gg;
    obsMask=mask & records.candidate_source=="observed";
    unobsMask=mask & records.candidate_source=="unobserved";
    isObserved(gg)=any(obsMask);isUnobserved(gg)=any(unobsMask);
    sourceRecordCount(gg)=sum(mask);observedRecordCount(gg)=sum(obsMask);
    unobservedRecordCount(gg)=sum(unobsMask);
    values=records.path_probability(mask);
    probMin(gg)=min(values);probMax(gg)=max(values);
    probRange(gg)=probMax(gg)-probMin(gg);probability(gg)=values(1);
    first=find(mask,1);
    riskValues(gg,:)=[records.grid_max_wind_mps(first), ...
        records.grid_cumulative_excess_mps(first),records.road_max_wind_mps(first), ...
        records.road_cumulative_excess_mps(first)];
    if any(obsMask)
        frequencyValues=records.observed_frequency(obsMask);
        massValues=records.observed_empirical_mass(obsMask);
        observedFrequency(gg)=frequencyValues(1);observedMass(gg)=massValues(1);
        frequencyRange(gg)=max(frequencyValues)-min(frequencyValues);
        massRange(gg)=max(massValues)-min(massValues);
        observedSourceId(gg)=records.source_path_id(find(obsMask,1));
    end
    if any(unobsMask)
        unobservedSourceId(gg)=records.source_path_id(find(unobsMask,1));
    end
    for ll=1:3
        levelMask=mask & abs(records.quantile_level-levels(ll))<1e-12;
        listed(gg,ll)=any(levelMask);
        proxyLevel(gg,1,ll)=any(records.hit_grid_max(levelMask));
        proxyLevel(gg,2,ll)=any(records.hit_grid_excess(levelMask));
        proxyLevel(gg,3,ll)=any(records.hit_road_max(levelMask));
        proxyLevel(gg,4,ll)=any(records.hit_road_excess(levelMask));
        paretoLevel(gg,ll)=any(proxyLevel(gg,:,ll));
    end
    proxyAny(gg,:)=reshape(any(proxyLevel(gg,:,:),3),1,4);
end

highestLevel=strings(nUnique,1);
highestLevel(listed(:,1))="q95";
highestLevel(listed(:,2))="q99";
highestLevel(listed(:,3))="q995";
numberListedLevels=sum(listed,2);

uniquePaths=addvars(keyTable,(1:nUnique).','Before',1, ...
    'NewVariableNames','unique_path_id');
uniquePaths=addvars(uniquePaths,probability,isObserved,isUnobserved, ...
    observedFrequency,observedMass,listed(:,1),listed(:,2),listed(:,3), ...
    highestLevel,numberListedLevels,paretoLevel(:,1),paretoLevel(:,2), ...
    paretoLevel(:,3),proxyAny(:,1),proxyAny(:,2),proxyAny(:,3),proxyAny(:,4), ...
    'NewVariableNames',{'path_probability','is_observed_candidate', ...
    'is_unobserved_candidate','observed_frequency','observed_empirical_mass', ...
    'listed_q95','listed_q99','listed_q995','highest_listed_level', ...
    'listed_level_count','pareto_q95','pareto_q99','pareto_q995', ...
    'hit_grid_max','hit_grid_excess','hit_road_max','hit_road_excess'});

for mm=1:4
    for ll=1:3
        variableName=char(proxyShort(mm)+"_"+levelLabels(ll));
        uniquePaths.(variableName)=proxyLevel(:,mm,ll);
    end
end
uniquePaths.source_record_count=sourceRecordCount;
uniquePaths.observed_source_record_count=observedRecordCount;
uniquePaths.unobserved_source_record_count=unobservedRecordCount;
uniquePaths.observed_source_unique_path_id=observedSourceId;
uniquePaths.unobserved_source_path_code=unobservedSourceId;
uniquePaths.grid_max_wind_mps=riskValues(:,1);
uniquePaths.grid_cumulative_excess_mps=riskValues(:,2);
uniquePaths.road_max_wind_mps=riskValues(:,3);
uniquePaths.road_cumulative_excess_mps=riskValues(:,4);

probabilityAudit=table((1:nUnique).',sourceRecordCount,probMin,probMax, ...
    probRange,probRange<=probabilityTolerance,frequencyRange,massRange, ...
    'VariableNames',{'unique_path_id','source_record_count', ...
    'path_probability_min','path_probability_max','path_probability_range', ...
    'probability_consistent','observed_frequency_range', ...
    'observed_empirical_mass_range'});

traceability=records(:,{'candidate_source','source_row_id','source_path_id', ...
    'unique_path_id','quantile_level','path_probability','hit_grid_max', ...
    'hit_grid_excess','hit_road_max','hit_road_excess','a0','loc0','lfw0', ...
    'a1','loc1','lfw1','a2','loc2','lfw2','a3','loc3','lfw3'});
traceability=sortrows(traceability,{'candidate_source','source_row_id'});

levelRows=cell(3,7);
for ll=1:3
    recordMask=abs(records.quantile_level-levels(ll))<1e-12;
    uniqueMask=listed(:,ll);
    levelRows(ll,:)={levels(ll),levelLabels(ll),sum(recordMask), ...
        sum(recordMask & records.candidate_source=="observed"), ...
        sum(recordMask & records.candidate_source=="unobserved"), ...
        sum(uniqueMask),sum(uniqueMask & isObserved)};
end
byLevel=cell2table(levelRows,'VariableNames', ...
    {'quantile_level','level_label','input_record_count', ...
    'observed_input_record_count','unobserved_input_record_count', ...
    'unique_path_count','observed_unique_path_count'});
byLevel.unobserved_unique_path_count=byLevel.unique_path_count- ...
    byLevel.observed_unique_path_count;

proxyRows=cell(4,10);
recordProxyFlags=[records.hit_grid_max,records.hit_grid_excess, ...
    records.hit_road_max,records.hit_road_excess];
for mm=1:4
    uniqueMask=proxyAny(:,mm);recordMask=recordProxyFlags(:,mm);
    proxyRows(mm,:)={proxyNames(mm),proxyShort(mm),sum(recordMask), ...
        sum(recordMask & records.candidate_source=="observed"), ...
        sum(recordMask & records.candidate_source=="unobserved"), ...
        sum(uniqueMask),sum(uniqueMask & isObserved),sum(uniqueMask & isUnobserved), ...
        sum(proxyLevel(:,mm,1)),sum(proxyLevel(:,mm,2))};
end
byProxy=cell2table(proxyRows,'VariableNames', ...
    {'risk_proxy','proxy_label','source_label_record_count', ...
    'observed_label_record_count','unobserved_label_record_count', ...
    'unique_path_count','observed_unique_path_count', ...
    'unobserved_unique_path_count','q95_unique_path_count', ...
    'q99_unique_path_count'});
for mm=1:4
    byProxy.q995_unique_path_count(mm)=sum(proxyLevel(:,mm,3));
end

[AA,LL]=ndgrid((2:6).',(1:7).');
initialRows=cell(numel(AA),13);
for ii=1:numel(AA)
    stateMask=uniquePaths.a0==AA(ii) & uniquePaths.loc0==LL(ii) & ...
        uniquePaths.lfw0==0;
    initialRows(ii,:)={AA(ii),LL(ii),0,sum(stateMask), ...
        sum(stateMask & isObserved),sum(stateMask & isUnobserved), ...
        sum(stateMask & isObserved & isUnobserved), ...
        sum(stateMask & listed(:,1)),sum(stateMask & listed(:,2)), ...
        sum(stateMask & listed(:,3)),sum(stateMask & numberListedLevels==1), ...
        sum(stateMask & numberListedLevels==2),sum(stateMask & numberListedLevels==3)};
end
byInitialState=cell2table(initialRows,'VariableNames', ...
    {'a0','loc0','lfw0','unique_path_count','observed_unique_path_count', ...
    'unobserved_unique_path_count','observed_unobserved_overlap_count', ...
    'q95_unique_path_count','q99_unique_path_count','q995_unique_path_count', ...
    'one_level_path_count','two_level_path_count','three_level_path_count'});

overlapCount=sum(isObserved & isUnobserved);
probabilityConflictCount=sum(~probabilityAudit.probability_consistent);
inputRows=height(records);
duplicateRowsRemoved=inputRows-nUnique;
stateCounts=byInitialState.unique_path_count;
overall=table(nObserved,nUnobserved,inputRows,nUnique,duplicateRowsRemoved, ...
    sum(numberListedLevels==1),sum(numberListedLevels==2), ...
    sum(numberListedLevels==3),sum(listed(:,1)),sum(listed(:,2)), ...
    sum(listed(:,3)),sum(isObserved),sum(isUnobserved),overlapCount, ...
    probabilityConflictCount,height(byInitialState),min(stateCounts), ...
    mean(stateCounts),median(stateCounts),max(stateCounts), ...
    'VariableNames',{'observed_input_record_count', ...
    'unobserved_input_record_count','input_record_count_total', ...
    'unique_path_count','duplicate_record_count_removed','one_level_path_count', ...
    'two_level_path_count','three_level_path_count','q95_unique_path_count', ...
    'q99_unique_path_count','q995_unique_path_count', ...
    'observed_unique_path_count','unobserved_unique_path_count', ...
    'observed_unobserved_overlap_count','path_probability_conflict_count', ...
    'initial_state_count','initial_state_candidate_count_min', ...
    'initial_state_candidate_count_mean','initial_state_candidate_count_median', ...
    'initial_state_candidate_count_max'});

unobservedLevelCounts=zeros(3,1);
for ll=1:3
    unobservedLevelCounts(ll)=sum(abs(double(unobserved.quantile_level)-levels(ll))<1e-12);
end
allInputMapped=height(traceability)==inputRows && all(traceability.unique_path_id>=1) && ...
    all(traceability.unique_path_id<=nUnique);
uniqueIdPass=numel(unique(uniquePaths.unique_path_id))==nUnique;
physicalKeyPass=height(unique(uniquePaths(:,keyNames),'rows'))==nUnique;
mainSamplePass=mainRows==expectedMainRows && mainHash==expectedMainHash;
sourceVersionPass=observedHash==observedArchiveHash && ...
    unobservedHash==unobservedArchiveHash;
frozenUnobservedPass=isequal(unobservedLevelCounts,expectedUnobservedLevelCounts);
initialStatePass=height(byInitialState)==35 && all(stateCounts>0);

checks={};
checks=add_check(checks,"AUDIT-01","local and Git input versions match", ...
    sourceVersionPass,strjoin([observedHash,unobservedHash],' | '), ...
    strjoin([observedArchiveHash,unobservedArchiveHash],' | '));
checks=add_check(checks,"AUDIT-02","observed input row count", ...
    nObserved==expectedObservedRows,nObserved,expectedObservedRows);
checks=add_check(checks,"AUDIT-03","run-004 frozen level counts", ...
    frozenUnobservedPass,strjoin(compose('%d',unobservedLevelCounts),'/'), ...
    strjoin(compose('%d',expectedUnobservedLevelCounts),'/'));
checks=add_check(checks,"AUDIT-04","all input records map to one physical path", ...
    allInputMapped,height(traceability),inputRows);
checks=add_check(checks,"AUDIT-05","unique_path_id has no duplicates", ...
    uniqueIdPass,numel(unique(uniquePaths.unique_path_id)),nUnique);
checks=add_check(checks,"AUDIT-06","physical path key has one output row", ...
    physicalKeyPass,height(unique(uniquePaths(:,keyNames),'rows')),nUnique);
checks=add_check(checks,"AUDIT-07","path_probability consistency", ...
    probabilityConflictCount==0,probabilityConflictCount,0);
checks=add_check(checks,"AUDIT-08","observed/unobserved physical overlap", ...
    overlapCount==0,overlapCount,0);
checks=add_check(checks,"AUDIT-09","main sample row count and SHA-256", ...
    mainSamplePass,mainHash,expectedMainHash);
checks=add_check(checks,"AUDIT-10","35 initial states represented", ...
    initialStatePass,height(byInitialState),35);
checks=add_check(checks,"AUDIT-11","source record traceability conserved", ...
    sum(uniquePaths.source_record_count)==inputRows, ...
    sum(uniquePaths.source_record_count),inputRows);
checks=add_check(checks,"AUDIT-12","no non-Pareto source records", ...
    all(any(recordProxyFlags,2)),sum(~any(recordProxyFlags,2)),0);
checks=add_check(checks,"AUDIT-13","observed frequency and mass consistent", ...
    all(frequencyRange==0) && all(massRange<=1e-15), ...
    max([frequencyRange;massRange]),0);
auditChecks=cell2table(checks,'VariableNames', ...
    {'check_id','description','passed','observed','expected'});
passCount=sum(auditChecks.passed);failCount=sum(~auditChecks.passed);
status="PASS";if failCount>0,status="FAIL";end

writetable(uniquePaths,fullfile(outputDir,'unique_tail_paths.csv'));
writetable(overall,fullfile(outputDir,'dedup_summary_overall.csv'));
writetable(byInitialState,fullfile(outputDir,'dedup_summary_by_initial_state.csv'));
writetable(byLevel,fullfile(outputDir,'dedup_summary_by_level.csv'));
writetable(byProxy,fullfile(outputDir,'dedup_summary_by_risk_proxy.csv'));
writetable(probabilityAudit,fullfile(outputDir, ...
    'path_probability_consistency_audit.csv'));
writetable(traceability,fullfile(outputDir,'source_record_traceability.csv'));
writetable(auditChecks,fullfile(outputDir,'audit_checklist.csv'));
write_manifest(fullfile(outputDir,'run_manifest.txt'),taskId,stepId,runId, ...
    status,passCount,failCount,observedFile,observedHash,unobservedFile, ...
    unobservedHash,mainSampleFile,mainHash,overall);
write_readme(fullfile(outputDir,'README.txt'),status,passCount,failCount, ...
    overall,byLevel,byProxy,probabilityTolerance);

fprintf('\nTail-path physical deduplication finished.\n');
fprintf('Status: %s; PASS=%d; FAIL=%d\n',status,passCount,failCount);
fprintf('Input rows: %d; unique physical paths: %d; duplicates removed: %d\n', ...
    inputRows,nUnique,duplicateRowsRemoved);
fprintf('Observed unique: %d; unobserved unique: %d; overlap: %d\n', ...
    sum(isObserved),sum(isUnobserved),overlapCount);
fprintf('One/two/three levels: %d/%d/%d\n',sum(numberListedLevels==1), ...
    sum(numberListedLevels==2),sum(numberListedLevels==3));
fprintf('Probability conflicts: %d\n',probabilityConflictCount);
fprintf('Output directory: %s\n',outputDir);
if failCount>0
    error('run_stage2b_deduplicate_tail_paths_h2:AuditFailed', ...
        'Deduplication audit failed: %s', ...
        strjoin(auditChecks.check_id(~auditChecks.passed),', '));
end

function require_vars(tbl,names,fileName)
for ii=1:numel(names)
    if ~ismember(names{ii},tbl.Properties.VariableNames)
        error('%s missing required field %s.',fileName,names{ii});
    end
end
end

function values=as_logical(values)
if islogical(values)
    return;
elseif isnumeric(values)
    values=values~=0;
else
    text=lower(strtrim(string(values)));
    values=text=="true" | text=="1";
end
end

function print_table_input(fileName,tbl,hash)
fprintf('INPUT|path=%s|rows=%d|fields=%s|sha256=%s\n',fileName,height(tbl), ...
    strjoin(string(tbl.Properties.VariableNames),','),hash);
end

function rows=add_check(rows,id,description,passed,observed,expected)
rows(end+1,:)={string(id),string(description),logical(passed), ...
    scalar_text(observed),scalar_text(expected)};
end

function text=scalar_text(value)
if isstring(value),text=strjoin(value(:).',' | ');
elseif ischar(value),text=string(value);
elseif isnumeric(value)&&isscalar(value),text=string(sprintf('%.15g',value));
elseif isnumeric(value),text=strjoin(compose('%.15g',value(:).'),' | ');
elseif islogical(value)&&isscalar(value),text=string(double(value));
else,text=string(value);end
end

function hash=sha256_file(fileName)
fid=fopen(fileName,'rb');if fid<0,error('Could not open %s.',fileName);end
cleanup=onCleanup(@()fclose(fid));
md=java.security.MessageDigest.getInstance('SHA-256');
while true
    bytes=fread(fid,1024*1024,'*uint8');if isempty(bytes),break;end
    md.update(typecast(bytes,'int8'));
end
digest=typecast(md.digest(),'uint8');
hash=lower(string(reshape(dec2hex(digest,2).',1,[])));
end

function [rows,fields]=count_csv_rows_and_fields(fileName)
fid=fopen(fileName,'rb');if fid<0,error('Could not open %s.',fileName);end
cleanup=onCleanup(@()fclose(fid));header=fgetl(fid);
fields=string(strsplit(header,','));newlineCount=1;lastByte=uint8(10);
while true
    bytes=fread(fid,1024*1024,'*uint8');if isempty(bytes),break;end
    newlineCount=newlineCount+sum(bytes==10);lastByte=bytes(end);
end
totalLines=newlineCount+double(lastByte~=10);rows=totalLines-1;
end

function write_manifest(fileName,taskId,stepId,runId,status,passCount,failCount,observedFile,observedHash,unobservedFile,unobservedHash,mainFile,mainHash,overall)
fid=fopen(fileName,'w');if fid<0,error('Could not write %s.',fileName);end
cleanup=onCleanup(@()fclose(fid));
fprintf(fid,'task_id=%s\nstep_id=%s\nrun_id=%s\n',taskId,stepId,runId);
fprintf(fid,'run_time=%s\nstatus=%s\npass_count=%d\nfail_count=%d\n', ...
    char(datetime('now','Format','yyyy-MM-dd HH:mm:ss Z')),status,passCount,failCount);
fprintf(fid,'observed_input=%s\nobserved_input_sha256=%s\n',observedFile,observedHash);
fprintf(fid,'unobserved_input=%s\nunobserved_input_sha256=%s\n',unobservedFile,unobservedHash);
fprintf(fid,'main_sample=%s\nmain_sample_sha256=%s\n',mainFile,mainHash);
fprintf(fid,'input_records=%d\nunique_paths=%d\nduplicate_records_removed=%d\n', ...
    overall.input_record_count_total,overall.unique_path_count, ...
    overall.duplicate_record_count_removed);
fprintf(fid,'observed_unique_paths=%d\nunobserved_unique_paths=%d\noverlap_paths=%d\n', ...
    overall.observed_unique_path_count,overall.unobserved_unique_path_count, ...
    overall.observed_unobserved_overlap_count);
fprintf(fid,'B3_run=false\nDAC_generated=false\nWDRO_run=false\nGurobi_run=false\nMSP_run=false\n');
end

function write_readme(fileName,status,passCount,failCount,overall,byLevel,byProxy,tolerance)
fid=fopen(fileName,'w');if fid<0,error('Could not write %s.',fileName);end
cleanup=onCleanup(@()fclose(fid));
fprintf(fid,'Step-02B-3 run-005: physical tail-path deduplication and labels\n\n');
fprintf(fid,'status=%s; PASS=%d; FAIL=%d\n',status,passCount,failCount);
fprintf(fid,'input_records=%d\nunique_physical_paths=%d\nduplicate_records_removed=%d\n', ...
    overall.input_record_count_total,overall.unique_path_count, ...
    overall.duplicate_record_count_removed);
fprintf(fid,'one_two_three_levels=%d/%d/%d\n',overall.one_level_path_count, ...
    overall.two_level_path_count,overall.three_level_path_count);
fprintf(fid,'observed_unobserved_overlap=%d\nprobability_tolerance=%.15g\n', ...
    overall.observed_unobserved_overlap_count,tolerance);
for ii=1:height(byLevel)
    fprintf(fid,'%s_unique_paths=%d\n',byLevel.level_label(ii),byLevel.unique_path_count(ii));
end
for ii=1:height(byProxy)
    fprintf(fid,'%s_unique_paths=%d\n',byProxy.proxy_label(ii),byProxy.unique_path_count(ii));
end
fprintf(fid,'\nOne physical path is defined only by the complete initial/W1/W2/W3 state sequence.\n');
fprintf(fid,'All quantile, proxy, and observed/unobserved labels are retained; no representative path is selected.\n');
fprintf(fid,'No resampling, wind calculation, legal-path search, B3, D/A/C, WDRO, Gurobi, or MSP.\n');
end
