%% Step-03Y-B-A: independently cross-check the fixed-T three-period LP.
clear; clc;
started = tic;
thisFile = mfilename('fullpath'); thisDir = fileparts(thisFile);
moduleDir = fileparts(thisDir); rootDir = fileparts(moduleDir);
addpath(rootDir); addpath(thisDir);
addpath(fullfile(rootDir, 'fa_h2', 'fuzhu', 'terminalLoh_windmc'));

expectedBranch = "task/002-stage2b-b3-smoke";
expectedHead = "2ae3d68a52c044086f37d21fd264005e796e1c9e";
states = [7; 11; 18; 21; 30; 31]; rowsPerState = 15000;
baseSeed = 20260723; windSeedOffset = 330000000;
demandToleranceKg = 1e-10; numericalTolerance = 1e-8;
largeDifferenceThreshold = 0.10; runName = "run-001";
outputDir = fullfile(rootDir, 'results', 'task-002-stage2b-b3-smoke', ...
    '29-period-lp-independent-crosscheck', runName);
tempDir = outputDir + ".tmp";
if isfolder(outputDir) || isfolder(tempDir), error('Step-03Y-B output path exists.'); end

[~, branch] = system('git branch --show-current');
[~, head] = system('git rev-parse HEAD');
[~, upstream] = system('git rev-parse "@{upstream}"');
branch = string(strtrim(branch)); head = string(strtrim(head));
upstream = string(strtrim(upstream));
if branch ~= expectedBranch || head ~= expectedHead || upstream ~= expectedHead
    error('Frozen Git baseline mismatch.');
end
[status, trackedDiff] = system('git status --porcelain --untracked-files=no');
[stagedStatus, stagedDiff] = system('git diff --cached --name-only');
trackedNames = splitlines(string(trackedDiff));
trackedNames(strlength(strtrim(trackedNames)) == 0) = [];
if status ~= 0 || stagedStatus ~= 0 || ...
        numel(trackedNames) ~= 1 || ...
        strtrim(trackedNames(1)) ~= "M codex_rule/log.md" || ...
        strlength(strtrim(string(stagedDiff))) > 0
    error('Unexpected tracked or staged worktree changes are present.');
end

protectedRelative = [ ...
    "results/task-002-stage2b-b3-smoke/16-dac-transport-cost-audit/run-001"; ...
    "results/task-002-stage2b-b3-smoke/23-fixed-decision-loss-consistency/run-001.failed-001"; ...
    "results/task-002-stage2b-b3-smoke/24-old-vs-ctilde-fixed-loss"; ...
    "results/task-002-stage2b-b3-smoke/25-old-cost-evidence-trace"; ...
    "results/task-002-stage2b-b3-smoke/26-old-ground-cost-recompute"; ...
    "results/task-002-stage2b-b3-smoke/27-period-data-recoverability"; ...
    "results/task-002-stage2b-b3-smoke/28-period-vs-aggregate-loss/run-001"; ...
    "terminalLoh_wdro/src/run_step03XB_old_ground_cost_recompute.py"; ...
    "terminalLoh_wdro/src/run_step03X_old_vs_ctilde_fixed_loss.py"; ...
    "terminalLoh_wdro/src/run_step03YA_period_data_recoverability_h2.m"];
protectedBefore = strings(numel(protectedRelative), 1);
for ii = 1:numel(protectedRelative)
    protectedBefore(ii) = path_digest(fullfile(rootDir, protectedRelative(ii)));
    if protectedBefore(ii) == "MISSING", error('Protected path missing.'); end
end

config = build_config(rootDir, moduleDir, thisDir);
stepYBReferenceFile = fullfile(rootDir, 'results', ...
    'task-002-stage2b-b3-smoke', '28-period-vs-aggregate-loss', ...
    'run-001', 'scenario_loss_comparison.csv');
inputs = [string(config.pairFile); string(config.mainSampleFile); ...
    string(config.nominalCsv); string(config.nominalMat); ...
    string(config.seedMapFile); string(config.nearInputFile); ...
    string(config.formalWindConfigFile); string(config.warningSolutionFile); ...
    string(config.locCoordinateFile); string(config.roadEdgeFile); ...
    string(config.siteNodeFile); string(config.stepYAReadme); ...
    string(config.stepYAAudit); ...
    string(fullfile(thisDir, 'evaluate_step03T_fixed_T_recourse_h2.m')); ...
    string(fullfile(thisDir, 'evaluate_step03Y_period_fixed_T_recourse_h2.m')); ...
    string(stepYBReferenceFile)];
for ii = 1:numel(inputs)
    if ~isfile(inputs(ii)), error('Required input missing: %s', inputs(ii)); end
end
inputBefore = strings(numel(inputs), 1);
for ii = 1:numel(inputs), inputBefore(ii) = sha256_file(inputs(ii)); end
if inputBefore(1) ~= "39717c789739a112c7af651a733df1475a58b9905d08bd8773bc242b82d6baa7" || ...
        inputBefore(2) ~= "972a8c58620c09ac19cfcfb29e8d6a3ed2819ef1a22dbd522043436418eb805d" || ...
        inputBefore(3) ~= "366dc3c0b57bfd76aca92f51ae1db82b93c764c87fa15e8cb4dd32388d018168" || ...
        inputBefore(4) ~= "6936a696f5cde137aca483f8c32adee33b52cbd90559a8e6395f3686c0712945"
    error('Frozen Step-03W/Step-03J input SHA-256 mismatch.');
end
if ~contains(fileread(config.stepYAAudit), 'status=PASS') || ...
        ~contains(fileread(config.stepYAAudit), ...
        'conclusion=B. PERIOD_DATA_DETERMINISTICALLY_RECOVERABLE')
    error('Step-03Y-A run-002 is not an accepted recovery input.');
end

rawNear = load(config.nearInputFile, 'NearStageInput');
ni = rawNear.NearStageInput;
if isfield(ni.Cost, 'reserve_shortage_penalty_yuan_per_kg')
    M = double(ni.Cost.reserve_shortage_penalty_yuan_per_kg);
elseif isfield(ni.Cost, 'cost_reserve_shortage')
    M = double(ni.Cost.cost_reserve_shortage);
else
    error('Cannot trace the frozen shortage penalty.');
end
if abs(M - 2000) > 1e-12, error('Frozen shortage penalty changed.'); end

testSolverCalls = 0;

pairs = readtable(config.pairFile, 'TextType', 'string');
if height(pairs) ~= 36 || ~isequal(sort(unique(double(pairs.initial_state_id))), states)
    error('Expected 36 frozen Step-03W pairs over the six requested states.');
end
request = table([double(pairs.initial_state_id); double(pairs.initial_state_id)], ...
    [double(pairs.scenario_r); double(pairs.scenario_s)], ...
    [double(pairs.path_id_r); double(pairs.path_id_s)], ...
    'VariableNames', {'initial_state_id', 'scenario_id', 'path_id'});
request = sortrows(unique(request, 'rows'), {'initial_state_id', 'scenario_id'});

nominalOptions = detectImportOptions(config.nominalCsv);
nominalOptions = setvartype(nominalOptions, 'initial_state', 'string');
nominal = readtable(config.nominalCsv, nominalOptions);
mainSample = readtable(config.mainSampleFile);
seedMap = readtable(config.seedMapFile, 'TextType', 'string');
seedMap = seedMap(seedMap.dataset_role == "nominal" & ...
    ismember(double(seedMap.initial_state_id), states), :);
windConfig = load_formal_b3_wind_config_h2(config.formalWindConfigFile);
model = build_replay_model(config, rawNear.NearStageInput);
[recovered, recoveryAudit] = recover_requested_scenarios(request, nominal, ...
    mainSample, seedMap, windConfig, model, config, baseSeed, ...
    windSeedOffset, rowsPerState, demandToleranceKg);
if ~recoveryAudit.all_final_DAC_exact || ~recoveryAudit.all_stream_hashes_match
    error('Step-03Y-B scenario recovery failed.');
end

evaluationCount = 4 * height(pairs);
Dperiod = zeros(evaluationCount, 3, model.nNodes);
Aperiod = false(evaluationCount, 3, model.nSites, model.nNodes);
Cperiod = inf(evaluationCount, 3, model.nSites, model.nNodes);
Trows = zeros(evaluationCount, model.nSites);
evalRows = cell(evaluationCount, 15); er = 0;
for pp = 1:height(pairs)
    stateId = double(pairs.initial_state_id(pp));
    r = double(pairs.scenario_r(pp)); s = double(pairs.scenario_s(pp));
    ir = find(recovered.identity.initial_state_id == stateId & ...
        recovered.identity.scenario_id == r, 1);
    is = find(recovered.identity.initial_state_id == stateId & ...
        recovered.identity.scenario_id == s, 1);
    if isempty(ir) || isempty(is), error('Recovered pair endpoint missing.'); end
    Tr = double([pairs.T_r1(pp), pairs.T_r2(pp), pairs.T_r3(pp), pairs.T_r4(pp)]);
    Ts = double([pairs.T_s1(pp), pairs.T_s2(pp), pairs.T_s3(pp), pairs.T_s4(pp)]);
    sceneIndices = [ir, is, ir, is]; labels = ["T_R_ON_R", "T_R_ON_S", "T_S_ON_R", "T_S_ON_S"];
    layouts = [Tr; Tr; Ts; Ts]; qAgg = double([pairs.Q_Tr_xi_r(pp); ...
        pairs.Q_Tr_xi_s(pp); pairs.Q_Ts_xi_r(pp); pairs.Q_Ts_xi_s(pp)]);
    scenarioRoles = ["xi_r"; "xi_s"; "xi_r"; "xi_s"];
    layoutSources = ["T_r"; "T_r"; "T_s"; "T_s"];
    for kk = 1:4
        er = er + 1; idx = sceneIndices(kk);
        Dperiod(er, :, :) = recovered.Dperiod(idx, :, :);
        Aperiod(er, :, :, :) = recovered.Aperiod(idx, :, :, :);
        Cperiod(er, :, :, :) = recovered.Cperiod(idx, :, :, :);
        Trows(er, :) = layouts(kk, :);
        evalRows(er, :) = {er, double(pairs.evaluation_pair_id(pp)), ...
            string(pairs.pair_group(pp)), stateId, recovered.identity.scenario_id(idx), ...
            recovered.identity.path_id(idx), scenarioRoles(kk), layoutSources(kk), ...
            labels(kk), qAgg(kk), layouts(kk, 1), layouts(kk, 2), ...
            layouts(kk, 3), layouts(kk, 4), idx};
    end
end
evaluationIdentity = cell2table(evalRows, 'VariableNames', ...
    {'evaluation_id', 'pair_id', 'pair_group', 'initial_state_id', ...
    'scenario_id', 'path_id', 'scenario_role', 'T_source', 'replay_case', ...
    'Q_agg', 'T1', 'T2', 'T3', 'T4', 'recovered_index'});

periodConfig = struct('gurobiOutputFlag', 0, 'gurobiFeasibilityTol', 1e-9, ...
    'gurobiOptimalityTol', 1e-9, 'gurobiTimeLimit', 300, 'objectiveScale', 1);
periodResult = evaluate_step03Y_period_fixed_T_recourse_h2( ...
    Dperiod, Aperiod, Cperiod, Trows, M, periodConfig);
mainSolverCalls = 1;
if periodResult.exitflag ~= 1 || periodResult.status ~= "OPTIMAL"
    error('Main fixed-T period LP batch was not OPTIMAL.');
end

% Flatten W1-W3 into 99 time-node slots and solve the audited static helper.
flatNodeCount = 3 * model.nNodes;
Dflat = reshape(permute(Dperiod, [1, 3, 2]), [evaluationCount, flatNodeCount]);
Aflat = reshape(permute(Aperiod, [1, 3, 4, 2]), ...
    [evaluationCount, model.nSites, flatNodeCount]);
Cflat = reshape(permute(Cperiod, [1, 3, 4, 2]), ...
    [evaluationCount, model.nSites, flatNodeCount]);
flatResult = evaluate_step03T_fixed_T_recourse_h2( ...
    Dflat, Aflat, Cflat, Trows, M, periodConfig);
flatSolverCalls = 1;
if flatResult.exitflag ~= 1 || flatResult.status ~= "OPTIMAL"
    error('Flattened existing fixed-T helper batch was not OPTIMAL.');
end

yFlatAsPeriod = permute(reshape(flatResult.y, ...
    [evaluationCount, model.nSites, model.nNodes, 3]), [1, 4, 2, 3]);
uFlatAsPeriod = permute(reshape(flatResult.u, ...
    [evaluationCount, model.nNodes, 3]), [1, 3, 2]);
solverTolerance = max(periodConfig.gurobiFeasibilityTol, ...
    periodConfig.gurobiOptimalityTol);

reference = readtable(stepYBReferenceFile, 'TextType', 'string');
if height(reference) ~= evaluationCount
    error('Step-03Y-B run-001 evaluation count mismatch.');
end
identityMatch = double(reference.evaluation_id) == evaluationIdentity.evaluation_id & ...
    double(reference.pair_id) == evaluationIdentity.pair_id & ...
    double(reference.initial_state_id) == evaluationIdentity.initial_state_id & ...
    double(reference.scenario_id) == evaluationIdentity.scenario_id & ...
    double(reference.path_id) == evaluationIdentity.path_id & ...
    reference.scenario_role == evaluationIdentity.scenario_role & ...
    reference.T_source == evaluationIdentity.T_source & ...
    reference.replay_case == evaluationIdentity.replay_case & ...
    abs(double(reference.T1) - evaluationIdentity.T1) <= numericalTolerance & ...
    abs(double(reference.T2) - evaluationIdentity.T2) <= numericalTolerance & ...
    abs(double(reference.T3) - evaluationIdentity.T3) <= numericalTolerance & ...
    abs(double(reference.T4) - evaluationIdentity.T4) <= numericalTolerance;

comparisonRows = cell(evaluationCount, 22);
metricErrors = zeros(evaluationCount, 8);
for rr = 1:evaluationCount
    metricErrors(rr, :) = [ ...
        abs(periodResult.operating_loss(rr) - flatResult.operating_loss(rr)), ...
        abs(periodResult.service_cost(rr) - flatResult.service_cost(rr)), ...
        abs(periodResult.shortage_kg(rr) - flatResult.shortage_kg(rr)), ...
        abs(periodResult.shortage_loss(rr) - flatResult.shortage_loss(rr)), ...
        max(abs(periodResult.site_service_total(rr, :) - flatResult.site_service(rr, :))), ...
        max(abs(squeeze(periodResult.y(rr, :, :, :)) - ...
            squeeze(yFlatAsPeriod(rr, :, :, :))), [], 'all'), ...
        max(abs(squeeze(periodResult.u(rr, :, :)) - ...
            squeeze(uFlatAsPeriod(rr, :, :))), [], 'all'), ...
        abs(flatResult.full_objective(rr) - flatResult.operating_loss(rr) - ...
            flatResult.holding_cost(rr))];
    comparisonRows(rr, :) = {evaluationIdentity.evaluation_id(rr), ...
        evaluationIdentity.pair_id(rr), evaluationIdentity.pair_group(rr), ...
        evaluationIdentity.initial_state_id(rr), evaluationIdentity.scenario_id(rr), ...
        evaluationIdentity.path_id(rr), evaluationIdentity.scenario_role(rr), ...
        evaluationIdentity.T_source(rr), evaluationIdentity.replay_case(rr), ...
        identityMatch(rr), periodResult.operating_loss(rr), flatResult.operating_loss(rr), ...
        metricErrors(rr, 1), metricErrors(rr, 2), metricErrors(rr, 3), ...
        metricErrors(rr, 4), metricErrors(rr, 5), metricErrors(rr, 6), ...
        metricErrors(rr, 7), metricErrors(rr, 8), ...
        max(metricErrors(rr, 1:7)), max(metricErrors(rr, 1:7)) <= solverTolerance};
end
comparison = cell2table(comparisonRows, 'VariableNames', ...
    {'evaluation_id', 'pair_id', 'pair_group', 'initial_state_id', ...
    'scenario_id', 'path_id', 'scenario_role', 'T_source', 'replay_case', ...
    'identity_and_fixed_T_match', 'period_operating_loss', ...
    'flat_operating_loss', 'operating_loss_abs_error', ...
    'service_cost_abs_error', 'shortage_kg_abs_error', ...
    'shortage_loss_abs_error', 'site_service_max_abs_error', ...
    'period_site_node_service_max_abs_error', ...
    'period_node_shortage_max_abs_error', ...
    'flat_objective_decomposition_abs_error', ...
    'evaluation_max_required_error', 'within_solver_tolerance'});

globalMax = max(metricErrors, [], 1);
requiredMax = max(globalMax(1:7));
bad = find(~identityMatch | comparison.evaluation_max_required_error > solverTolerance, 1);
allPass = isempty(bad) && all(identityMatch) && ...
    periodResult.max_site_capacity_violation <= numericalTolerance && ...
    flatResult.max_site_capacity_violation <= numericalTolerance && ...
    isequal(Dflat, reshape(permute(Dperiod, [1, 3, 2]), ...
        [evaluationCount, flatNodeCount])) && ...
    isequaln(Aflat, reshape(permute(Aperiod, [1, 3, 4, 2]), ...
        [evaluationCount, model.nSites, flatNodeCount])) && ...
    isequaln(Cflat, reshape(permute(Cperiod, [1, 3, 4, 2]), ...
        [evaluationCount, model.nSites, flatNodeCount]));

mkdir(tempDir);
writetable(comparison, fullfile(tempDir, 'step03YBA_evaluation_comparison.csv'));
summary = table(["operating_loss"; "service_cost"; "shortage_kg"; ...
    "shortage_loss"; "site_service"; "period_site_node_service"; ...
    "period_node_shortage"; "flat_objective_decomposition"], ...
    globalMax.', repmat(solverTolerance, 8, 1), ...
    globalMax.' <= solverTolerance, ...
    'VariableNames', {'metric', 'maximum_absolute_error', ...
    'solver_tolerance', 'passed'});
writetable(summary, fullfile(tempDir, 'step03YBA_max_error_summary.csv'));

solverCallCount = 1 + flatSolverCalls + testSolverCalls;
auditLines = ["Step-03Y-B-A independent period-LP cross-check"; ...
    "status=" + string(ternary(allPass, 'PASS', 'FAIL')); ...
    "evaluation_count=" + string(evaluationCount); ...
    "flat_node_count=" + string(flatNodeCount); ...
    "solver_tolerance=" + string(sprintf('%.17g', solverTolerance)); ...
    "maximum_required_error=" + string(sprintf('%.17g', requiredMax)); ...
    "scenario_and_fixed_T_mapping_match=" + string(all(identityMatch)); ...
    "shared_T_capacity_period_max_violation=" + string(periodResult.max_site_capacity_violation); ...
    "shared_T_capacity_flat_max_violation=" + string(flatResult.max_site_capacity_violation); ...
    "holding_cost_excluded_from_comparison=true"; ...
    "costTau_averaging_count=0"; "costTau_rescaling_count=0"; ...
    "solver_call_count=" + string(solverCallCount); ...
    "wdro_call_count=0"; "msp_call_count=0"; ...
    "validation_file_count=0"];
if isempty(bad)
    auditLines(end + 1) = "first_mismatch=NONE";
else
    auditLines(end + 1) = "first_mismatch_evaluation_id=" + ...
        string(comparison.evaluation_id(bad));
    auditLines(end + 1) = "first_mismatch_state_scenario_T=" + ...
        string(comparison.initial_state_id(bad)) + "/" + ...
        string(comparison.scenario_id(bad)) + "/" + comparison.T_source(bad);
    auditLines(end + 1) = "first_mismatch_max_error=" + ...
        string(sprintf('%.17g', comparison.evaluation_max_required_error(bad)));
end
write_lines(fullfile(tempDir, 'mechanical_audit.txt'), auditLines);

readmeLines = ["# Step-03Y-B-A independent three-period LP cross-check"; ""; ...
    "The 144 frozen fixed-T evaluations from Step-03Y-B were deterministically recovered again. W1-W3 were concatenated into 99 time-node slots and passed directly to evaluate_step03T_fixed_T_recourse_h2."; ""; ...
    "Both helpers used the same four-site T row, M=" + string(M) + ...
        ", objectiveScale=1, FeasibilityTol=" + string(periodConfig.gurobiFeasibilityTol) + ...
        ", and OptimalityTol=" + string(periodConfig.gurobiOptimalityTol) + "."; ...
    "The comparison uses operating_loss only. The static helper's holding_cost and full_objective were not used as target quantities."; ...
    "costTau values were concatenated without averaging or rescaling."; ""; ...
    "status=" + string(ternary(allPass, 'PASS', 'FAIL')); ...
    "maximum_required_error=" + string(sprintf('%.17g', requiredMax)); ...
    "solver_tolerance=" + string(sprintf('%.17g', solverTolerance)); ...
    "solver_call_count=" + string(solverCallCount) + ...
        "; WDRO=0; MSP=0; validation=0."; ...
    "runtime_sec=" + string(sprintf('%.6f', toc(started)))];
write_lines(fullfile(tempDir, 'README.md'), readmeLines);
movefile(tempDir, outputDir);
fprintf('Step-03Y-B-A %s. Output: %s\n', ternary(allPass, 'PASS', 'FAIL'), outputDir);
fprintf('maximum_required_error=%.17g solver_tolerance=%.17g\n', requiredMax, solverTolerance);
if ~allPass
    error('Step-03Y-B-A mismatch at evaluation %d.', comparison.evaluation_id(bad));
end
function [recovered, audit] = recover_requested_scenarios(request, nominal, ...
        mainSample, seedMap, windConfig, model, config, baseSeed, ...
        windSeedOffset, rowsPerState, demandToleranceKg)
R = height(request); Dperiod = zeros(R, 3, model.nNodes);
Aperiod = false(R, 3, model.nSites, model.nNodes);
Cperiod = inf(R, 3, model.nSites, model.nNodes);
AaggAll = false(R, model.nSites, model.nNodes);
CaggAll = inf(R, model.nSites, model.nNodes);
DaggAll = zeros(R, model.nNodes); identity = request;
identity.joint_stream_position = zeros(R, 1);
identity.wind_seed = zeros(R, 1); identity.resistance_seed = zeros(R, 1);
identity.final_D_exact = false(R, 1); identity.final_A_exact = false(R, 1);
identity.final_C_exact = false(R, 1); identity.max_DAC_error = inf(R, 1);
streamMatches = 0; sidecar = matfile(config.nominalMat);
for ss = 1:numel(unique(request.initial_state_id))
    stateId = unique(request.initial_state_id); stateId = stateId(ss);
    meta = nominal(double(nominal.initial_state_id) == stateId, :);
    if height(meta) ~= rowsPerState, error('Nominal state block mismatch.'); end
    a0 = double(meta.a0(1)); loc0 = double(meta.loc0(1)); lfw0 = double(meta.lfw0(1));
    stateSample = mainSample(double(mainSample.a0) == a0 & ...
        double(mainSample.loc0) == loc0 & double(mainSample.lfw0) == lfw0, :);
    if height(stateSample) ~= rowsPerState, error('Main-sample state block mismatch.'); end
    resistanceSeed = baseSeed + 100003 * stateId;
    rng(resistanceSeed, 'twister'); permutation = randperm(rowsPerState).';
    lineU = rand(rowsPerState, model.nLines); roadU = rand(rowsPerState, model.nRoads);
    selected = stateSample(permutation, :);
    windSeed = windSeedOffset + baseSeed + 100019 * stateId;
    stream = RandStream('mt19937ar', 'Seed', windSeed); qAll = rand(stream, rowsPerState, 3);
    seedRow = seedMap(double(seedMap.initial_state_id) == stateId, :);
    streamPass = sha256_uint32(permutation) == string(seedRow.step3i_permutation_sha256) && ...
        sha256_double(qAll(:, 1)) == string(seedRow.q_W1_sha256) && ...
        sha256_double(qAll(:, 2)) == string(seedRow.q_W2_sha256) && ...
        sha256_double(qAll(:, 3)) == string(seedRow.q_W3_sha256);
    streamMatches = streamMatches + double(streamPass);
    if ~streamPass, error('Random-stream hash mismatch.'); end
    localIdx = find(request.initial_state_id == stateId);
    for jj = 1:numel(localIdx)
        rr = localIdx(jj); scenarioId = request.scenario_id(rr);
        row = meta(double(meta.scenario_id_in_state) == scenarioId, :);
        if height(row) ~= 1 || double(row.path_id) ~= request.path_id(rr)
            error('Frozen scenario identity mismatch.');
        end
        pos = double(row.joint_stream_position); sample = selected(pos, :);
        if double(sample.path_id) ~= request.path_id(rr), error('Stream mapping mismatch.'); end
        aStage = double([sample.a_W1, sample.a_W2, sample.a_W3]);
        locStage = double([sample.loc_W1, sample.loc_W2, sample.loc_W3]);
        lfwStage = double([sample.lfw_W1, sample.lfw_W2, sample.lfw_W3]);
        pFail = cell(3, 1); pClose = cell(3, 1);
        for tau = 1:3
            vmax = triangular_by_level(aStage(tau), qAll(pos, tau), ...
                windConfig.randomLower, windConfig.randomMode, windConfig.randomUpper);
            idx = state_index(model, aStage(tau), locStage(tau), lfwStage(tau));
            pFail{tau} = compute_line_failure_prob_h2(model.lineFactor(idx, :) .* vmax, model.designWindSpeedVN);
            pClose{tau} = compute_line_failure_prob_h2(model.roadFactor(idx, :) .* vmax, model.roadDesignWindVN);
        end
        failed = false(3, model.nLines); closed = false(3, model.nRoads); slow = zeros(3, model.nRoads);
        failed(1, :) = lineU(pos, :) <= pFail{1};
        failed(2, :) = failed(1, :) | lineU(pos, :) <= pFail{2};
        failed(3, :) = failed(2, :) | lineU(pos, :) <= pFail{3};
        closed(1, :) = roadU(pos, :) <= pClose{1};
        closed(2, :) = closed(1, :) | roadU(pos, :) <= pClose{2};
        closed(3, :) = closed(2, :) | roadU(pos, :) <= pClose{3};
        slow(1, :) = pClose{1}; slow(2, :) = max(slow(1, :), pClose{2});
        slow(3, :) = max(slow(2, :), pClose{3});
        outage = false(3, model.nNodes);
        for tau = 1:3
            outage(tau, :) = double(failed(tau, :)) * model.nodePathIncidence.' > 0;
            outage(tau, model.sourceNode) = false;
        end
        Dtau = double(outage) .* model.Pnode_kW.' * model.DFactorKgPerKWh;
        reachTau = false(3, model.nSites, model.nNodes);
        costTau = inf(3, model.nSites, model.nNodes);
        for tau = 1:3
            edgeCost = model.roadLength .* (1 + slow(tau, :).');
            edgeCost(closed(tau, :).') = Inf;
            [reach, cost] = road_state(model.nNodes, model.roadFrom, model.roadTo, edgeCost, model.siteNodes);
            reachTau(tau, :, :) = reach; costTau(tau, :, :) = cost;
        end
        Dagg = sum(Dtau, 1); Aagg = false(model.nSites, model.nNodes);
        Cagg = inf(model.nSites, model.nNodes);
        for nn = 1:model.nNodes
            critical = find(Dtau(:, nn) > demandToleranceKg);
            if isempty(critical), critical = (1:3).'; end
            for ii = 1:model.nSites
                reach = squeeze(reachTau(critical, ii, nn));
                if all(reach)
                    Aagg(ii, nn) = true;
                    Cagg(ii, nn) = mean(squeeze(costTau(critical, ii, nn)));
                end
            end
        end
        globalRow = (stateId - 1) * rowsPerState + scenarioId;
        Dnom = double(sidecar.D_node_kg(globalRow, :));
        Anom = logical(squeeze(sidecar.A_site_node(globalRow, :, :)));
        Cnom = double(squeeze(sidecar.C_site_node_km(globalRow, :, :)));
        dExact = isequal(Dagg, Dnom); aExact = isequal(Aagg, Anom); cExact = isequaln(Cagg, Cnom);
        finiteBoth = isfinite(Cagg) & isfinite(Cnom); cError = 0;
        if any(finiteBoth, 'all'), cError = max(abs(Cagg(finiteBoth) - Cnom(finiteBoth))); end
        Dperiod(rr, :, :) = Dtau; Aperiod(rr, :, :, :) = reachTau;
        Cperiod(rr, :, :, :) = costTau; DaggAll(rr, :) = Dagg;
        AaggAll(rr, :, :) = Aagg; CaggAll(rr, :, :) = Cagg;
        identity.joint_stream_position(rr) = pos; identity.wind_seed(rr) = windSeed;
        identity.resistance_seed(rr) = resistanceSeed; identity.final_D_exact(rr) = dExact;
        identity.final_A_exact(rr) = aExact; identity.final_C_exact(rr) = cExact;
        identity.max_DAC_error(rr) = max([max(abs(Dagg - Dnom)), cError, ...
            double(sum(Aagg ~= Anom, 'all')), double(sum(isinf(Cagg) ~= isinf(Cnom), 'all'))]);
        if ~(dExact && aExact && cExact), error('Recovered final D/A/C mismatch.'); end
    end
end
recovered = struct('identity', identity, 'Dperiod', Dperiod, 'Aperiod', Aperiod, ...
    'Cperiod', Cperiod, 'Dagg', DaggAll, 'Aagg', AaggAll, 'Cagg', CaggAll);
audit = struct('all_final_DAC_exact', all(identity.final_D_exact & identity.final_A_exact & identity.final_C_exact), ...
    'max_DAC_error', max(identity.max_DAC_error), ...
    'all_stream_hashes_match', streamMatches == numel(unique(request.initial_state_id)), ...
    'stream_match_count', streamMatches);
end

function config = build_config(rootDir, moduleDir, thisDir)
config.pairFile = fullfile(rootDir, 'results', 'task-002-stage2b-b3-smoke', '23-fixed-decision-loss-consistency', 'run-001', 'step03W_pair_results.csv');
config.mainSampleFile = fullfile(moduleDir, 'output', 'stage2a2_W3_path_sampling', 'run-002', 'main_path_samples.csv');
config.nominalCsv = fullfile(moduleDir, 'output', 'stage3j_wdro_input_freeze', 'run-001', 'wdro_nominal_input.csv');
config.nominalMat = fullfile(moduleDir, 'output', 'stage3j_wdro_input_freeze', 'run-001', 'wdro_nominal_input_DAC.mat');
config.seedMapFile = fullfile(moduleDir, 'output', 'stage3j_wdro_input_freeze', 'run-001', 'dataset_role_and_seed_map.csv');
config.nearInputFile = fullfile(rootDir, 'data', 'yuanqi', 'near_stage_msp_input.mat');
config.formalWindConfigFile = fullfile(moduleDir, 'config', 'formal_b3_wind_modes.csv');
config.warningSolutionFile = fullfile(moduleDir, 'output', 'stage2_foundation_warning100_Rmax30_40_50_Wstep_sweep', 'warning_y_base_solution.csv');
config.locCoordinateFile = fullfile(moduleDir, 'output', 'stage2_foundation_audit', 'loc_lf_coordinate_table.csv');
config.roadEdgeFile = fullfile(rootDir, 'data', 'yuanqi', 'stage1_road_edges.csv');
config.siteNodeFile = fullfile(rootDir, 'data', 'yuanqi', 'stage1_site_nodes.csv');
config.stepYAReadme = fullfile(rootDir, 'results', 'task-002-stage2b-b3-smoke', '27-period-data-recoverability', 'run-002', 'README.md');
config.stepYAAudit = fullfile(rootDir, 'results', 'task-002-stage2b-b3-smoke', '27-period-data-recoverability', 'run-002', 'mechanical_audit.txt');
config.Rmax = 40; config.Wstep = 40; config.windDecayB = 0.6;
config.designWindSpeedVN = 25; config.roadDesignWindVN = 30; config.sourceNode = 1; config.thisDir = thisDir;
end

function model = build_replay_model(config, near)
warning = readtable(config.warningSolutionFile); yBase = double(warning.y_base(1));
locRaw = readtable(config.locCoordinateFile); locTable = sortrows(unique(locRaw(:, {'loc', 'x_coord'}), 'rows', 'stable'), 'loc');
layout = build_h2_spatial_layout_preview(near); nodes = sortrows(layout.nodes, 'node_id'); lines = sortrows(layout.lines, 'line_id');
grid = table(lines.line_id, lines.source_edge_id, lines.from_node, lines.to_node, ...
    nodes.x_km(lines.from_node), nodes.y_km(lines.from_node), nodes.x_km(lines.to_node), nodes.y_km(lines.to_node), ...
    'VariableNames', {'line_id', 'source_edge_id', 'from_node', 'to_node', 'x1', 'y1', 'x2', 'y2'});
roadRaw = readtable(config.roadEdgeFile);
road = table(double(roadRaw.road_edge_id), double(roadRaw.from_node), double(roadRaw.to_node), ...
    nodes.x_km(double(roadRaw.from_node)), nodes.y_km(double(roadRaw.from_node)), ...
    nodes.x_km(double(roadRaw.to_node)), nodes.y_km(double(roadRaw.to_node)), ...
    'VariableNames', {'road_edge_id', 'from_node', 'to_node', 'x1', 'y1', 'x2', 'y2'});
site = sortrows(readtable(config.siteNodeFile), 'site_id'); Pnode = double(near.Grid.P_load_base_kw(:));
eta = double(near.HydrogenDevice.eta_FC); lhv = double(near.HydrogenDevice.h2_lhv_kWh_per_kg);
locValues = sort(double(locTable.loc)); lineFactor = zeros(6 * numel(locValues) * 4, height(grid));
roadFactor = zeros(6 * numel(locValues) * 4, height(road)); stateIndex = zeros(6, numel(locValues), 4); rr = 0;
for a = 1:6
    for loc = locValues(:).'
        locRow = locTable(locTable.loc == loc, :);
        for lfw = 0:3
            rr = rr + 1; x = double(locRow.x_coord); y = yBase + lfw * config.Wstep;
            ld = compute_point_to_segment_distance_h2(x, y, grid.x1, grid.y1, grid.x2, grid.y2);
            rd = compute_point_to_segment_distance_h2(x, y, road.x1, road.y1, road.x2, road.y2);
            lineFactor(rr, :) = compute_wind_speed_radial_h2(ld, 1, config.Rmax, config.windDecayB).';
            roadFactor(rr, :) = compute_wind_speed_radial_h2(rd, 1, config.Rmax, config.windDecayB).';
            stateIndex(a, loc - min(locValues) + 1, lfw + 1) = rr;
        end
    end
end
model = struct('lineFactor', lineFactor, 'roadFactor', roadFactor, 'stateIndex', stateIndex, ...
    'locMin', min(locValues), 'nLines', height(grid), 'nRoads', height(road), ...
    'nNodes', numel(Pnode), 'nSites', height(site), 'sourceNode', config.sourceNode, ...
    'Pnode_kW', Pnode, 'nodePathIncidence', radial_node_path_incidence(numel(Pnode), grid.from_node, grid.to_node, config.sourceNode), ...
    'roadFrom', double(road.from_node), 'roadTo', double(road.to_node), ...
    'roadLength', hypot(road.x2 - road.x1, road.y2 - road.y1), ...
    'siteNodes', double(site.grid_node), 'DFactorKgPerKWh', 1 / (eta * lhv), ...
    'designWindSpeedVN', config.designWindSpeedVN, 'roadDesignWindVN', config.roadDesignWindVN);
end

function incidence = radial_node_path_incidence(nNodes, fromNode, toNode, sourceNode)
nLines = numel(fromNode); adj = cell(nNodes, 1); edgeAdj = cell(nNodes, 1);
for ll = 1:nLines, i = fromNode(ll); j = toNode(ll); adj{i}(end+1)=j; edgeAdj{i}(end+1)=ll; adj{j}(end+1)=i; edgeAdj{j}(end+1)=ll; end
parent=zeros(nNodes,1); parentEdge=zeros(nNodes,1); visited=false(nNodes,1); queue=zeros(nNodes,1); h=1; t=1; queue(1)=sourceNode; visited(sourceNode)=true;
while h<=t, u=queue(h); h=h+1; for kk=1:numel(adj{u}), v=adj{u}(kk); if visited(v),continue;end; visited(v)=true; parent(v)=u; parentEdge(v)=edgeAdj{u}(kk); t=t+1; queue(t)=v; end,end
incidence=false(nNodes,nLines); for node=1:nNodes, cur=node; while cur~=sourceNode, incidence(node,parentEdge(cur))=true; cur=parent(cur); end,end
end

function idx = state_index(model, a, loc, lfw), idx=model.stateIndex(sub2ind(size(model.stateIndex),a,loc-model.locMin+1,lfw+1)); if idx<=0,error('Missing state.');end,end
function vmax = triangular_by_level(a,q,lo,mode,hi), if a==1,vmax=0;return;end; x=lo(a);c=mode(a);b=hi(a);fc=(c-x)/(b-x);if q<=fc,vmax=x+sqrt(q*(b-x)*(c-x));else,vmax=b-sqrt((1-q)*(b-x)*(b-c));end,end
function [reach,cost]=road_state(nNodes,fromNode,toNode,edgeCost,sources),adj=inf(nNodes);adj(1:nNodes+1:end)=0;for ee=1:numel(edgeCost),if ~isfinite(edgeCost(ee)),continue;end;i=fromNode(ee);j=toNode(ee);if edgeCost(ee)<adj(i,j),adj(i,j)=edgeCost(ee);adj(j,i)=edgeCost(ee);end,end;reach=false(numel(sources),nNodes);cost=inf(numel(sources),nNodes);for ii=1:numel(sources),dist=inf(1,nNodes);vis=false(1,nNodes);dist(sources(ii))=0;for it=1:nNodes,cand=dist;cand(vis)=Inf;[best,u]=min(cand);if ~isfinite(best),break;end;vis(u)=true;dist=min(dist,best+adj(u,:));end;reach(ii,:)=isfinite(dist);cost(ii,:)=dist;end,end
function hash=sha256_file(fileName),fid=fopen(fileName,'rb');if fid<0,error('Cannot open file.');end;c=onCleanup(@()fclose(fid));md=java.security.MessageDigest.getInstance('SHA-256');while true,b=fread(fid,1024*1024,'*uint8');if isempty(b),break;end;md.update(typecast(b,'int8'));end;d=typecast(md.digest(),'uint8');hash=lower(string(reshape(dec2hex(d,2).',1,[])));end
function hash=sha256_uint32(x),md=java.security.MessageDigest.getInstance('SHA-256');b=typecast(uint32(x(:)),'uint8');md.update(typecast(b,'int8'));d=typecast(md.digest(),'uint8');hash=lower(string(reshape(dec2hex(d,2).',1,[])));end
function hash=sha256_double(x),md=java.security.MessageDigest.getInstance('SHA-256');b=typecast(double(x(:)),'uint8');md.update(typecast(b,'int8'));d=typecast(md.digest(),'uint8');hash=lower(string(reshape(dec2hex(d,2).',1,[])));end
function digest=path_digest(p),if isfile(p),digest=sha256_file(p);return;end;if ~isfolder(p),digest="MISSING";return;end;f=dir(fullfile(p,'**','*'));f=f(~[f.isdir]);rel=strings(numel(f),1);for i=1:numel(f),full=fullfile(f(i).folder,f(i).name);rel(i)=string(erase(full,[char(p),filesep]));end;[rel,o]=sort(rel);f=f(o);md=java.security.MessageDigest.getInstance('SHA-256');for i=1:numel(f),full=fullfile(f(i).folder,f(i).name);token=rel(i)+"|"+string(f(i).bytes)+"|"+sha256_file(full)+newline;md.update(typecast(unicode2native(char(token),'UTF-8'),'int8'));end;d=typecast(md.digest(),'uint8');digest=lower(string(reshape(dec2hex(d,2).',1,[])));end
function write_lines(fileName,lines),fid=fopen(fileName,'w');if fid<0,error('Cannot write.');end;c=onCleanup(@()fclose(fid));for i=1:numel(lines),fprintf(fid,'%s\n',lines(i));end,end
function value=ternary(condition,a,b),if condition,value=a;else,value=b;end,end
