clear; clc;

thisDir = fileparts(mfilename('fullpath'));
moduleDir = fileparts(thisDir);
rootDir = fileparts(moduleDir);
inputDir = fullfile(moduleDir, 'output', 'stage3j_wdro_input_freeze', 'run-001');
outputDir = fullfile(moduleDir, 'output', ...
    'stage2_foundation_step03M_wdro_constraint_generation');

if exist(outputDir, 'dir')
    error('Step-03M output directory already exists: %s', outputDir);
end
addpath(rootDir);
addpath(thisDir);
gurobiCandidates = {fullfile(getenv('GUROBI_HOME'), 'matlab'), ...
    fullfile('D:\', 'gurobi1201', 'win64', 'matlab'), ...
    fullfile('C:\', 'gurobi1201', 'win64', 'matlab')};
for ii = 1:numel(gurobiCandidates)
    if ~isempty(gurobiCandidates{ii}) && exist(gurobiCandidates{ii}, 'dir')
        addpath(gurobiCandidates{ii});
    end
end
if ~ismember(exist('gurobi', 'file'), [2, 3])
    error('Step-03M requires the existing Gurobi MATLAB interface.');
end

nominalCsv = fullfile(inputDir, 'wdro_nominal_input.csv');
nominalMat = fullfile(inputDir, 'wdro_nominal_input_DAC.mat');
expectedCsvHash = "366dc3c0b57bfd76aca92f51ae1db82b93c764c87fa15e8cb4dd32388d018168";
expectedMatHash = "6936a696f5cde137aca483f8c32adee33b52cbd90559a8e6395f3686c0712945";
if ~isfile(nominalCsv) || ~isfile(nominalMat)
    error('Step-03J nominal frozen files are missing.');
end
csvHashBefore = sha256_file(nominalCsv);
matHashBefore = sha256_file(nominalMat);
if csvHashBefore ~= expectedCsvHash || matHashBefore ~= expectedMatHash
    error('Step-03J nominal frozen-file SHA-256 mismatch.');
end

protectedFiles = [ ...
    string(fullfile(thisDir, 'build_wdro_distance_matrix_h2.m')); ...
    string(fullfile(thisDir, 'solve_wdro_terminal_loh_lp_h2.m')); ...
    string(fullfile(thisDir, 'load_frozen_b3_wdro_dataset_h2.m')); ...
    string(fullfile(thisDir, 'run_terminal_loh_wdro_preview_h2.m'))];
expectedProtectedHashes = [ ...
    "e1dd61fe85f0ea9cc6e0919b713b2ddee1af46271cc52ecf4941ce4f5998a0fe"; ...
    "2393abcb1627ef77564402843779d38b7a0c2b5dc0d6521629f9bf1dad253b00"; ...
    "0ee23259dfe3393860e0d916efad59cc22aa6cd1ed33cba656ea5864981a7c83"; ...
    "ef895fa5833906de56a9f9dce6b6335417bd0b276688166bbedeFC19A8C3D34D"];
expectedProtectedHashes = lower(expectedProtectedHashes);
protectedBefore = strings(numel(protectedFiles), 1);
for ii = 1:numel(protectedFiles)
    protectedBefore(ii) = sha256_file(char(protectedFiles(ii)));
end
if any(protectedBefore ~= expectedProtectedHashes)
    error('A protected WDRO source hash differs from the accepted precheck.');
end
oldBenchmark = fullfile(moduleDir, 'output', ...
    'stage3k_wdro_integration_scaling', 'run-001', 'wdro_scaling_benchmark.csv');
oldBenchmarkHashBefore = sha256_file(oldBenchmark);

fprintf('Step-03M nominal CSV: %s\n', nominalCsv);
fprintf('Step-03M nominal DAC: %s\n', nominalMat);
fprintf('Step-03M nominal CSV SHA-256: %s\n', csvHashBefore);
fprintf('Step-03M nominal DAC SHA-256: %s\n', matHashBefore);

selectOpts = detectImportOptions(nominalCsv, 'TextType', 'string');
selectOpts.SelectedVariableNames = {'initial_state_id','a0','loc0','lfw0', ...
    'D_Hres3h_total_kg'};
selectTbl = readtable(nominalCsv, selectOpts);
if height(selectTbl) ~= 525000
    error('Step-03J nominal CSV must contain 525000 records.');
end
stateRows = cell(35, 6);
for stateId = 1:35
    mask = double(selectTbl.initial_state_id) == stateId;
    rows = selectTbl(mask, :);
    if height(rows) ~= 15000
        error('Initial state %d does not contain 15000 nominal records.', stateId);
    end
    stateRows(stateId, :) = {stateId, double(rows.a0(1)), ...
        double(rows.loc0(1)), double(rows.lfw0(1)), ...
        mean(double(rows.D_Hres3h_total_kg)), height(rows)};
end
stateSummary = cell2table(stateRows, 'VariableNames', ...
    {'initial_state_id','a0','loc0','lfw0','nominal_D_mean_kg','record_count'});
stateSorted = sortrows(stateSummary, {'nominal_D_mean_kg','initial_state_id'});
selected = [stateSorted(1, :); ...
    stateSorted(ceil(height(stateSorted) / 2), :); ...
    stateSorted(end, :)];
selected.complexity_label = ["simple"; "medium"; "complex"];
selected.selection_rule = [ ...
    "minimum nominal D mean; tie break state ID"; ...
    "median nominal D mean; tie break state ID"; ...
    "maximum nominal D mean; tie break state ID"];
clear selectTbl rows;

nearInput = fullfile(rootDir, 'data', 'yuanqi', 'near_stage_msp_input.mat');
raw = load(nearInput, 'NearStageInput');
ni = raw.NearStageInput;
tankCap = double(ni.HydrogenDevice.tank_cap_kg(:));
if isfield(ni.Cost, 'reserve_shortage_penalty_yuan_per_kg')
    M = double(ni.Cost.reserve_shortage_penalty_yuan_per_kg);
    penaltySource = "NearStageInput.Cost.reserve_shortage_penalty_yuan_per_kg";
elseif isfield(ni.Cost, 'cost_reserve_shortage')
    M = double(ni.Cost.cost_reserve_shortage);
    penaltySource = "NearStageInput.Cost.cost_reserve_shortage";
else
    M = 2000;
    penaltySource = "existing_explicit_default_2000_yuan_per_kg";
end
capacityFraction = 0.8;
Cap = capacityFraction .* tankCap;
rhoValues = [0, 0.02];
rValues = [100, 250, 500, 1000];
distanceMode = 'DAC_maskedC';
config = struct();
config.gamma = 0.001 * M;
config.gurobiOutputFlag = 0;
config.distanceWeightsDACMaskedC = struct('D', 0.6, 'A', 0.25, 'C', 0.15);
config.epsDistance = 1e-9;
config.scaleTolerance = 1e-12;
config.violationTolerance = 1e-8;
config.gurobiFeasibilityTol = 1e-9;
config.gurobiOptimalityTol = 1e-9;
config.blockSize = 100;
config.independentScanBlockSize = 73;
config.maxIterations = 200;

comparisonRows = cell(0, 49);
iterationTables = cell(0, 1);
caseIndex = 0;
for stateRow = 1:height(selected)
    state = selected(stateRow, :);
    fprintf('\nStep-03M loading %s state ID %d: a0=%d loc0=%d lfw0=%d\n', ...
        state.complexity_label, state.initial_state_id, state.a0, state.loc0, state.lfw0);
    [allSamples, metadata] = load_frozen_b3_wdro_dataset_h2( ...
        nominalCsv, nominalMat, state.a0, state.loc0, state.lfw0);
    if any(double(metadata.initial_state_id) ~= state.initial_state_id)
        error('Frozen loader state identity differs from deterministic selection.');
    end
    for rr = 1:numel(rValues)
        R = rValues(rr);
        D = allSamples.D(1:R, :);
        A = allSamples.A(1:R, :, :);
        C = allSamples.C_raw(1:R, :, :);

        fullDistanceTic = tic;
        [dMat, distanceInfo] = build_wdro_distance_matrix_h2( ...
            D, A, C, distanceMode, config);
        fullDistanceTime = toc(fullDistanceTic);
        distanceBytes = whos_bytes('dMat');

        for pp = 1:numel(rhoValues)
            rho = rhoValues(pp);
            caseIndex = caseIndex + 1;
            fprintf('Case %d/24: %s state=%d R=%d rho=%.2f\n', ...
                caseIndex, state.complexity_label, state.initial_state_id, R, rho);

            fullCallTic = tic;
            fullSol = solve_full_with_tight_env( ...
                D, A, C, Cap, M, rho, dMat, config);
            fullCallTime = toc(fullCallTic);
            fullModelTime = max(0, fullCallTime - fullSol.runtime_sec);
            fullViolation = full_solution_max_violation(fullSol, dMat, 100);

            cgCallTic = tic;
            cgSol = solve_wdro_terminal_loh_lp_constraint_generation_h2( ...
                D, A, C, Cap, M, rho, config);
            cgCallTime = toc(cgCallTic);

            objectiveError = abs(fullSol.objective_value - cgSol.objective_value);
            terminalError = max(abs(fullSol.T - cgSol.T));
            scaleError = max(abs([distanceInfo.D_scale - cgSol.distance_info.D_scale, ...
                distanceInfo.A_scale - cgSol.distance_info.A_scale, ...
                distanceInfo.C_scale - cgSol.distance_info.C_scale]));
            statusOk = fullSol.exitflag == 1 && cgSol.exitflag == 1;
            objectiveOk = objectiveError <= 1e-8;
            terminalOk = terminalError <= 1e-7;
            scanOk = cgSol.final_independent_scan_max_violation <= 1e-8;
            scaleOk = scaleError <= 1e-12;
            casePass = statusOk && objectiveOk && terminalOk && scanOk && scaleOk;

            comparisonRows(end + 1, :) = { ...
                char(state.complexity_label), state.initial_state_id, ...
                state.a0, state.loc0, state.lfw0, state.nominal_D_mean_kg, ...
                R, rho, char(distanceMode), fullSol.status, cgSol.status, ...
                fullSol.objective_value, cgSol.objective_value, objectiveError, ...
                fullSol.T(1), fullSol.T(2), fullSol.T(3), fullSol.T(4), ...
                cgSol.T(1), cgSol.T(2), cgSol.T(3), cgSol.T(4), terminalError, ...
                fullSol.lambda, cgSol.lambda, fullViolation, ...
                cgSol.last_scan_max_violation, ...
                cgSol.final_independent_scan_max_violation, ...
                fullDistanceTime, distanceBytes, fullModelTime, ...
                fullSol.runtime_sec, fullCallTime, ...
                cgSol.distance_context_time_sec, cgSol.total_modeling_time_sec, ...
                cgSol.total_solve_time_sec, cgSol.total_separation_time_sec, ...
                cgSol.final_independent_scan_time_sec, cgCallTime, ...
                height(cgSol.history), cgSol.final_active_constraints, ...
                cgSol.active_constraint_ratio, scaleError, ...
                statusOk, objectiveOk, terminalOk, scanOk, scaleOk, casePass};

            hist = cgSol.history;
            hist.complexity_label = repmat(state.complexity_label, height(hist), 1);
            hist.initial_state_id = repmat(state.initial_state_id, height(hist), 1);
            hist.a0 = repmat(state.a0, height(hist), 1);
            hist.loc0 = repmat(state.loc0, height(hist), 1);
            hist.lfw0 = repmat(state.lfw0, height(hist), 1);
            hist.R = repmat(R, height(hist), 1);
            hist.rho = repmat(rho, height(hist), 1);
            hist = movevars(hist, {'complexity_label','initial_state_id','a0', ...
                'loc0','lfw0','R','rho'}, 'Before', 1);
            iterationTables{end + 1, 1} = hist; %#ok<AGROW>

            if ~casePass
                error('Step-03M acceptance failed for state %d R=%d rho=%.2f.', ...
                    state.initial_state_id, R, rho);
            end
        end
        clear dMat D A C fullSol cgSol;
    end
    clear allSamples metadata;
end

comparison = cell2table(comparisonRows, 'VariableNames', { ...
    'complexity_label','initial_state_id','a0','loc0','lfw0','nominal_D_mean_kg', ...
    'R','rho','distance_mode','full_status','cg_status', ...
    'full_objective','cg_objective','objective_abs_error', ...
    'full_T1','full_T2','full_T3','full_T4', ...
    'cg_T1','cg_T2','cg_T3','cg_T4','TerminalLOH_max_abs_error', ...
    'full_lambda','cg_lambda','full_max_constraint_violation', ...
    'cg_stopping_scan_max_violation','cg_independent_scan_max_violation', ...
    'full_distance_build_time_sec','full_distance_matrix_bytes', ...
    'full_modeling_time_sec','full_gurobi_solve_time_sec','full_total_time_sec', ...
    'cg_distance_context_time_sec','cg_modeling_time_sec','cg_gurobi_solve_time_sec', ...
    'cg_separation_time_sec','cg_independent_scan_time_sec','cg_total_time_sec', ...
    'cg_iterations','cg_final_active_constraints','cg_active_ratio_R2', ...
    'distance_scale_max_abs_error','status_ok','objective_ok','TerminalLOH_ok', ...
    'independent_scan_ok','distance_scale_ok','case_pass'});
iterationHistory = vertcat(iterationTables{:});

performance = groupsummary(comparison, {'R','rho'}, {'min','mean','max'}, ...
    {'cg_active_ratio_R2','cg_final_active_constraints','cg_iterations', ...
    'full_total_time_sec','cg_total_time_sec','cg_gurobi_solve_time_sec', ...
    'cg_separation_time_sec'});
performance.cg_total_gurobi_time_sec = performance.mean_cg_gurobi_solve_time_sec;
performance.cg_total_scan_time_sec = performance.mean_cg_separation_time_sec;
performance.cg_gurobi_time_share = performance.cg_total_gurobi_time_sec ./ ...
    (performance.cg_total_gurobi_time_sec + performance.cg_total_scan_time_sec);
performance.cg_separation_time_share = 1 - performance.cg_gurobi_time_share;

acceptance = comparison(:, {'complexity_label','initial_state_id','R','rho', ...
    'full_status','cg_status','objective_abs_error','TerminalLOH_max_abs_error', ...
    'cg_independent_scan_max_violation','distance_scale_max_abs_error', ...
    'status_ok','objective_ok','TerminalLOH_ok','independent_scan_ok', ...
    'distance_scale_ok','case_pass'});
acceptance.objective_tolerance = repmat(1e-8, height(acceptance), 1);
acceptance.TerminalLOH_tolerance = repmat(1e-7, height(acceptance), 1);
acceptance.violation_tolerance = repmat(1e-8, height(acceptance), 1);

csvHashAfter = sha256_file(nominalCsv);
matHashAfter = sha256_file(nominalMat);
protectedAfter = strings(numel(protectedFiles), 1);
for ii = 1:numel(protectedFiles)
    protectedAfter(ii) = sha256_file(char(protectedFiles(ii)));
end
oldBenchmarkHashAfter = sha256_file(oldBenchmark);
inputUnchanged = csvHashAfter == csvHashBefore && matHashAfter == matHashBefore;
protectedUnchanged = all(protectedAfter == protectedBefore);
oldBenchmarkUnchanged = oldBenchmarkHashAfter == oldBenchmarkHashBefore;
allCasesPass = all(comparison.case_pass);
failCount = sum(~comparison.case_pass) + double(~inputUnchanged) + ...
    double(~protectedUnchanged) + double(~oldBenchmarkUnchanged);
passCount = height(comparison) * 5 + 3 - failCount;
if failCount ~= 0
    error('Step-03M final audit failed with %d failures.', failCount);
end

totalCgGurobi = sum(comparison.cg_gurobi_solve_time_sec);
totalCgSeparation = sum(comparison.cg_separation_time_sec) + ...
    sum(comparison.cg_independent_scan_time_sec);
if totalCgGurobi >= totalCgSeparation
    dominantTime = "GUROBI_SOLVE";
else
    dominantTime = "FULL_SEPARATION_SCAN";
end
activeMin = min(comparison.cg_active_ratio_R2);
activeMean = mean(comparison.cg_active_ratio_R2);
activeMax = max(comparison.cg_active_ratio_R2);
recommendation = "TEST_R2000_NEXT; TEST_R5000_ONLY_AFTER_R2000_RESOURCE_REVIEW";

mkdir(outputDir);
writetable(selected, fullfile(outputDir, 'step03M_selected_states.csv'));
writetable(comparison, fullfile(outputDir, 'step03M_full_vs_constraint_generation.csv'));
writetable(iterationHistory, fullfile(outputDir, 'step03M_iteration_history.csv'));
writetable(performance, fullfile(outputDir, 'step03M_performance_summary.csv'));
writetable(acceptance, fullfile(outputDir, 'step03M_acceptance_tests.csv'));
write_math_audit(fullfile(outputDir, 'step03M_current_wdro_math_audit.md'), ...
    config, M, Cap, penaltySource);
write_summary(fullfile(outputDir, 'step03M_summary.txt'), comparison, ...
    passCount, failCount, activeMin, activeMean, activeMax, ...
    totalCgGurobi, totalCgSeparation, dominantTime, recommendation, ...
    inputUnchanged, protectedUnchanged, oldBenchmarkUnchanged);

manifest = strings(0, 1);
manifest(end + 1) = "task=Step-03M exact WDRO constraint generation validation";
manifest(end + 1) = "branch=task/002-stage2b-b3-smoke";
manifest(end + 1) = "nominal_csv_sha256=" + csvHashAfter;
manifest(end + 1) = "nominal_mat_sha256=" + matHashAfter;
manifest(end + 1) = "selected_state_ids=" + join(string(selected.initial_state_id.'), ",");
manifest(end + 1) = "R_values=100,250,500,1000";
manifest(end + 1) = "rho_values=0,0.02";
manifest(end + 1) = "distance_mode=DAC_maskedC";
manifest(end + 1) = "capacity_fraction=" + string(capacityFraction);
manifest(end + 1) = "gamma=" + string(config.gamma);
manifest(end + 1) = "M=" + string(M);
manifest(end + 1) = "violation_tolerance=1e-8";
manifest(end + 1) = "full_solver_temporary_gurobi_env=OptimalityTol_1e-9,FeasibilityTol_1e-9,NumericFocus_3";
manifest(end + 1) = "full_pair_scan=true";
manifest(end + 1) = "R15000_run=false";
manifest(end + 1) = "MSP_run=false";
manifest(end + 1) = "formal_WDRO_run=false";
write_lines(fullfile(outputDir, 'run_manifest.txt'), manifest);

fprintf('\nStep-03M completed: PASS=%d FAIL=%d\n', passCount, failCount);
fprintf('Active constraint ratio min/mean/max: %.9g / %.9g / %.9g\n', ...
    activeMin, activeMean, activeMax);
fprintf('CG Gurobi time %.3f s; complete separation time %.3f s; dominant=%s\n', ...
    totalCgGurobi, totalCgSeparation, dominantTime);
fprintf('Recommendation: %s\n', recommendation);

function value = whos_bytes(variableName)
info = evalin('caller', sprintf('whos(''%s'')', variableName));
value = info.bytes;
end

function maxViolation = full_solution_max_violation(sol, dMat, blockSize)
if sol.exitflag ~= 1
    maxViolation = NaN;
    return;
end
R = numel(sol.L);
maxViolation = -inf;
for start = 1:blockSize:R
    rIdx = start:min(R, start + blockSize - 1);
    violation = reshape(sol.L, 1, []) - sol.lambda .* dMat(rIdx, :) - sol.alpha(rIdx);
    maxViolation = max(maxViolation, max(violation, [], 'all'));
end
end

function sol = solve_full_with_tight_env(D, A, C, Cap, M, rho, dMat, config)
% The accepted full solver does not expose numerical-tolerance fields. A
% temporary Gurobi environment tightens only the benchmark solve and leaves
% the accepted MATLAB source and repository configuration unchanged.
oldDir = pwd;
tempDir = tempname;
mkdir(tempDir);
fid = fopen(fullfile(tempDir, 'gurobi.env'), 'w');
if fid < 0
    error('Cannot create temporary Gurobi environment.');
end
fprintf(fid, 'OptimalityTol 1e-9\n');
fprintf(fid, 'FeasibilityTol 1e-9\n');
fprintf(fid, 'NumericFocus 3\n');
fclose(fid);
try
    cd(tempDir);
    sol = solve_wdro_terminal_loh_lp_h2(D, A, C, Cap, M, rho, dMat, config);
    cd(oldDir);
    rmdir(tempDir, 's');
catch ME
    cd(oldDir);
    if exist(tempDir, 'dir'); rmdir(tempDir, 's'); end
    rethrow(ME);
end
end

function write_math_audit(path, config, M, Cap, penaltySource)
lines = [ ...
    "# Step-03M Current WDRO Mathematical Audit"; ...
    ""; ...
    "## Scope and suitability"; ...
    ""; ...
    "The accepted solver is `solve_wdro_terminal_loh_lp_h2.m`; the accepted distance builder is `build_wdro_distance_matrix_h2.m`. Neither file is modified by Step-03M."; ...
    ""; ...
    "The current finite-support Wasserstein dual is suitable for an exact exchange method. For fixed restricted-master variables, every omitted pair constraint has an explicit violation value and all ordered pairs can be scanned exactly."; ...
    ""; ...
    "## Variables"; ...
    ""; ...
    "- `T_i`, i=1,...,4: TerminalLOH at each of the four sites, bounded by `Cap_i`."; ...
    "- `y^s_{i,n}`: hydrogen service from site i to node n in consequence atom s."; ...
    "- `u^s_n`: unmet node demand in atom s."; ...
    "- `L_s`: optimized service and shortage loss of atom s."; ...
    "- `lambda >= 0`: Wasserstein-radius dual multiplier."; ...
    "- `alpha_r` unrestricted: empirical-atom dual intercept."; ...
    ""; ...
    "## Current objective"; ...
    ""; ...
    "`min gamma * sum_i T_i + rho * lambda + (1/R) * sum_r alpha_r`."; ...
    ""; ...
    "The implementation fixes the empirical mass at `1/R`; it does not accept non-equal sample weights."; ...
    ""; ...
    "## Consequence and service constraints"; ...
    ""; ...
    "For every atom s and node n: `sum_i y^s_{i,n} + u^s_n = D^s_n`."; ...
    ""; ...
    "For every atom s and site i: `sum_n y^s_{i,n} <= T_i`, with `0 <= T_i <= Cap_i`."; ...
    ""; ...
    "Reachability enters through `0 <= y^s_{i,n} <= A^s_{i,n} D^s_n`."; ...
    ""; ...
    "Loss is constrained by `L_s >= sum_{i,n} Ceff^s_{i,n} y^s_{i,n} + M sum_n u^s_n`, where `Ceff=0` at A=0 and reachable C must be finite."; ...
    ""; ...
    "## Wasserstein distance"; ...
    ""; ...
    "Step-03M uses the accepted `DAC_maskedC` distance. D contributes full node-level L1 demand difference, A contributes full 4x33 binary reachability L1 difference, and C contributes L1 service-cost difference only where both atoms have A=1."; ...
    ""; ...
    sprintf("Component weights are D/A/C = %.6g/%.6g/%.6g. Each component is divided by its maximum pairwise value plus epsDistance %.3g when that scale exceeds %.3g.", config.distanceWeightsDACMaskedC.D, config.distanceWeightsDACMaskedC.A, config.distanceWeightsDACMaskedC.C, config.epsDistance, config.scaleTolerance); ...
    ""; ...
    "Path states, sampled winds, and random seeds are metadata and do not enter the current distance or loss."; ...
    ""; ...
    "## Origin of the R-squared constraints"; ...
    ""; ...
    "For every empirical atom r and consequence atom s, the solver adds `alpha_r + lambda*d(r,s) >= L_s`, equivalently `L_s - lambda*d(r,s) - alpha_r <= 0`. The nested r,s loops create exactly R^2 rows."; ...
    ""; ...
    "## Exact separation"; ...
    ""; ...
    "For each r, Step-03M computes `max_s {L_s - lambda*d(r,s) - alpha_r}` over every s. If the maximum exceeds 1e-8, the most violated pair for that r is added. The distance scale scan, every iteration scan, and the post-convergence independent scan cover all ordered pairs in blocks without retaining an R-by-R distance matrix."; ...
    ""; ...
    "This is an exact exchange implementation for the current finite LP. It uses no clustering, scenario reduction, random subset, approximate nearest neighbor, or partial separation."; ...
    ""; ...
    "For the 1e-8 objective comparison, the unchanged full solver is called under a temporary out-of-repository `gurobi.env` with `OptimalityTol=1e-9`, `FeasibilityTol=1e-9`, and `NumericFocus=3`. This avoids a measured default-tolerance alpha/L slack while leaving the accepted solver source, default mode, and repository configuration unchanged."; ...
    ""; ...
    "## Experiment parameters"; ...
    ""; ...
    sprintf("`M=%.12g` from `%s`; `gamma=%.12g`; `Cap=0.8*tank_capacity=[%s]` kg; rho values are 0 and the existing minimum positive radius 0.02.", M, penaltySource, config.gamma, strtrim(sprintf('%.12g ', Cap))); ...
    ""; ...
    "Literature basis: Mohajerin Esfahani and Kuhn (2018) for the Wasserstein dual reformulation; Luo and Mehrotra (2019) for exchange/cutting-surface decomposition. The present experiment retains this project's existing four-site TerminalLOH variables and D/A/C definitions."];
write_lines(path, lines);
end

function write_summary(path, tbl, passCount, failCount, activeMin, activeMean, ...
        activeMax, gurobiTime, separationTime, dominantTime, recommendation, ...
        inputUnchanged, protectedUnchanged, oldBenchmarkUnchanged)
lines = [ ...
    "Step-03M exact WDRO constraint-generation validation"; ...
    "PASS=" + string(passCount); ...
    "FAIL=" + string(failCount); ...
    "case_count=" + string(height(tbl)); ...
    "exact_small_scale_match=" + string(all(tbl.case_pass)); ...
    "max_objective_abs_error=" + string(sprintf('%.16g', max(tbl.objective_abs_error))); ...
    "max_TerminalLOH_abs_error=" + string(sprintf('%.16g', max(tbl.TerminalLOH_max_abs_error))); ...
    "max_independent_constraint_violation=" + string(sprintf('%.16g', max(tbl.cg_independent_scan_max_violation))); ...
    "active_constraint_ratio_min=" + string(sprintf('%.16g', activeMin)); ...
    "active_constraint_ratio_mean=" + string(sprintf('%.16g', activeMean)); ...
    "active_constraint_ratio_max=" + string(sprintf('%.16g', activeMax)); ...
    "constraint_generation_gurobi_time_sec=" + string(sprintf('%.16g', gurobiTime)); ...
    "complete_separation_time_sec=" + string(sprintf('%.16g', separationTime)); ...
    "dominant_time_component=" + dominantTime; ...
    "next_scale_recommendation=" + recommendation; ...
    "Step03J_input_unchanged=" + string(inputUnchanged); ...
    "protected_WDRO_core_unchanged=" + string(protectedUnchanged); ...
    "Step03K_old_result_unchanged=" + string(oldBenchmarkUnchanged); ...
    "R15000_tested=false"; ...
    "all_35_states_tested=false"; ...
    "formal_WDRO_run=false"; ...
    "MSP_run=false"];
write_lines(path, lines);
end

function write_lines(path, lines)
fid = fopen(path, 'w');
if fid < 0
    error('Cannot write %s.', path);
end
cleanup = onCleanup(@() fclose(fid));
for ii = 1:numel(lines)
    fprintf(fid, '%s\n', char(lines(ii)));
end
end

function hash = sha256_file(path)
if ~isfile(path)
    error('SHA-256 input file is missing: %s', path);
end
[status, output] = system(sprintf('certutil -hashfile "%s" SHA256', path));
if status ~= 0
    error('certutil failed for %s: %s', path, output);
end
tokens = regexp(output, '[0-9A-Fa-f]{64}', 'match');
if isempty(tokens)
    error('Could not parse SHA-256 for %s.', path);
end
hash = lower(string(tokens{1}));
end
