function run_step03S_state_distribution_tail_regret_audit_h2()
%RUN_STEP03S_STATE_DISTRIBUTION_TAIL_REGRET_AUDIT_H2 Full Step-03S audit.

clc;
runTic = tic;
thisDir = fileparts(mfilename('fullpath'));
moduleDir = fileparts(thisDir);
rootDir = fileparts(moduleDir);
addpath(rootDir);
addpath(thisDir);
for candidate = {fullfile(getenv('GUROBI_HOME'), 'matlab'), ...
        'D:\gurobi1201\win64\matlab', 'C:\gurobi1201\win64\matlab'}
    if ~isempty(candidate{1}) && exist(candidate{1}, 'dir')
        addpath(candidate{1});
    end
end
if ~ismember(exist('gurobi', 'file'), [2, 3])
    error('Step-03S requires the existing Gurobi MATLAB interface.');
end

expectedHead = "9579fdf785cb8a182d2b5bc225600b6467d9dfd9";
[headStatus, headText] = system('git rev-parse HEAD');
actualHead = lower(strtrim(string(headText)));
if headStatus ~= 0 || actualHead ~= expectedHead
    error('Step-03S must start from baseline commit %s.', expectedHead);
end
resultRoot = fullfile(rootDir, 'results', 'task-002-stage2b-b3-smoke');
outputDir = fullfile(resultRoot, ...
    '19-state-distribution-tail-regret-audit', 'run-001');
tempDir = outputDir + ".tmp";
localDir = fullfile(moduleDir, 'output', ...
    'stage3s_state_distribution_tail_regret_audit', 'run-001');
checkpointDir = fullfile(localDir, 'checkpoints');
if isfolder(outputDir)
    error('Step-03S final output directory already exists.');
end
if isfolder(tempDir)
    rmdir(tempDir, 's');
end
if ~isfolder(checkpointDir)
    mkdir(checkpointDir);
end

inputDir = fullfile(moduleDir, 'output', ...
    'stage3j_wdro_input_freeze', 'run-001');
nominalPath = fullfile(inputDir, 'wdro_nominal_input_DAC.mat');
nominalCsv = fullfile(inputDir, 'wdro_nominal_input.csv');
nominalHash = "6936a696f5cde137aca483f8c32adee33b52cbd90559a8e6395f3686c0712945";
if sha256_file(nominalPath) ~= nominalHash
    error('Step-03S Step-03J nominal MAT hash mismatch.');
end
step03QDir = fullfile(resultRoot, ...
    '17-dctilde-strict-metric-audit', 'run-001');
step03RDir = fullfile(resultRoot, ...
    '18-ctilde-decision-similarity-audit', 'run-001');
step03PFailedDir = fullfile(resultRoot, ...
    '16-dac-transport-cost-audit', 'run-001');
if ~isfolder(step03QDir) || ~isfolder(step03RDir) || ...
        ~isfolder(step03PFailedDir)
    error('Step-03S required accepted/history directories are missing.');
end
step03JBefore = directory_hash(inputDir);
step03QBefore = directory_hash(step03QDir);
step03RBefore = directory_hash(step03RDir);
step03PFailedBefore = directory_hash(step03PFailedDir);
protectedFiles = [ ...
    string(fullfile(thisDir, 'build_wdro_distance_matrix_h2.m')); ...
    string(fullfile(thisDir, 'build_step03Q_distance_matrix_h2.m')); ...
    string(fullfile(thisDir, 'build_step03P_distance_components_h2.m')); ...
    string(fullfile(thisDir, 'solve_wdro_terminal_loh_lp_h2.m')); ...
    string(fullfile(thisDir, 'solve_wdro_terminal_loh_lp_constraint_generation_h2.m')); ...
    string(fullfile(thisDir, 'solve_step03P_weighted_cg_h2.m')); ...
    string(fullfile(rootDir, 'main_msp_h2_near.m')); ...
    string(fullfile(rootDir, 'h2_default_options.m')); ...
    string(fullfile(rootDir, 'run_h2_with_options.m')); ...
    string(fullfile(rootDir, 'fa_h2', 'build_stage_model_h2.m')); ...
    string(fullfile(rootDir, 'fa_h2', 'update_rhs_h2.m')); ...
    string(fullfile(rootDir, 'fa_h2', 'solve_stage_model_h2.m'))];
protectedBefore = hash_files(protectedFiles);

[probabilityAudit, probabilityPass] = audit_probability_semantics( ...
    nominalCsv, nominalPath);
if ~probabilityPass
    error('Step-03S probability semantics audit failed.');
end
raw = load(fullfile(rootDir, 'data', 'yuanqi', ...
    'near_stage_msp_input.mat'), 'NearStageInput');
ni = raw.NearStageInput;
Cap = double(ni.HydrogenDevice.tank_cap_kg(:));
if max(abs(Cap - [300; 200; 100; 150])) > 1e-12
    error('Step-03S capacity vector is not [300,200,100,150].');
end
if isfield(ni.Cost, 'reserve_shortage_penalty_yuan_per_kg')
    M = double(ni.Cost.reserve_shortage_penalty_yuan_per_kg);
    penaltySource = "NearStageInput.Cost.reserve_shortage_penalty_yuan_per_kg";
elseif isfield(ni.Cost, 'cost_reserve_shortage')
    M = double(ni.Cost.cost_reserve_shortage);
    penaltySource = "NearStageInput.Cost.cost_reserve_shortage";
else
    error('Step-03S cannot trace the shortage penalty source.');
end

config = struct('gamma', 0.001 * M, 'gurobiOutputFlag', 0, ...
    'gurobiFeasibilityTol', 1e-9, 'gurobiOptimalityTol', 1e-9, ...
    'gurobiTimeLimit', 600, 'primaryObjectiveTolerance', 1e-8, ...
    'C_bound', 357.1526447416079, 'kappa', 1, ...
    'weight_D', 0.6, 'weight_Ctilde', 0.4, ...
    'epsDistance', 1e-9, 'scaleTolerance', 1e-12, ...
    'featureCount', 16, 'stateCount', 35, 'rowsPerState', 15000, ...
    'energySampleSize', 1000, 'energyRepeats', 10, ...
    'energyBlockSize', 250, 'distanceQueryBlockSize', 20, ...
    'distanceTargetBlockSize', 500, 'variableLossChunkSize', 2000, ...
    'tail95Count', 750, 'tail99Count', 150, 'tail995Count', 75, ...
    'nearestCount', 10, 'zeroDistanceTolerance', 1e-12, ...
    'regretTolerance', 1e-8, 'multipleOptimumWidth', 1e-5, ...
    'historicalNearFraction', 0.01, 'historicalHighFraction', 0.01, ...
    'tierRelative10', 0.10, 'tierRelative5', 0.05, ...
    'lossSimilarityFraction', 0.01);
featureNames = ["total_D", "unreachable_D", "unreachable_D_ratio", ...
    "reachable_D_1", "reachable_D_2", "reachable_D_3", ...
    "reachable_D_4", "demand_weighted_C_1", ...
    "demand_weighted_C_2", "demand_weighted_C_3", ...
    "demand_weighted_C_4", "loss_T0", "loss_T25", ...
    "loss_T50", "loss_T75", "loss_T100"];
phaseRecords = cell(0, 1);
peakMemory = memory_used_bytes();

phaseTic = tic;
[featureData, distributionTbl, tailProfileTbl, stateSummaryTbl] = ...
    build_all_state_features(nominalPath, Cap, M, featureNames, ...
    checkpointDir, config);
phaseRecords{end + 1, 1} = phase_record("FEATURES_AND_PROFILES", ...
    toc(phaseTic), memory_used_bytes());
peakMemory = max(peakMemory, phaseRecords{end}.memory_bytes);

scalingTbl = build_feature_scaling(featureData.Z, featureNames);
Zstandard = standardize_features(featureData.Z, scalingTbl);
if any(~isfinite(Zstandard), 'all')
    error('Step-03S standardized features contain NaN or Inf.');
end

phaseTic = tic;
[bulkMedian, tailMedian, uncertaintyTbl, energyReproError] = ...
    compute_energy_audit(Zstandard, featureData.tail95, ...
    checkpointDir, config);
phaseRecords{end + 1, 1} = phase_record("ENERGY_DISTANCE", ...
    toc(phaseTic), memory_used_bytes());
peakMemory = max(peakMemory, phaseRecords{end}.memory_bytes);

[selectedTbl, selectionLines] = select_depth_states( ...
    stateSummaryTbl, tailProfileTbl, bulkMedian, tailMedian, config);
selectedStates = double(selectedTbl.initial_state_id);
fprintf('\nStep-03S selected states: %s\n', join(string(selectedStates.'), ', '));

phaseTic = tic;
[neighborTbl, crossRegretTbl, falseNearTbl, diagnosticLines, ...
    deepAudit] = run_tail_depth_audit(nominalPath, featureData, ...
    selectedTbl, Cap, M, checkpointDir, config);
phaseRecords{end + 1, 1} = phase_record("TAIL_DEPTH_AUDIT", ...
    toc(phaseTic), memory_used_bytes());
peakMemory = max(peakMemory, phaseRecords{end}.memory_bytes);

codeFiles = [string(mfilename('fullpath')) + ".m"; ...
    string(fullfile(thisDir, 'step03S_distance_block_h2.m')); ...
    string(fullfile(thisDir, 'step03S_energy_distance_h2.m')); ...
    string(fullfile(thisDir, 'evaluate_step03S_variable_T_losses_h2.m'))];
checkcodeWarningCount = 0;
for ff = 1:numel(codeFiles)
    messages = checkcode(codeFiles(ff), '-id');
    checkcodeWarningCount = checkcodeWarningCount + numel(messages);
end

protectedAfter = hash_files(protectedFiles);
protectedPass = all(protectedAfter == protectedBefore);
step03JPass = directory_hash(inputDir) == step03JBefore && ...
    sha256_file(nominalPath) == nominalHash;
oldRunPass = directory_hash(step03QDir) == step03QBefore && ...
    directory_hash(step03RDir) == step03RBefore && ...
    directory_hash(step03PFailedDir) == step03PFailedBefore;
bulkSymmetry = max(abs(bulkMedian - bulkMedian.'), [], 'all');
tailSymmetry = max(abs(tailMedian - tailMedian.'), [], 'all');
bulkDiagonal = max(abs(diag(bulkMedian)));
tailDiagonal = max(abs(diag(tailMedian)));
profileComplete = height(distributionTbl) == 35 * (numel(featureNames) + 13);
requiredSelectionRules = ["BASE_STATE_7", "BASE_STATE_18", ...
    "BASE_STATE_30", "BULK_OUTLIER", "Q995_LOSS_MAX", ...
    "CVAR995_LOSS_MAX", "Q995_UNREACHABLE_D_MAX", ...
    "BULK_CLOSE_TAIL_FAR", "SPATIAL_TAIL_MODE"];
observedSelectionRules = unique(split(join(selectedTbl.selection_rules, ";"), ";"));
selectionRulesPass = all(ismember(requiredSelectionRules, observedSelectionRules));
regretNonnegative = deepAudit.minimum_objective_regret >= -1e-7 && ...
    deepAudit.minimum_loss_regret >= -1e-7;
zeroRegretPass = deepAudit.zero_distance_max_regret <= 1e-8;
domainPass = all(isfinite(distributionTbl{:, 4:end}), 'all') && ...
    all(isfinite(crossRegretTbl{:, {'d_new','regret_obj_r_to_s', ...
    'regret_obj_s_to_r','relative_regret_obj_r_to_s', ...
    'relative_regret_obj_s_to_r'}}), 'all');

auditRows = {
    'DATA-01', pass_fail(size(featureData.Z, 1) == 525000), size(featureData.Z, 1), '35 x 15000 nominal rows';
    'PROB-01', pass_fail(probabilityPass), probabilityPass, 'code-level empirical-mass audit complete';
    'FEATURE-01', pass_fail(all(isfinite(featureData.Z), 'all')), all(isfinite(featureData.Z), 'all'), 'no NaN/Inf in risk-decision features';
    'PROFILE-01', pass_fail(profileComplete), height(distributionTbl), '35 states x (16 features + 13 state audits)';
    'ENERGY-01', pass_fail(max(bulkSymmetry, tailSymmetry) <= 1e-10), max(bulkSymmetry, tailSymmetry), '<=1e-10 symmetry error';
    'ENERGY-02', pass_fail(max(bulkDiagonal, tailDiagonal) <= 1e-10), max(bulkDiagonal, tailDiagonal), '<=1e-10 diagonal';
    'ENERGY-03', pass_fail(energyReproError <= 1e-12), energyReproError, '<=1e-12 fixed-seed reproduction';
    'SELECT-01', pass_fail(selectionRulesPass), selectionRulesPass, 'all mandatory state-selection rules applied';
    'SOLVE-01', pass_fail(deepAudit.all_single_optimal), deepAudit.all_single_optimal, 'all required two-stage atom solves OPTIMAL';
    'REGRET-01', pass_fail(regretNonnegative), min(deepAudit.minimum_objective_regret, deepAudit.minimum_loss_regret), '>=-1e-7';
    'ZERO-01', pass_fail(zeroRegretPass), deepAudit.zero_distance_max_regret, '<=1e-8';
    'DIAG-01', pass_fail(deepAudit.all_required_pairs_diagnosed), deepAudit.diagnosed_pair_count, 'all Tier-1 and top-20 pairs diagnosed';
    'TUNE-01', 'PASS', 'nominal only', 'validation not used for selection/scaling/tuning';
    'CORE-01', pass_fail(protectedPass), protectedPass, 'formal distance/rho/loss/MSP unchanged';
    'SCOPE-01', 'PASS', 'no formal WDRO; no R=5000/R=15000 solve', 'scope restriction';
    'CODE-01', pass_fail(checkcodeWarningCount == 0), checkcodeWarningCount, '0 checkcode warnings';
    'RESOURCE-01', pass_fail(all(cellfun(@(x) isfinite(x.elapsed_sec), phaseRecords))), toc(runTic), 'complete phase timing and memory records';
    'DATA-02', pass_fail(step03JPass), step03JPass, 'Step-03J unchanged';
    'OLD-01', pass_fail(oldRunPass), oldRunPass, 'Step-03P/Q/R history unchanged';
    'DOMAIN-01', pass_fail(domainPass), domainPass, 'finite output domain'};
acceptanceTbl = cell2table(auditRows, 'VariableNames', ...
    {'check_id', 'status', 'observed', 'expected'});
failCount = sum(strcmp(acceptanceTbl.status, 'FAIL'));
if failCount > 0
    disp(acceptanceTbl(strcmp(acceptanceTbl.status, 'FAIL'), :));
    error('Step-03S has %d mechanical failures; no archive or Git write.', failCount);
end

decision = choose_decision(crossRegretTbl, deepAudit);
bulkTbl = matrix_table(bulkMedian, "bulk_energy");
tailTbl = matrix_table(tailMedian, "tail95_energy");
resourceTbl = records_to_table(phaseRecords);
resourceTbl.total_elapsed_sec = repmat(toc(runTic), height(resourceTbl), 1);
resourceTbl.peak_memory_bytes = repmat(peakMemory, height(resourceTbl), 1);

mkdir(tempDir);
write_probability_semantics(fullfile(tempDir, ...
    'step03S_probability_semantics.md'), probabilityAudit);
write_feature_definition(fullfile(tempDir, ...
    'step03S_risk_decision_feature_definition.md'), featureNames, ...
    Cap, M, penaltySource, config);
writetable(scalingTbl, fullfile(tempDir, 'step03S_state_feature_scaling.csv'));
writetable(distributionTbl, fullfile(tempDir, ...
    'step03S_state_distribution_profiles.csv'));
writetable(tailProfileTbl, fullfile(tempDir, ...
    'step03S_state_tail_profiles.csv'));
writetable(bulkTbl, fullfile(tempDir, 'step03S_bulk_energy_distance.csv'));
writetable(tailTbl, fullfile(tempDir, 'step03S_tail95_energy_distance.csv'));
writetable(uncertaintyTbl, fullfile(tempDir, ...
    'step03S_energy_distance_uncertainty.csv'));
writetable(selectedTbl, fullfile(tempDir, 'step03S_selected_states.csv'));
write_lines(fullfile(tempDir, 'step03S_state_selection_rationale.md'), ...
    selectionLines);
writetable(neighborTbl, fullfile(tempDir, ...
    'step03S_tail_nearest_neighbors.csv'));
writetable(crossRegretTbl, fullfile(tempDir, ...
    'step03S_tail_cross_regret.csv'));
writetable(falseNearTbl, fullfile(tempDir, 'step03S_false_near_cases.csv'));
write_lines(fullfile(tempDir, 'step03S_false_near_diagnostics.md'), ...
    ["# Step-03S False-Near Diagnostics"; ""; diagnosticLines]);
writetable(acceptanceTbl, fullfile(tempDir, ...
    'step03S_acceptance_tests.csv'));
writetable(resourceTbl, fullfile(tempDir, 'step03S_resource_report.csv'));
write_summary(fullfile(tempDir, 'step03S_summary.txt'), decision, ...
    selectedTbl, stateSummaryTbl, bulkMedian, tailMedian, crossRegretTbl, ...
    deepAudit, toc(runTic), peakMemory, failCount);
write_local_manifest(localDir, checkpointDir, nominalPath, config, ...
    toc(runTic), peakMemory);
movefile(tempDir, outputDir);
fprintf('\nStep-03S completed: %s; PASS=%d FAIL=%d; elapsed=%.1f sec.\n', ...
    decision, height(acceptanceTbl), failCount, toc(runTic));
end

function [audit, pass] = audit_probability_semantics(csvPath, matPath)
opts = detectImportOptions(csvPath, 'TextType', 'string');
names = string(opts.VariableNames);
selected = intersect(["initial_state_id", "path_id", "sample_weight", ...
    "dataset_role"], names, 'stable');
opts.SelectedVariableNames = cellstr(selected);
metadata = readtable(csvPath, opts);
required = ["initial_state_id", "path_id", "sample_weight", "dataset_role"];
fieldsPass = all(ismember(required, string(metadata.Properties.VariableNames)));
stateCountPass = height(metadata) == 525000 && ...
    numel(unique(metadata.initial_state_id)) == 35;
weightPass = true;
for stateId = 1:35
    mask = double(metadata.initial_state_id) == stateId;
    weightPass = weightPass && sum(mask) == 15000 && ...
        max(abs(double(metadata.sample_weight(mask)) - 1 / 15000)) <= 1e-15 && ...
        abs(sum(double(metadata.sample_weight(mask))) - 1) <= 1e-12;
end
probabilityNames = names(contains(lower(names), "probability") | ...
    contains(lower(names), "transition_prob") | ...
    contains(lower(names), "path_prob") | contains(lower(names), "scenario_prob"));
m = matfile(matPath);
matInfo = whos(m);
matNames = string({matInfo.name});
explicitProbability = ~isempty(probabilityNames) || ...
    any(contains(lower(matNames), "probability"));
audit = struct('row_count', height(metadata), 'state_count', ...
    numel(unique(metadata.initial_state_id)), 'rows_per_state', 15000, ...
    'sample_weight_value', 1 / 15000, 'weight_sum_per_state', 1, ...
    'scenario_csv_fields', join(names, ", "), ...
    'dac_mat_fields', join(matNames, ", "), ...
    'explicit_probability_fields', join(probabilityNames, ", "), ...
    'explicit_probability_present', explicitProbability, ...
    'path_id_is_record_identity', true, ...
    'repeated_rows_represent_empirical_mass', true, ...
    'dataset_role_unique', join(unique(metadata.dataset_role), ", "));
pass = fieldsPass && stateCountPass && weightPass && ...
    ~explicitProbability && all(metadata.dataset_role == "nominal");
end

function [data, profileTbl, tailTbl, stateSummaryTbl] = ...
        build_all_state_features(matPath, Cap, M, featureNames, ...
        checkpointDir, config)
totalRows = config.stateCount * config.rowsPerState;
Z = zeros(totalRows, numel(featureNames));
tail95 = false(totalRows, 1);
tail99 = false(totalRows, 1);
tail995 = false(totalRows, 1);
pathId = zeros(totalRows, 1);
profileRecords = cell(0, 1);
tailRecords = cell(0, 1);
summaryRecords = cell(0, 1);
m = matfile(matPath);
for stateId = 1:config.stateCount
    cp = fullfile(checkpointDir, sprintf('features_state_%02d.mat', stateId));
    if isfile(cp)
        loaded = load(cp, 'stateFeature');
        stateFeature = loaded.stateFeature;
        fprintf('Step-03S state %d feature checkpoint loaded.\n', stateId);
    else
        fprintf('Step-03S state %d/35: build 16 risk-decision features.\n', stateId);
        rows = (stateId - 1) * config.rowsPerState + (1:config.rowsPerState);
        D = double(m.D_node_kg(rows, :));
        A = double(m.A_site_node(rows, :, :));
        C = double(m.C_site_node_km(rows, :, :));
        statePathId = double(m.path_id(rows, 1));
        stateIds = double(m.initial_state_id(rows, 1));
        if any(stateIds ~= stateId) || ~isequal(size(A), [15000, 4, 33]) || ...
                ~isequal(size(C), size(A))
            error('Step-03S frozen state %d layout mismatch.', stateId);
        end
        stateFeature = compute_state_feature(stateId, D, A, C, ...
            statePathId, Cap, M, config);
        save(cp, 'stateFeature', '-v7.3');
    end
    rows = (stateId - 1) * config.rowsPerState + (1:config.rowsPerState);
    Z(rows, :) = stateFeature.Z;
    tail95(rows) = stateFeature.tail95;
    tail99(rows) = stateFeature.tail99;
    tail995(rows) = stateFeature.tail995;
    pathId(rows) = stateFeature.path_id;
    for ff = 1:numel(featureNames)
        profileRecords{end + 1, 1} = feature_profile_record( ...
            stateId, featureNames(ff), stateFeature.Z(:, ff)); %#ok<AGROW>
    end
    for rr = 1:numel(stateFeature.tail_records)
        tailRecords{end + 1, 1} = stateFeature.tail_records{rr}; %#ok<AGROW>
    end
    summaryMetricNames = ["unique_D_count", "unique_A_count", ...
        "unique_Ctilde_count", "unique_joint_D_A_Ctilde_count", ...
        "zero_demand_share", "fully_unreachable_demand_share", ...
        "full_capacity_positive_loss_share", ...
        "tail95_threshold_loss_T50", "tail99_threshold_loss_T50", ...
        "tail995_threshold_loss_T50", "tail95_boundary_tie_count", ...
        "tail99_boundary_tie_count", "tail995_boundary_tie_count"];
    for mm = 1:numel(summaryMetricNames)
        metricName = char(summaryMetricNames(mm));
        profileRecords{end + 1, 1} = scalar_profile_record( ...
            stateId, "audit_" + summaryMetricNames(mm), ...
            stateFeature.summary.(metricName)); %#ok<AGROW>
    end
    summaryRecords{end + 1, 1} = stateFeature.summary; %#ok<AGROW>
end
data = struct('Z', Z, 'tail95', tail95, 'tail99', tail99, ...
    'tail995', tail995, 'path_id', pathId);
profileTbl = records_to_table(profileRecords);
tailTbl = records_to_table(tailRecords);
stateSummaryTbl = records_to_table(summaryRecords);
end

function out = compute_state_feature(stateId, D, A, C, pathId, Cap, M, config)
R = size(D, 1);
totalD = sum(D, 2);
unreachableAll = reshape(all(A <= 0.5, 2), R, size(D, 2));
unreachableD = sum(D .* unreachableAll, 2);
unreachableRatio = unreachableD ./ max(totalD, eps);
reachableD = zeros(R, 4);
weightedC = zeros(R, 4);
siteUnreachableD = zeros(R, 4);
for ii = 1:4
    Ai = reshape(A(:, ii, :), R, size(D, 2));
    Ci = reshape(C(:, ii, :), R, size(D, 2));
    Ci(~isfinite(Ci) | Ai <= 0.5) = 0;
    reachableD(:, ii) = sum(Ai .* D, 2);
    denominator = reachableD(:, ii);
    weightedC(:, ii) = sum(Ai .* D .* Ci, 2) ./ max(denominator, eps);
    weightedC(denominator <= eps, ii) = 0;
    siteUnreachableD(:, ii) = sum((Ai <= 0.5) .* D, 2);
end
fractions = [0, 0.25, 0.5, 0.75, 1];
anchorLoss = zeros(R, numel(fractions));
for ff = 1:numel(fractions)
    ev = evaluate_step03P_fixed_T_losses_h2( ...
        D, A, C, fractions(ff) .* Cap, M, config);
    if ev.exitflag ~= 1
        error('Step-03S fixed-T loss evaluation failed at fraction %.2f.', ...
            fractions(ff));
    end
    anchorLoss(:, ff) = ev.loss;
end
Z = [totalD, unreachableD, unreachableRatio, reachableD, weightedC, anchorLoss];
[tail95, threshold95, tie95] = ranked_tail(anchorLoss(:, 3), ...
    config.tail95Count);
[tail99, threshold99, tie99] = ranked_tail(anchorLoss(:, 3), ...
    config.tail99Count);
[tail995, threshold995, tie995] = ranked_tail(anchorLoss(:, 3), ...
    config.tail995Count);

Aflat = reshape(A, R, []);
Ccanonical = reshape(C, R, []);
Ccanonical(~isfinite(Ccanonical) | Aflat <= 0.5) = -1;
uniqueD = size(unique(D, 'rows'), 1);
uniqueA = size(unique(Aflat, 'rows'), 1);
uniqueCtilde = size(unique([Aflat, Ccanonical], 'rows'), 1);
uniqueJoint = size(unique([D, Aflat, Ccanonical], 'rows'), 1);

tailLoss = anchorLoss(tail995, 3);
tailUnreachableNode = mean(D(tail995, :) .* unreachableAll(tail995, :), 1);
[~, affectedNode] = max(tailUnreachableNode);
tailSiteUnreachable = mean(siteUnreachableD(tail995, :), 1);
[~, affectedSite] = max(tailSiteUnreachable);
tailRecords = cell(0, 1);
tailSets = {tail95, tail99, tail995};
tailLabels = ["q95", "q99", "q99.5"];
for tt = 1:3
    mask = tailSets{tt};
    tailRecords{end + 1, 1} = struct('initial_state_id', stateId, ...
        'tail_level', tailLabels(tt), 'record_type', "overall", ...
        'entity_id', 0, 'tail_count', sum(mask), ...
        'mean_value', mean(anchorLoss(mask, 3)), ...
        'maximum_value', max(anchorLoss(mask, 3)), ...
        'share_or_score', sum(mask) / R); %#ok<AGROW>
    for nn = 1:size(D, 2)
        tailRecords{end + 1, 1} = struct('initial_state_id', stateId, ...
            'tail_level', tailLabels(tt), 'record_type', "affected_node", ...
            'entity_id', nn, 'tail_count', sum(mask), ...
            'mean_value', mean(D(mask, nn) .* unreachableAll(mask, nn)), ...
            'maximum_value', max(D(mask, nn) .* unreachableAll(mask, nn)), ...
            'share_or_score', mean(unreachableAll(mask, nn))); %#ok<AGROW>
    end
    for ii = 1:4
        tailRecords{end + 1, 1} = struct('initial_state_id', stateId, ...
            'tail_level', tailLabels(tt), 'record_type', "affected_site", ...
            'entity_id', ii, 'tail_count', sum(mask), ...
            'mean_value', mean(siteUnreachableD(mask, ii)), ...
            'maximum_value', max(siteUnreachableD(mask, ii)), ...
            'share_or_score', mean(siteUnreachableD(mask, ii) ./ max(totalD(mask), eps))); %#ok<AGROW>
    end
end
summary = struct('initial_state_id', stateId, 'mean_total_D', mean(totalD), ...
    'q995_loss_T50', pct(anchorLoss(:, 3), 0.995), ...
    'cvar995_loss_T50', tail_mean(anchorLoss(:, 3), 0.995), ...
    'q995_unreachable_D', pct(unreachableD, 0.995), ...
    'unique_D_count', uniqueD, 'unique_A_count', uniqueA, ...
    'unique_Ctilde_count', uniqueCtilde, ...
    'unique_joint_D_A_Ctilde_count', uniqueJoint, ...
    'zero_demand_share', mean(totalD <= 1e-12), ...
    'fully_unreachable_demand_share', mean(totalD > 1e-12 & ...
        unreachableD >= totalD - 1e-10), ...
    'full_capacity_positive_loss_share', mean(anchorLoss(:, 5) > 1e-8), ...
    'tail95_threshold_loss_T50', threshold95, ...
    'tail99_threshold_loss_T50', threshold99, ...
    'tail995_threshold_loss_T50', threshold995, ...
    'tail95_boundary_tie_count', tie95, ...
    'tail99_boundary_tie_count', tie99, ...
    'tail995_boundary_tie_count', tie995, ...
    'q995_affected_site_mode', affectedSite, ...
    'q995_affected_node_mode', affectedNode, ...
    'q995_mean_loss_T50', mean(tailLoss));
out = struct('Z', Z, 'path_id', pathId, 'tail95', tail95, ...
    'tail99', tail99, 'tail995', tail995, 'summary', summary, ...
    'tail_records', {tailRecords});
end

function rec = feature_profile_record(stateId, featureName, values)
rec = struct('initial_state_id', stateId, 'feature_name', featureName, ...
    'sample_count', numel(values), 'mean', mean(values), ...
    'std', std(values, 0), 'q50', pct(values, 0.50), ...
    'q90', pct(values, 0.90), 'q95', pct(values, 0.95), ...
    'q99', pct(values, 0.99), 'q995', pct(values, 0.995), ...
    'maximum', max(values), 'CVaR95', tail_mean(values, 0.95), ...
    'CVaR99', tail_mean(values, 0.99), ...
    'CVaR995', tail_mean(values, 0.995));
end

function rec = scalar_profile_record(stateId, featureName, value)
rec = struct('initial_state_id', stateId, 'feature_name', featureName, ...
    'sample_count', 1, 'mean', value, 'std', 0, 'q50', value, ...
    'q90', value, 'q95', value, 'q99', value, 'q995', value, ...
    'maximum', value, 'CVaR95', value, 'CVaR99', value, ...
    'CVaR995', value);
end

function [mask, threshold, tieCount] = ranked_tail(values, count)
values = double(values(:));
indices = (1:numel(values)).';
[~, order] = sortrows([-values, indices], [1, 2]);
mask = false(size(values));
mask(order(1:count)) = true;
threshold = pct(values, 1 - count / numel(values));
boundary = values(order(count));
tieCount = sum(values == boundary);
end

function tbl = build_feature_scaling(Z, featureNames)
featureCount = numel(featureNames);
records = cell(featureCount, 1);
for ff = 1:featureCount
    center = mean(Z(:, ff));
    scale = std(Z(:, ff), 0);
    constant = scale <= 1e-12;
    if constant
        scale = 1;
    end
    records{ff} = struct('feature_name', featureNames(ff), ...
        'scaling_dataset', "nominal_35_states_525000_equal_mass_rows", ...
        'center_mean', center, 'scale_std', scale, ...
        'constant_feature', constant, 'minimum', min(Z(:, ff)), ...
        'maximum', max(Z(:, ff)));
end
tbl = records_to_table(records);
end

function Zstandard = standardize_features(Z, scalingTbl)
centers = scalingTbl.center_mean.';
scales = scalingTbl.scale_std.';
Zstandard = (Z - centers) ./ scales;
end

function [bulkMedian, tailMedian, uncertaintyTbl, reproError] = ...
        compute_energy_audit(Z, tail95, checkpointDir, config)
bulkAll = zeros(config.stateCount, config.stateCount, config.energyRepeats);
tailAll = zeros(config.stateCount, config.stateCount, config.energyRepeats);
for repeatId = 1:config.energyRepeats
    cp = fullfile(checkpointDir, sprintf('energy_repeat_%02d.mat', repeatId));
    if isfile(cp)
        loaded = load(cp, 'bulkMatrix', 'tailMatrix', 'sampleIndex');
        bulkMatrix = loaded.bulkMatrix;
        tailMatrix = loaded.tailMatrix;
        fprintf('Step-03S energy repeat %d checkpoint loaded.\n', repeatId);
    else
        fprintf('Step-03S energy-distance repeat %d/%d.\n', ...
            repeatId, config.energyRepeats);
        bulkSamples = cell(config.stateCount, 1);
        tailSamples = cell(config.stateCount, 1);
        sampleIndex = cell(config.stateCount, 1);
        for stateId = 1:config.stateCount
            rows = (stateId - 1) * config.rowsPerState + ...
                (1:config.rowsPerState);
            stream = RandStream('mt19937ar', 'Seed', ...
                20260300 + repeatId * 100 + stateId);
            local = randperm(stream, config.rowsPerState, ...
                config.energySampleSize);
            sampleIndex{stateId} = local;
            bulkSamples{stateId} = Z(rows(local), :);
            tailRows = rows(tail95(rows));
            if numel(tailRows) > config.energySampleSize
                tailLocal = randperm(stream, numel(tailRows), ...
                    config.energySampleSize);
                tailRows = tailRows(tailLocal);
            end
            tailSamples{stateId} = Z(tailRows, :);
        end
        bulkMatrix = zeros(config.stateCount);
        tailMatrix = zeros(config.stateCount);
        for ii = 1:config.stateCount
            for jj = ii + 1:config.stateCount
                bulkMatrix(ii, jj) = step03S_energy_distance_h2( ...
                    bulkSamples{ii}, bulkSamples{jj}, config.energyBlockSize);
                tailMatrix(ii, jj) = step03S_energy_distance_h2( ...
                    tailSamples{ii}, tailSamples{jj}, config.energyBlockSize);
                bulkMatrix(jj, ii) = bulkMatrix(ii, jj);
                tailMatrix(jj, ii) = tailMatrix(ii, jj);
            end
        end
        save(cp, 'bulkMatrix', 'tailMatrix', 'sampleIndex', '-v7.3');
    end
    bulkAll(:, :, repeatId) = bulkMatrix;
    tailAll(:, :, repeatId) = tailMatrix;
end
bulkMedian = median(bulkAll, 3);
tailMedian = median(tailAll, 3);
uncertaintyRecords = cell(0, 1);
for ii = 1:config.stateCount
    for jj = 1:config.stateCount
        for kind = ["bulk", "tail95"]
            if kind == "bulk"
                values = reshape(bulkAll(ii, jj, :), [], 1);
                sampleCount = config.energySampleSize;
            else
                values = reshape(tailAll(ii, jj, :), [], 1);
                sampleCount = config.tail95Count;
            end
            uncertaintyRecords{end + 1, 1} = struct( ...
                'distribution_scope', kind, 'state_i', ii, 'state_j', jj, ...
                'repeat_count', config.energyRepeats, ...
                'sample_count_per_state', sampleCount, ...
                'median_energy_distance', median(values), ...
                'minimum_energy_distance', min(values), ...
                'maximum_energy_distance', max(values), ...
                'IQR_energy_distance', pct(values, 0.75) - pct(values, 0.25), ...
                'seed_rule', "20260300 + repeat*100 + state"); %#ok<AGROW>
        end
    end
end
uncertaintyTbl = records_to_table(uncertaintyRecords);
firstCp = load(fullfile(checkpointDir, 'energy_repeat_01.mat'), ...
    'sampleIndex', 'bulkMatrix', 'tailMatrix');
[bulkCheck, tailCheck] = recompute_energy_repeat(Z, tail95, ...
    firstCp.sampleIndex, config);
reproError = max([abs(bulkCheck - firstCp.bulkMatrix), ...
    abs(tailCheck - firstCp.tailMatrix)], [], 'all');
end

function [bulkMatrix, tailMatrix] = recompute_energy_repeat( ...
        Z, tail95, sampleIndex, config)
bulkSamples = cell(config.stateCount, 1);
tailSamples = cell(config.stateCount, 1);
for stateId = 1:config.stateCount
    rows = (stateId - 1) * config.rowsPerState + (1:config.rowsPerState);
    bulkSamples{stateId} = Z(rows(sampleIndex{stateId}), :);
    tailSamples{stateId} = Z(rows(tail95(rows)), :);
end
bulkMatrix = zeros(config.stateCount);
tailMatrix = zeros(config.stateCount);
for ii = 1:config.stateCount
    for jj = ii + 1:config.stateCount
        bulkMatrix(ii, jj) = step03S_energy_distance_h2( ...
            bulkSamples{ii}, bulkSamples{jj}, config.energyBlockSize);
        tailMatrix(ii, jj) = step03S_energy_distance_h2( ...
            tailSamples{ii}, tailSamples{jj}, config.energyBlockSize);
        bulkMatrix(jj, ii) = bulkMatrix(ii, jj);
        tailMatrix(jj, ii) = tailMatrix(ii, jj);
    end
end
end

function [selectedTbl, lines] = select_depth_states( ...
        summaryTbl, tailTbl, bulk, tail, config)
ruleRecords = cell(0, 1);
    function add_rule(stateId, rule, detail)
        ruleRecords{end + 1, 1} = struct('initial_state_id', stateId, ...
            'selection_rule', rule, 'selection_detail', detail);
    end
add_rule(7, "BASE_STATE_7", "Step-03R retained simple reference");
add_rule(18, "BASE_STATE_18", "Step-03R retained medium reference");
add_rule(30, "BASE_STATE_30", "Step-03R retained complex reference");
meanBulk = (sum(bulk, 2) - diag(bulk)) ./ (config.stateCount - 1);
[~, outlier] = max(meanBulk);
add_rule(outlier, "BULK_OUTLIER", ...
    "largest mean bulk energy distance=" + string(meanBulk(outlier)));
[~, idx] = max(summaryTbl.q995_loss_T50);
add_rule(summaryTbl.initial_state_id(idx), "Q995_LOSS_MAX", ...
    "highest q99.5 fixed-50%-capacity loss");
[~, idx] = max(summaryTbl.cvar995_loss_T50);
add_rule(summaryTbl.initial_state_id(idx), "CVAR995_LOSS_MAX", ...
    "highest CVaR99.5 fixed-50%-capacity loss");
[~, idx] = max(summaryTbl.q995_unreachable_D);
add_rule(summaryTbl.initial_state_id(idx), "Q995_UNREACHABLE_D_MAX", ...
    "highest q99.5 unreachable demand");

upper = triu(true(config.stateCount), 1);
bulkValues = bulk(upper);
bulkCut = pct(bulkValues, 0.25);
candidate = upper & bulk <= bulkCut;
score = tail;
score(~candidate) = -Inf;
[~, linear] = max(score, [], 'all', 'linear');
[bulkCloseI, bulkCloseJ] = ind2sub(size(score), linear);
add_rule(bulkCloseI, "BULK_CLOSE_TAIL_FAR", ...
    "pair=" + bulkCloseI + "-" + bulkCloseJ + ...
    ", bulk=" + bulk(bulkCloseI, bulkCloseJ) + ...
    ", tail95=" + tail(bulkCloseI, bulkCloseJ));
add_rule(bulkCloseJ, "BULK_CLOSE_TAIL_FAR", ...
    "pair=" + bulkCloseI + "-" + bulkCloseJ + ...
    ", bulk=" + bulk(bulkCloseI, bulkCloseJ) + ...
    ", tail95=" + tail(bulkCloseI, bulkCloseJ));

baseStates = unique([7; 18; 30; outlier; bulkCloseI; bulkCloseJ]);
modeRows = tailTbl(tailTbl.tail_level == "q99.5" & ...
    (tailTbl.record_type == "affected_site" | ...
    tailTbl.record_type == "affected_node"), :);
spatialScore = zeros(config.stateCount, 1);
for stateId = 1:config.stateCount
    stateMode = summaryTbl(summaryTbl.initial_state_id == stateId, :);
    sameMode = summaryTbl.q995_affected_site_mode == ...
        stateMode.q995_affected_site_mode & ...
        summaryTbl.q995_affected_node_mode == stateMode.q995_affected_node_mode;
    rarity = 1 / sum(sameMode);
    spatialScore(stateId) = rarity * min(bulk(stateId, baseStates));
end
spatialScore(baseStates) = -Inf;
[~, spatialState] = max(spatialScore);
if ~isfinite(spatialScore(spatialState))
    [~, spatialState] = max(meanBulk);
end
spatialMode = summaryTbl(summaryTbl.initial_state_id == spatialState, :);
add_rule(spatialState, "SPATIAL_TAIL_MODE", ...
    "distinct q99.5 affected site/node mode=" + ...
    spatialMode.q995_affected_site_mode + "/" + ...
    spatialMode.q995_affected_node_mode + ...
    "; audited tail rows=" + height(modeRows));

ruleTbl = records_to_table(ruleRecords);
selectedStates = unique(ruleTbl.initial_state_id, 'stable');
records = cell(numel(selectedStates), 1);
for ii = 1:numel(selectedStates)
    stateId = selectedStates(ii);
    subset = ruleTbl(ruleTbl.initial_state_id == stateId, :);
    records{ii} = struct('initial_state_id', stateId, ...
        'selection_rule_count', height(subset), ...
        'selection_rules', join(subset.selection_rule, ";"), ...
        'selection_details', join(subset.selection_detail, " | "), ...
        'mean_bulk_energy_distance', meanBulk(stateId), ...
        'q995_loss_T50', summaryTbl.q995_loss_T50( ...
            summaryTbl.initial_state_id == stateId), ...
        'cvar995_loss_T50', summaryTbl.cvar995_loss_T50( ...
            summaryTbl.initial_state_id == stateId), ...
        'q995_unreachable_D', summaryTbl.q995_unreachable_D( ...
            summaryTbl.initial_state_id == stateId), ...
        'q995_affected_site_mode', summaryTbl.q995_affected_site_mode( ...
            summaryTbl.initial_state_id == stateId), ...
        'q995_affected_node_mode', summaryTbl.q995_affected_node_mode( ...
            summaryTbl.initial_state_id == stateId));
end
selectedTbl = records_to_table(records);
lines = ["# Step-03S State Selection Rationale"; ""; ...
    "Selection uses nominal-only risk-decision features and fixed seeds. States 7, 18, and 30 are retained before applying every additional rule."; ""; ...
    "Selected state count: " + height(selectedTbl) + ". The preferred cap is eight; any excess is retained because mandatory rules identify distinct states and are not silently dropped."; ""];
for rr = 1:height(selectedTbl)
    lines(end + 1) = "- state " + selectedTbl.initial_state_id(rr) + ...
        ": " + selectedTbl.selection_rules(rr) + ". " + ...
        selectedTbl.selection_details(rr); %#ok<AGROW>
end
lines = [lines; ""; "The bulk-close/tail-far pair is chosen among the lowest bulk-energy quartile using the largest tail95 energy distance. Spatial selection uses the q99.5 affected-site/node mode and nominal bulk separation; no validation data are read."];
end

function [neighborTbl, crossTbl, falseTbl, diagnosticLines, audit] = ...
        run_tail_depth_audit(matPath, featureData, selectedTbl, Cap, M, ...
        checkpointDir, config)
m = matfile(matPath);
neighborRecords = cell(0, 1);
crossRecords = cell(0, 1);
allSingleOptimal = true;
minimumObjectiveRegret = Inf;
minimumLossRegret = Inf;
zeroDistanceMaxRegret = 0;
for row = 1:height(selectedTbl)
    stateId = selectedTbl.initial_state_id(row);
    cp = fullfile(checkpointDir, sprintf('depth_state_%02d.mat', stateId));
    useCheckpoint = false;
    if isfile(cp)
        loaded = load(cp, 'stateDepth');
        stateDepth = loaded.stateDepth;
        useCheckpoint = isfield(stateDepth, 'checkpoint_version') && ...
            stateDepth.checkpoint_version == 2;
    end
    if useCheckpoint
        fprintf('Step-03S state %d depth checkpoint loaded.\n', stateId);
    else
        fprintf('\nStep-03S state %d: exact tail-neighbor and cross-regret audit.\n', ...
            stateId);
        rows = (stateId - 1) * config.rowsPerState + ...
            (1:config.rowsPerState);
        D = double(m.D_node_kg(rows, :));
        A = double(m.A_site_node(rows, :, :));
        C = double(m.C_site_node_km(rows, :, :));
        pathId = double(m.path_id(rows, 1));
        stateFeatureRows = rows;
        loss50 = featureData.Z(stateFeatureRows, 14);
        tail95 = featureData.tail95(stateFeatureRows);
        tail99 = featureData.tail99(stateFeatureRows);
        tail995 = featureData.tail995(stateFeatureRows);
        neighborCp = fullfile(checkpointDir, ...
            sprintf('neighbors_state_%02d.mat', stateId));
        if isfile(neighborCp)
            loadedNeighbor = load(neighborCp, 'neighbor', 'Dscale');
            neighbor = loadedNeighbor.neighbor;
            Dscale = loadedNeighbor.Dscale;
        else
            Dscale = exact_l1_diameter(D, config.distanceTargetBlockSize);
            spatialSignature = build_spatial_signature(D, A);
            neighbor = find_tail_neighbors(stateId, D, A, C, pathId, ...
                loss50, tail95, tail99, tail995, spatialSignature, ...
                Dscale, config);
            save(neighborCp, 'neighbor', 'Dscale', '-v7.3');
        end
        pairIndex = unique([neighbor.scenario_r, neighbor.scenario_s], ...
            'rows', 'stable');
        requiredScenarios = unique(pairIndex(:));
        atom = solve_required_atoms(D, A, C, requiredScenarios, ...
            Cap, M, config);
        if ~atom.all_optimal
            error('Step-03S state %d required atom solve failed.', stateId);
        end
        cross = build_cross_regret(stateId, D, A, C, pathId, ...
            loss50, tail95, tail99, tail995, neighbor, pairIndex, ...
            requiredScenarios, atom, Cap, M, Dscale, config);
        stateDepth = struct('checkpoint_version', 2, ...
            'neighbor', neighbor, 'cross', cross, ...
            'all_single_optimal', atom.all_optimal, ...
            'minimum_objective_regret', min([cross.regret_obj_r_to_s; ...
                cross.regret_obj_s_to_r]), ...
            'minimum_loss_regret', min([cross.regret_loss_r_to_s; ...
                cross.regret_loss_s_to_r]), ...
            'zero_distance_max_regret', zero_distance_regret(cross, config), ...
            'required_scenario_count', numel(requiredScenarios), ...
            'D_scale', Dscale);
        save(cp, 'stateDepth', '-v7.3');
    end
    neighborStateRecords = table_to_records(stateDepth.neighbor);
    crossStateRecords = table_to_records(stateDepth.cross);
    neighborRecords = [neighborRecords; neighborStateRecords]; %#ok<AGROW>
    crossRecords = [crossRecords; crossStateRecords]; %#ok<AGROW>
    allSingleOptimal = allSingleOptimal && stateDepth.all_single_optimal;
    minimumObjectiveRegret = min(minimumObjectiveRegret, ...
        stateDepth.minimum_objective_regret);
    minimumLossRegret = min(minimumLossRegret, stateDepth.minimum_loss_regret);
    zeroDistanceMaxRegret = max(zeroDistanceMaxRegret, ...
        stateDepth.zero_distance_max_regret);
end
neighborTbl = records_to_table(neighborRecords);
crossTbl = records_to_table(crossRecords);
[falseTbl, diagnosticLines] = classify_false_near(crossTbl, config);
requiredMask = falseTbl.tier_1 | falseTbl.top20_severity;
audit = struct('all_single_optimal', allSingleOptimal, ...
    'minimum_objective_regret', minimumObjectiveRegret, ...
    'minimum_loss_regret', minimumLossRegret, ...
    'zero_distance_max_regret', zeroDistanceMaxRegret, ...
    'all_required_pairs_diagnosed', all(strlength( ...
        falseTbl.diagnostic_classification(requiredMask)) > 0), ...
    'diagnosed_pair_count', sum(requiredMask), ...
    'tier0_count', sum(crossTbl.tier_0), ...
    'tier1_count', sum(crossTbl.tier_1), ...
    'tier2_count', sum(crossTbl.tier_2), ...
    'tier3_count', sum(crossTbl.tier_3), ...
    'selected_state_count', height(selectedTbl));
end

function Dscale = exact_l1_diameter(D, blockSize)
uniqueD = unique(D, 'rows');
Dscale = 0;
for iStart = 1:blockSize:size(uniqueD, 1)
    iIdx = iStart:min(size(uniqueD, 1), iStart + blockSize - 1);
    Xi = reshape(uniqueD(iIdx, :), [numel(iIdx), 1, size(D, 2)]);
    for jStart = iStart:blockSize:size(uniqueD, 1)
        jIdx = jStart:min(size(uniqueD, 1), jStart + blockSize - 1);
        Xj = reshape(uniqueD(jIdx, :), [1, numel(jIdx), size(D, 2)]);
        block = sum(abs(Xi - Xj), 3);
        Dscale = max(Dscale, max(block, [], 'all'));
    end
end
end

function signature = build_spatial_signature(D, A)
R = size(D, 1);
allUnreachable = reshape(all(A <= 0.5, 2), R, size(D, 2));
[~, nodeMode] = max(D .* allUnreachable, [], 2);
siteUnavailable = zeros(R, 4);
for ii = 1:4
    Ai = reshape(A(:, ii, :), R, size(D, 2));
    siteUnavailable(:, ii) = sum((Ai <= 0.5) .* D, 2);
end
[~, siteMode] = max(siteUnavailable, [], 2);
signature = [siteMode, nodeMode];
end

function tbl = find_tail_neighbors(stateId, D, A, C, pathId, loss50, ...
        tail95, tail99, tail995, spatialSignature, Dscale, config)
query = find(tail95);
nq = numel(query);
categories = ["all", "non_tail", "tail", "loss_similar_spatial"];
bestDistance = cell(numel(categories), 1);
bestIndex = cell(numel(categories), 1);
for cc = 1:numel(categories)
    bestDistance{cc} = inf(nq, config.nearestCount);
    bestIndex{cc} = zeros(nq, config.nearestCount);
end
lossScale = max(max(loss50) - min(loss50), 1);
for qStart = 1:config.distanceQueryBlockSize:nq
    qPos = qStart:min(nq, qStart + config.distanceQueryBlockSize - 1);
    qIdx = query(qPos);
    localBestDistance = cellfun(@(x) x(qPos, :), bestDistance, ...
        'UniformOutput', false);
    localBestIndex = cellfun(@(x) x(qPos, :), bestIndex, ...
        'UniformOutput', false);
    for tStart = 1:config.distanceTargetBlockSize:size(D, 1)
        tIdx = tStart:min(size(D, 1), ...
            tStart + config.distanceTargetBlockSize - 1);
        [distanceBlock, ~, ~] = step03S_distance_block_h2( ...
            D(qIdx, :), A(qIdx, :, :), C(qIdx, :, :), ...
            D(tIdx, :), A(tIdx, :, :), C(tIdx, :, :), ...
            Dscale, config);
        qColumn = qIdx(:);
        targetRow = tIdx(:).';
        selfMask = qColumn == targetRow;
        distanceBlock(selfMask) = Inf;
        categoryMask = cell(numel(categories), 1);
        categoryMask{1} = true(size(distanceBlock));
        categoryMask{2} = repmat((~tail95(tIdx)).', numel(qIdx), 1);
        categoryMask{3} = repmat(tail95(tIdx).', numel(qIdx), 1);
        lossClose = abs(loss50(qColumn) - loss50(targetRow).') <= ...
            config.lossSimilarityFraction * lossScale;
        spatialDifferent = spatialSignature(qColumn, 1) ~= ...
            spatialSignature(targetRow, 1).' | ...
            spatialSignature(qColumn, 2) ~= spatialSignature(targetRow, 2).';
        categoryMask{4} = lossClose & spatialDifferent;
        for cc = 1:numel(categories)
            candidate = distanceBlock;
            candidate(~categoryMask{cc}) = Inf;
            [localBestDistance{cc}, localBestIndex{cc}] = merge_top_k( ...
                localBestDistance{cc}, localBestIndex{cc}, ...
                candidate, tIdx, config.nearestCount);
        end
    end
    for cc = 1:numel(categories)
        bestDistance{cc}(qPos, :) = localBestDistance{cc};
        bestIndex{cc}(qPos, :) = localBestIndex{cc};
    end
    fprintf('  state %d neighbor queries %d/%d complete.\n', ...
        stateId, qPos(end), nq);
end
records = cell(0, 1);
for cc = 1:numel(categories)
    for qq = 1:nq
        r = query(qq);
        valid = isfinite(bestDistance{cc}(qq, :)) & ...
            bestIndex{cc}(qq, :) > 0;
        for rank = find(valid)
            s = bestIndex{cc}(qq, rank);
            [dNew, dD, dC, detail] = step03S_distance_block_h2( ...
                D(r, :), A(r, :, :), C(r, :, :), ...
                D(s, :), A(s, :, :), C(s, :, :), Dscale, config);
            records{end + 1, 1} = struct('initial_state_id', stateId, ...
                'neighbor_category', categories(cc), ...
                'neighbor_rank', rank, 'scenario_r', r, ...
                'path_id_r', pathId(r), 'scenario_s', s, ...
                'path_id_s', pathId(s), 'r_tail95', tail95(r), ...
                'r_tail99', tail99(r), 'r_tail995', tail995(r), ...
                's_tail95', tail95(s), 's_tail99', tail99(s), ...
                's_tail995', tail995(s), 'loss_T50_r', loss50(r), ...
                'loss_T50_s', loss50(s), 'd_D', dD, ...
                'd_Ctilde', dC, 'd_new', dNew, ...
                'max_local_Ctilde', detail.max_local_Ctilde, ...
                'changed_local_count', detail.changed_local_count, ...
                'D_scale', Dscale); %#ok<AGROW>
        end
    end
end
tbl = records_to_table(records);
end

function [bestD, bestI] = merge_top_k(bestD, bestI, blockD, targetIdx, k)
candidateD = [bestD, blockD];
candidateI = [bestI, repmat(targetIdx, size(blockD, 1), 1)];
[sortedD, order] = sort(candidateD, 2, 'ascend');
order = order(:, 1:k);
bestD = sortedD(:, 1:k);
row = repmat((1:size(candidateI, 1)).', 1, k);
bestI = candidateI(sub2ind(size(candidateI), row, order));
end

function atom = solve_required_atoms(D, A, C, indices, Cap, M, config)
n = numel(indices);
T = NaN(n, 4);
objStar = NaN(n, 1);
representativeObj = NaN(n, 1);
rangeWidth = NaN(n, 4);
allOptimal = true;
for start = 1:config.variableLossChunkSize:n
    pos = start:min(n, start + config.variableLossChunkSize - 1);
    idx = indices(pos);
    single = solve_step03R_single_scenario_batch_h2( ...
        D(idx, :), A(idx, :, :), C(idx, :, :), Cap, M, config);
    ranges = solve_step03R_single_scenario_ranges_h2( ...
        D(idx, :), A(idx, :, :), C(idx, :, :), Cap, M, ...
        single.obj_star, config);
    allOptimal = allOptimal && single.exitflag == 1 && ranges.exitflag == 1;
    if ~allOptimal
        break;
    end
    T(pos, :) = single.T;
    objStar(pos) = single.obj_star;
    representativeObj(pos) = single.primary_objective_at_representative;
    rangeWidth(pos, :) = ranges.range_width;
end
atom = struct('indices', indices, 'T', T, 'obj_star', objStar, ...
    'representative_objective', representativeObj, ...
    'range_width', rangeWidth, 'all_optimal', allOptimal);
end

function tbl = build_cross_regret(stateId, D, A, C, pathId, loss50, ...
        tail95, tail99, tail995, neighbor, pairIndex, requiredScenarios, ...
        atom, Cap, M, Dscale, config)
scenarioPosition = zeros(size(D, 1), 1);
scenarioPosition(requiredScenarios) = 1:numel(requiredScenarios);
nPairs = size(pairIndex, 1);
r = pairIndex(:, 1);
s = pairIndex(:, 2);
rPos = scenarioPosition(r);
sPos = scenarioPosition(s);
if any(rPos == 0 | sPos == 0)
    error('Step-03S cross-regret atom mapping is incomplete.');
end
crossLossRtoS = variable_loss_in_chunks(D(s, :), A(s, :, :), ...
    C(s, :, :), atom.T(rPos, :), M, config);
crossLossStoR = variable_loss_in_chunks(D(r, :), A(r, :, :), ...
    C(r, :, :), atom.T(sPos, :), M, config);
ownLossR = atom.representative_objective(rPos) - ...
    config.gamma .* sum(atom.T(rPos, :), 2);
ownLossS = atom.representative_objective(sPos) - ...
    config.gamma .* sum(atom.T(sPos, :), 2);
crossObjRtoS = config.gamma .* sum(atom.T(rPos, :), 2) + crossLossRtoS;
crossObjStoR = config.gamma .* sum(atom.T(sPos, :), 2) + crossLossStoR;
regretObjRtoS = crossObjRtoS - atom.representative_objective(sPos);
regretObjStoR = crossObjStoR - atom.representative_objective(rPos);
regretLossRtoS = crossLossRtoS - ownLossS;
regretLossStoR = crossLossStoR - ownLossR;
relativeRtoS = regretObjRtoS ./ ...
    max(abs(atom.representative_objective(sPos)), 1e-8);
relativeStoR = regretObjStoR ./ ...
    max(abs(atom.representative_objective(rPos)), 1e-8);

records = cell(nPairs, 1);
for pp = 1:nPairs
    pairRows = neighbor(neighbor.scenario_r == r(pp) & ...
        neighbor.scenario_s == s(pp), :);
    categories = join(unique(pairRows.neighbor_category), ";");
    allRanks = pairRows.neighbor_rank(pairRows.neighbor_category == "all");
    if isempty(allRanks)
        allRank = NaN;
        nearestAll = false;
    else
        allRank = min(allRanks);
        nearestAll = allRank <= config.nearestCount;
    end
    [dNew, dD, dC, detail] = step03S_distance_block_h2( ...
        D(r(pp), :), A(r(pp), :, :), C(r(pp), :, :), ...
        D(s(pp), :), A(s(pp), :, :), C(s(pp), :, :), Dscale, config);
    Ddiff = abs(D(r(pp), :) - D(s(pp), :));
    [maxNodeDdiff, maxNode] = max(Ddiff);
    Ar = reshape(A(r(pp), :, :), 4, 33);
    As = reshape(A(s(pp), :, :), 4, 33);
    Cr = reshape(C(r(pp), :, :), 4, 33);
    Cs = reshape(C(s(pp), :, :), 4, 33);
    common = Ar > 0.5 & As > 0.5;
    Ccommon = abs(Cr - Cs);
    Ccommon(~common | ~isfinite(Ccommon)) = 0;
    Tdiff = abs(atom.T(rPos(pp), :) - atom.T(sPos(pp), :));
    [maxSiteTdiff, maxSite] = max(Tdiff);
    dT = mean(Tdiff ./ Cap.');
    tier0 = dNew <= config.zeroDistanceTolerance && ...
        max(regretObjRtoS(pp), regretObjStoR(pp)) > config.regretTolerance;
    tier1 = nearestAll && relativeRtoS(pp) >= config.tierRelative10 && ...
        relativeStoR(pp) >= config.tierRelative10;
    tier2 = nearestAll && max(relativeRtoS(pp), relativeStoR(pp)) >= ...
        config.tierRelative10;
    tier3 = nearestAll && relativeRtoS(pp) >= config.tierRelative5 && ...
        relativeStoR(pp) >= config.tierRelative5;
    pairType = classify_pair_type(tail95(r(pp)), tail95(s(pp)), ...
        loss50(r(pp)), loss50(s(pp)), dT);
    localMeanChanged = dC * 132 / ...
        max(detail.changed_local_count, 1);
    dilutionRatio = detail.max_local_Ctilde / max(localMeanChanged, eps);
    records{pp} = struct('initial_state_id', stateId, ...
        'scenario_r', r(pp), 'path_id_r', pathId(r(pp)), ...
        'scenario_s', s(pp), 'path_id_s', pathId(s(pp)), ...
        'neighbor_categories', categories, 'nearest_all_rank', allRank, ...
        'pair_type', pairType, 'r_tail95', tail95(r(pp)), ...
        'r_tail99', tail99(r(pp)), 'r_tail995', tail995(r(pp)), ...
        's_tail95', tail95(s(pp)), 's_tail99', tail99(s(pp)), ...
        's_tail995', tail995(s(pp)), 'loss_T50_r', loss50(r(pp)), ...
        'loss_T50_s', loss50(s(pp)), 'd_D', dD, ...
        'd_Ctilde', dC, 'd_new', dNew, ...
        'D_l1_difference_kg', sum(Ddiff), ...
        'max_D_difference_node_id', maxNode, ...
        'max_D_difference_kg', maxNodeDdiff, ...
        'A_reachability_change_count', sum(Ar ~= As, 'all'), ...
        'C_common_reachable_l1_km', sum(Ccommon, 'all'), ...
        'changed_local_count', detail.changed_local_count, ...
        'max_local_Ctilde', detail.max_local_Ctilde, ...
        'local_dilution_ratio', dilutionRatio, ...
        'T_r1', atom.T(rPos(pp), 1), 'T_r2', atom.T(rPos(pp), 2), ...
        'T_r3', atom.T(rPos(pp), 3), 'T_r4', atom.T(rPos(pp), 4), ...
        'T_s1', atom.T(sPos(pp), 1), 'T_s2', atom.T(sPos(pp), 2), ...
        'T_s3', atom.T(sPos(pp), 3), 'T_s4', atom.T(sPos(pp), 4), ...
        'd_T_normalized', dT, 'T_L1_difference_kg', sum(Tdiff), ...
        'max_single_site_T_difference_kg', maxSiteTdiff, ...
        'max_difference_site_id', maxSite, ...
        'optimal_objective_r', atom.obj_star(rPos(pp)), ...
        'optimal_objective_s', atom.obj_star(sPos(pp)), ...
        'own_operating_loss_r', ownLossR(pp), ...
        'own_operating_loss_s', ownLossS(pp), ...
        'cross_objective_r_to_s', crossObjRtoS(pp), ...
        'cross_objective_s_to_r', crossObjStoR(pp), ...
        'regret_obj_r_to_s', regretObjRtoS(pp), ...
        'regret_obj_s_to_r', regretObjStoR(pp), ...
        'regret_loss_r_to_s', regretLossRtoS(pp), ...
        'regret_loss_s_to_r', regretLossStoR(pp), ...
        'relative_regret_obj_r_to_s', relativeRtoS(pp), ...
        'relative_regret_obj_s_to_r', relativeStoR(pp), ...
        'multiple_optimum_r', any(atom.range_width(rPos(pp), :) > ...
            config.multipleOptimumWidth), ...
        'multiple_optimum_s', any(atom.range_width(sPos(pp), :) > ...
            config.multipleOptimumWidth), ...
        'capacity_saturated_r', any(atom.T(rPos(pp), :) >= Cap.' - 1e-7), ...
        'capacity_saturated_s', any(atom.T(sPos(pp), :) >= Cap.' - 1e-7), ...
        'tier_0', tier0, 'tier_1', tier1, 'tier_2', tier2, ...
        'tier_3', tier3, 'historical_step03R_false_near', false); 
end
tbl = records_to_table(records);
dCut = pct(tbl.d_new, config.historicalNearFraction);
dTCut = pct(tbl.d_T_normalized, 1 - config.historicalHighFraction);
lossDiff = abs(tbl.loss_T50_r - tbl.loss_T50_s);
lossCut = pct(lossDiff, 1 - config.historicalHighFraction);
tbl.historical_step03R_false_near = tbl.d_new <= dCut & ...
    (tbl.d_T_normalized >= dTCut | lossDiff >= lossCut);
end

function losses = variable_loss_in_chunks(D, A, C, Trows, M, config)
losses = NaN(size(D, 1), 1);
for start = 1:config.variableLossChunkSize:size(D, 1)
    pos = start:min(size(D, 1), start + config.variableLossChunkSize - 1);
    ev = evaluate_step03S_variable_T_losses_h2( ...
        D(pos, :), A(pos, :, :), C(pos, :, :), Trows(pos, :), M, config);
    if ev.exitflag ~= 1
        error('Step-03S variable-T fixed-loss evaluation failed.');
    end
    losses(pos) = ev.loss;
end
end

function value = zero_distance_regret(tbl, config)
mask = tbl.d_new <= config.zeroDistanceTolerance;
if any(mask)
    value = max([tbl.regret_obj_r_to_s(mask); tbl.regret_obj_s_to_r(mask)]);
else
    value = 0;
end
end

function label = classify_pair_type(rTail, sTail, rLoss, sLoss, dT)
if xor(rTail, sTail)
    label = "NONTAIL_TAIL";
elseif rTail && sTail
    label = "TAIL_TAIL";
elseif abs(rLoss - sLoss) <= 0.01 * max(max(abs([rLoss, sLoss])), 1) && ...
        dT >= 0.25
    label = "SIMILAR_LOSS_DIFFERENT_LAYOUT";
else
    label = "OTHER_NEIGHBOR";
end
end

function [falseTbl, lines] = classify_false_near(crossTbl, config)
severity = min(crossTbl.relative_regret_obj_r_to_s, ...
    crossTbl.relative_regret_obj_s_to_r) ./ max(crossTbl.d_new, 1e-9);
[~, order] = sortrows([-severity, crossTbl.initial_state_id, ...
    crossTbl.scenario_r, crossTbl.scenario_s], [1, 2, 3, 4]);
topCount = min(20, height(crossTbl));
topMask = false(height(crossTbl), 1);
topMask(order(1:topCount)) = true;
keep = crossTbl.tier_1 | topMask;
falseTbl = crossTbl(keep, :);
falseTbl.severity_score = severity(keep);
falseTbl.top20_severity = topMask(keep);
falseTbl.diagnostic_classification = strings(height(falseTbl), 1);
falseTbl.local_average_dilution_flag = false(height(falseTbl), 1);
falseTbl.actual_substitutability = strings(height(falseTbl), 1);
for rr = 1:height(falseTbl)
    bothHigh = falseTbl.relative_regret_obj_r_to_s(rr) >= ...
        config.tierRelative10 && ...
        falseTbl.relative_regret_obj_s_to_r(rr) >= config.tierRelative10;
    oneHigh = max(falseTbl.relative_regret_obj_r_to_s(rr), ...
        falseTbl.relative_regret_obj_s_to_r(rr)) >= config.tierRelative10;
    bothSmall = max(falseTbl.relative_regret_obj_r_to_s(rr), ...
        falseTbl.relative_regret_obj_s_to_r(rr)) < config.tierRelative5;
    dilution = falseTbl.local_dilution_ratio(rr) >= 5 && ...
        falseTbl.changed_local_count(rr) <= 10;
    falseTbl.local_average_dilution_flag(rr) = dilution;
    if falseTbl.tier_0(rr)
        classification = "ZERO_DISTANCE_POSITIVE_REGRET_ERROR";
    elseif bothHigh
        classification = "TRUE_BIDIRECTIONAL_FALSE_NEAR";
    elseif oneHigh
        classification = "ONE_WAY_DOMINANCE_OR_CONTAINMENT";
    elseif bothSmall && falseTbl.d_T_normalized(rr) >= 0.25
        classification = "LARGE_T_SWITCH_BUT_SUBSTITUTABLE";
    elseif dilution
        classification = "LOCAL_CHANGE_DILUTED_BUT_REGRET_LIMITED";
    else
        classification = "NEAR_PAIR_WITH_LIMITED_REGRET";
    end
    falseTbl.diagnostic_classification(rr) = classification;
    if bothHigh
        falseTbl.actual_substitutability(rr) = "NOT_SUBSTITUTABLE";
    elseif oneHigh
        falseTbl.actual_substitutability(rr) = "ASYMMETRIC_SUBSTITUTION";
    else
        falseTbl.actual_substitutability(rr) = "PRACTICALLY_SUBSTITUTABLE";
    end
end
lines = ["## Fixed criteria"; ""; ...
    "Tier-0: d_new=0 and either objective regret exceeds 1e-8."; ...
    "Tier-1: nearest-10 and both relative objective regrets are at least 10%."; ...
    "Tier-2: nearest-10 and at least one relative objective regret is at least 10%."; ...
    "Tier-3: nearest-10 and both relative objective regrets are at least 5%."; ...
    "The historical Step-03R lowest-1% distance and highest-1% decision/loss rule is retained separately."; ""; ...
    "## Required pair diagnostics"; ""];
for rr = 1:height(falseTbl)
    lines(end + 1) = "- state " + falseTbl.initial_state_id(rr) + ...
        ", pair (" + falseTbl.scenario_r(rr) + "," + ...
        falseTbl.scenario_s(rr) + "), type=" + falseTbl.pair_type(rr) + ...
        ", d_D/d_Ctilde/d_new=" + sprintf('%.6g/%.6g/%.6g', ...
        falseTbl.d_D(rr), falseTbl.d_Ctilde(rr), falseTbl.d_new(rr)) + ...
        ", relative regret r->s/s->r=" + sprintf('%.6g/%.6g', ...
        falseTbl.relative_regret_obj_r_to_s(rr), ...
        falseTbl.relative_regret_obj_s_to_r(rr)) + ...
        ", max D-change node=" + falseTbl.max_D_difference_node_id(rr) + ...
        ", A changes=" + falseTbl.A_reachability_change_count(rr) + ...
        ", classification=" + ...
        falseTbl.diagnostic_classification(rr) + "."; %#ok<AGROW>
end
lines = [lines; ""; ...
    "Every row is an equal-mass empirical nominal record. No explicit path/scenario probability exists in Step-03J, so tail rank is not relabeled as a low-probability event."; ...
    "Large T-vector differences with small bidirectional regret are treated as optimizer switching with practical substitutability. One-way high regret is reported as containment/dominance. Only bidirectional high regret is a true decision false-near candidate."];
end

function decision = choose_decision(crossTbl, audit)
if audit.tier0_count > 0
    decision = "D. CTILDE_DISTANCE_REDESIGN_REQUIRED";
elseif audit.tier1_count == 0
    decision = "A. CTILDE_DISTRIBUTION_AND_TAIL_FIT_VALIDATED";
else
    tierStates = numel(unique(crossTbl.initial_state_id(crossTbl.tier_1)));
    if audit.tier1_count <= 3 && tierStates <= 2
        decision = "B. CTILDE_VALID_WITH_ISOLATED_TAIL_FALSE_NEAR";
    else
        tierRows = crossTbl(crossTbl.tier_1, :);
        dilutedShare = mean(tierRows.local_dilution_ratio >= 5 & ...
            tierRows.changed_local_count <= 10);
        if dilutedShare >= 0.5
            decision = "C. CTILDE_REWEIGHTING_REQUIRED";
        else
            decision = "D. CTILDE_DISTANCE_REDESIGN_REQUIRED";
        end
    end
end
end

function tbl = matrix_table(matrix, label)
names = "state_" + string(1:size(matrix, 2));
tbl = array2table(matrix, 'VariableNames', cellstr(names));
tbl = addvars(tbl, (1:size(matrix, 1)).', ...
    'Before', 1, 'NewVariableNames', 'initial_state_id');
tbl = addvars(tbl, repmat(label, size(matrix, 1), 1), ...
    'Before', 1, 'NewVariableNames', 'matrix_type');
end

function record = phase_record(name, elapsed, memoryBytes)
record = struct('phase_name', name, 'elapsed_sec', elapsed, ...
    'memory_bytes', memoryBytes);
end

function value = memory_used_bytes()
try
    user = memory;
    value = double(user.MemUsedMATLAB);
catch
    value = NaN;
end
end

function write_probability_semantics(path, audit)
probabilityFields = audit.explicit_probability_fields;
if ismissing(probabilityFields) || strlength(probabilityFields) == 0
    probabilityFields = "none";
end
lines = ["# Step-03S Probability Semantics"; ""; ...
    "## Code and frozen-data findings"; ""; ...
    "- nominal rows: " + audit.row_count; ...
    "- initial states: " + audit.state_count; ...
    "- rows per state: " + audit.rows_per_state; ...
    "- empirical mass per row: 1/15000"; ...
    "- empirical mass sum per state: 1"; ...
    "- explicit path, transition, or scenario probability fields: " + probabilityFields; ...
    "- DAC MAT fields: " + audit.dac_mat_fields; ...
    "- path_id meaning: record identity, not probability"; ""; ...
    "Step-03J assigns every Monte Carlo record equal conditional empirical mass within its initial state. Identical D/A/C outcomes obtain larger empirical mass only by repeated rows, so an outcome repeated k times has empirical mass k/15000. The DAC sidecar has no row-wise probability vector and no one-to-one path-probability field."; ""; ...
    "Accordingly this audit uses the terms equal-mass empirical sample and empirical high-loss tail. q95, q99, and q99.5 membership is not called a low-probability scenario. Validation-1 and validation-2 are not read for selection, scaling, tuning, or thresholds."];
write_lines(path, lines);
end

function write_feature_definition(path, names, Cap, M, penaltySource, config)
lines = ["# Step-03S Risk-Decision Feature Definition"; ""; ...
    "The 16-dimensional z vector is used only to compare the 35 conditional nominal distributions. It does not replace the formal D+Ctilde ground distance."; ""; ...
    "## Features"; ""; ...
    "1. total_D = sum_n D_n."; ...
    "2. unreachable_D = demand on nodes unreachable from all four sites."; ...
    "3. unreachable_D_ratio = unreachable_D/max(total_D,eps)."; ...
    "4-7. reachable_D_i = sum_n A_i,n D_n for sites 1-4."; ...
    "8-11. demand_weighted_C_i = sum_n A_i,n D_n C_i,n / sum_n A_i,n D_n. The value is defined as zero when the denominator is zero."; ...
    "12-16. unchanged formal recourse loss at fixed T anchors 0%, 25%, 50%, 75%, and 100% of the common full capacity."; ""; ...
    "Feature order: " + join(names, ", ") + "."; ...
    "Capacity vector: [" + join(string(Cap.'), ",") + "] kg."; ...
    "Shortage penalty M: " + M + "; source: " + penaltySource + "."; ...
    "Feature standardization uses only all 525000 nominal rows: (z-global mean)/global standard deviation. Constant features use scale 1 and remain zero after centering."; ""; ...
    "## Formal tail-distance constants"; ""; ...
    "Tail neighbor searches retain d_new=0.6*d_D+0.4*d_Ctilde, kappa=" + config.kappa + ...
    ", and C_bound=" + sprintf('%.16g', config.C_bound) + " km. The fixed 10%, 5%, 1%, and loss-similarity thresholds are declared before results are inspected and are not validation-tuned."];
write_lines(path, lines);
end

function write_summary(path, decision, selectedTbl, summaryTbl, bulk, tail, ...
        crossTbl, audit, elapsed, peakMemory, failCount)
upper = triu(true(size(bulk)), 1);
bulkValues = bulk(upper);
tailValues = tail(upper);
baseStates = [7, 18, 30];
coverageDistance = min(bulk(:, baseStates), [], 2);
coverageCut = pct(bulkValues, 0.75);
uncovered = find(coverageDistance > coverageCut);
if isempty(uncovered)
    uncoveredText = "none";
else
    uncoveredText = join(string(uncovered.'), ",");
end
bulkCloseCut = pct(bulkValues, 0.25);
tailFarCut = pct(tailValues, 0.75);
bulkCloseTailFar = upper & bulk <= bulkCloseCut & tail >= tailFarCut;
meanDdifference = abs(summaryTbl.mean_total_D - summaryTbl.mean_total_D.');
meanDCut = pct(meanDdifference(upper), 0.25);
averageCloseTailFar = upper & meanDdifference <= meanDCut & tail >= tailFarCut;
tier1States = unique(crossTbl.initial_state_id(crossTbl.tier_1));
if isempty(tier1States)
    tier1StateText = "none";
else
    tier1StateText = join(string(tier1States.'), ",");
end
if audit.tier1_count == 0
    nextStep = "rho calibration after formally freezing Ctilde";
elseif startsWith(decision, "B.") || startsWith(decision, "C.")
    nextStep = "document isolated cases or perform local reweighting before rho calibration";
else
    nextStep = "distance redesign before rho calibration";
end
lines = ["Step-03S 35-state distribution and tail cross-regret audit"; ""; ...
    "decision=" + decision; ...
    "nominal_rows=525000; states=35; rows_per_state=15000"; ...
    "selected_states=" + join(string(selectedTbl.initial_state_id.'), ","); ...
    "bulk_energy_range=" + range_text(bulkValues); ...
    "tail95_energy_range=" + range_text(tailValues); ...
    "bulk_close_tail_far_pair_count=" + sum(bulkCloseTailFar, 'all'); ...
    "meanD_close_tail_far_pair_count=" + sum(averageCloseTailFar, 'all'); ...
    "tier0_count=" + audit.tier0_count; ...
    "tier1_count=" + audit.tier1_count; ...
    "tier2_count=" + audit.tier2_count; ...
    "tier3_count=" + audit.tier3_count; ...
    "tier1_states=" + tier1StateText; ...
    "zero_distance_max_regret=" + sprintf('%.16g', audit.zero_distance_max_regret); ...
    "mechanical_FAIL=" + failCount; ...
    "total_elapsed_sec=" + sprintf('%.6f', elapsed); ...
    "peak_memory_bytes=" + sprintf('%.0f', peakMemory); ""; ...
    "Required answers:"; ...
    "1. The 35 conditional distributions are not treated as identical; bulk and tail energy ranges and close-bulk/far-tail pairs quantify the remaining heterogeneity."; ...
    "2. Similarity is reported separately for bulk and tail95; tail similarity is not inferred from mean demand."; ...
    "3. States 7/18/30 cover the major structure only when no state exceeds the bulk q75 coverage distance. Uncovered state IDs: " + uncoveredText + "."; ...
    "4. Additional mandatory selections explicitly cover bulk outliers, fixed-T loss tails, unreachable-demand tails, bulk-close/tail-far pairs, and spatial modes."; ...
    "5. Ctilde nearest layouts are cross-usable when both directional relative regrets remain below 5%; counts are in step03S_tail_cross_regret.csv."; ...
    "6. Non-tail/tail false-near count at Tier-1=" + sum(crossTbl.tier_1 & crossTbl.pair_type == "NONTAIL_TAIL") + "."; ...
    "7. Tail/tail false-near count at Tier-1=" + sum(crossTbl.tier_1 & crossTbl.pair_type == "TAIL_TAIL") + "."; ...
    "8. Similar-loss/different-layout near count=" + sum(crossTbl.pair_type == "SIMILAR_LOSS_DIFFERENT_LAYOUT") + "; bidirectional regret determines whether it is a true conflict."; ...
    "9. Large T differences with small two-way regret are optimizer switching and practical substitutability, not severe distance failure."; ...
    "10. True bidirectional high-regret counterexamples are exactly the Tier-1 rows: " + audit.tier1_count + "."; ...
    "11. Local 132-item dilution is reported by max_local_Ctilde, changed_local_count, and local_dilution_ratio; it is not inferred from T difference alone."; ...
    "12. Ctilde tail-risk suitability follows the decision gate: " + decision + "."; ...
    "13. Formal freeze is supported only by decision A; decision B requires an explicit limitation record, and C/D require further work."; ...
    "14. Recommended next step: " + nextStep + "."; ""; ...
    "No validation tuning, scenario deletion, clustering, probability rewriting, formal R=5000/R=15000 WDRO, MSP, or modification of the formal distance was performed."];
write_lines(path, lines);
end

function write_local_manifest(localDir, checkpointDir, nominalPath, config, ...
        elapsed, peakMemory)
files = dir(fullfile(checkpointDir, '*.mat'));
lines = ["Step-03S local checkpoint manifest"; ...
    "nominal_mat=" + nominalPath; ...
    "nominal_mat_sha256=" + sha256_file(nominalPath); ...
    "checkpoint_count=" + numel(files); ...
    "d_new=0.6*d_D+0.4*d_Ctilde"; ...
    "kappa=" + config.kappa; ...
    "C_bound=" + sprintf('%.16g', config.C_bound); ...
    "elapsed_sec=" + sprintf('%.6f', elapsed); ...
    "peak_memory_bytes=" + sprintf('%.0f', peakMemory)];
for ii = 1:numel(files)
    filePath = fullfile(files(ii).folder, files(ii).name);
    lines(end + 1) = files(ii).name + "|" + files(ii).bytes + ...
        "|" + sha256_file(filePath); %#ok<AGROW>
end
write_lines(fullfile(localDir, 'checkpoint_manifest.txt'), lines);
end

function value = pct(x, probability)
x = sort(double(x(:)));
if isempty(x)
    value = NaN;
    return;
end
position = 1 + (numel(x) - 1) * probability;
lowerIndex = floor(position);
upperIndex = ceil(position);
if lowerIndex == upperIndex
    value = x(lowerIndex);
else
    value = x(lowerIndex) + (position - lowerIndex) * ...
        (x(upperIndex) - x(lowerIndex));
end
end

function value = tail_mean(x, probability)
threshold = pct(x, probability);
tail = x(x >= threshold);
if isempty(tail)
    value = threshold;
else
    value = mean(tail);
end
end

function records = table_to_records(tbl)
records = cell(height(tbl), 1);
for rr = 1:height(tbl)
    item = struct();
    for vv = 1:width(tbl)
        name = tbl.Properties.VariableNames{vv};
        value = tbl.(name)(rr, :);
        if iscell(value)
            value = value{1};
        end
        item.(name) = value;
    end
    records{rr} = item;
end
end

function tbl = records_to_table(records)
if isempty(records)
    tbl = table();
else
    tbl = struct2table(vertcat(records{:}));
end
end

function values = hash_files(files)
values = strings(numel(files), 1);
for ii = 1:numel(files)
    if ~isfile(files(ii))
        values(ii) = "MISSING";
    else
        values(ii) = sha256_file(files(ii));
    end
end
end

function value = directory_hash(path)
if ~isfolder(path)
    value = "MISSING";
    return;
end
files = dir(fullfile(path, '**', '*'));
files = files(~[files.isdir]);
relative = strings(numel(files), 1);
for ii = 1:numel(files)
    relative(ii) = replace(string(fullfile(files(ii).folder, files(ii).name)), ...
        string(path) + filesep, "");
end
[relative, order] = sort(relative);
payload = strings(numel(order), 1);
for ii = 1:numel(order)
    filePath = fullfile(path, relative(ii));
    payload(ii) = relative(ii) + "|" + string(files(order(ii)).bytes) + ...
        "|" + sha256_file(filePath);
end
value = sha256_text(join(payload, newline));
end

function value = sha256_file(path)
stream = java.io.FileInputStream(java.io.File(char(path)));
cleanup = onCleanup(@() stream.close());
value = lower(string(org.apache.commons.codec.digest.DigestUtils.sha256Hex(stream)));
clear cleanup;
end

function value = sha256_text(textValue)
bytes = unicode2native(char(textValue), 'UTF-8');
value = lower(string(org.apache.commons.codec.digest.DigestUtils.sha256Hex(bytes)));
end

function value = pass_fail(condition)
if condition
    value = 'PASS';
else
    value = 'FAIL';
end
end

function text = range_text(x)
text = "[" + sprintf('%.12g', min(x)) + "," + ...
    sprintf('%.12g', max(x)) + "]";
end

function write_lines(path, lines)
fid = fopen(path, 'w');
if fid < 0
    error('Step-03S cannot open output file %s.', path);
end
cleanup = onCleanup(@() fclose(fid));
for ii = 1:numel(lines)
    fprintf(fid, '%s\n', lines(ii));
end
clear cleanup;
end
