function run_step03R_ctilde_decision_similarity_audit_h2()
%RUN_STEP03R_CTILDE_DECISION_SIMILARITY_AUDIT_H2 Audit decision similarity.

clc;
thisDir = fileparts(mfilename('fullpath'));
moduleDir = fileparts(thisDir);
rootDir = fileparts(moduleDir);
addpath(rootDir);
addpath(thisDir);
for candidate = {fullfile(getenv('GUROBI_HOME'), 'matlab'), ...
        'D:\gurobi1201\win64\matlab', 'C:\gurobi1201\win64\matlab'}
    if ~isempty(candidate{1}) && exist(candidate{1}, 'dir')
        addpath(candidate{1});
    end
end
if ~ismember(exist('gurobi', 'file'), [2, 3])
    error('Step-03R requires the existing Gurobi MATLAB interface.');
end

expectedHead = "45fc03faed0c7a687de6f1198b1ecde01c194fe3";
[headStatus, headText] = system('git rev-parse HEAD');
if headStatus ~= 0 || lower(strtrim(string(headText))) ~= expectedHead
    error('Step-03R must start from baseline commit %s.', expectedHead);
end
outputDir = fullfile(rootDir, 'results', 'task-002-stage2b-b3-smoke', ...
    '18-ctilde-decision-similarity-audit', 'run-001');
tempDir = outputDir + ".tmp";
if isfolder(outputDir) || isfolder(tempDir)
    error('Step-03R run-001 output or temporary directory already exists.');
end

inputDir = fullfile(moduleDir, 'output', 'stage3j_wdro_input_freeze', 'run-001');
nominalPath = fullfile(inputDir, 'wdro_nominal_input_DAC.mat');
nominalHash = "6936a696f5cde137aca483f8c32adee33b52cbd90559a8e6395f3686c0712945";
if sha256_file(nominalPath) ~= nominalHash
    error('Step-03R Step-03J nominal MAT hash mismatch.');
end
step03QDir = fullfile(rootDir, 'results', 'task-002-stage2b-b3-smoke', ...
    '17-dctilde-strict-metric-audit', 'run-001');
step03PFailedDir = fullfile(rootDir, 'results', 'task-002-stage2b-b3-smoke', ...
    '16-dac-transport-cost-audit', 'run-001');
if ~isfolder(step03QDir)
    error('Step-03R requires the accepted Step-03Q run-001 archive.');
end
step03JBefore = directory_hash(inputDir);
step03QBefore = directory_hash(step03QDir);
step03PFailedBefore = directory_hash(step03PFailedDir);
protectedFiles = [ ...
    string(fullfile(thisDir, 'build_wdro_distance_matrix_h2.m')); ...
    string(fullfile(thisDir, 'solve_wdro_terminal_loh_lp_h2.m')); ...
    string(fullfile(thisDir, 'solve_wdro_terminal_loh_lp_constraint_generation_h2.m')); ...
    string(fullfile(thisDir, 'solve_step03P_weighted_cg_h2.m')); ...
    string(fullfile(rootDir, 'main_msp_h2_near.m')); ...
    string(fullfile(rootDir, 'h2_default_options.m')); ...
    string(fullfile(rootDir, 'run_h2_with_options.m')); ...
    string(fullfile(rootDir, 'fa_h2', 'build_stage_model_h2.m')); ...
    string(fullfile(rootDir, 'fa_h2', 'update_rhs_h2.m')); ...
    string(fullfile(rootDir, 'fa_h2', 'solve_stage_model_h2.m'))];
protectedBefore = hash_files(protectedFiles);

raw = load(fullfile(rootDir, 'data', 'yuanqi', 'near_stage_msp_input.mat'), ...
    'NearStageInput');
ni = raw.NearStageInput;
Cap = double(ni.HydrogenDevice.tank_cap_kg(:));
if max(abs(Cap - [300;200;100;150])) > 1e-12
    error('Step-03R full capacity vector is not [300,200,100,150].');
end
if isfield(ni.Cost, 'reserve_shortage_penalty_yuan_per_kg')
    M = double(ni.Cost.reserve_shortage_penalty_yuan_per_kg);
elseif isfield(ni.Cost, 'cost_reserve_shortage')
    M = double(ni.Cost.cost_reserve_shortage);
else
    error('Step-03R cannot trace the shortage penalty source.');
end

config = struct('gamma', 0.001 * M, 'gurobiOutputFlag', 0, ...
    'gurobiFeasibilityTol', 1e-9, 'gurobiOptimalityTol', 1e-9, ...
    'gurobiTimeLimit', 300, 'primaryObjectiveTolerance', 1e-8, ...
    'violationTolerance', 1e-8, 'maxIterations', 200, ...
    'blockSize', 100, 'independentScanBlockSize', 73, ...
    'epsDistance', 1e-9, 'scaleTolerance', 1e-12, ...
    'C_bound', 357.1526447416079, 'kappa', 1, ...
    'multipleOptimumWidth', 1e-5, 'zeroDistanceTolerance', 1e-12, ...
    'pairBlockSize', 50000, 'lossProfileQ95', 0.95);
states = table([7;18;30], [2;4;6], [7;4;2], [0;0;0], ...
    ["simple";"medium";"complex"], ...
    'VariableNames', {'initial_state_id','a0','loc0','lfw0','complexity_label'});
R = 2000;
step03QWdro = readtable(fullfile(step03QDir, 'step03Q_wdro_results.csv'), ...
    'TextType', 'string');
step03QDecision = readtable(fullfile(step03QDir, ...
    'step03Q_distance_decision_consistency.csv'), 'TextType', 'string');

stateData = cell(height(states), 1);
singleRecords = cell(0, 1);
rangeRecords = cell(0, 1);
allSingleOptimal = true;
allRangeOptimal = true;
reproMaxTError = 0;
reproMaxObjectiveError = 0;
maxIndependentViolation = 0;

for stateRow = 1:height(states)
    state = states(stateRow, :);
    fprintf('\nStep-03R %s state %d: load and solve 2000 deterministic atoms.\n', ...
        state.complexity_label, state.initial_state_id);
    data = load_frozen_state(nominalPath, state.initial_state_id, R);
    components = build_step03P_distance_components_h2( ...
        data.D, data.A, data.C, config);
    [oldDistance, oldInfo] = build_wdro_distance_matrix_h2( ...
        data.D, data.A, data.C, 'DAC_maskedC', config);
    buildConfig = config;
    buildConfig.components = components;
    buildConfig.oldDistance = oldDistance;
    buildConfig.oldInfo = oldInfo;
    buildConfig.matchOldMedian = false;
    [dNew, ~, detail] = build_step03Q_distance_matrix_h2( ...
        data.D, data.A, data.C, 'ctilde', buildConfig);
    buildConfig.matchOldMedian = true;
    [dNewMatched, matchedInfo] = build_step03Q_distance_matrix_h2( ...
        data.D, data.A, data.C, 'ctilde', buildConfig);

    single = solve_step03R_single_scenario_batch_h2( ...
        data.D, data.A, data.C, Cap, M, config);
    allSingleOptimal = allSingleOptimal && single.exitflag == 1;
    if single.exitflag ~= 1
        error('Step-03R single-scenario batch failed for state %d.', ...
            state.initial_state_id);
    end
    ranges = solve_step03R_single_scenario_ranges_h2( ...
        data.D, data.A, data.C, Cap, M, single.obj_star, config);
    allRangeOptimal = allRangeOptimal && ranges.exitflag == 1;
    if ranges.exitflag ~= 1
        error('Step-03R optimal-range solve failed for state %d.', ...
            state.initial_state_id);
    end

    totalDemand = sum(data.D, 2);
    [~, reproIdx] = min(abs(totalDemand - median(totalDemand)));
    repeated = solve_step03R_single_scenario_batch_h2( ...
        data.D(reproIdx, :), data.A(reproIdx, :, :), ...
        data.C(reproIdx, :, :), Cap, M, config);
    reproMaxTError = max(reproMaxTError, ...
        max(abs(repeated.T - single.T(reproIdx, :)), [], 'all'));
    reproMaxObjectiveError = max(reproMaxObjectiveError, ...
        abs(repeated.obj_star - single.obj_star(reproIdx)));

    activitySol = solve_step03P_weighted_cg_h2( ...
        data.D, data.A, data.C, Cap, M, 0.02, dNewMatched, ...
        ones(R, 1) / R, config);
    if activitySol.exitflag ~= 1 || ~activitySol.converged
        error('Step-03R activity solve failed for state %d.', ...
            state.initial_state_id);
    end
    maxIndependentViolation = max(maxIndependentViolation, ...
        activitySol.final_independent_scan_max_violation);
    activeR = activitySol.activeR;
    activeS = activitySol.activeS;
    activeSlack = activitySol.alpha(activeR) + ...
        activitySol.lambda .* dNewMatched(sub2ind([R, R], activeR, activeS)) - ...
        activitySol.L(activeS);
    keyMask = activeR ~= activeS & abs(activeSlack) <= 1e-7;
    activeDestinationCount = accumarray(activeS(keyMask), 1, [R, 1]);
    activeSourceCount = accumarray(activeR(keyMask), 1, [R, 1]);

    isMultiple = any(ranges.range_width > config.multipleOptimumWidth, 2);
    isSaturated = any(single.T >= Cap.' - 1e-7, 2);
    isFullySaturated = all(single.T >= Cap.' - 1e-7, 2);
    for ss = 1:R
        singleRecords{end + 1, 1} = struct( ...
            'complexity_label', state.complexity_label, ...
            'initial_state_id', state.initial_state_id, ...
            'scenario_index', ss, 'path_id', data.path_id(ss), ...
            'T1', single.T(ss, 1), 'T2', single.T(ss, 2), ...
            'T3', single.T(ss, 3), 'T4', single.T(ss, 4), ...
            'primary_objective_star', single.obj_star(ss), ...
            'representative_primary_objective', ...
                single.primary_objective_at_representative(ss), ...
            'primary_tolerance_slack', single.primary_objective_slack(ss), ...
            'capacity_saturated', isSaturated(ss), ...
            'fully_capacity_saturated', isFullySaturated(ss), ...
            'multiple_optimum_flag', isMultiple(ss), ...
            'wdro_active_destination_count', activeDestinationCount(ss), ...
            'wdro_active_source_count', activeSourceCount(ss)); %#ok<AGROW>
        for ii = 1:numel(Cap)
            rangeRecords{end + 1, 1} = struct( ...
                'complexity_label', state.complexity_label, ...
                'initial_state_id', state.initial_state_id, ...
                'scenario_index', ss, 'path_id', data.path_id(ss), ...
                'site_id', ii, 'T_representative', single.T(ss, ii), ...
                'T_min', ranges.T_min(ss, ii), ...
                'T_max', ranges.T_max(ss, ii), ...
                'range_width', ranges.range_width(ss, ii), ...
                'multiple_optimum_flag', ...
                    ranges.range_width(ss, ii) > config.multipleOptimumWidth); %#ok<AGROW>
        end
    end
    stateData{stateRow} = struct('state', state, 'data', data, ...
        'single', single, 'ranges', ranges, 'dNew', dNew, ...
        'dD', components.normD, 'dCtilde', detail.d_Ctilde, ...
        'rawD', components.rawD, 'rawA', components.rawA, ...
        'rawMaskedC', components.rawC, 'matchedInfo', matchedInfo, ...
        'activitySol', activitySol, ...
        'activeDestinationCount', activeDestinationCount, ...
        'activeSourceCount', activeSourceCount, ...
        'isMultiple', isMultiple, 'isSaturated', isSaturated, ...
        'isFullySaturated', isFullySaturated);
end

[libraryTbl, libraryT] = build_T_library( ...
    stateData, states, step03QWdro, Cap);
fprintf('\nStep-03R common TerminalLOH library contains %d unique vectors.\n', ...
    height(libraryTbl));

pairStatisticRecords = cell(0, 1);
comparisonRecords = cell(0, 1);
falseNearRecords = cell(0, 1);
counterfactualSelections = cell(0, 1);
nearReconciliation = cell(0, 1);
zeroDistanceMaxDT = 0;
zeroDistanceMaxLoss = 0;
nearFarDecisionPass = true;
nearFarLossPass = true;
spearmanDecision = zeros(height(states), 1);
spearmanLoss = zeros(height(states), 1);

for stateRow = 1:height(states)
    item = stateData{stateRow};
    state = item.state;
    fprintf('\nStep-03R %s state %d: evaluate %d common T vectors.\n', ...
        state.complexity_label, state.initial_state_id, height(libraryTbl));
    lossProfile = zeros(R, height(libraryTbl));
    for tt = 1:height(libraryTbl)
        ev = evaluate_step03P_fixed_T_losses_h2( ...
            item.data.D, item.data.A, item.data.C, libraryT(tt, :), M, config);
        if ev.exitflag ~= 1
            error('Step-03R T-library loss evaluation failed.');
        end
        lossProfile(:, tt) = ev.loss;
        if mod(tt, 10) == 0 || tt == height(libraryTbl)
            fprintf('  evaluated %d/%d T vectors.\n', tt, height(libraryTbl));
        end
    end
    item.lossProfile = lossProfile;
    analysis = analyze_pairs(item, Cap, config);
    item.analysis = analysis;
    stateData{stateRow} = item;
    pairStatisticRecords{end + 1, 1} = analysis.statistics; %#ok<AGROW>
    for rr = 1:numel(analysis.comparisonRecords)
        comparisonRecords{end + 1, 1} = analysis.comparisonRecords{rr}; %#ok<AGROW>
    end
    for rr = 1:numel(analysis.falseNearRecords)
        falseNearRecords{end + 1, 1} = analysis.falseNearRecords{rr}; %#ok<AGROW>
    end
    counterfactualSelections{end + 1, 1} = analysis.counterfactualSelection; %#ok<AGROW>
    zeroDistanceMaxDT = max(zeroDistanceMaxDT, analysis.zeroDistanceMaxDT);
    zeroDistanceMaxLoss = max(zeroDistanceMaxLoss, analysis.zeroDistanceMaxLoss);
    nearFarDecisionPass = nearFarDecisionPass && analysis.nearMedianDT < analysis.farMedianDT;
    nearFarLossPass = nearFarLossPass && ...
        analysis.nearMedianLossProfile < analysis.farMedianLossProfile;
    spearmanDecision(stateRow) = analysis.statistics.spearman_dnew_dT;
    spearmanLoss(stateRow) = analysis.statistics.spearman_dnew_dloss_profile;

    qNear = step03QDecision(step03QDecision.initial_state_id == ...
        state.initial_state_id & step03QDecision.distance_label == ...
        "new_Ctilde_k1p0" & step03QDecision.pair_category == "near", :);
    if height(qNear) ~= 1
        error('Step-03R expected one Step-03Q kappa=1 near pair per state.');
    end
    source = qNear.source_scenario_index(1);
    destination = qNear.destination_scenario_index(1);
    nearReconciliation{end + 1, 1} = reconcile_step03Q_near( ...
        item, source, destination, qNear.TerminalLOH_max_abs_change(1), ...
        Cap, config); %#ok<AGROW>
    counterfactualSelections{end + 1, 1} = struct( ...
        'stateRow', stateRow, 'source', source, 'destination', destination, ...
        'selectionBasis', "STEP03Q_NEAR_PERTURBATION"); %#ok<AGROW>
end

counterfactualTbl = run_counterfactuals( ...
    stateData, counterfactualSelections, Cap, M, config);
singleTbl = records_to_table(singleRecords);
rangeTbl = records_to_table(rangeRecords);
pairStatisticsTbl = records_to_table(pairStatisticRecords);
comparisonTbl = records_to_table(comparisonRecords);
falseNearTbl = false_near_table(falseNearRecords);
reconciliationTbl = records_to_table(nearReconciliation);

codeFiles = [ ...
    string(fullfile(thisDir, 'build_step03R_single_scenario_lp_h2.m')); ...
    string(fullfile(thisDir, 'solve_step03R_single_scenario_batch_h2.m')); ...
    string(fullfile(thisDir, 'solve_step03R_single_scenario_ranges_h2.m')); ...
    string(mfilename('fullpath')) + ".m"];
checkcodeWarningCount = 0;
for ff = 1:numel(codeFiles)
    messages = checkcode(codeFiles(ff), '-id');
    checkcodeWarningCount = checkcodeWarningCount + numel(messages);
end

protectedAfter = hash_files(protectedFiles);
protectedPass = all(protectedAfter == protectedBefore);
step03JPass = directory_hash(inputDir) == step03JBefore && ...
    sha256_file(nominalPath) == nominalHash;
step03QPass = directory_hash(step03QDir) == step03QBefore;
step03PFailedPass = directory_hash(step03PFailedDir) == step03PFailedBefore;
singleBoundsPass = all(singleTbl{:, {'T1','T2','T3','T4'}} >= -1e-8, 'all') && ...
    all(singleTbl{:, {'T1','T2','T3','T4'}} <= Cap.' + 1e-8, 'all');
zeroDistancePass = zeroDistanceMaxDT <= 1e-8 && zeroDistanceMaxLoss <= 1e-8;
reproPass = reproMaxTError <= 1e-8 && reproMaxObjectiveError <= 1e-8;
falseNearExplainedPass = isempty(falseNearTbl) || ...
    all(strlength(falseNearTbl.diagnostic_reason) > 0);
domainPass = all(isfinite(singleTbl{:, {'T1','T2','T3','T4', ...
    'primary_objective_star'}}), 'all') && ...
    all(isfinite(pairStatisticsTbl.spearman_dnew_dT)) && ...
    all(isfinite(pairStatisticsTbl.spearman_dnew_dloss_profile));

auditRows = {
    'BASE-01', pass_fail(lower(strtrim(string(headText))) == expectedHead), strtrim(string(headText)), expectedHead;
    'SINGLE-01', pass_fail(allSingleOptimal), allSingleOptimal, '6000 two-stage solves OPTIMAL';
    'SINGLE-02', pass_fail(singleBoundsPass), singleBoundsPass, 'all T within full capacities';
    'SINGLE-03', pass_fail(reproPass), max(reproMaxTError, reproMaxObjectiveError), '<=1e-8';
    'RANGE-01', pass_fail(allRangeOptimal), allRangeOptimal, 'all range solves OPTIMAL';
    'ZERO-01', pass_fail(zeroDistancePass), max(zeroDistanceMaxDT, zeroDistanceMaxLoss), '<=1e-8';
    'ORDER-01', pass_fail(nearFarDecisionPass), nearFarDecisionPass, 'near median d_T < far median d_T for all states';
    'ORDER-02', pass_fail(nearFarLossPass), nearFarLossPass, 'near median profile distance < far median for all states';
    'FALSE-01', pass_fail(falseNearExplainedPass), falseNearExplainedPass, 'all severe candidates diagnosed';
    'SOLVE-01', pass_fail(maxIndependentViolation <= 1e-8), maxIndependentViolation, '<=1e-8';
    'CODE-01', pass_fail(checkcodeWarningCount == 0), checkcodeWarningCount, '0 warnings';
    'CORE-01', pass_fail(protectedPass), protectedPass, 'formal WDRO and MSP unchanged';
    'DATA-01', pass_fail(step03JPass), step03JPass, 'Step-03J unchanged';
    'OLD-01', pass_fail(step03QPass && step03PFailedPass), step03QPass && step03PFailedPass, 'Step-03Q and untracked Step-03P history unchanged';
    'DOMAIN-01', pass_fail(domainPass), domainPass, 'finite outputs';
    'SCOPE-01', 'PASS', '3 states x R=2000 nominal only', 'no validation tuning/R=5000/R=15000/all states';
    'MSP-01', 'PASS', 'not run or modified', 'formal distance, WDRO loss, and MSP protected'};
acceptanceTbl = cell2table(auditRows, 'VariableNames', ...
    {'check_id','status','observed','expected'});
failCount = sum(strcmp(acceptanceTbl.status, 'FAIL'));
if failCount > 0
    disp(acceptanceTbl(strcmp(acceptanceTbl.status, 'FAIL'), :));
    error('Step-03R has %d mechanical audit failures; no archive or Git write.', failCount);
end

trueConflictCount = 0;
if ~isempty(falseNearTbl)
    trueConflictCount = sum(falseNearTbl.diagnostic_reason == "TRUE_FALSE_NEAR_CONFLICT");
end
if isempty(falseNearTbl)
    decision = "A. CTILDE_DECISION_SIMILARITY_VALIDATED";
elseif trueConflictCount == 0
    decision = "B. CTILDE_VALID_WITH_LIMITED_FALSE_NEAR_CASES";
else
    decision = "C. CTILDE_REWEIGHTING_REQUIRED";
end

mkdir(tempDir);
writetable(singleTbl, fullfile(tempDir, 'step03R_single_scenario_T.csv'));
writetable(rangeTbl, fullfile(tempDir, 'step03R_single_scenario_optimal_ranges.csv'));
writetable(libraryTbl, fullfile(tempDir, 'step03R_T_library.csv'));
writetable(pairStatisticsTbl, fullfile(tempDir, ...
    'step03R_pairwise_decision_statistics.csv'));
writetable(comparisonTbl, fullfile(tempDir, ...
    'step03R_near_middle_far_comparison.csv'));
writetable(falseNearTbl, fullfile(tempDir, 'step03R_false_near_cases.csv'));
writetable(counterfactualTbl, fullfile(tempDir, 'step03R_counterfactual_results.csv'));
writetable(acceptanceTbl, fullfile(tempDir, 'step03R_acceptance_tests.csv'));
write_diagnostics(fullfile(tempDir, 'step03R_false_near_diagnostics.md'), ...
    decision, pairStatisticsTbl, falseNearTbl, reconciliationTbl, ...
    counterfactualTbl, config);
write_summary(fullfile(tempDir, 'step03R_summary.txt'), decision, ...
    pairStatisticsTbl, comparisonTbl, falseNearTbl, reconciliationTbl, ...
    counterfactualTbl, spearmanDecision, spearmanLoss, ...
    zeroDistanceMaxDT, zeroDistanceMaxLoss, failCount);
movefile(tempDir, outputDir);
fprintf('\nStep-03R completed: %s; PASS=%d FAIL=%d.\n', ...
    decision, height(acceptanceTbl), failCount);
end

function data = load_frozen_state(path, stateId, R)
rows = (stateId - 1) * 15000 + (1:R);
m = matfile(path);
data = struct('D', double(m.D_node_kg(rows, :)), ...
    'A', double(m.A_site_node(rows, :, :)), ...
    'C', double(m.C_site_node_km(rows, :, :)), ...
    'path_id', double(m.path_id(rows, 1)));
if any(double(m.initial_state_id(rows, 1)) ~= stateId) || ...
        ~isequal(size(data.A), [R, 4, 33]) || ~isequal(size(data.C), size(data.A))
    error('Step-03R frozen state layout mismatch.');
end
end

function [tbl, T] = build_T_library(stateData, states, wdro, Cap)
records = cell(0, 1);
vectors = zeros(0, numel(Cap));
    function add_vector(sourceType, sourceLabel, stateId, scenarioIdx, ...
            pathId, rho, distanceLabel, value)
        value = double(value(:).');
        duplicate = find(all(vectors == value, 2), 1, 'first');
        if ~isempty(duplicate)
            records{duplicate}.source_record_count = ...
                records{duplicate}.source_record_count + 1;
            records{duplicate}.source_labels = records{duplicate}.source_labels + ...
                ";" + sourceLabel;
            return;
        end
        vectors(end + 1, :) = value;
        records{end + 1, 1} = struct('T_library_id', size(vectors, 1), ...
            'source_type', sourceType, 'source_labels', sourceLabel, ...
            'initial_state_id', stateId, 'scenario_index', scenarioIdx, ...
            'path_id', pathId, 'rho', rho, 'distance_label', distanceLabel, ...
            'T1', value(1), 'T2', value(2), 'T3', value(3), 'T4', value(4), ...
            'source_record_count', 1);
    end

fractions = [0;0.25;0.5;0.75;1];
for ff = 1:numel(fractions)
    add_vector("CAPACITY_FRACTION", "fraction_" + string(fractions(ff)), ...
        0, 0, 0, NaN, "not_applicable", fractions(ff) .* Cap);
end
selectedWdro = wdro(wdro.distance_label == "old_D_A_maskedC" | ...
    wdro.distance_label == "new_Ctilde_k1p0", :);
for rr = 1:height(selectedWdro)
    add_vector("STEP03Q_WDRO", selectedWdro.complexity_label(rr) + ...
        "_" + selectedWdro.distance_label(rr) + "_rho_" + ...
        string(selectedWdro.rho(rr)), selectedWdro.initial_state_id(rr), ...
        0, 0, selectedWdro.rho(rr), selectedWdro.distance_label(rr), ...
        selectedWdro{rr, {'T1','T2','T3','T4'}});
end
for stateRow = 1:numel(stateData)
    item = stateData{stateRow};
    values = item.single.T;
    criteria = [sum(values, 2), values];
    names = ["T_total","T1","T2","T3","T4"];
    for cc = 1:size(criteria, 2)
        [~, order] = sort(criteria(:, cc), 'ascend');
        if cc == 1
            positions = unique(round(linspace(1, size(values, 1), 5)));
        else
            positions = [1, size(values, 1)];
        end
        for pp = positions
            ss = order(pp);
            add_vector("T_SINGLE_REPRESENTATIVE", ...
                item.state.complexity_label + "_" + names(cc) + "_rank_" + ...
                string(pp), item.state.initial_state_id, ss, ...
                item.data.path_id(ss), NaN, "not_applicable", values(ss, :));
        end
    end
end
stream = RandStream('mt19937ar', 'Seed', 20263801);
randomT = rand(stream, 16, numel(Cap)) .* Cap.';
for rr = 1:size(randomT, 1)
    add_vector("DETERMINISTIC_RANDOM_FEASIBLE", "seed_20263801_draw_" + ...
        string(rr), 0, rr, 0, NaN, "not_applicable", randomT(rr, :));
end
tbl = records_to_table(records);
T = tbl{:, {'T1','T2','T3','T4'}};
if any(T < -1e-8, 'all') || any(T > Cap.' + 1e-7, 'all')
    error('Step-03R T library contains an infeasible vector.');
end
if ~all(ismember(states.initial_state_id, unique(tbl.initial_state_id)))
    error('Step-03R T library lacks a representative state.');
end
end

function out = analyze_pairs(item, Cap, config)
R = size(item.dNew, 1);
[pairI, pairJ] = find(triu(true(R), 1));
pairLinear = sub2ind([R, R], pairI, pairJ);
dNew = item.dNew(pairLinear);
dD = item.dD(pairLinear);
dCtilde = item.dCtilde(pairLinear);
rawD = item.rawD(pairLinear);
rawA = item.rawA(pairLinear);
rawMaskedC = item.rawMaskedC(pairLinear);
Tdiff = abs(item.single.T(pairI, :) - item.single.T(pairJ, :));
dT = mean(Tdiff ./ Cap.', 2);
T_l1 = sum(Tdiff, 2);
T_l2 = sqrt(sum(Tdiff .^ 2, 2));
[T_max, T_max_site] = max(Tdiff, [], 2);

pairCount = numel(pairI);
lossMax = zeros(pairCount, 1);
lossMean = zeros(pairCount, 1);
lossQ95 = zeros(pairCount, 1);
for start = 1:config.pairBlockSize:pairCount
    idx = start:min(pairCount, start + config.pairBlockSize - 1);
    delta = abs(item.lossProfile(pairI(idx), :) - item.lossProfile(pairJ(idx), :));
    lossMax(idx) = max(delta, [], 2);
    lossMean(idx) = mean(delta, 2);
    sorted = sort(delta, 2);
    qIndex = max(1, ceil(config.lossProfileQ95 * size(sorted, 2)));
    lossQ95(idx) = sorted(:, qIndex);
end

q01D = pct(dNew, 0.01);
q45D = pct(dNew, 0.45);
q55D = pct(dNew, 0.55);
q99D = pct(dNew, 0.99);
q99T = pct(dT, 0.99);
q99Loss = pct(lossMax, 0.99);
lowMask = dNew <= q01D + 1e-15;
falseDecision = lowMask & dT >= q99T - 1e-15;
falseLoss = lowMask & lossMax >= q99Loss - 1e-12;
falseMask = falseDecision | falseLoss;

distanceForNeighbors = item.dNew;
distanceForNeighbors(1:R + 1:end) = inf;
[~, neighbors] = mink(distanceForNeighbors, 10, 2);
nearPairs = sort([repelem((1:R).', 10, 1), neighbors(:)], 2);
nearPairs = unique(nearPairs, 'rows');
positionMap = zeros(R * R, 1, 'uint32');
positionMap(pairLinear) = uint32(1:pairCount);
nearPosition = double(positionMap(sub2ind([R, R], nearPairs(:, 1), nearPairs(:, 2))));
nearPosition = nearPosition(nearPosition > 0);
middleCandidate = find(dNew >= q45D & dNew <= q55D);
farCandidate = find(dNew >= q99D);
targetCount = numel(nearPosition);
middlePosition = comparable_selection(middleCandidate, targetCount);
farPosition = comparable_selection(farCandidate, targetCount);

categories = {"near", nearPosition; "middle", middlePosition; "far", farPosition};
comparisonRecords = cell(size(categories, 1), 1);
for cc = 1:size(categories, 1)
    name = categories{cc, 1};
    idx = categories{cc, 2};
    pairMultiple = item.isMultiple(pairI(idx)) | item.isMultiple(pairJ(idx));
    pairSaturated = item.isSaturated(pairI(idx)) | item.isSaturated(pairJ(idx));
    pairActive = item.activeDestinationCount(pairI(idx)) > 0 | ...
        item.activeDestinationCount(pairJ(idx)) > 0;
    comparisonRecords{cc} = struct( ...
        'complexity_label', item.state.complexity_label, ...
        'initial_state_id', item.state.initial_state_id, ...
        'pair_category', name, 'pair_count', numel(idx), ...
        'd_new_min', min(dNew(idx)), 'd_new_median', median(dNew(idx)), ...
        'd_new_q95', pct(dNew(idx), 0.95), 'd_new_max', max(dNew(idx)), ...
        'd_T_mean', mean(dT(idx)), 'd_T_median', median(dT(idx)), ...
        'd_T_q95', pct(dT(idx), 0.95), 'd_T_q99', pct(dT(idx), 0.99), ...
        'd_loss_profile_mean', mean(lossMax(idx)), ...
        'd_loss_profile_median', median(lossMax(idx)), ...
        'd_loss_profile_q95', pct(lossMax(idx), 0.95), ...
        'd_loss_profile_q99', pct(lossMax(idx), 0.99), ...
        'max_single_site_T_difference_median', median(T_max(idx)), ...
        'capacity_saturation_pair_share', mean(pairSaturated), ...
        'multiple_optimum_pair_share', mean(pairMultiple), ...
        'wdro_active_destination_pair_share', mean(pairActive));
end

zeroMask = dNew <= config.zeroDistanceTolerance;
if any(zeroMask)
    zeroMaxDT = max(dT(zeroMask));
    zeroMaxLoss = max(lossMax(zeroMask));
else
    zeroMaxDT = 0;
    zeroMaxLoss = 0;
end
statistics = struct( ...
    'complexity_label', item.state.complexity_label, ...
    'initial_state_id', item.state.initial_state_id, ...
    'all_unordered_pair_count', pairCount, ...
    'spearman_dnew_dT', spearman_corr(dNew, dT), ...
    'spearman_dnew_dloss_profile', spearman_corr(dNew, lossMax), ...
    'distance_low_1pct_cut', q01D, 'distance_middle_45pct_cut', q45D, ...
    'distance_middle_55pct_cut', q55D, 'distance_high_99pct_cut', q99D, ...
    'd_T_high_99pct_cut', q99T, ...
    'd_loss_profile_high_99pct_cut', q99Loss, ...
    'lowest_distance_pair_count_with_ties', sum(lowMask), ...
    'decision_false_near_count', sum(falseDecision), ...
    'loss_false_near_count', sum(falseLoss), ...
    'combined_false_near_count', sum(falseMask), ...
    'combined_false_near_share_all_pairs', mean(falseMask), ...
    'combined_false_near_share_low_distance', ...
        sum(falseMask) / max(1, sum(lowMask)), ...
    'zero_distance_pair_count', sum(zeroMask), ...
    'zero_distance_max_d_T', zeroMaxDT, ...
    'zero_distance_max_d_loss_profile', zeroMaxLoss);

falsePositions = find(falseMask);
if isempty(falsePositions)
    falseNearRecords = cell(0, 1);
    lowPositions = find(lowMask);
    severity = normalized_severity(dT(lowPositions), q99T) + ...
        normalized_severity(lossMax(lowPositions), q99Loss);
    [~, order] = sort(severity, 'descend');
    chosen = lowPositions(order(1:min(3, numel(order))));
    selectionBasis = "LOWEST_1PCT_STRESS_PAIR_NO_FORMAL_FALSE_NEAR";
else
    severity = normalized_severity(dT(falsePositions), q99T) + ...
        normalized_severity(lossMax(falsePositions), q99Loss);
    [~, order] = sort(severity, 'descend');
    chosen = falsePositions(order(1:min(20, numel(order))));
    falseNearRecords = cell(numel(chosen), 1);
    for kk = 1:numel(chosen)
        pos = chosen(kk);
        rangeOverlap = all(max(item.ranges.T_min(pairI(pos), :), ...
            item.ranges.T_min(pairJ(pos), :)) <= ...
            min(item.ranges.T_max(pairI(pos), :), ...
            item.ranges.T_max(pairJ(pos), :)) + 1e-7);
        reason = diagnose_pair(item, pairI(pos), pairJ(pos), ...
            rangeOverlap, falseDecision(pos), falseLoss(pos));
        falseNearRecords{kk} = struct( ...
            'complexity_label', item.state.complexity_label, ...
            'initial_state_id', item.state.initial_state_id, ...
            'severity_rank', kk, 'scenario_r', pairI(pos), ...
            'path_id_r', item.data.path_id(pairI(pos)), ...
            'scenario_s', pairJ(pos), 'path_id_s', item.data.path_id(pairJ(pos)), ...
            'decision_false_near', falseDecision(pos), ...
            'loss_false_near', falseLoss(pos), ...
            'd_D', dD(pos), 'd_Ctilde', dCtilde(pos), 'd_new', dNew(pos), ...
            'D_l1_difference_kg', rawD(pos), ...
            'A_reachability_difference_count', rawA(pos), ...
            'C_common_reachable_l1_difference_km', rawMaskedC(pos), ...
            'T_r1', item.single.T(pairI(pos), 1), ...
            'T_r2', item.single.T(pairI(pos), 2), ...
            'T_r3', item.single.T(pairI(pos), 3), ...
            'T_r4', item.single.T(pairI(pos), 4), ...
            'T_s1', item.single.T(pairJ(pos), 1), ...
            'T_s2', item.single.T(pairJ(pos), 2), ...
            'T_s3', item.single.T(pairJ(pos), 3), ...
            'T_s4', item.single.T(pairJ(pos), 4), ...
            'd_T', dT(pos), 'T_L1_difference_kg', T_l1(pos), ...
            'T_L2_difference_kg', T_l2(pos), ...
            'max_single_site_T_difference_kg', T_max(pos), ...
            'max_difference_site_id', T_max_site(pos), ...
            'd_loss_profile', lossMax(pos), ...
            'mean_loss_profile_difference', lossMean(pos), ...
            'q95_loss_profile_difference', lossQ95(pos), ...
            'optimal_range_overlap_all_sites', rangeOverlap, ...
            'multiple_optimum_in_pair', item.isMultiple(pairI(pos)) || ...
                item.isMultiple(pairJ(pos)), ...
            'capacity_saturation_in_pair', item.isSaturated(pairI(pos)) || ...
                item.isSaturated(pairJ(pos)), ...
            'both_scenarios_fully_saturated', ...
                item.isFullySaturated(pairI(pos)) && item.isFullySaturated(pairJ(pos)), ...
            'wdro_active_destination_in_pair', ...
                item.activeDestinationCount(pairI(pos)) > 0 || ...
                item.activeDestinationCount(pairJ(pos)) > 0, ...
            'diagnostic_reason', reason);
    end
    chosen = chosen(1:min(5, numel(chosen)));
    selectionBasis = "FORMAL_FALSE_NEAR_TOP_SEVERITY";
end
counterfactualSelection = cell(numel(chosen), 1);
for kk = 1:numel(chosen)
    counterfactualSelection{kk} = struct('stateRow', ...
        find([7,18,30] == item.state.initial_state_id, 1), ...
        'source', pairI(chosen(kk)), 'destination', pairJ(chosen(kk)), ...
        'selectionBasis', selectionBasis);
end
out = struct('statistics', statistics, ...
    'comparisonRecords', {comparisonRecords}, ...
    'falseNearRecords', {falseNearRecords}, ...
    'counterfactualSelection', {counterfactualSelection}, ...
    'zeroDistanceMaxDT', zeroMaxDT, 'zeroDistanceMaxLoss', zeroMaxLoss, ...
    'nearMedianDT', comparisonRecords{1}.d_T_median, ...
    'farMedianDT', comparisonRecords{3}.d_T_median, ...
    'nearMedianLossProfile', comparisonRecords{1}.d_loss_profile_median, ...
    'farMedianLossProfile', comparisonRecords{3}.d_loss_profile_median);
end

function reason = diagnose_pair(item, r, s, rangeOverlap, falseDecision, falseLoss)
if rangeOverlap && (item.isMultiple(r) || item.isMultiple(s))
    reason = "MULTIPLE_OPTIMA_RANGE_OVERLAP";
elseif item.isFullySaturated(r) && item.isFullySaturated(s)
    reason = "CAPACITY_SATURATION";
elseif item.activeDestinationCount(r) == 0 && item.activeDestinationCount(s) == 0
    reason = "NON_KEY_SCENARIOS_UNDER_STEP03Q_WDRO";
elseif falseDecision || falseLoss
    reason = "TRUE_FALSE_NEAR_CONFLICT";
else
    reason = "LIMITED_NEAR_DIFFERENCE";
end
end

function rec = reconcile_step03Q_near(item, source, destination, deltaT, Cap, config)
dT = mean(abs(item.single.T(source, :) - item.single.T(destination, :)) ./ Cap.');
profileDistance = max(abs(item.lossProfile(source, :) - item.lossProfile(destination, :)));
rangeOverlap = all(max(item.ranges.T_min(source, :), item.ranges.T_min(destination, :)) <= ...
    min(item.ranges.T_max(source, :), item.ranges.T_max(destination, :)) + 1e-7);
wdroFullySaturated = all(item.activitySol.T >= Cap - 1e-7);
if dT <= 1e-6 && profileDistance <= 1e-6
    classification = "TRUE_SCENARIO_SIMILARITY";
elseif wdroFullySaturated
    classification = "CAPACITY_SATURATION";
elseif rangeOverlap && (item.isMultiple(source) || item.isMultiple(destination))
    classification = "MULTIPLE_OPTIMA";
elseif item.activeDestinationCount(source) == 0 && ...
        item.activeDestinationCount(destination) == 0
    classification = "SCENARIOS_NOT_WDRO_KEY";
else
    activeLoss = item.activitySol.L(item.activeDestinationCount > 0);
    pairLoss = item.activitySol.L([source, destination]);
    if ~isempty(activeLoss) && max(activeLoss) > max(pairLoss) + config.primaryObjectiveTolerance
        classification = "DOMINATED_BY_MORE_SEVERE_ACTIVE_SCENARIOS";
    else
        classification = "MIXED_OR_LIMITED_EFFECT";
    end
end
rec = struct('complexity_label', item.state.complexity_label, ...
    'initial_state_id', item.state.initial_state_id, ...
    'source_scenario_index', source, 'destination_scenario_index', destination, ...
    'step03Q_perturbed_T_max_abs_change', deltaT, ...
    'single_scenario_d_T', dT, 'loss_profile_distance', profileDistance, ...
    'optimal_range_overlap_all_sites', rangeOverlap, ...
    'source_multiple_optimum', item.isMultiple(source), ...
    'destination_multiple_optimum', item.isMultiple(destination), ...
    'wdro_solution_fully_saturated', wdroFullySaturated, ...
    'source_fully_saturated', item.isFullySaturated(source), ...
    'destination_fully_saturated', item.isFullySaturated(destination), ...
    'source_active_destination_count', item.activeDestinationCount(source), ...
    'destination_active_destination_count', item.activeDestinationCount(destination), ...
    'classification', classification);
end

function tbl = run_counterfactuals(stateData, selections, Cap, M, config)
flat = cell(0, 1);
for ii = 1:numel(selections)
    current = selections{ii};
    if iscell(current)
        for jj = 1:numel(current)
            flat{end + 1, 1} = current{jj}; %#ok<AGROW>
        end
    else
        flat{end + 1, 1} = current; %#ok<AGROW>
    end
end
keys = strings(numel(flat), 1);
for ii = 1:numel(flat)
    keys(ii) = string(flat{ii}.stateRow) + "_" + ...
        string(min(flat{ii}.source, flat{ii}.destination)) + "_" + ...
        string(max(flat{ii}.source, flat{ii}.destination));
end
[~, keep] = unique(keys, 'stable');
flat = flat(sort(keep));
records = cell(numel(flat), 1);
for ii = 1:numel(flat)
    selection = flat{ii};
    item = stateData{selection.stateRow};
    r = selection.source;
    s = selection.destination;
    localD = item.data.D([r,s], :);
    localA = item.data.A([r,s], :, :);
    localC = item.data.C([r,s], :, :);
    empiricalDistance = [0,1;1,0];
    mixture = solve_step03P_weighted_cg_h2(localD, localA, localC, ...
        Cap, M, 0, empiricalDistance, [0.5;0.5], config);
    if mixture.exitflag ~= 1 || ~mixture.converged
        error('Step-03R two-scenario counterfactual solve failed.');
    end
    dNew = item.dNew(r, s);
    dT = mean(abs(item.single.T(r, :) - item.single.T(s, :)) ./ Cap.');
    profileDistance = max(abs(item.lossProfile(r, :) - item.lossProfile(s, :)));
    records{ii} = struct('complexity_label', item.state.complexity_label, ...
        'initial_state_id', item.state.initial_state_id, ...
        'selection_basis', selection.selectionBasis, ...
        'scenario_r', r, 'path_id_r', item.data.path_id(r), ...
        'scenario_s', s, 'path_id_s', item.data.path_id(s), ...
        'd_new', dNew, 'd_T', dT, 'd_loss_profile', profileDistance, ...
        'T_r1', item.single.T(r, 1), 'T_r2', item.single.T(r, 2), ...
        'T_r3', item.single.T(r, 3), 'T_r4', item.single.T(r, 4), ...
        'T_s1', item.single.T(s, 1), 'T_s2', item.single.T(s, 2), ...
        'T_s3', item.single.T(s, 3), 'T_s4', item.single.T(s, 4), ...
        'T_mix1', mixture.T(1), 'T_mix2', mixture.T(2), ...
        'T_mix3', mixture.T(3), 'T_mix4', mixture.T(4), ...
        'mix_objective_value', mixture.objective_value, ...
        'mix_max_independent_violation', mixture.final_independent_scan_max_violation, ...
        'mix_T_distance_from_r', mean(abs(mixture.T.' - item.single.T(r, :)) ./ Cap.'), ...
        'mix_T_distance_from_s', mean(abs(mixture.T.' - item.single.T(s, :)) ./ Cap.'));
end
tbl = records_to_table(records);
end

function positions = comparable_selection(candidates, targetCount)
if isempty(candidates)
    error('Step-03R comparable pair category is empty.');
end
count = min(targetCount, numel(candidates));
pick = unique(round(linspace(1, numel(candidates), count)));
positions = candidates(pick);
end

function values = normalized_severity(x, threshold)
values = x ./ max(threshold, eps);
end

function value = spearman_corr(x, y)
rx = average_rank(x);
ry = average_rank(y);
matrix = corrcoef(rx, ry);
value = matrix(1, 2);
end

function ranks = average_rank(x)
[sorted, order] = sort(x(:));
ranks = zeros(size(sorted));
start = 1;
while start <= numel(sorted)
    finish = start;
    while finish < numel(sorted) && sorted(finish + 1) == sorted(start)
        finish = finish + 1;
    end
    ranks(order(start:finish)) = (start + finish) / 2;
    start = finish + 1;
end
end

function value = pct(x, probability)
x = sort(double(x(:)));
if isempty(x)
    value = NaN;
    return;
end
position = 1 + (numel(x) - 1) * probability;
lower = floor(position);
upper = ceil(position);
if lower == upper
    value = x(lower);
else
    value = x(lower) + (position - lower) * (x(upper) - x(lower));
end
end

function tbl = false_near_table(records)
if ~isempty(records)
    tbl = records_to_table(records);
    return;
end
template = struct('complexity_label', "", 'initial_state_id', 0, ...
    'severity_rank', 0, 'scenario_r', 0, 'path_id_r', 0, ...
    'scenario_s', 0, 'path_id_s', 0, 'decision_false_near', false, ...
    'loss_false_near', false, 'd_D', 0, 'd_Ctilde', 0, 'd_new', 0, ...
    'D_l1_difference_kg', 0, 'A_reachability_difference_count', 0, ...
    'C_common_reachable_l1_difference_km', 0, ...
    'T_r1', 0, 'T_r2', 0, 'T_r3', 0, 'T_r4', 0, ...
    'T_s1', 0, 'T_s2', 0, 'T_s3', 0, 'T_s4', 0, ...
    'd_T', 0, 'T_L1_difference_kg', 0, 'T_L2_difference_kg', 0, ...
    'max_single_site_T_difference_kg', 0, 'max_difference_site_id', 0, ...
    'd_loss_profile', 0, 'mean_loss_profile_difference', 0, ...
    'q95_loss_profile_difference', 0, ...
    'optimal_range_overlap_all_sites', false, ...
    'multiple_optimum_in_pair', false, 'capacity_saturation_in_pair', false, ...
    'both_scenarios_fully_saturated', false, ...
    'wdro_active_destination_in_pair', false, 'diagnostic_reason', "");
tbl = struct2table(template);
tbl(1, :) = [];
end

function tbl = records_to_table(records)
if isempty(records)
    tbl = table();
else
    tbl = struct2table(vertcat(records{:}));
end
end

function values = hash_files(files)
values = strings(numel(files), 1);
for ii = 1:numel(files)
    values(ii) = sha256_file(files(ii));
end
end

function value = directory_hash(path)
if ~isfolder(path)
    value = "MISSING";
    return;
end
files = dir(fullfile(path, '**', '*'));
files = files(~[files.isdir]);
relative = strings(numel(files), 1);
for ii = 1:numel(files)
    relative(ii) = replace(string(fullfile(files(ii).folder, files(ii).name)), ...
        string(path) + filesep, "");
end
[relative, order] = sort(relative);
payload = strings(numel(order), 1);
for ii = 1:numel(order)
    filePath = fullfile(path, relative(ii));
    payload(ii) = relative(ii) + "|" + string(files(order(ii)).bytes) + ...
        "|" + sha256_file(filePath);
end
value = sha256_text(join(payload, newline));
end

function value = sha256_file(path)
stream = java.io.FileInputStream(java.io.File(char(path)));
cleanup = onCleanup(@() stream.close());
value = lower(string(org.apache.commons.codec.digest.DigestUtils.sha256Hex(stream)));
end

function value = sha256_text(textValue)
bytes = unicode2native(char(textValue), 'UTF-8');
value = lower(string(org.apache.commons.codec.digest.DigestUtils.sha256Hex(bytes)));
end

function value = pass_fail(condition)
if condition
    value = 'PASS';
else
    value = 'FAIL';
end
end

function write_diagnostics(path, decision, statistics, falseNear, ...
        reconciliation, counterfactual, config)
lines = ["# Step-03R False-Near Diagnostics"; ""; ...
    "## Scope"; ""; ...
    "This audit follows Bertsimas and Mundru, Optimization-Based Scenario Reduction for Data-Driven Two-Stage Stochastic Optimization, Operations Research (2023; an online version may carry 2022). The borrowed principle is that scenario similarity should be checked against optimization objectives and decisions, not geometry alone. This project does not reduce, delete, merge, or reweight scenarios; it tests D+Ctilde using four-site deterministic T, complete loss profiles, and finite counterfactual distributions."; ""; ...
    "The audited unscaled distance is d_new=0.6*d_D+0.4*d_Ctilde with kappa=1 and C_bound=" + ...
        string(sprintf('%.16g', config.C_bound)) + " km. Step-03Q median scaling is used only when reproducing its WDRO activity solution because positive scalar scaling leaves pair rankings unchanged."; ""; ...
    "## Overall decision"; ""; decision; ""; ...
    "## Pairwise statistics"; ""];
for rr = 1:height(statistics)
    lines(end + 1) = "- " + statistics.complexity_label(rr) + ...
        ": Spearman(d_new,d_T)=" + string(sprintf('%.6g', statistics.spearman_dnew_dT(rr))) + ...
        ", Spearman(d_new,d_loss_profile)=" + ...
        string(sprintf('%.6g', statistics.spearman_dnew_dloss_profile(rr))) + ...
        ", formal false-near pairs=" + string(statistics.combined_false_near_count(rr)) + "."; %#ok<AGROW>
end
lines = [lines; ""; "## Severe false-near cases"; ""];
if isempty(falseNear)
    lines(end + 1) = "No pair simultaneously met the formal lowest-1%-distance and highest-1%-decision/loss criteria. Counterfactuals therefore use the most severe stress pairs inside the lowest-distance set.";
else
    for rr = 1:height(falseNear)
        lines(end + 1) = "- " + falseNear.complexity_label(rr) + ...
            " pair (" + string(falseNear.scenario_r(rr)) + "," + ...
            string(falseNear.scenario_s(rr)) + "): d_new=" + ...
            string(sprintf('%.6g', falseNear.d_new(rr))) + ", d_T=" + ...
            string(sprintf('%.6g', falseNear.d_T(rr))) + ", profile=" + ...
            string(sprintf('%.6g', falseNear.d_loss_profile(rr))) + ...
            ", reason=" + falseNear.diagnostic_reason(rr) + "."; %#ok<AGROW>
    end
end
lines = [lines; ""; "## Step-03Q near-perturbation reconciliation"; ""];
for rr = 1:height(reconciliation)
    lines(end + 1) = "- " + reconciliation.complexity_label(rr) + ...
        ": Step-03Q DeltaT=" + string(sprintf('%.6g', ...
        reconciliation.step03Q_perturbed_T_max_abs_change(rr))) + ...
        ", single-scenario d_T=" + string(sprintf('%.6g', ...
        reconciliation.single_scenario_d_T(rr))) + ", profile distance=" + ...
        string(sprintf('%.6g', reconciliation.loss_profile_distance(rr))) + ...
        ", classification=" + reconciliation.classification(rr) + "."; %#ok<AGROW>
end
lines = [lines; ""; "## Counterfactual checks"; ""; ...
    "Each listed pair was solved as scenario r alone, scenario s alone, and a 50/50 two-scenario empirical distribution. The single-scenario rows use the deterministic two-stage tie break; the mixture uses the unchanged loss model with a common T."; ""];
for rr = 1:height(counterfactual)
    lines(end + 1) = "- " + counterfactual.complexity_label(rr) + ...
        " pair (" + string(counterfactual.scenario_r(rr)) + "," + ...
        string(counterfactual.scenario_s(rr)) + "), basis=" + ...
        counterfactual.selection_basis(rr) + ", d_new=" + ...
        string(sprintf('%.6g', counterfactual.d_new(rr))) + ...
        ", mix distance from r/s=" + ...
        string(sprintf('%.6g/%.6g', counterfactual.mix_T_distance_from_r(rr), ...
        counterfactual.mix_T_distance_from_s(rr))) + "."; %#ok<AGROW>
end
write_lines(path, lines);
end

function write_summary(path, decision, ~, comparison, falseNear, ...
        reconciliation, counterfactual, spearmanDecision, spearmanLoss, ...
        zeroMaxDT, zeroMaxLoss, failCount)
near = comparison(comparison.pair_category == "near", :);
far = comparison(comparison.pair_category == "far", :);
replaceAllowed = startsWith(decision, "A.") || startsWith(decision, "B.");
lines = ["Step-03R Ctilde decision-similarity audit"; ""; ...
    "decision=" + decision; ...
    "states=simple 7, medium 18, complex 30; R=2000 each; nominal only"; ...
    "single_scenario_count=6000"; ...
    "spearman_dnew_dT_range=" + range_text(spearmanDecision); ...
    "spearman_dnew_dloss_profile_range=" + range_text(spearmanLoss); ...
    "near_dT_median_range=" + range_text(near.d_T_median); ...
    "far_dT_median_range=" + range_text(far.d_T_median); ...
    "near_loss_profile_median_range=" + range_text(near.d_loss_profile_median); ...
    "far_loss_profile_median_range=" + range_text(far.d_loss_profile_median); ...
    "formal_false_near_count=" + string(height(falseNear)); ...
    "zero_distance_max_dT=" + string(sprintf('%.16g', zeroMaxDT)); ...
    "zero_distance_max_loss_profile=" + string(sprintf('%.16g', zeroMaxLoss)); ...
    "counterfactual_pair_count=" + string(height(counterfactual)); ...
    "mechanical_FAIL=" + string(failCount); ""; ...
    "Required answers:"; ...
    "1. Near single-scenario ideal T is usually closer than far T: " + yes_no(all(near.d_T_median < far.d_T_median)) + "."; ...
    "2. Near complete loss profiles are usually closer than far profiles: " + yes_no(all(near.d_loss_profile_median < far.d_loss_profile_median)) + "."; ...
    "3. Far T differences are materially larger in the median comparison: " + yes_no(all(far.d_T_median > near.d_T_median)) + "."; ...
    "4. Small-distance opposite-layout counterexamples: " + false_near_answer(falseNear) + "."; ...
    "5. Step-03Q near DeltaT explanations: " + join(unique(reconciliation.classification), ", ") + "."; ...
    "6. Complex full capacity masking present: " + yes_no(any(reconciliation.complexity_label == "complex" & reconciliation.wdro_solution_fully_saturated)) + "."; ...
    "7. Multiple optima affect some comparisons: " + yes_no(any(reconciliation.source_multiple_optimum | reconciliation.destination_multiple_optimum)) + "."; ...
    "8. Ctilde reflects pre-layout similarity under this audit: " + yes_no(replaceAllowed) + "."; ...
    "9. Formal replacement recommendation: " + replacement_answer(replaceAllowed) + "."; ...
    "10. Rho recalibration and R=5000 may proceed only after accepted replacement and separate resource protection: " + yes_no(replaceAllowed) + "."; ""; ...
    "Formal distance, kappa, WDRO loss, MSP, Step-03J, Step-03Q, and the untracked Step-03P failed history were not modified."; ...
    "No validation data, scenario reduction, clustering, R=5000, R=15000, or all-35-state run was used."];
write_lines(path, lines);
end

function text = false_near_answer(tbl)
if isempty(tbl)
    text = "none under the specified 1% by 1% definitions";
elseif any(tbl.diagnostic_reason == "TRUE_FALSE_NEAR_CONFLICT")
    text = "yes; see diagnosed true conflicts";
else
    text = "limited candidates exist but are explained by range overlap, saturation, or non-key status";
end
end

function text = replacement_answer(allowed)
if allowed
    text = "supported after freezing the candidate definition and recalibrating rho; this run does not replace it";
else
    text = "not supported by this audit";
end
end

function text = yes_no(condition)
if condition
    text = "YES";
else
    text = "NO";
end
end

function text = range_text(x)
text = "[" + string(sprintf('%.12g', min(x))) + "," + ...
    string(sprintf('%.12g', max(x))) + "]";
end

function write_lines(path, lines)
fid = fopen(path, 'w');
if fid < 0
    error('Step-03R cannot open output file %s.', path);
end
cleanup = onCleanup(@() fclose(fid));
for ii = 1:numel(lines)
    fprintf(fid, '%s\n', lines(ii));
end
end
