function [status, recommendedWstep, reason] = ...
    select_foundation_Wstep_recommendation_h2(candidateSummary)
%SELECT_FOUNDATION_WSTEP_RECOMMENDATION_H2 Symmetric three-way selector.

required = {'candidate_Wstep', 'Rmax_count', 'joint_support_Rmax_count', ...
    'lower_W1_risk_Rmax_count', 'physically_valid'};
for ii = 1:numel(required)
    if ~ismember(required{ii}, candidateSummary.Properties.VariableNames)
        error('select_foundation_Wstep_recommendation_h2:MissingColumn', ...
            'candidateSummary is missing %s.', required{ii});
    end
end
if height(candidateSummary) ~= 2 || ...
        ~isequal(sort(double(candidateSummary.candidate_Wstep(:))), [40; 45])
    error('select_foundation_Wstep_recommendation_h2:BadCandidates', ...
        'candidateSummary must contain exactly Wstep 40 and 45.');
end

dominates = false(2, 1);
for ii = 1:2
    nRmax = candidateSummary.Rmax_count(ii);
    majority = ceil(2 * nRmax / 3);
    other = 3 - ii;
    dominates(ii) = candidateSummary.physically_valid(ii) && ...
        candidateSummary.joint_support_Rmax_count(ii) >= majority && ...
        candidateSummary.lower_W1_risk_Rmax_count(ii) >= majority && ...
        candidateSummary.joint_support_Rmax_count(ii) > ...
        candidateSummary.joint_support_Rmax_count(other);
end

if sum(dominates) == 1
    idx = find(dominates, 1, 'first');
    recommendedWstep = double(candidateSummary.candidate_Wstep(idx));
    status = compose("recommend_%g", recommendedWstep);
    reason = string(sprintf(['Wstep %g is physically valid and has symmetric ' ...
        'joint support in %g/%g Rmax cases versus %g/%g for Wstep %g; ' ...
        'the decision uses no smaller-Wstep tie break.'], ...
        recommendedWstep, candidateSummary.joint_support_Rmax_count(idx), ...
        candidateSummary.Rmax_count(idx), ...
        candidateSummary.joint_support_Rmax_count(3 - idx), ...
        candidateSummary.Rmax_count(3 - idx), ...
        candidateSummary.candidate_Wstep(3 - idx)));
else
    status = "inconclusive_40_45";
    recommendedWstep = NaN;
    reason = strcat( ...
        "Neither candidate uniquely dominates under the same physical ", ...
        "validity, W1 timing, main-impact coverage, and D-stage coverage rules; ", ...
        "no numeric Wstep tie break is applied.");
end
end
