function result = select_b3_candidate_validation_paths_h2( ...
    candidatePool, mainSample, config, foundation)
%SELECT_B3_CANDIDATE_VALIDATION_PATHS_H2 Build candidates and matched references.

candidateVars = {'unique_path_id','a0','loc0','lfw0','a1','loc1','lfw1', ...
    'a2','loc2','lfw2','a3','loc3','lfw3','path_probability', ...
    'is_observed_candidate','is_unobserved_candidate','observed_frequency', ...
    'observed_empirical_mass','grid_max_wind_mps', ...
    'grid_cumulative_excess_mps','road_max_wind_mps', ...
    'road_cumulative_excess_mps'};
mainVars = {'a0','loc0','lfw0','a_W1','loc_W1','lfw_W1','a_W2', ...
    'loc_W2','lfw_W2','a_W3','loc_W3','lfw_W3','path_probability'};
require_vars(candidatePool,candidateVars,'unique_tail_paths.csv');
require_vars(mainSample,mainVars,'main_path_samples.csv');

candidatePool = sortrows(candidatePool,{'a0','loc0','lfw0','unique_path_id'});
stateRisk = build_state_risk_cache(config,foundation);
states = unique(candidatePool(:,{'a0','loc0','lfw0'}),'rows');
states = sortrows(states,{'a0','loc0','lfw0'});
if height(states) ~= 35
    error('select_b3_candidate_validation_paths_h2:InitialStateCount', ...
        'Expected 35 initial states, found %d.',height(states));
end

candidateRows = cell(height(candidatePool),34);
referenceRows = cell(height(candidatePool),34);
probabilityRows = cell(2*height(candidatePool),14);
strataRows = cell(height(states),17);
candidateCursor = 0;referenceCursor = 0;probabilityCursor = 0;

for ss = 1:height(states)
    a0 = states.a0(ss);loc0 = states.loc0(ss);lfw0 = states.lfw0(ss);
    stateCandidates = candidatePool(candidatePool.a0==a0 & ...
        candidatePool.loc0==loc0 & candidatePool.lfw0==lfw0,:);
    requiredCount = height(stateCandidates);
    mainUnique = aggregate_main_paths(mainSample,a0,loc0,lfw0);
    mainUnique = attach_path_risk(mainUnique,stateRisk);
    mainKeys = physical_keys(mainUnique);
    candidateKeys = physical_keys(stateCandidates);
    mainUnique.is_candidate_pool_member = ismember(mainKeys,candidateKeys);

    available = mainUnique(~mainUnique.is_candidate_pool_member,:);
    if height(available) < requiredCount
        error('select_b3_candidate_validation_paths_h2:ReferenceShortage', ...
            'State (%g,%g,%g) needs %d references but only %d are available.', ...
            a0,loc0,lfw0,requiredCount,height(available));
    end
    ranks = [percentile_rank(available.grid_max_wind_mps), ...
        percentile_rank(available.grid_cumulative_excess_mps), ...
        percentile_rank(available.road_max_wind_mps), ...
        percentile_rank(available.road_cumulative_excess_mps)];
    available.risk_envelope_percentile = max(ranks,[],2);
    available.risk_mean_percentile = mean(ranks,2);
    available = sortrows(available,{'risk_envelope_percentile', ...
        'risk_mean_percentile','a1','loc1','lfw1','a2','loc2','lfw2', ...
        'a3','loc3','lfw3'});
    selectedIndex = round(linspace(1,height(available),requiredCount)).';
    if numel(unique(selectedIndex)) ~= requiredCount
        error('select_b3_candidate_validation_paths_h2:DuplicateReferenceRank', ...
            'Evenly spaced deterministic ranks were not unique.');
    end
    selectedReferences = available(selectedIndex,:);
    selectedReferences.reference_selection_rank = selectedIndex;
    selectedReferences.risk_band = risk_bands(requiredCount);

    candidateObserved = as_logical(stateCandidates.is_observed_candidate);
    candidateUnobserved = as_logical(stateCandidates.is_unobserved_candidate);
    if any(candidateObserved==candidateUnobserved) || ...
            sum(candidateObserved)+sum(candidateUnobserved)~=requiredCount
        error('select_b3_candidate_validation_paths_h2:CandidateIdentity', ...
            'Every candidate must be exactly observed or unobserved.');
    end

    for ii = 1:requiredCount
        row = stateCandidates(ii,:);
        key = physical_keys(row);
        match = mainUnique(mainKeys==key,:);
        isObserved = candidateObserved(ii);
        isUnobserved = candidateUnobserved(ii);
        if isObserved
            if height(match)~=1
                error('Observed candidate must map to one main-sample path.');
            end
            frequency = double(match.frequency);
            empiricalWeight = frequency/config.mainPathsPerInitialState;
            status = "included_in_main_empirical_distribution";
            tracePass = abs(frequency-double(row.observed_frequency))<=0 && ...
                abs(empiricalWeight-double(row.observed_empirical_mass))<= ...
                config.probabilityTolerance;
            overlap = true;
            source = "observed_candidate";
        else
            frequency = 0;empiricalWeight = 0;status = "pending_after_B3";
            tracePass = isempty(match);overlap = ~isempty(match);
            source = "unobserved_candidate";
        end
        candidateCursor = candidateCursor+1;
        candidateRows(candidateCursor,:) = common_row(candidateCursor, ...
            "candidate",source,double(row.unique_path_id),row,frequency, ...
            empiricalWeight,status,"all_run005_candidates",NaN,NaN, ...
            "candidate",height(available),double(row.grid_max_wind_mps), ...
            double(row.grid_cumulative_excess_mps), ...
            double(row.road_max_wind_mps), ...
            double(row.road_cumulative_excess_mps),isObserved,isUnobserved);
        probabilityCursor = probabilityCursor+1;
        probabilityRows(probabilityCursor,:) = probability_row(candidateCursor, ...
            source,frequency,empiricalWeight,double(row.observed_empirical_mass), ...
            double(row.path_probability),overlap,tracePass,status, ...
            isObserved,isUnobserved,false,false);
    end

    for ii = 1:requiredCount
        row = selectedReferences(ii,:);
        selectionId = height(candidatePool)+referenceCursor+1;
        frequency = double(row.frequency);
        empiricalWeight = frequency/config.mainPathsPerInitialState;
        referenceCursor = referenceCursor+1;
        referenceRows(referenceCursor,:) = common_row(selectionId, ...
            "reference","main_reference",NaN,row,frequency,empiricalWeight, ...
            "included_in_main_empirical_distribution", ...
            "deterministic_even_risk_envelope_rank", ...
            double(row.risk_envelope_percentile), ...
            double(row.risk_mean_percentile),row.risk_band, ...
            height(available),double(row.grid_max_wind_mps), ...
            double(row.grid_cumulative_excess_mps), ...
            double(row.road_max_wind_mps), ...
            double(row.road_cumulative_excess_mps),false,false);
        probabilityCursor = probabilityCursor+1;
        probabilityRows(probabilityCursor,:) = probability_row(selectionId, ...
            "main_reference",frequency,empiricalWeight,empiricalWeight, ...
            double(row.path_probability),false,true, ...
            "included_in_main_empirical_distribution",false,false,true, ...
            row.is_candidate_pool_member);
    end

    strataRows(ss,:) = {a0,loc0,lfw0,requiredCount,height(available), ...
        sum(selectedReferences.risk_band=="low"), ...
        sum(selectedReferences.risk_band=="medium"), ...
        sum(selectedReferences.risk_band=="high"), ...
        min(selectedReferences.risk_envelope_percentile), ...
        pct(selectedReferences.risk_envelope_percentile,50), ...
        max(selectedReferences.risk_envelope_percentile), ...
        min(selectedReferences.grid_max_wind_mps), ...
        max(selectedReferences.grid_max_wind_mps), ...
        min(selectedReferences.grid_cumulative_excess_mps), ...
        max(selectedReferences.grid_cumulative_excess_mps), ...
        min(selectedReferences.road_max_wind_mps), ...
        max(selectedReferences.road_max_wind_mps)};
end

candidatePaths = cell2table(candidateRows,'VariableNames',common_names());
referencePaths = cell2table(referenceRows,'VariableNames',common_names());
selection = [candidatePaths;referencePaths];
probabilityAudit = cell2table(probabilityRows,'VariableNames', ...
    probability_names());
strataAudit = cell2table(strataRows,'VariableNames', ...
    {'a0','loc0','lfw0','candidate_count','available_reference_count', ...
    'selected_low_count','selected_medium_count','selected_high_count', ...
    'risk_envelope_min','risk_envelope_median','risk_envelope_max', ...
    'grid_max_wind_min_mps','grid_max_wind_max_mps', ...
    'grid_excess_min_mps','grid_excess_max_mps', ...
    'road_max_wind_min_mps','road_max_wind_max_mps'});

if height(candidatePaths)~=config.expectedCandidateRows || ...
        height(referencePaths)~=config.expectedCandidateRows || ...
        numel(unique(physical_keys(selection)))~=height(selection)
    error('select_b3_candidate_validation_paths_h2:FinalCount', ...
        'Candidate/reference counts or physical-key uniqueness failed.');
end

result = struct();
result.candidate_paths = candidatePaths;
result.reference_paths = referencePaths;
result.selection = selection;
result.probability_audit = probabilityAudit;
result.reference_strata_audit = strataAudit;
result.state_risk_cache = stateRisk;
end

function T = aggregate_main_paths(mainSample,a0,loc0,lfw0)
sub = mainSample(mainSample.a0==a0 & mainSample.loc0==loc0 & ...
    mainSample.lfw0==lfw0,:);
if height(sub)~=15000
    error('Expected 15000 main rows for (%g,%g,%g), found %d.', ...
        a0,loc0,lfw0,height(sub));
end
key = table(double(sub.a0),double(sub.loc0),double(sub.lfw0), ...
    double(sub.a_W1),double(sub.loc_W1),double(sub.lfw_W1), ...
    double(sub.a_W2),double(sub.loc_W2),double(sub.lfw_W2), ...
    double(sub.a_W3),double(sub.loc_W3),double(sub.lfw_W3), ...
    'VariableNames',{'a0','loc0','lfw0','a1','loc1','lfw1', ...
    'a2','loc2','lfw2','a3','loc3','lfw3'});
[G,keyTable] = findgroups(key);
frequency = splitapply(@numel,double(sub.path_probability),G);
pMin = splitapply(@min,double(sub.path_probability),G);
pMax = splitapply(@max,double(sub.path_probability),G);
if any(pMax-pMin>1e-12)
    error('Main-sample duplicate paths have inconsistent path_probability.');
end
T = addvars(keyTable,frequency,pMin,'NewVariableNames', ...
    {'frequency','path_probability'});
end

function cache = build_state_risk_cache(config,foundation)
locValues = sort(double(foundation.loc_table.loc));
n = 6*numel(locValues)*4;
rows = cell(n,11);rr = 0;
for a = 1:6
    for loc = locValues(:).'
        locRow = foundation.loc_table(foundation.loc_table.loc==loc,:);
        for lfw = 0:3
            rr = rr+1;x = double(locRow.x_coord);
            y = foundation.y_base+lfw*config.Wstep;Vmax = intensity_to_vmax(a);
            lineDist = compute_point_to_segment_distance_h2(x,y, ...
                foundation.grid_segments.x1,foundation.grid_segments.y1, ...
                foundation.grid_segments.x2,foundation.grid_segments.y2);
            roadDist = compute_point_to_segment_distance_h2(x,y, ...
                foundation.road_segments.x1,foundation.road_segments.y1, ...
                foundation.road_segments.x2,foundation.road_segments.y2);
            lineWind = compute_wind_speed_radial_h2(lineDist,Vmax, ...
                config.Rmax,config.windDecayB);
            roadWind = compute_wind_speed_radial_h2(roadDist,Vmax, ...
                config.Rmax,config.windDecayB);
            rows(rr,:) = {a,loc,lfw,x,y,Vmax,max(lineWind), ...
                sum(max(0,lineWind-config.designWindSpeedVN)),max(roadWind), ...
                sum(max(0,roadWind-config.roadDesignWindVN)),rr};
        end
    end
end
cache = cell2table(rows,'VariableNames',{'a','loc','lfw','x','y','Vmax', ...
    'grid_max_wind_mps','grid_cumulative_excess_mps', ...
    'road_max_wind_mps','road_cumulative_excess_mps','cache_index'});
end

function T = attach_path_risk(T,cache)
i1 = cache_indices(cache,T.a1,T.loc1,T.lfw1);
i2 = cache_indices(cache,T.a2,T.loc2,T.lfw2);
i3 = cache_indices(cache,T.a3,T.loc3,T.lfw3);
T.grid_max_wind_mps = max([cache.grid_max_wind_mps(i1), ...
    cache.grid_max_wind_mps(i2),cache.grid_max_wind_mps(i3)],[],2);
T.grid_cumulative_excess_mps = cache.grid_cumulative_excess_mps(i1)+ ...
    cache.grid_cumulative_excess_mps(i2)+cache.grid_cumulative_excess_mps(i3);
T.road_max_wind_mps = max([cache.road_max_wind_mps(i1), ...
    cache.road_max_wind_mps(i2),cache.road_max_wind_mps(i3)],[],2);
T.road_cumulative_excess_mps = cache.road_cumulative_excess_mps(i1)+ ...
    cache.road_cumulative_excess_mps(i2)+cache.road_cumulative_excess_mps(i3);
end

function idx = cache_indices(cache,a,loc,lfw)
idx = zeros(numel(a),1);
for ii=1:numel(a)
    hit = find(cache.a==a(ii)&cache.loc==loc(ii)&cache.lfw==lfw(ii));
    if numel(hit)~=1,error('Joint state is not uniquely cached.');end
    idx(ii)=hit;
end
end

function ranks = percentile_rank(x)
x = double(x(:));n = numel(x);ranks = zeros(n,1);
[sorted,order] = sort(x,'ascend');ii = 1;
while ii<=n
    jj=ii;while jj<n && sorted(jj+1)==sorted(ii),jj=jj+1;end
    if n==1,value=0.5;else,value=((ii+jj)/2-1)/(n-1);end
    ranks(order(ii:jj))=value;ii=jj+1;
end
end

function bands = risk_bands(n)
position = ((1:n).'-1)/max(1,n-1);bands = strings(n,1);
bands(position<=1/3)="low";
bands(position>1/3 & position<2/3)="medium";
bands(position>=2/3)="high";
end

function row = common_row(selectionId,pathSet,source,candidateId,T,frequency, ...
    weight,status,rule,envelope,meanRank,band,availableCount,gridMax, ...
    gridExcess,roadMax,roadExcess,isObserved,isUnobserved)
row = {selectionId,pathSet,source,double(candidateId),double(T.a0), ...
    double(T.loc0),double(T.lfw0),double(T.a1),double(T.loc1), ...
    double(T.lfw1),double(T.a2),double(T.loc2),double(T.lfw2), ...
    double(T.a3),double(T.loc3),double(T.lfw3),double(T.path_probability), ...
    double(frequency),double(weight),status,rule,double(envelope), ...
    double(meanRank),band,double(availableCount),double(gridMax), ...
    double(gridExcess),double(roadMax),double(roadExcess),logical(isObserved), ...
    logical(isUnobserved),config_text(pathSet),physical_keys(T), ...
    "persistent_fixed_resistance"};
end

function value=config_text(pathSet)
if pathSet=="reference",value="matched_non_candidate_main_sample";
else,value="run005_complete_candidate_pool";end
end

function row = probability_row(selectionId,source,frequency,weight,reported, ...
    theoretical,overlap,tracePass,status,isObserved,isUnobserved,isReference, ...
    candidateMember)
if isUnobserved,identityPass=weight==0 && reported==0 && status=="pending_after_B3";
else,identityPass=abs(weight-reported)<=1e-12 && weight>0;end
row = {selectionId,source,double(frequency),double(weight),double(reported), ...
    double(weight-reported),double(theoretical),logical(overlap), ...
    logical(tracePass),logical(identityPass),status,logical(isObserved), ...
    logical(isUnobserved),logical(isReference||candidateMember)};
end

function names = common_names()
names = {'selection_path_id','path_set','source_category', ...
    'candidate_pool_unique_path_id','a0','loc0','lfw0','a1','loc1','lfw1', ...
    'a2','loc2','lfw2','a3','loc3','lfw3','path_probability', ...
    'observed_frequency','empirical_weight','nominal_inclusion_status', ...
    'selection_rule','risk_envelope_percentile','risk_mean_percentile', ...
    'risk_band','available_reference_path_count','grid_max_wind_mps', ...
    'grid_cumulative_excess_mps','road_max_wind_mps', ...
    'road_cumulative_excess_mps','is_observed_candidate', ...
    'is_unobserved_candidate','selection_population','physical_path_key', ...
    'damage_mode'};
end

function names = probability_names()
names = {'selection_path_id','source_category','main_sample_frequency', ...
    'assigned_empirical_weight','reported_empirical_weight', ...
    'empirical_weight_error','theoretical_path_probability', ...
    'main_sample_overlap','traceability_pass','probability_identity_pass', ...
    'nominal_inclusion_status','is_observed_candidate', ...
    'is_unobserved_candidate','is_reference_or_candidate_member'};
end

function keys = physical_keys(T)
keys = string(compose('%d|%d|%d|%d|%d|%d|%d|%d|%d|%d|%d|%d', ...
    T.a0,T.loc0,T.lfw0,T.a1,T.loc1,T.lfw1,T.a2,T.loc2,T.lfw2, ...
    T.a3,T.loc3,T.lfw3));
end

function values = as_logical(values)
if islogical(values),return;end
if isnumeric(values),values=values~=0;else
    text=lower(strtrim(string(values)));values=text=="true"|text=="1";
end
end

function value = pct(x,p)
x=sort(double(x(:)));x=x(isfinite(x));
if isempty(x),value=NaN;else
    value=x(max(1,min(numel(x),ceil(p/100*numel(x)))));
end
end

function Vmax = intensity_to_vmax(a)
map=[0;20.8;28.55;37.05;46.20;55.50];
if a<1||a>numel(map)||floor(a)~=a,error('Unsupported intensity a=%g.',a);end
Vmax=map(a);
end

function require_vars(T,names,fileName)
for ii=1:numel(names)
    if ~ismember(names{ii},T.Properties.VariableNames)
        error('%s missing required field %s.',fileName,names{ii});
    end
end
end
