function sol = solve_terminal_loh_flat_chi2_decomposition_c5c_h2( ...
        Dperiod,Aperiod,Cperiod,q,Cap,M,gamma,eta,config)
%SOLVE_TERMINAL_LOH_FLAT_CHI2_DECOMPOSITION_C5C_H2 Isolated C5C driver.
%
% This is the accepted decomposition architecture with the configured
% single-thread setting also applied to every master LP. The historical
% production/C5B solvers remain unchanged. Applying the frozen Threads=1
% setting to both recourse and master calls avoids repeated native solver
% thread-pool teardown in the isolated MATLAB processes.

if nargin<9||isempty(config),config=struct();end
config=fill_defaults(config);q=double(q(:));q=q./sum(q);Cap=double(Cap(:));
G=numel(q);I=numel(Cap);
if eta<=0,error('C5C decomposition requires positive eta.');end
started=tic;points=zeros(0,I);riskValues=zeros(0,1);gradients=zeros(0,I);
objectiveValues=zeros(0,1);lossCell=cell(0,1);probabilityCell=cell(0,1);fixedCell=cell(0,1);
initial=[zeros(1,I);0.5.*Cap.';Cap.'];
if isfield(config,'initialT')&&numel(config.initialT)==I
    initial=[reshape(double(config.initialT),1,I);initial];
end
initial=unique(initial,'rows','stable');bestUpper=inf;bestIndex=0;lowerBound=-inf;
masterRuntime=0;evaluationRuntime=0;masterCalls=0;status="ITERATION_LIMIT";iteration=0;
for ii=1:size(initial,1)
    [points,riskValues,gradients,objectiveValues,lossCell,probabilityCell, ...
        fixedCell,evaluationRuntime,bestUpper,bestIndex]=evaluate_and_add( ...
        initial(ii,:),points,riskValues,gradients,objectiveValues,lossCell, ...
        probabilityCell,fixedCell,evaluationRuntime,bestUpper,bestIndex, ...
        Dperiod,Aperiod,Cperiod,q,Cap,M,gamma,eta,config);
end
for iteration=1:config.maximumIterations
    if toc(started)>=config.totalTimeLimit,status="TIME_LIMIT";break;end
    masterStarted=tic;master=solve_master(points,riskValues,gradients,Cap,gamma,config);
    masterRuntime=masterRuntime+toc(masterStarted);masterCalls=masterCalls+1;
    if master.status~="OPTIMAL",status="MASTER_"+master.status;break;end
    lowerBound=master.objective;absoluteGap=bestUpper-lowerBound;
    relativeGap=absoluteGap/max(1,abs(bestUpper));
    fprintf('  decomposition iter=%d cuts=%d LB=%.9f UB=%.9f gap=%.6g rel=%.3g\n', ...
        iteration,size(points,1),lowerBound,bestUpper,absoluteGap,relativeGap);
    if absoluteGap<=config.absoluteGapTolerance||relativeGap<=config.relativeGapTolerance
        status="OPTIMAL";break;
    end
    distance=max(abs(points-master.T.'),[],2);
    if any(distance<=config.pointTolerance),status="NUMERICAL_STALL";break;end
    [points,riskValues,gradients,objectiveValues,lossCell,probabilityCell, ...
        fixedCell,evaluationRuntime,bestUpper,bestIndex]=evaluate_and_add( ...
        master.T.',points,riskValues,gradients,objectiveValues,lossCell, ...
        probabilityCell,fixedCell,evaluationRuntime,bestUpper,bestIndex, ...
        Dperiod,Aperiod,Cperiod,q,Cap,M,gamma,eta,config);
end
absoluteGap=bestUpper-lowerBound;relativeGap=absoluteGap/max(1,abs(bestUpper));
if status=="ITERATION_LIMIT"&&(absoluteGap<=config.absoluteGapTolerance|| ...
        relativeGap<=config.relativeGapTolerance),status="OPTIMAL";end
sol=struct('mode',"FLAT_CHI2_CERTIFIED_DECOMPOSITION_C5C", ...
    'status',status,'exitflag',double(status=="OPTIMAL"),'R_model',G, ...
    'eta',eta,'T',NaN(I,1),'terminal_loh_total',NaN,'first_stage_cost',NaN, ...
    'scenario_operating_loss',NaN(G,1),'nominal_expected_recourse',NaN, ...
    'model_risk_value',NaN,'objective_value',bestUpper, ...
    'objective_reconstruction_error',NaN,'max_demand_balance_error',NaN, ...
    'max_site_capacity_violation',NaN,'qcp_residual',0, ...
    'maximum_risk_linear_violation',0, ...
    'maximum_risk_linear_violation_raw_cost_units',0,'nu',NaN,'lambda',NaN, ...
    't',NaN(G,1),'h',NaN(G,1),'site_service_by_scenario',NaN(G,I), ...
    'build_runtime_sec',masterRuntime,'solve_runtime_sec',toc(started), ...
    'variable_count',I+1,'linear_constraint_count',size(points,1), ...
    'linear_matrix_nnz',size(points,1)*(I+1),'quadratic_constraint_count',0, ...
    'service_variable_count',NaN,'shortage_variable_count',NaN, ...
    'constructed_R_by_R_matrix',false,'objective_scale',1, ...
    'decomposition_lower_bound',lowerBound,'decomposition_upper_bound',bestUpper, ...
    'decomposition_absolute_gap',absoluteGap,'decomposition_relative_gap',relativeGap, ...
    'decomposition_iteration_count',iteration,'decomposition_cut_count',size(points,1), ...
    'master_solver_calls',masterCalls,'recourse_solver_calls',size(points,1), ...
    'evaluation_runtime_sec',evaluationRuntime);
if bestIndex>0
    sol.T=points(bestIndex,:).';sol.terminal_loh_total=sum(sol.T);
    sol.first_stage_cost=gamma*sum(sol.T);sol.model_risk_value=riskValues(bestIndex);
    sol.scenario_operating_loss=lossCell{bestIndex};
    sol.nominal_expected_recourse=sum(q.*lossCell{bestIndex});
    sol.objective_reconstruction_error=abs(bestUpper-(sol.first_stage_cost+sol.model_risk_value));
    sol.max_demand_balance_error=fixedCell{bestIndex}.max_demand_balance_error;
    sol.max_site_capacity_violation=fixedCell{bestIndex}.max_site_capacity_violation;
    sol.site_service_by_scenario=fixedCell{bestIndex}.site_service_total;
    sol.best_group_worst_probability=probabilityCell{bestIndex};
end
end

function [points,riskValues,gradients,objectives,lossCell,pCell,fixedCell, ...
        evalRuntime,bestUpper,bestIndex]=evaluate_and_add(T,points,riskValues, ...
        gradients,objectives,lossCell,pCell,fixedCell,evalRuntime,bestUpper, ...
        bestIndex,D,A,C,q,Cap,M,gamma,eta,config)
T=max(zeros(size(Cap.')),min(Cap.',T));G=numel(q);evalConfig=config;
evalConfig.gurobiTimeLimit=min(config.recourseTimeLimit,max(1,config.totalTimeLimit));
fixed=evaluate_terminal_loh_period_fixed_T_sparse_h2(D,A,C,repmat(T,G,1),M,evalConfig);
if fixed.exitflag~=1,error('Decomposition recourse failed: %s',fixed.status);end
if any(~isfinite(fixed.site_capacity_dual),'all')
    error('Decomposition requires finite recourse capacity duals.');
end
adversary=solve_flat_chi2_worst_probability_h2(q,fixed.operating_loss,eta);
p=adversary.worst_probability;risk=adversary.worst_value;
gradient=sum(p.*fixed.site_capacity_dual,1);
if any(gradient>config.subgradientSignTolerance)
    error('Positive capacity subgradient violates nonincreasing recourse.');
end
objective=gamma*sum(T)+risk;
points(end+1,:)=T;riskValues(end+1,1)=risk;gradients(end+1,:)=gradient;objectives(end+1,1)=objective; %#ok<AGROW>
lossCell{end+1,1}=fixed.operating_loss;pCell{end+1,1}=p;fixedCell{end+1,1}=fixed; %#ok<AGROW>
evalRuntime=evalRuntime+fixed.build_runtime_sec+fixed.solve_runtime_sec;
if objective<bestUpper,bestUpper=objective;bestIndex=size(points,1);end
end

function master=solve_master(points,riskValues,gradients,Cap,gamma,config)
nCuts=size(points,1);I=numel(Cap);nvar=I+1;theta=nvar;A=sparse(nCuts,nvar);rhs=zeros(nCuts,1);
for kk=1:nCuts
    A(kk,1:I)=-gradients(kk,:);A(kk,theta)=1;
    rhs(kk)=riskValues(kk)-gradients(kk,:)*points(kk,:).';
end
model=struct('A',A,'rhs',rhs,'sense',repmat('>',nCuts,1), ...
    'obj',[gamma*ones(I,1);1],'lb',[zeros(I,1);0],'ub',[Cap(:);inf], ...
    'modelsense','min','modelname','flat_chi2_master_c5c');
params=struct('OutputFlag',config.gurobiOutputFlag, ...
    'FeasibilityTol',config.gurobiFeasibilityTol, ...
    'OptimalityTol',config.gurobiOptimalityTol,'TimeLimit',config.masterTimeLimit, ...
    'Threads',config.gurobiThreads);
result=gurobi(model,params);
master=struct('status',string(result.status),'T',NaN(I,1),'objective',NaN);
if strcmp(result.status,'OPTIMAL'),master.T=result.x(1:I);master.objective=result.objval;end
end

function config=fill_defaults(config)
defaults=struct('gurobiOutputFlag',0,'gurobiFeasibilityTol',1e-9, ...
    'gurobiOptimalityTol',1e-9,'gurobiTimeLimit',1800,'gurobiThreads',1, ...
    'objectiveScale',1e5,'maximumIterations',100,'absoluteGapTolerance',1e-4, ...
    'relativeGapTolerance',1e-8,'pointTolerance',1e-8, ...
    'subgradientSignTolerance',1e-6,'totalTimeLimit',7200, ...
    'recourseTimeLimit',1800,'masterTimeLimit',60);
names=fieldnames(defaults);
for ii=1:numel(names)
    if ~isfield(config,names{ii})||isempty(config.(names{ii})),config.(names{ii})=defaults.(names{ii});end
end
end
