function write_damage_persistence_v2_diagnostics_h2(bySlice, hresTbl, ...
    comparisonTbl, stateSaturationTbl, roadACTbl, checksTbl, diagnostics, config)
%WRITE_DAMAGE_PERSISTENCE_V2_DIAGNOSTICS_H2 Write v2 artifacts and figures.

writetable(bySlice, fullfile(config.outputDir, ...
    'damage_persistence_v2_by_slice.csv'));
writetable(hresTbl, fullfile(config.outputDir, ...
    'damage_persistence_v2_Hres3h_summary.csv'));
writetable(comparisonTbl, fullfile(config.outputDir, ...
    'damage_mode_comparison_v2.csv'));
writetable(stateSaturationTbl, fullfile(config.outputDir, ...
    'state_level_saturation_v2.csv'));
writetable(roadACTbl, fullfile(config.outputDir, ...
    'road_AC_stage_diagnostics_v2.csv'));
writetable(checksTbl, fullfile(config.outputDir, ...
    'damage_persistence_v2_checks.csv'));
write_summary(stateSaturationTbl, diagnostics, checksTbl, config);
write_audit(diagnostics, checksTbl, config);
write_figures(bySlice, hresTbl, config);
end

function write_summary(S, diagnostics, checks, config)
fid = fopen(fullfile(config.outputDir, 'diagnostics_summary_v2.txt'), 'w');
if fid < 0
    error('write_damage_persistence_v2_diagnostics_h2:OpenFailed', ...
        'Could not open diagnostics_summary_v2.txt.');
end
cleanup = onCleanup(@()fclose(fid));
fprintf(fid, 'W1-W3 damage persistence v2: fixed resistance comparison\n\n');
fprintf(fid, ['Parameters: Wstep=%g from config, Rmax=%s, a=%s, loc=%s, ' ...
    'Nmc=%d, seed=%d.\n'], config.Wstep, vec(config.RmaxValues), ...
    vec(config.aValues), vec(config.locValues), config.Nmc, config.rngSeed);
fprintf(fid, 'W1/W2/W3 each use %.12g h; Hres total is %.12g h.\n\n', ...
    config.sliceDurationH, config.HresTotalH);
fprintf(fid, 'Modes:\n');
fprintf(fid, '- independent_snapshot: stage-specific draw; recovery allowed.\n');
fprintf(fid, '- persistent_independent_draws: stage-specific draws with cumulative OR/max; no repair.\n');
fprintf(fid, '- persistent_fixed_resistance: one W1 uniform threshold per component/scenario reused across W1-W3, cumulative state, no repair.\n\n');
fprintf(fid, 'Common random numbers pass: %d.\n', ...
    diagnostics.common_random_numbers_pass);
fprintf(fid, 'CRN evidence: %s\n', diagnostics.common_random_numbers_evidence);
fprintf(fid, 'W1 outcomes identical across all modes: %d.\n', ...
    diagnostics.W1_identical_across_modes);
fprintf(fid, 'Fixed component threshold reuse pass: %d.\n', ...
    diagnostics.fixed_threshold_reuse_pass);
fprintf(fid, 'Threshold evidence: %s\n\n', ...
    diagnostics.fixed_threshold_reuse_evidence);

for rmax = config.RmaxValues(:).'
    fprintf(fid, 'Rmax=%g aggregate means across a/loc/scenarios\n', rmax);
    for mode = config.damageModes(:).'
        q = diagnostics.rmax_aggregate( ...
            diagnostics.rmax_aggregate.Rmax == rmax & ...
            diagnostics.rmax_aggregate.damage_mode == mode, :);
        fprintf(fid, ['- %s: failed=[%s], closed=[%s], P_loss_kW=[%s], ' ...
            'D_kg=[%s], D_Hres3h_mean=%.12g, D_Hres3h_p95=%.12g\n'], ...
            char(mode), vec([q.failed_W1_mean,q.failed_W2_mean,q.failed_W3_mean]), ...
            vec([q.closed_W1_mean,q.closed_W2_mean,q.closed_W3_mean]), ...
            vec([q.P_loss_W1_mean_kW,q.P_loss_W2_mean_kW,q.P_loss_W3_mean_kW]), ...
            vec([q.D_W1_mean_kg,q.D_W2_mean_kg,q.D_W3_mean_kg]), ...
            q.D_Hres3h_mean_kg,q.D_Hres3h_p95_kg);
    end
    o = diagnostics.overestimate_by_rmax( ...
        diagnostics.overestimate_by_rmax.Rmax == rmax, :);
    fprintf(fid, ['  cumulative OR minus fixed resistance: D_mean=%.12g kg ' ...
        '(%.6g%%), failed_stage_mean=%.12g, closed_stage_mean=%.12g, ' ...
        'P_loss_stage_mean=%.12g kW, reachable_share_delta=%.12g.\n\n'], ...
        o.cumulative_minus_fixed_D_mean_kg, ...
        100*o.cumulative_vs_fixed_D_relative, o.failed_line_stage_mean_delta, ...
        o.closed_road_stage_mean_delta, o.P_loss_stage_mean_delta_kW, ...
        o.reachable_pair_share_delta);
end

fprintf(fid, 'Overall cumulative D mean: %.12g kg.\n', ...
    diagnostics.overall_cumulative_D_mean_kg);
fprintf(fid, 'Overall fixed-resistance D mean: %.12g kg.\n', ...
    diagnostics.overall_fixed_D_mean_kg);
fprintf(fid, 'Overall cumulative minus fixed: %.12g kg (%.6g%%).\n', ...
    diagnostics.overall_cumulative_minus_fixed_D_kg, ...
    100*diagnostics.overall_cumulative_minus_fixed_D_relative);
fprintf(fid, 'Material overestimate threshold %.6g met: %d.\n\n', ...
    config.overestimateThreshold, diagnostics.cumulative_overestimate_detected);

fprintf(fid, ['Fixed-resistance monotonic violations: line=%d, road=%d, ' ...
    'slowdown=%d.\n'], diagnostics.fixed_line_monotonic_violation_count, ...
    diagnostics.fixed_road_monotonic_violation_count, ...
    diagnostics.fixed_slowdown_monotonic_violation_count);
fprintf(fid, 'Maximum aggregate fixed-resistance saturation share: %.12g.\n', ...
    diagnostics.max_fixed_aggregate_saturation_share);
fprintf(fid, 'Fixed-resistance mass saturation detected at %.6g: %d.\n', ...
    config.massSaturationThreshold, diagnostics.fixed_mass_saturation_detected);
fprintf(fid, 'Fixed-resistance stage distinction pass: %d.\n', ...
    diagnostics.fixed_stage_distinction_pass);

fprintf(fid, '\nState-level full-load saturation rows with positive rate:\n');
for mode = config.damageModes(:).'
    q = S(S.damage_mode == mode & S.full_load_loss_share > 0, :);
    fprintf(fid, '- %s: %d of %d state-stage rows; maximum=%.12g.\n', ...
        mode, height(q), sum(S.damage_mode == mode), ...
        max_or_zero(q.full_load_loss_share));
end

auto = checks.passed(~isnan(checks.passed));
fprintf(fid, '\nAutomatic checks passed: %d/%d; failures=%d; warnings=%d.\n', ...
    sum(auto == 1), numel(auto), sum(auto == 0), ...
    sum(strlength(checks.warning) > 0));
fprintf(fid, 'Formal-B3 recommendation: %s.\n', diagnostics.B3_recommendation);
fprintf(fid, ['No Stage2A2, path_prob, formal B3, Stage2C, WDRO, Gurobi, ' ...
    'or MSP run was performed.\n']);
end

function write_audit(diagnostics, checks, config)
fid = fopen(fullfile(config.outputDir, 'implementation_audit_v2.md'), 'w');
if fid < 0
    error('write_damage_persistence_v2_diagnostics_h2:AuditOpenFailed', ...
        'Could not open implementation_audit_v2.md.');
end
cleanup = onCleanup(@()fclose(fid));
fprintf(fid, '# Damage persistence v2 implementation audit\n\n');
fprintf(fid, '- Scope: small W1-W3 comparison of three damage-state inheritance rules only.\n');
fprintf(fid, '- `Wstep` is read from `config.Wstep=%g`; the evaluator does not embed a stage-step literal.\n', config.Wstep);
fprintf(fid, '- `independent_snapshot` uses each stage uniform draw directly and allows recovery.\n');
fprintf(fid, '- `persistent_independent_draws` uses each stage uniform draw and cumulative OR for line/road damage.\n');
fprintf(fid, '- `persistent_fixed_resistance` uses the W1 uniform as one fixed component resistance threshold for W1-W3, then retains first damage without repair.\n');
fprintf(fid, '- Persistent slowdown severity is the historical maximum of `roadSlowdownLambda*pClose`.\n');
fprintf(fid, '- Common base random inputs pass=%d; W1 equality pass=%d; fixed-threshold exact reuse pass=%d.\n', ...
    diagnostics.common_random_numbers_pass, ...
    diagnostics.W1_identical_across_modes, ...
    diagnostics.fixed_threshold_reuse_pass);
fprintf(fid, '- Spatial/risk functions reused read-only: `build_foundation_fix_coordinates_h2`, `compute_point_to_segment_distance_h2`, `compute_wind_speed_radial_h2`, and `compute_line_failure_prob_h2`.\n');
fprintf(fid, '- D conversion reused read-only: `compute_Hres3h_node_demand_h2`; D sums W1-W3 only, one hour each, Hres=3 h.\n');
fprintf(fid, '- Road data: `data/yuanqi/stage1_road_edges.csv` and `stage1_site_nodes.csv`; node coordinates come from the existing Foundation layout.\n');
fprintf(fid, '- Road A is binary finite-path reachability from four site anchors to 33 nodes.\n');
fprintf(fid, '- Road C is the current Dijkstra shortest-path cost `dist(n)` on `edge_length*(1+slowdown)` with closed edges excluded. No `baseCost+dist(n)` term is used.\n');
fprintf(fid, '- Unreachable C values are excluded from finite-C statistics; A/C automatic validation is included in `damage_persistence_v2_checks.csv`.\n');
fprintf(fid, '- Fixed-resistance monotonic violations: line=%d, road=%d, slowdown=%d.\n', ...
    diagnostics.fixed_line_monotonic_violation_count, ...
    diagnostics.fixed_road_monotonic_violation_count, ...
    diagnostics.fixed_slowdown_monotonic_violation_count);
fprintf(fid, '- Cumulative-OR minus fixed-resistance overall D mean: %.12g kg (%.6g%%).\n', ...
    diagnostics.overall_cumulative_minus_fixed_D_kg, ...
    100*diagnostics.overall_cumulative_minus_fixed_D_relative);
fprintf(fid, '- Fixed-resistance maximum aggregate saturation share=%.12g; mass saturation detected=%d.\n', ...
    diagnostics.max_fixed_aggregate_saturation_share, ...
    diagnostics.fixed_mass_saturation_detected);
fprintf(fid, '- Fixed-resistance stage distinction pass=%d.\n', ...
    diagnostics.fixed_stage_distinction_pass);
fprintf(fid, '- Protected old outputs unchanged=%d; protected MSP/data files unchanged=%d.\n', ...
    diagnostics.old_output_pass, diagnostics.msp_file_pass);
fprintf(fid, '- Source call scan: WDRO/Gurobi hits=%d, MSP hits=%d, Stage2A2/path_prob/B3/Stage2C hits=%d.\n', ...
    diagnostics.source_scan.WDRO_call_hit_count, ...
    diagnostics.source_scan.MSP_call_hit_count, ...
    diagnostics.source_scan.B3_call_hit_count);
fprintf(fid, '- Automatic check failures=%d; warnings=%d.\n', ...
    sum(checks.passed == 0), sum(strlength(checks.warning) > 0));
fprintf(fid, '- Recommendation for formal B3 design: `%s`; formal B3 was not executed.\n', ...
    diagnostics.B3_recommendation);
fprintf(fid, '- Stage2A2, path probability, path screening, formal B3, Stage2C, WDRO, Gurobi, and MSP were not executed.\n');
fprintf(fid, '- Existing Foundation, B1/B2, and previous persistence-smoke outputs were not overwritten.\n');
end

function write_figures(T, H, config)
figDir = fullfile(config.outputDir, 'figures');
if ~isfolder(figDir)
    mkdir(figDir);
end
plot_stage_metric(T, 'failed_line_count', 'Mean failed line count', ...
    fullfile(figDir, 'failed_line_count_by_stage_v2.png'), config);
plot_stage_metric(T, 'closed_road_count', 'Mean closed road count', ...
    fullfile(figDir, 'closed_road_count_by_stage_v2.png'), config);
plot_stage_metric(T, 'P_loss_total_kW', 'Mean P loss (kW)', ...
    fullfile(figDir, 'P_loss_by_stage_v2.png'), config);
plot_stage_metric(T, 'D_slice_total_kg', 'Mean D slice (kg-H2)', ...
    fullfile(figDir, 'D_by_stage_v2.png'), config);
plot_stage_metric(T, 'reachable_pair_share', 'Mean site-node reachable share', ...
    fullfile(figDir, 'road_reachability_by_stage_v2.png'), config);
plot_D_total(H, fullfile(figDir, 'D_Hres3h_total_by_Rmax_v2.png'), config);
end

function plot_stage_metric(T, fieldName, yLabel, outFile, config)
fig = figure('Visible','off','Color','w','Position',[100 100 1050 580]);
cleanup = onCleanup(@()close(fig));
ax = axes(fig); hold(ax,'on'); grid(ax,'on');
colors = lines(numel(config.RmaxValues));
styles = {'--','-.','-'};
for rr = 1:numel(config.RmaxValues)
    for mm = 1:numel(config.damageModes)
        q = T(T.Rmax == config.RmaxValues(rr) & ...
            T.damage_mode == config.damageModes(mm), :);
        values = zeros(1,3);
        metricValues = q.(fieldName);
        for ss = 1:3
            values(ss) = mean(metricValues(q.stage_index == ss));
        end
        plot(ax,1:3,values,styles{mm},'Color',colors(rr,:), ...
            'Marker','o','LineWidth',1.35,'DisplayName', ...
            sprintf('Rmax=%g %s',config.RmaxValues(rr),char(config.damageModes(mm))));
    end
end
xticks(ax,1:3);xticklabels(ax,{'W1','W2','W3'});ylabel(ax,yLabel);
title(ax,[yLabel ' by damage mode']);
legend(ax,'Location','eastoutside','Interpreter','none');
exportgraphics(fig,outFile,'Resolution',180);
end

function plot_D_total(H, outFile, config)
fig = figure('Visible','off','Color','w','Position',[100 100 900 520]);
cleanup = onCleanup(@()close(fig));
ax = axes(fig); hold(ax,'on'); grid(ax,'on');
for mm = 1:numel(config.damageModes)
    values = zeros(size(config.RmaxValues));
    for rr = 1:numel(config.RmaxValues)
        q = H(H.damage_mode == config.damageModes(mm) & ...
            H.Rmax == config.RmaxValues(rr), :);
        values(rr) = mean(q.D_Hres3h_total_kg);
    end
    plot(ax,config.RmaxValues,values,'-o','LineWidth',1.5, ...
        'DisplayName',char(config.damageModes(mm)));
end
xlabel(ax,'Rmax (km-equivalent)');
ylabel(ax,'Mean Hres3h D total (kg-H2)');
title(ax,'Three-mode Hres3h demand comparison');
legend(ax,'Location','best','Interpreter','none');
exportgraphics(fig,outFile,'Resolution',180);
end

function s = vec(x)
s = char(strjoin(compose('%.6g',x(:).'),','));
end

function value = max_or_zero(x)
if isempty(x)
    value = 0;
else
    value = max(x);
end
end
